### ISSUE TITLE
Thumbnail title regression since 0.11.0

### ISSUE THREAD

**Issue by StefRe** [sphinx-gallery/sphinx-gallery#1002]
#906 changed the way thumbnail views of galleries are created. It now exposes the rst formatting in the caption:

[Current](https://matplotlib.org/devdocs/tutorials/index.html#intermediate):

![image](https://user-images.githubusercontent.com/19879328/189995776-e11a23b2-5f03-4f9b-bf51-e8bc0d9076f4.png)

[Previous:](https://matplotlib.org/2.2.5/tutorials/index.html)

![grafik](https://user-images.githubusercontent.com/19879328/190082348-9c0e7231-f4b0-41ea-a7ac-4f069d9867db.png)
See also https://github.com/sphinx-gallery/sphinx-gallery/issues/998#issuecomment-1245912973

**Comment by larsoner** [comment]
@alexisthual can you take a look? Presumably we should be using some sanitized version of the title that we already have access to somewhere

**Comment by StefRe** [comment]
While #1005 removes the formatting it doesn't resolve roles, it just removes the backticks.
The above example with SG 0.12.2:
![grafik](https://user-images.githubusercontent.com/19879328/224987801-083f1318-0814-434a-a4e7-c01139b28ec4.png)

**Comment by StefRe** [comment]
@larsoner will you re-open this issue or is the decision "won't fix"?  
In the latter case, https://github.com/matplotlib/matplotlib/issues/23884 will have to be resolved by removing refs from the titles.

I looked a bit into it but don't understand enough of doctutils/Sphinx to come up with a solution. When using a `Figure` instead of just an `Image`, docutils adds a caption as `pending_xref` which is later resolved by Sphinx. Maybe Sphinx Gallery can add the same in `generate_dir_rst`?

**Comment by larsoner** [comment]
> I looked a bit into it but don't understand enough of doctutils/Sphinx to come up with a solution. 

Neither do I :( But I agree it would be nice to have this resolve/parse automatically. Maybe we could restructure the elements as suggested in https://github.com/sphinx-gallery/sphinx-gallery/issues/998#issuecomment-1399215582 ? Perhaps if we create `.. container`s where the title is in there somewhere (unsanitized) in a way that Sphinx can directly process it like any other RST then we'd get it for free...

**Comment by StefRe** [comment]
I must admit my html and css knowledge is at a very basic level, so maybe this question sounds silly, but why do we need the extra title (`sphx-glr-thumbnail-title`) when the - already sanitized - version of the title is already in the preceding `<span class="std std-ref">`? See [this example](https://matplotlib.org/devdocs/tutorials/intermediate/index.html), where I temporarily switched off the hiding of that span 
![grafik](https://user-images.githubusercontent.com/19879328/225891246-bc6e1a64-8413-4aa1-941f-98ad58ef66ea.png):
<br>  

![grafik](https://user-images.githubusercontent.com/19879328/225891330-550e43ac-8069-4429-a015-d6a8468a8cb6.png)

So can't the blue text just be aligned under the thumbnails using some css and that's it, without using the extra `sphx-glr-thumbnail-title` nodes?

**Comment by larsoner** [comment]
> but why do we need the extra title (sphx-glr-thumbnail-title) when the - already sanitized - version of the title is already in the preceding <span class="std std-ref">

I don't know -- is it nested in the correct `div` to render properly if we do un-hide it? And/or does it become un-hidden when you mouse over the thumbnail?

One way to approach the problem would be to remove the redundancy as you say by using the Sphinx-generated/parsed version, and see if you can get it to look equivalent.

**Comment by GaelVaroquaux** [comment]
Sounds reasonable. cc @alexisthual

**Comment by StefRe** [comment]
I went through all examples and tutorials in Matplotlib and there are just 3 cases with wrong formatting:

1. https://matplotlib.org/stable/gallery/text_labels_and_annotations/dfrac_demo.html#sphx-glr-gallery-text-labels-and-annotations-dfrac-demo-py
2.  https://matplotlib.org/stable/tutorials/intermediate/imshow_extent.html#sphx-glr-tutorials-intermediate-imshow-extent-py
3. https://matplotlib.org/stable/gallery/axes_grid1/demo_colorbar_with_axes_divider.html#sphx-glr-gallery-axes-grid1-demo-colorbar-with-axes-divider-py


The first case will be fixed by #1108, the other two cases can easily be fixed in Matplotlib by adding an explicit role.

**Comment by alexisthual** [comment]
I'm a bit late in the game but if I remember correctly, this clunky structure comes from the fact that we could not find a way of making the whole gallery item be a link (an `<a>`) in sphinx. In short, there is now simple way in sphinx to create a link that has custom HTML inside.

Instead, what we did is we:
1. "inflated" a link contained in a `<div>` so that it would fill the div (in our case, this div is our gallery item)
2. added another `<span>` with redundant information :unamused: 

I remember spending a few hours trying to come with a more elegant solution to this but can't really remember what was missing. #998 is where you should start if you want to investigate :detective:
