### ISSUE TITLE
Filter image warnings when using `make html-noplot`

### ISSUE THREAD

**Issue by rcomer** [sphinx-gallery/sphinx-gallery#1006]
I recently added the `html-noplot` option to matplolib's Makefile (https://github.com/matplotlib/matplotlib/pull/23870).  There were a lot of warnings generated where rst files link to the gallery images that were skipped (as discussed at #751).  We looked at the option to create dummy images via comments in the example (#828).  However, for matplotlib this would involve adding the comment to over 80 examples, and would need some extra check to make sure we continue to have the right comments in the right examples in future.  So we decided this was not the ideal solution there.

In the end we added a simple logging filter in `conf.py`:
https://github.com/matplotlib/matplotlib/blob/4a62222ff48eae3b8027813ed4313362cfb39da0/doc/conf.py#L204-L220

It was suggested that this filter could be implemented in Sphinx-Gallery itself.  What do you think?

**Comment by rcomer** [comment]
Thanks @larsoner, and sorry it's taken me so long to come back to this.

I just looked at the `tinybuild` and sphinx-gallery's doc build but, as far as I can see, they do not have any `.. figure::` directives in the rst files, so do not have this problem.  I also went back to [Iris](https://github.com/SciTools/iris) (as the project I'm most familiar with) and established that it also does not use those `.. figure::` directives to include gallery images.

It's probably fair to assume that Matplotlib is an outlier in terms of the sheer number of gallery examples, so perhaps this is mostly a Matplotlib-specific issue. :thinking:

**Comment by larsoner** [comment]
> It's probably fair to assume that Matplotlib is an outlier in terms of the sheer number of gallery examples, so perhaps this is mostly a Matplotlib-specific issue.

Indeed. Is the `.. figure::` a matplotlib directive? If so, you could check to see if the image exists before inserting any RST/HTML where the directive is called. This could be an option for `..figure ::` like `:allow-missing:` or so, where if it's missing, nothing is inserted so no warning is generated. But really how this is handled is perhaps best decided by you all. I don't expect `..figure::` pointing to a SG-generated thumbnail or file is very common outside MPL.

**Comment by rcomer** [comment]
`.. figure::` is documented [here in Sphinx](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-ref) and seems to be a standard [rst thing](https://docutils.sourceforge.io/docs/ref/rst/directives.html#figure).

I guess you would expect `.. image::` to cause similar issues, but neither Sphinx-Gallery nor Iris point to their gallery images with that either.

**Comment by rcomer** [comment]
I think I'll close this one as there doesn't seem to be enough evidence to justify the change.  Thanks for taking the time to consider it @larsoner.
