### ISSUE TITLE
`rcParams` seems ignored; overriding some image scraping

### ISSUE THREAD

**Issue by OverLordGoldDragon** [sphinx-gallery/sphinx-gallery#1007]
The title is out of bounds for

```python
plt.plot([1, 2, 3])
plt.suptitle("Title", weight='bold', fontsize=26, y=1.025)
```
unless `bbox_inches='tight'` is passed to `plt.savefig()`, which can be made default via `matplotlib.rcParams['savefig.bbox'] = 'tight'`, but doing so in `conf.py` doesn't yield this behavior. Is it necessary to override the entire image scraper, or how else to approach this?

**Comment by larsoner** [comment]
This is because of the default resetting behavior, can you look at https://sphinx-gallery.github.io/stable/configuration.html#reset-modules to see if it answers your question?

**Comment by larsoner** [comment]
Yes that should work, glad it's working for you
