### ISSUE TITLE
QUESTION about full role names

### ISSUE THREAD

**Issue by StefRe** [sphinx-gallery/sphinx-gallery#1008]
The regex for roles of references allows for fully written out names `:function:`, `:method:`, `:attribute:`, `:object:` along with the standard `:func:`, `:meth:`, `:attr:`, `:obj:` role names:

https://github.com/sphinx-gallery/sphinx-gallery/blob/51cd69c71c099d1b3ef50894d9817f9bba9fd3ee/sphinx_gallery/backreferences.py#L210-L216

I couldn't find any sphinx documentation describing this feature, in particular the [Cross-referencing Python objects](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#cross-referencing-python-objects) section doesn't mention it.

The regex with the full names was added in 6a1810e38 by @choldgraf. The [documentation](https://sphinx-gallery.github.io/stable/configuration.html#add-mini-galleries-for-api-documentation) doesn't mention the full names.

So I have two questions:

1. is the use of full names documented somewhere?
2. if not, do we need the full role names here?

(the reason for my question is that I'm working on a PR to enhance the regex to allow for default roles, titles etc. and don't want to make it more complex than needed)

**Comment by larsoner** [comment]
No idea if it's documented somewhere or not. To see if we need the full ones, I would try changing some `:meth:` or `:func:` somewhere to use the full names and see if it breaks

**Comment by StefRe** [comment]
Very good proposal - I should have thought of that myself :).  

It indeed throws an `ERROR: Unknown interpreted text role "object"` when I change `:obj:` to `object:` (e.g. [here](https://github.com/sphinx-gallery/sphinx-gallery/blob/51cd69c71c099d1b3ef50894d9817f9bba9fd3ee/examples/plot_6_function_identifier.py#L16)). So I think we can simplify the regex a bit.
