### ISSUE TITLE
Displaying saved animations

### ISSUE THREAD

**Issue by OverLordGoldDragon** [sphinx-gallery/sphinx-gallery#1011]
Can a saved animation be displayed in a generated file? I'm using

```python
class Animator(matplotlib.animation.TimedAnimation):
    def __init__(self):
        animation.TimedAnimation.__init__(self, ...)

Animator().save(fps=..., savefig_kwargs=...)
```
where animation behavior is controlled in `save`, which I presume can't be scraped. In my context it also fails to animate entirely but I've not yet reproduced minimally (a minimal example works fine).

I imagine something like

```python
ani.save("path.mp4")
some_sphinx_gallery_function("path.mp4")
```

and I'm aware there's ways to insert images via standard sphinx functionality, but don't know how to do it inline for HTML generated from `.py` by sphinx-gallery.

**Comment by larsoner** [comment]
Have you read https://sphinx-gallery.github.io/stable/configuration.html#image-scrapers ?

**Comment by OverLordGoldDragon** [comment]
Yes I am using `'matplotlib_animations': True` and a minimal example works. I did miss [this page](https://sphinx-gallery.github.io/stable/advanced.html#example-2-detecting-image-files-on-disk) though, which may be the solution - I'll update.

**Comment by OverLordGoldDragon** [comment]
Yes something like `PNGScraper` will work but how do I also preserve default scraping behavior? I don't see docs on how a scraper works, ideally I can run `PNGScraper` at the end of the script (since the files aren't going anywhere), while `matplotlib_scraper` handles everything else as usual.

**Comment by lucyleeow** [comment]
Some more info on how scrapers work: https://sphinx-gallery.github.io/stable/advanced.html#write-a-custom-image-scraper

**Comment by OverLordGoldDragon** [comment]
What I learned:

 1. `'image_scrapers': ('matplotlib', CustomScraper())` _appends_ my scraper to the existing one.
 2. Scrapers execute after every cell.
 3. `sphinx-gallery` doesn't support `.mp4` saved animations, so one must either 1) save as `.gif` instead, or 2) `.mp4` -> `.gif` in the scraper. Useful: `_anim_rst` in [scrapers](https://sphinx-gallery.github.io/stable/_modules/sphinx_gallery/scrapers.html#matplotlib_scraper).

Can you confirm? I've extended the `PNGScraper` to encompass all supported formats:

```python
class PlotScraper(object):
    def __init__(self):
        self.seen = set()

    def __repr__(self):
        return 'PlotScraper'

    def __call__(self, block, block_vars, gallery_conf):
        # Find all supported plot files in the directory of this example.
        path_current_example = os.path.dirname(block_vars['src_file'])
        supported = ('png', 'jpg', 'svg', 'gif')
        files = [values for ext in supported for values in
                 sorted(glob(os.path.join(path_current_example, f'*.{ext}')))]

        # Iterate through files, copy them to the sphinx-gallery output directory
        file_names = list()
        image_path_iterator = block_vars['image_path_iterator']
        for file in files:
            if file not in self.seen:
                self.seen |= set(file)
                this_path = image_path_iterator.next()
                this_path = this_path.replace(Path(this_path).suffix,
                                              Path(file).suffix)
                file_names.append(this_path)
                shutil.move(file, this_path)
        # Use the `figure_rst` helper function to generate rST for image files
        return figure_rst(file_names, gallery_conf['src_dir'])
```

**Comment by larsoner** [comment]
> 'image_scrapers': ('matplotlib', CustomScraper()) appends my scraper to the existing one.

Yep, and they will run in that order (mpl then yours).

> Scrapers execute after every cell.

Yes indeed, see:

https://sphinx-gallery.github.io/stable/advanced.html#write-a-custom-image-scraper

in particular the quote:

    This function will be called once for each code block of your examples

> sphinx-gallery doesn't support .mp4 saved animations

SG internally just supports mpl (including animations if used properly) and mayavi, with PyVista and PyGMT maintaining their implementations. Other formats -- including any saved to disk -- are left to the user to support.
