### ISSUE TITLE
Outdated import in docs: "Advanced usage"

### ISSUE THREAD

**Issue by OverLordGoldDragon** [sphinx-gallery/sphinx-gallery#1014]
https://sphinx-gallery.github.io/stable/advanced.html#example-2-detecting-image-files-on-disk

```python
from sphinx_gallery.gen_rst import figure_rst
```

should be(?)

```python
from sphinx_gallery.scrapers import figure_rst
```
The first one fails on my 0.11.1 pip install.

**Comment by lucyleeow** [comment]
Yes you're right. Do you want to open an PR to fix?
