### ISSUE TITLE
Disable thumbnail generation in examples' `index.rst`

### ISSUE THREAD

**Issue by OverLordGoldDragon** [sphinx-gallery/sphinx-gallery#1023]
Instead I wish to use a custom format (not just thumbnails) and `.. include my_thumbnails.txt` into `source/examples/index.rst`. 

Example `my_thumbnails.txt`:

```rst
.. raw:: html

   <div class="gallery">
     <a href="examples/plot_1.html"><img src="_images/thumbnail_1.png"></img></a><br>
	 <div><a href="examples/plot_1.html">Plot 1</a></div>
   </div>
   
   <div class="gallery">
     <a href="examples/plot_2.html"><img src="_images/thumbnail_2.png"></img></a><br>
	 <div><a href="examples/plot_2.html">Plot 2</a></div>
   </div>
```

which has `class="gallery"` defined in `style.css`. And `my_pkg/examples/README.rst`:

```rst
Examples
========
Here be examples
```

Is there native support or some light hack to achieve this?

**Comment by larsoner** [comment]
Including your own stuff should be easy enough because you can just `.. include` it I think. To get rid of the SG version, could you use CSS to set the visibility of some div to `hidden` to hide it? It's not the most efficient but it might work

**Comment by OverLordGoldDragon** [comment]
Figured, hoped for something more native but seems to work fine; `examples/README.rst`:

```
Examples
========
Here be examples

.. include:: ../custom_gallery.txt

.. raw:: html

    <head>
      <style>
        .sphx-glr-thumbcontainer { display: none; }
        .sphx-glr-thumbnail-title { display: none; }
      </style>
    </head>
```

**Comment by OverLordGoldDragon** [comment]
Though, that's prone to breaking if class names change, e.g. `.sphinx-glr-thumbcontainer`. Can these be fetched from `sphinx_gallery` to warrant forward-compatibility? I've not found the line for thumbnail generation that invokes these classes:

<img src="https://user-images.githubusercontent.com/16495490/192669964-b7ab6d3e-09e4-40fa-b617-54055a64d565.png" width="650">

The closest is `n_thumb` in `tests/` but that's also brittle... Seems like something for the library to address explicitly.

**Comment by larsoner** [comment]
I think that name has been around for years, but feel free to look through the commit history to confirm. Given the way people customize appearance using CSS it would be a backward compat break to change the name, so it's unlikely to happen

**Comment by OverLordGoldDragon** [comment]
Still seems feasible to `if sphinx_gallery_conf['root_thumbnails']`, but I'll leave that up to maintainers - feel free to close.
