### ISSUE TITLE
Create mini-gallery with an arbitrary list of gallery items

### ISSUE THREAD

**Issue by alexisthual** [sphinx-gallery/sphinx-gallery#1029]
Hi there :slightly_smiling_face: 

For now, mini-galleries filter out gallery items based on whether they use a specified method / class / etc or not.
I think it'd be very nice to be able to generate mini-galleries from an arbitrary list of items specified by the user.
Specifically, I'm planning to use this in `nilearn`'s user guide to reference examples using the nice `sphinx-gallery` thumbnail.

It could look something like this:
```
.. minigallery::
    :add-heading: A list of examples relevant to the section above
    :sg-items: section_1/item_3.py section_4/item_2.py
```

Let me know what you think!

**Comment by larsoner** [comment]
This seems reasonable in principle -- I could see us potentially using this in MNE-Python to do stuff like a `See Also` section at the bottom of a given tutorial to suggest other examples people should look at. WDYT @drammock ?

**Comment by alexisthual** [comment]
> I could see us potentially using this in MNE-Python to do stuff like a `See Also` section at the bottom of a given tutorial to suggest other examples people should look at. 

Yes that's exactly what I'm trying to do with `nilearn`. For now, I'm building a mini-gallery manually in the [user guide introduction](https://output.circle-artifacts.com/output/job/8fa99f0c-05e5-467e-8594-6d8273224797/artifacts/0/dev/introduction.html#learning-with-examples).

I have given this some thoughts. Maybe we could:
1. update `mini-gallery` so that the main argument selecting gallery items based on whether they use a function or not becomes an optional specification `:filter:` (may require a deprecation cycle?)
2. add an optional specification `:items:`, which, if specified, yields a list of items among which the previous filter will be applied
3. if `:filter:` is not specified, all `:items:` are used to generate the gallery
4. if `:items:` are not specified, all items are filtered
5. either `:items:` or `:filter:` should not be null

**Comment by larsoner** [comment]
Do you see a clean way we could do it without needing any deprecation cycle? It would be nice not to break people's existing use cases

**Comment by drammock** [comment]
> potentially using this in MNE-Python to do stuff like a `See Also` section at the bottom of a given tutorial to suggest other examples people should look at. WDYT @drammock ?

Seems useful, yes!

**Comment by alexisthual** [comment]
> Do you see a clean way we could do it without needing any deprecation cycle? It would be nice not to break people's existing use cases

We could turn the required argument in `mini-gallery` into an optional argument, which wouldn't break current use cases while allowing for new ones.
However, I feel like this would make `mini-gallery` confusing, as it would overstate the importance of this optional argument in comparison to other parameters.

**Comment by larsoner** [comment]
> However, I feel like this would make mini-gallery confusing, as it would overstate the importance of this optional argument in comparison to other parameters.

I think this slight inequality of arguments is worth it to avoid code churn for people.

**Comment by ayshih** [comment]
Writer of `minigallery` here.  I think a much cleaner API than what has been discussed above is to enhance the directive such that each element of the provided list is first checked as an API reference and then as a path to an example.  That is, for the case in the original post, it'd look like:
```
.. minigallery:: section_1/item_3.py section_4/item_2.py
    :add-heading: A list of examples relevant to the section above
```

**Comment by larsoner** [comment]
@story645 sounds reasonable to me!

Now we "just" need a volunteer to work on it :)
