### ISSUE TITLE
Rare data type PyTorch problems

### ISSUE THREAD

**Issue by joacorapela** [sphinx-gallery/sphinx-gallery#1036]
I have a very simple test script that uses PyTorch. 
https://github.com/joacorapela/svGPFA/blob/master/examples/sphinx_gallery/plot_test.py

This script runs without error from the command line.
> ~/svGPFA/repos/svGPFA/examples/sphinx_gallery(master)$ python plot_test.py

But it fails with a PyTorch type error when it is run from sphinx-gallery:
> ~/svGPFA/repos/svGPFA/docs/sphinx(master)$ make html
>
> Extension error:
> Here is a summary of the problems encountered when running the examples
>
> Unexpected failing examples:
> /nfs/ghome/live/rapela/dev/work/ucl/gatsby-swc/gatsby/svGPFA/repos/svGPFA/examples/sphinx_gallery/plot_test.py failed leaving traceback:
> Traceback (most recent call last):
>  File "/nfs/ghome/live/rapela/dev/work/ucl/gatsby-swc/gatsby/svGPFA/repos/svGPFA/examples/sphinx_gallery/plot_test.py", line 49, in <module>
>     em_max_iter=em_max_iter)
>   File "/nfs/ghome/live/rapela/deplot_test.pyv/work/ucl/gatsby-swc/gatsby/svGPFA/repos/svGPFA/src/svGPFA/utils/initUtils.py", line 109, in getDefaultParamsDict
    diag_var_cov0_value)
> TypeError: 'empty' object does not support item assignment

These are the lines around initUtils.py:109 where the error occurs:

>         var_cov0[k] = torch.empty((n_trials, n_ind_points[k], n_ind_points[k]), dtype=torch.double)
>         for r in range(n_trials):
>             var_cov0[k][r, :, :] = torch.eye(n_ind_points[k]) * diag_var_cov0_value                                                                                                                                                       

The error reported by sphinx-gallery (SG) makes no sense, especially since the python script runs without problem from the command line.

Suprisingly, if I copy the code of the function where the error happens to a new module (svGPFA.utils.test.), the error dissappears.

In case it helps, his is my sphinx-gallery configuration:

> sphinx_gallery_conf = {
    'examples_dirs': '../../../examples/sphinx_gallery/',   # path to your example scripts
    'gallery_dirs': 'auto_examples',  # path to where to save gallery generated output
}

All this code can be obtained from a public repo https://github.com/joacorapela/svGPFA

**Comment by larsoner** [comment]
Do you have just one example or many?

One thing SG does is run all examples sequentially in the same interpreter, so if there is some state that can be held between scripts or some resource that can be used up (like GPU memory) then problems like this can happen if `reset_modules` is not utilized/configured properly.

IIRC some other PyTorch projects have used SG, have you looked around at the `conf.py` for those for hints? For exmaple if they set a `reset_modules` to reset some state or prevent from using the GPU at all this might also fix your problem, or tell you what your problem might be

**Comment by joacorapela** [comment]
Thanks for your comments @larsoner. I have only one very simple example.

I realized that [torchvision](https://pytorch.org/vision/stable/auto_examples/index.html) uses SG  I looked at their conf.py and did not recognized anything special.

This is very rare, Now I generated two SG plot functions, one that fails when invoked by `make html` (`plot_test_fails.py`) and the other that succeeds (`plot_test_succeeds.py`). These functions are identical except that the one that fails invokes function `getDefaultParamsDict` in module `svGPFA.utils.initUtils` and the one that succeeds invokes the same function in module `svGPFA.utils.test`. However, these modules are identical to each other.                                                               

As before, when I invoke the SG functions from the command line, they both succeed.

You can reproduce the above statements by following the steps below.


```
conda create --name test python=3.8
conda activate test

git clone --branch develop https://github.com/joacorapela/svGPFA.git
cd svGPFA
pip install -e .[notebook]

conda install -y -c conda-forge sphinx sphinxcontrib-bibtex sphinx-gallery nbsphinx
pip install python-docs-theme

cd docs/sphinx
make html

# Please note that the execution of plot_test_fails.py failed but that of
# plot_test_succeeds.py succeeded.
#
# Also note that plot_test_fails.py and plot_test_succeeds.py are
# identical, with the exception that plot_test_fails.py invokes function
# getDefaultParamsDict in the svGPFA.utils.initUtils module and
# plot_test_succeeds.py invokes this function in the svGPFA.utils.test module.
# This error should not happen as these modules are identical.

diff ../../examples/sphinx_gallery/plot_test_*.py
# 15c15
# import svGPFA.utils.initUtils
# ---
# import svGPFA.utils.test
# 44c44
# < default_params_spec = svGPFA.utils.initUtils.getDefaultParamsDict(
# ---
# > default_params_spec = svGPFA.utils.test.getDefaultParamsDict(
# >

diff ../../src/svGPFA/utils/initUtils.py ../../src/svGPFA/utils/test.py
# no output; i.e., identical files

# Both plot_test_fails.py and plot_test_succeeds.py run without error when
# ivoked from the command line.

cd ../../examples/sphinx_gallery/
python plot_test_fails.py
# Execution succeeded
python plot_test_succeeds.py
# Execution succeeded 
```

**Comment by larsoner** [comment]
In these situations instead of `make html` I use `python -im sphinx ...` and then when it fails I do `import pdb; pdb.pm()` and do some inspection to figure out what failed and why. Can you try it?

**Comment by joacorapela** [comment]
Thanks again @larsoner. The tip for using ``python -m sphinx -j 1 -b html --color -a -n -W source build -vvv`` instead of ``make html`` was very helpful. Specifically, the verbose ``-vvv`` option helped me realize that my ``conf.py`` contained a line ``autodoc_mock_imports = ["torch"]``. I removed this line and everything works fine now. Thanks a lot for your great help @larsoner.

**Comment by larsoner** [comment]
Wow that's tricky -- glad you could figure it out, and thanks for reporting back!
