### ISSUE TITLE
Filter cell outputs

### ISSUE THREAD

**Issue by OverLordGoldDragon** [sphinx-gallery/sphinx-gallery#1043]
I use

```python
from IPython.display import Image, display
_ = display(Image("img.png"))
```

so it also works with `ipynb`. That's inside my `show_visual()` method that also does `shutil.copy` for SG. Problem, SG executes in plain Python so the resulting HTML has both the image and a text blob printed:

```
Out: <IPython.core.display.Image object>
```
and it's not simply `stdout` - [details](https://stackoverflow.com/q/74198138/10133797).

Is there a non-too-hackish way to post-process `.rst` before it's converted to HTML? Sample rst,

```rst
.. image-sg:: /examples-rendered/images/sphx_glr_plot_ex_023.gif
   :alt: plot ex
   :srcset: /examples-rendered/images/sphx_glr_plot_ex_023.gif
   :class: sphx-glr-single-img


.. rst-class:: sphx-glr-script-out

 .. code-block:: none

    <IPython.core.display.Image object>
```

This is only an issue if using `display()`, which I think isn't needed if it's the only image per cell, but a more general solution is preferred.

**Comment by larsoner** [comment]
SG is really meant to work with "pure python" code moreso than pure python + Jupyter / IPython calls. So in some sense I think this is a bit outside our scope and more toward what `nbsphinx` or something would support.

That said, postprocessing RST can be done fairly easily by hooking into the `source-read` event:

https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx-core-events

We even do it in SG to process some files
