### ISSUE TITLE
Option to disable text preview on thumbnail

### ISSUE THREAD

**Issue by HealthyPear** [sphinx-gallery/sphinx-gallery#1044]
I couldn't find a clear description of this in your docs - apologies if I have overlooked it!

I would like to know if I can avoid showing the text in my `examples/sub-dir/README.rst` when crossing the thumbnail with the cursor, namely with my README something like this,

```
=====
Title
=====

blablablablablablablablablablablablablablablablablablablabla
blablablablablablablablablablablablablablablablablablablablablablablabla.
```

 would like to avoid this

<img width="250" alt="image" src="https://user-images.githubusercontent.com/17836610/199079479-bcf85a6d-432b-4b44-889b-631eb17e3b5d.png">

and always have this

<img width="258" alt="image" src="https://user-images.githubusercontent.com/17836610/199079537-6b5a9f67-9eb4-42e1-9458-9f0f6dd001c4.png">

**Comment by larsoner** [comment]
Have you checked to see if you can solve this problem with customized / overridden CSS?

**Comment by HealthyPear** [comment]
As totally ignorant about CSS I didn't even think about it, but if you tell me that for the moment this is the most accessible solution can give it a try.

**Comment by HealthyPear** [comment]
I guess the content I should look for is somewhere in `sphinx_gallery/_static/sg_gallery.css`?

I see entries with the term `hover` and some of them make sense to me, like `--sg-thumb-hover-border: #003975;`, but for the moment I am not able to identify what might enable/disable the text preview.

**Comment by HealthyPear** [comment]
After I added 

```css
/* Disable thumbnail tooltips on hover */
.sphx-glr-thumbcontainer[tooltip]:hover::before,
.sphx-glr-thumbcontainer[tooltip]:hover::after {
    display: none;
}
```

to a `disable_gallery_thumbnail_text.css` file in my `_static` folder, I make sure my `conf.py` file was setup,

```python
html_static_path = ["./_static"]
html_css_files = [
    'disable_gallery_thumbnail_text.css',
]
```

and it worked, many thanks.

Though, I think this feature might be worth a configurable option of this sphinx extension.
At the very least an update of the documentation as an example under `Advanced usage/Altering Sphinx-Gallery CSS`.

**Comment by larsoner** [comment]
In general I think it's better to prefer CSS fixes when possible, it keeps the Python end of the code more maintainable. PR welcome to update the Advanced Usage page, though!
