### ISSUE TITLE
Make preview text longer

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#1066]
The preview text (summary of the example made from the first words of the docstring) could be longer:
![image](https://user-images.githubusercontent.com/208217/213178085-0c95df31-5c38-41b6-84ae-ce0f4746d76e.png)

We should make it much longer and use css to cut (overlap=hidden)

**Comment by anushkabishnoi** [comment]
Hello, this is my first experience with open source contributions. Would really appreciate it if you explained exactly what is needed to be done.

I would love to work on this issue.

Thanks in advance! :)

**Comment by larsoner** [comment]
@anushkabishnoi sorry for the slow response. We generally follow a standard GitHub contribution setup, so feel free to read about how to contribute to scikit-learn, nilearn, matplotlib, MNE-Python, etc. (whichever instructions are clearest/easiest). The TL;DR is that you make a PR with the change, and ideally modify some test that would fail on `master` but pass on your PR (in this case, it could be that the entire > 80 char intro paragraph text shows up in the gallery index for example)

@fgmacedo feel free to give it a shot as well if you want!
