### ISSUE TITLE
Passthrough bare rst, and possibly index.rst

### ISSUE THREAD

**Issue by jklymak** [sphinx-gallery/sphinx-gallery#1067]
Over in Matplotlib we are trying to improve our narrative user docs.  These have traditionally been written in rst, but we have a bunch of tutorials written as sphinx-galleries that we would like to move into our narrative docs.   

First, it would be quite nice if a gallery that had a bare rst in it would pass this through to the doc build.  So if we have `/gallery/subdir/my_interesting_doc.rst` it would just be copied over to `/doc/gallery/subdir/my_interesting_doc.rst` allowing sphinxs to render it there.  Perhaps this is already available somehow, but I didn't see the ability.

Second, it would be nice if _we_ provided `/gallery/subdir/index.rst` that sphinx-gallery didn't bother making its own.  Yes, appreciated that thumbnails etc would not be in the built index page, but those are not always the most useful in narrative docs where you just want the outline rather than a bunch of snapshots.

Is this already all possible and I'm missing something?  If not, it seems relatively straightforward (at least conceptually, I haven't dug into the code), and non-breaking in that folks who don't want this don't have to do it.   Thanks!

**Comment by GaelVaroquaux** [comment]
> First, it would be quite nice if a gallery that had a bare rst in it would pass this through to the doc build. So if we have /gallery/subdir/my_interesting_doc.rst it would just be copied over to /doc/gallery/subdir/my_interesting_doc.rst allowing spins to render it there.

Sounds useful indeed.

> Second, it would be nice if we provided /gallery/subdir/index.rst that sphinx-gallery didn't bother making its own.

Open to that too, IMHO.

**Comment by jklymak** [comment]
Ok I'm half way to implementing this so I'll have a PR in this weekend.  There are a few decisions to make if this rst is to end up having a thumbnail etc.
