### ISSUE TITLE
MAINT: Deprecate Mayavi scraper

### ISSUE THREAD

**Issue by larsoner** [sphinx-gallery/sphinx-gallery#1075]
We have a built in Mayavi scraper. However, given the limited maintenance Mayavi gets, I think we should really deprecate it and tell people how to make their own

_Originally posted by @larsoner in https://github.com/sphinx-gallery/sphinx-gallery/issues/1074#issuecomment-1410931810_

This is motivated by the fact that many of our CI troubles come from Mayavi

**Comment by GaelVaroquaux** [comment]
I agree

**Comment by agramfort** [comment]
+1
