### ISSUE TITLE
The gallery intro is truncated and I want to display more content (is not possible to change the size)

### ISSUE THREAD

**Issue by fgmacedo** [sphinx-gallery/sphinx-gallery#1085]
Hi, first time here, so I want to say thanks for maintaining this project! 

I've found that the `intro` size, the one that is displayed as the tooltip is truncated at `95` chars. 

I've made a [image gallery with large thumbs](https://python-statemachine.readthedocs.io/en/latest/auto_examples/index.html) and It would be nice to have more content on the tooltip.

![image](https://user-images.githubusercontent.com/281007/222931710-202cbf02-5317-4697-850d-545099fd2017.png)

Here's the code that truncates:

Ref: https://github.com/sphinx-gallery/sphinx-gallery/blob/60b4b5b9597efa7957dc4437ae0aa301192f45b3/sphinx_gallery/gen_rst.py#L243-L244

It would be nice if there's some way to get more `intro` content displayed, being a configuration or another way.

Best regards,

**Comment by larsoner** [comment]
I wonder if what we should instead do is use CSS to set overflow text to use ellipsis

https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

WDYT?

**Comment by fgmacedo** [comment]
I like this solution @larsoner , works for me!

**Comment by fgmacedo** [comment]
Closing as duplicated of https://github.com/sphinx-gallery/sphinx-gallery/issues/1066
