### ISSUE TITLE
The "ignore code" flags stop working when `remove_config_comments` is True.

### ISSUE THREAD

**Issue by SimenZhor** [sphinx-gallery/sphinx-gallery#1087]
Hi, this is my first time raising an issue here. Thanks for the work you do on this great plugin.

I've accidentaly noticed that the `# sphinx_gallery_start_ignore`and `# sphinx_gallery_end_ignore` flags appear to stop working when `remove_config_comments` is set to `True`.

This seems to contradict [the documentation](https://sphinx-gallery.github.io/stable/configuration.html#hiding-lines-of-code), which states: 
> These flags and the code between them are always removed, regardless of what remove_config_comments is set to.

I'm using sphinx-gallery 0.11.1 with Sphinx 5.3.0

**Comment by larsoner** [comment]
Can you try latest master? I think this might already be fixed
