### ISSUE TITLE
Extra indentation in output block?

### ISSUE THREAD

**Issue by adrn** [sphinx-gallery/sphinx-gallery#109]
It seems that, for output blocks with more than one line, the first line is indented. Is this a bug, or is there some way to tell sphinx-gallery *not* to do this?

See, for example, http://sphinx-gallery.readthedocs.org/en/latest/auto_examples/plot_strings.html#sphx-glr-auto-examples-plot-strings-py

**Comment by Titan-C** [comment]
Yes this a bug. There should not be this indentation. I'll try to get to it in the next weeks. You are also welcome to try a fix yourself. You would only need to change in sphing_gallery/gen_rst.py the string variable that holds the output and check why it gives the rst file an extra indent

**Comment by GaelVaroquaux** [comment]
It's probably in the CSS.
