### ISSUE TITLE
Choose thumbnail image from multiple figures in same example

### ISSUE THREAD

**Issue by adrn** [sphinx-gallery/sphinx-gallery#110]
Is there a way to choose the thumbnail image figure for examples that generate multiple figures?

**Comment by Titan-C** [comment]
For the moment this feature is not available/designed. It is in our plan. Possible we might implement it by introducing comment flags on the file header to specify if a particular image is to be preferred.

**Comment by lesteve** [comment]
This could work I guess. You would use some kind of number inside the example source code, right, something like:

```python
sphx_glr_fig_number = 3
```

If the variable is not found it would default to 0 to match the current behaviour.

Alternatively we could have a convention that if a variable with an agreed name and of the right type (some kind of matlplotlib figure) is found in the `__main__` namespace then it is used for the gallery thubmnail . I am not convinced it is better though, a bit more complicated and intrusive in the example code.

**Comment by lesteve** [comment]
> You would use some kind of number inside the example source code, right, something like:

I think part of what I was trying to say is that just using a variable in the `__main__` namespace would be simpler than to a magical comment/header that you have to parse.
