### ISSUE TITLE
Update to `jupyterlite-sphinx` 0.8.0

### ISSUE THREAD

**Issue by jtpio** [sphinx-gallery/sphinx-gallery#1103]
Quick heads-up that the latest release of `jupyterlite-sphinx` now depends on a smaller `jupyterlite-core` package by default: https://github.com/jupyterlite/jupyterlite-sphinx/releases/tag/v0.8.0

Which means that the Pyodide kernel should now be installed along `jupyterlite-sphinx`.

It's available on PyPI so it can be installed with `pip install jupyterlite-pyodide-kernel`.

**Comment by jtpio** [comment]
I can put up a PR later today to help with this.

**Comment by lesteve** [comment]
Thanks for the heads-up which I missed completely :wink:

Yep, I realised while trying to put together a draft PR on scikit-learn https://github.com/scikit-learn/scikit-learn/pull/25887#issuecomment-1474080205

I updated the doc in https://github.com/sphinx-gallery/sphinx-gallery/pull/1106 but I did not think of updating the code in sphinx-gallery ...

I'll try to put a PR together quickly!

**Comment by lesteve** [comment]
Done in #1107

**Comment by jtpio** [comment]
Nice thanks!
