### ISSUE TITLE
Uniform abbreviation for "reStructuredText"

### ISSUE THREAD

**Issue by StefRe** [sphinx-gallery/sphinx-gallery#1117]
SG currently uses different abbreviations, e.g. https://sphinx-gallery.github.io/dev/syntax.html:
![image](https://user-images.githubusercontent.com/19879328/228341679-c75cef94-2871-4710-9201-571981f2dbe5.png)

`grep -r --include "*.py" --include "*.rst" -w  "$rst_abbr" | wc -l` reveals the following usages within SG:

- `reST`: 2 occasions
- `ReST`: 2 occasions
- `RST`: 22 occasions
- `rST`: 52 occasions

[docutils](https://docutils.sourceforge.io/rst.html) and [PEP287](https://peps.python.org/pep-0287) don't use any abbreviation at all. [Sphinx](https://www.sphinx-doc.org/en/master/usage/restructuredtext/index.html) uses `reST`, [Wikipedia](https://en.wikipedia.org/wiki/ReStructuredText) lists three variants `RST`, `ReST`, or `reST`.

Being a Sphinx extension I think SG should follow Sphinx and use `reST` throughout. If this is consensus I can make a PR.

**Comment by larsoner** [comment]
Yes feel free. I think following Sphinx with reST makes sense. At least if we change all occurrences to that it'll be easier to change in the future if we decide that version is wrong :)

**Comment by lucyleeow** [comment]
Thank you! This has bothered me in the past.
