### ISSUE TITLE
Commit messages

### ISSUE THREAD

**Issue by StefRe** [sphinx-gallery/sphinx-gallery#1121]
I noticed that starting from Nov 2, 2022,  the commit text contains only the title (and co-authors), the actual body of the commit message is lost when merging into master. Is this intentional?

**Comment by larsoner** [comment]
Yes because we always squash+merge. People generally don't keep clean commits and just using the PR title (plus co-author lines) keeps things clean

**Comment by StefRe** [comment]
Ah, I see - and I always make an effort to write meaningful commit messages and squash before pushing :).
