### ISSUE TITLE
Help with ``String``s

### ISSUE THREAD

**Issue by garrettwrong** [sphinx-gallery/sphinx-gallery#1127]
We are increasingly using gallery examples and I've occasionally run into situations where I want to describe plurals that is giving odd behavior.  Can someone point out what I'm doing wrong and the best way to fix it?  Example code and render below. Thanks!

```
"""
Test Plural
===========
lorem ipsum
"""

# %%
# The ``Thing`` Class
# -------------------
#
# Talk about ``Thing``s.
#
```

<img width="563" alt="Screen Shot 2023-04-06 at 1 52 46 PM" src="https://user-images.githubusercontent.com/47759732/230457673-b3229365-ca7c-4ef8-8960-85fa2b16bc19.png">

**Comment by larsoner** [comment]
I think this is really a reST question more than a SG one, but I think this should work:
```
``B``\ s
```

**Comment by larsoner** [comment]
... at least according to vscode's rendering

<img width="447" alt="Screenshot 2023-04-06 at 1 12 07 PM" src="https://user-images.githubusercontent.com/2365790/230473165-96e371b5-3290-4125-86ac-41b0fdb76d4f.png">

**Comment by garrettwrong** [comment]
Excellent, that seems to work. Sorry I didn't realize it was a pure RST thing. Thank you!
