### ISSUE TITLE
Make a new sphinx-gallery release with JupyterLite integration improvements?

### ISSUE THREAD

**Issue by lesteve** [sphinx-gallery/sphinx-gallery#1129]
I have been trying the JupyterLite integration for scikit-learn in https://github.com/scikit-learn/scikit-learn/pull/25887.

As far as I can see, this is working fine, and it would be great to cut a new spinx-gallery release to have the fix from https://github.com/sphinx-gallery/sphinx-gallery/pull/1115 (The JupyterLite button links were always wrong with the scikit-learn gallery layout ...) and the feature from https://github.com/sphinx-gallery/sphinx-gallery/pull/1113 (ability to add cells to add warnings about JupyterLite and code to make the notebook work in JupyterLite).

Let me know if I can help in any way!

**Comment by larsoner** [comment]
https://pypi.org/project/sphinx-gallery/0.13.0/
