### ISSUE TITLE
Some external functions / classes don't resolve into links

### ISSUE THREAD

**Issue by adrn** [sphinx-gallery/sphinx-gallery#113]
For example, in [this example](http://sphinx-gallery.readthedocs.org/en/latest/auto_examples/plot_exp.html#sphx-glr-auto-examples-plot-exp-py) in the sphinx-gallery gallery, `np.linspace` does not become a link, but all other numpy functions do.

**Comment by lesteve** [comment]
Yeah this limitation is kind of known but I don't think anyone has had the bandwith to look into it in more details ... Insights or PR welcome :-) !

**Comment by dfroger** [comment]
I'm trying to fix this issue too. Here is where I am.

For [the example](http://sphinx-gallery.readthedocs.io/en/latest/auto_examples/plot_exp.html#sphx-glr-auto-examples-plot-exp-py), the code in  [docs_resolv.py](https://github.com/sphinx-gallery/sphinx-gallery/blob/829dc34c1f2b40fc3a4c9738e882892c9c162d8f/sphinx_gallery/docs_resolv.py#L389-L404) behaves like this snippet:

    import re

    names = ['<span>np</span>', '<span>plt</span>', '<span>pd</span>']

    expr = re.compile(r'(?<!\.)\b' +  '|'.join(re.escape(name) for name in names))

    lines = ['<span>x</span> <span>np</span> <span>x</span>',
             '<span>x</span> <span>plt</span> <span>x</span>',
             '<span>x</span> <span>pd</span> <span>x</span>']

    for line in lines:
        print(expr.search(line) is not None)

which prints:

    False
    True
    True

In the `regexp`, word boundary `\b` apply only to first `name` of the `names` list. As `\b` does not matches `<` (first character in `name`), value `name` is not replaced to add `<a href`

The regular expression seems to want to work on something like `np.linspace`, where `(?<!\.)` prevent matching `xxx.np.linspace`, and `\b` to prevent matching `xxxnp.linspace`.

However, the regular expression is not used on something like `np.linspace`, but on:

    <span class="n">np</span><span class="o">.</span><span class="n">linspace</span>

**Comment by lesteve** [comment]
@dfroger this seems like a good lead, sorry not to have answered sooner. Have you had the chance to get to the bottom of this?

**Comment by lesteve** [comment]
I think #214 fixed the regex problem mentioned by @dfroger in https://github.com/sphinx-gallery/sphinx-gallery/issues/113#issuecomment-219239502. The remaining problems I spotted were due to some information missing from searchindex.js. I don't know much about how searchindex.js is built and I am not sure whether our logic for making sense of searchindex.js is to blame.

**Comment by larsoner** [comment]
This issue can be closed, this should have been fixed by the PR that switched to using `intersphinx`

**Comment by lesteve** [comment]
Thanks!
