### ISSUE TITLE
Running example scripts with custom command 

### ISSUE THREAD

**Issue by mrava87** [sphinx-gallery/sphinx-gallery#1149]
Hello, 
Thanks for the great project, I use it for all the documentations of my projects :)

We are currently developing a library for distributed computing with MPI4Py and we would like to have some examples in our Sphinx doc to showcase how to use it. For this we would need to run the examples with mpiexec -n NUMPROC python file.py instead of just python file.py. We were wondering if there is a way to customize the command to run the examples in Sphinx-gallery.

Thanks!

**Comment by larsoner** [comment]
Unfortunately not that I can see -- we don't run the examples in isolated `python` instances but rather parse the `.py` files using `ast` and execute code blocks one by one in the current interpreter (same one running `sphinx-gallery`) :(

**Comment by mrava87** [comment]
Thanks for the quick reply. Good to know more about what happens under the hood. At least we will not spend time trying to find a way, now that we know it is not possible :)

I think we can close this.
