### ISSUE TITLE
Add an "encoding" attribute to _LoggingTee?

### ISSUE THREAD

**Issue by o-laurent** [sphinx-gallery/sphinx-gallery#1150]
Would it be possible to add an "encoding" property or parameter in the  _LoggingTee class? Its value could be "utf-8" for instance, or computed in set_std_and_reset_position.

For information, I am building a gallery with PyTorch Lightning-based scripts. This library (at least its version 1.9.5) uses "sys.stdout.encoding" to print the test results (in pytorch_lightning/loops/dataloader/evaluation_loop.py). If this function is run into the gallery wrapper, sys.stdout is a _LoggingTee which has no "encoding" attribute.

I am not very "proficient" in sys, but it seems that the encoding parameter is a property that is expected and not an eccentricity from the lightning.ai team.

Thank you very much in advance. I can add details if needed.

**Comment by larsoner** [comment]
Yes I think it makes sense to do this! Not sure if it's better to use `sys.__stdout__.encoding` as the value for the `_LoggingTee.encoding`, but I'm inclined just to use `'utf-8'` for now since there are probably places in our code that assume that things are encoded that way already.

**Comment by o-laurent** [comment]
Thanks a lot for the answer. I can make the PR if needed.

**Comment by larsoner** [comment]
Yes feel free!

**Comment by o-laurent** [comment]
Great, I'll add this line. 
As a side comment (but I'm a bit less sure about how to do it), wouldn't it be logical to support all other attributes from classic TextIOs to avoid any future problems?

**Comment by larsoner** [comment]
Yes in principle there is probably compat with some base class we could check. I was thinking something in here:

- https://docs.python.org/3/library/io.html#class-hierarchy

But I'm not sure how hard it would be to support. So I'm also fine with adding things bit by bit as people need them if it's difficult, no need to let the perfect be the enemy of the good here 👍

**Comment by o-laurent** [comment]
As written in #1151, I've tried to include all the attributes that could be expected, along with some "sensible" behaviors. Let me know what you think. Otherwise I will just add the "encoding".
