### ISSUE TITLE
Broken page index with custom gallery order

### ISSUE THREAD

**Issue by oruebel** [sphinx-gallery/sphinx-gallery#1152]
This is in relation to https://github.com/NeurodataWithoutBorders/pynwb/issues/1726 . We are using sphinx-gallery for tutorials for the PyNWB software. PyNWB uses an `ExplicitOrder` for the 'subsection_order' and variant of `ExampleTitleSortKey` to partially fix the 'within_subsection_order' (see [here](https://github.com/NeurodataWithoutBorders/pynwb/blob/d40dd30220e798d34a8fb0b6186771dba477cfd5/docs/source/conf.py#L63-L137) for the relevant config). With sphinx-gallery <=0.10.1 the index of the page is rendered correctly as: 

![Screen Shot 2023-07-19 at 11 52 57 AM](https://github.com/NeurodataWithoutBorders/pynwb/assets/10999845/80373a1c-6676-4b27-8e76-c5feb5f7d3dc)

However with sphinx-gallery 0.11 and above the index does not render correctly, i.e., only the last entry shows sub-section but those sub-sections are the headings of the main sections rather than the correct sub-sections. 

<img width="311" alt="image" src="https://github.com/NeurodataWithoutBorders/pynwb/assets/844306/383e9024-7633-4535-beab-ef86c0745fc3"> 

Looking at the changelog, https://github.com/sphinx-gallery/sphinx-gallery/issues/935 as part of the 0.11 release describes a similar problem. I don't know the sphinx-gallery codebase very well, but I was just wondering whether maybe the fix that was implemented there either triggered or did not cover this issue for our particular case.

**Comment by larsoner** [comment]
It's likely that this is another related bug that still needs to be fixed. Help fixing welcome! @alexisthual if you still remember the code you're welcome to come back to it, too :)

**Comment by alexisthual** [comment]
Sorry I'm a bit hazy on the details now haha.
Maybe explicitly setting `"nested_sections": True,` in your sphinx gallery config (`sphinx_gallery_conf` dict) would help? I don't remember what the default value is.

Moreover, I'm not sure I understand this issue completely: is the nested structure alright (but not well ordered) if you don't use `ExplicitOrder`?

**Comment by oruebel** [comment]
Thanks for the responses!

> Maybe explicitly setting `"nested_sections": True,` in your sphinx gallery config

Unfortunately setting `"nested_sections": True,`did not fix the issue. I tried removing the settings for `subsection order` and `within_subsection_order` but neither of those settings appears to fix the problem.

> is the nested structure alright (but not well ordered) if you don't use `ExplicitOrder`?

The top-level sections are ordered correctly, in our case `General tutorials`, `Domain-specific tutorials`, and `Advanced IO`. However, the galleries within those sections are not listed in the index (see the missing [+] button in the index for  `General tutorials`, `Domain-specific tutorials`) and for whatever is listed as the last section (here `Advanced IO`) the headings of the main sections are listed as the names of the subsections (i.e.,  `General tutorials`, `Domain-specific tutorials`, and `Advanced IO`) rather than the titles of the galleries that are in that section.

**Comment by alexisthual** [comment]
How about `"nested_sections": False` then? :smile:

**Comment by oruebel** [comment]
> How about `"nested_sections": False` then?

Thanks for the help @alexisthual! Setting ``"nested_sections": False`` fixed the issue.
