### ISSUE TITLE
Searching for short module names in backreferences has side effects

### ISSUE THREAD

**Issue by aganders3** [sphinx-gallery/sphinx-gallery#1158]
This came up via a weird problem we were having building [napari docs](https://github.com/napari/docs) on certain platforms. I think this is a pretty niche problem, and in our case was caused partly by [setuptools allowing case-insensitive imports from editable installations](https://github.com/pypa/setuptools/issues/3994) on certain platforms (in our case macOS). I think that will eventually be fixed, but regardless it suggests a possible improvement in sphinx-gallery.

The basic problem is that sphinx-gallery does some importing when searching for short(er) module names in backreferences:
https://github.com/sphinx-gallery/sphinx-gallery/blob/2e1e2a8a23ed8becb737dac15a733f8b93318cda/sphinx_gallery/backreferences.py#L165

This has potential side effects that may affect examples, scrapers, and reset functions.

Unfortunately I don't really know a good way to clean up after such imports or perform them in isolation (subprocesses would be way too slow). You can remove things from `sys.modules`, but imports also get inserted into the namespace of the parent module. There are also ways to use `importlib` to execute the module without importing it, but none of this prevents the module itself from importing others.

All this said, my current best idea is to _only import modules that are already imported_ when looking at backreferences. That is, something like this:
```diff
diff --git a/sphinx_gallery/backreferences.py b/sphinx_gallery/backreferences.py
index 2d070f5..dfc2d9d 100644
--- a/sphinx_gallery/backreferences.py
+++ b/sphinx_gallery/backreferences.py
@@ -14,6 +14,7 @@ from html import escape
 import inspect
 import os
 import re
+import sys
 import warnings
 
 from sphinx.errors import ExtensionError
@@ -163,6 +164,7 @@ class NameFinder(ast.NodeVisitor):
 
 
 def _from_import(a, b):
+    assert a in sys.modules, f'{a} not in sys.modules, not importing it'
     imp_line = f'from {a} import {b}'
     scope = dict()
     with warnings.catch_warnings(record=True):  # swallow warnings
```

This should be safer as it leaves all initial importing up to the user/example code. I think the cost is that it may be a little less aggressive at finding shorter names. I don't think this will generally make a big (or any) difference, but I am also not that familiar with the feature. I did a build with and without this change on the napari docs and couldn't find a meaningful difference in the backrefs. If needed it could be added as a configuration, or maybe an existing configuration already covers this behavior?

I'm happy to hear other ideas here or thoughts on whether this is a real problem at all 😅.

See https://github.com/napari/docs/issues/214 for more discussion - also thanks to @lucyleeow for listening to all my wild theories as I investigated this.

**Comment by larsoner** [comment]
> I'm happy to hear other ideas here or thoughts on whether this is a real problem at all 😅.

Yes it is! I spent a large number of hours fighting a very similar problem with `sphinx.ext.autosummary` and wrote up https://github.com/sphinx-doc/sphinx/issues/11362 -- so I'm not too optimistic about Sphinx doc builds working well on macOS given this case-insensitivity tolerance... That being said, anything we can do at the SG side to make things smoother seems reasonable. In particular the proposed change:

> All this said, my current best idea is to only import modules that are already imported when looking at backreferences.

Seems like a good idea to me. It seems safer / cleaner / faster to me, so if you're up for a PR that would be great!

**Comment by lucyleeow** [comment]
@larsoner do you think it will make much difference in resolving imports? I don't have enough experience to have a good feel for this. Might be good to mention this in the release notes at least

**Comment by lucyleeow** [comment]
I've just remembered how imports work:

>  In this case, Python first tries to import foo, then foo.bar, and finally foo.bar.baz.

ref: https://docs.python.org/3/reference/import.html#searching

So I don't think this should affect resolving imports.

**Comment by larsoner** [comment]
Indeed, I think it should be safe enough
