### ISSUE TITLE
MAINT: Use black and pre-commit

### ISSUE THREAD

**Issue by larsoner** [sphinx-gallery/sphinx-gallery#1162]
We should:

1. Use `black`
2. Use `ruff` instead of flake8 etc (if we don't already)
3. Add both to `pre-commit`
4. Add `pre-commit.ci`

@lucyleeow let me know if this sounds fun/interesting to you and I'm happy to let you do it and give you some pointers. If not then I can do it fairly quickly I think

**Comment by lucyleeow** [comment]
All yours!

**Comment by larsoner** [comment]
I think this is all set now!
