### ISSUE TITLE
How to pass a data path in gallery .py directories that works also for testing

### ISSUE THREAD

**Issue by timonmerk** [sphinx-gallery/sphinx-gallery#1168]
[Sphinx-gallery][1] offers the option to create `.py` files that can be generated into `.ipynb` files and directly execute them for documentation.

I have the following file structure:

    Project/
    |--doc
    |  |--Makefile
    | 
    |--examples
    |  |--data
    |  |--plot_example_1.py
    |  
    |--tests
    |  |--test_run_examples.py

In `plot_example_1.py` I now want to read the example data stored in `data`, and therefore require the path of the current directory.
When first generating the documentation I can resolve it with 

    from pathlib import Path
    
    Path().resolve()

I want to test the examples however additionally using `pytest`. This fails when calling `pytest tests` from the root directory.

Instead I could succesfully test it when adapting the path call to `Path(__file__).absolute()`, but the `__file__` option is not available in the `ipynb` as explained [here][2] 

So I need an option that can resolve the path for both the python file and ipynb. Is there any option for that?

  [1]: https://sphinx-gallery.github.io/stable/index.html
  [2]: https://stackoverflow.com/questions/16771894/python-nameerror-global-name-file-is-not-defined

**Comment by larsoner** [comment]
In MNE-Python for example we have dedicated data fetchers and getters that store to `~/mne_data`. IIRC this was inspired by `sklearn` having similar mechanisms. But for now if I were you, assuming you have `Project/project_name/__init__.py` / standard setup I'd `import project_name` then use `Path(project_name.__file__).parent.parent / 'examples' / 'data'` or so. Assuming people have the `git` repo checked out and installed in editable mode it should work. If they have some other configuration... then they might not even have the `examples` directory at all (e.g., if they `pip install`ed your project and then downloaded the file from the website). Then you need a more fleshed out/complete solution. Or you need to move your `data` to your `project_name` folder someone and distribute with your `sdist`, but that could get big depending on what your data are like.

**Comment by timonmerk** [comment]
Many thanks @larsoner!
