### ISSUE TITLE
Sidebar navigation broken when using v0.11.0 onwards

### ISSUE THREAD

**Issue by leonfoks** [sphinx-gallery/sphinx-gallery#1178]
When I upgrade my sphinx-gallery install from 0.10.1 to anything later, my navigation on the left of the page creates duplicates of all examples nested under the last example that is processed.

All I did to generate the two images below was re-install the version of sphinx-gallery.  My directory structure/files etc. were not touched.

Was the perhaps a change or an update that I've missed?

The upper image is the working version and shows what I expect.  Creating and Interacting each have a single python script inside that correctly render.
The lower image shows the nested nature of the navigation under "Interacting".

This happens for all version 0.11.0 and onwards.

Thanks for any help!

![Working_0 10 1](https://github.com/sphinx-gallery/sphinx-gallery/assets/15173535/9ab080e2-c1db-4d75-b8b5-7788f1d978a0)
![Broken_0 11 0](https://github.com/sphinx-gallery/sphinx-gallery/assets/15173535/e0fce940-a111-4f54-b668-cb34195ce66e)

**Comment by tmillenaar** [comment]
I encountered the same bug. For now I use `'nested_sections': False,` in the `sphinx_gallery_conf` dictionary in `conf.py`,  after the following documentation section:
https://sphinx-gallery.github.io/stable/configuration.html#nesting-gallery-sections

This brings back to the pre 0.11.0 behavior as you show in your screenshots.

**Comment by leonfoks** [comment]
Awesome! Thanks for that.  That works just fine.
