### ISSUE TITLE
Most recent version shows table of content

### ISSUE THREAD

**Issue by Zethson** [sphinx-gallery/sphinx-gallery#1186]
Hi,

I just upgrade my sphinx-gallery version and

```
## Quick start

```{eval-rst}
.. nbgallery::

   notebooks/guide_rna_assignment
   notebooks/mixscape
   notebooks/augur
   notebooks/sccoda
   notebooks/sccoda_extended
   notebooks/tasccoda
   notebooks/milo
   notebooks/dialogue
   notebooks/distances
   notebooks/distance_tests
   notebooks/scgen_perturbation_prediction
   notebooks/scgen_batch_removal
   notebooks/ontology_mapping
```

now displays a table of content
![image](https://github.com/sphinx-gallery/sphinx-gallery/assets/21954664/e344f3ad-6fdc-4a05-a8c8-5942b8f7b37e)

before the gallery, whereas before it only showed the gallery

![image](https://github.com/sphinx-gallery/sphinx-gallery/assets/21954664/aad70afc-2091-44b2-84df-74069f0f3a40)

Is this intended? Did you change a default somewhere?

**Comment by larsoner** [comment]
I see that you're using `nbgallery`, can you raise the issue there? I think that is their directive
