### ISSUE TITLE
Debug Example Gallery Sorting

### ISSUE THREAD

**Issue by timonmerk** [sphinx-gallery/sphinx-gallery#1190]
I am building a sphinx gallery with different examples files, and try to sort the examples.

According to the [documentation ](https://sphinx-gallery.github.io/stable/configuration.html#sub-gallery-order)this should be possible by passing the `subsection_order` key to the `sphinx_gallery_conf` dictionary.

But 

```
sphinx_gallery_conf = {
    'within_subsection_order': sphinx_gallery.sorting.FileNameSortKey,
}

```
won't give the expected results.

Things I also tried:
 - naming the examples in numerical oder: plot_0, plot_1, etc.
 - passing `ExplicitOrder`

but it won't give the desired results.

The files I include in the examples:

["../../examples/plot_0_first_demo", 
"../../examples/plot_1_example_BIDS",
"../../examples/plot_2_example_add_feature",
"../../examples/plot_3_example_sharpwave_analysis",
"../../examples/plot_4_example_gridPointProjection",
"../../examples/plot_5_example_rmap_computing",
"../../examples/plot_6_real_time_demo"]

The output is however not in that order and starts with plot_5.

Code: https://github.com/neuromodulation/py_neuromodulation/blob/main/docs/source/conf.py
ReadTheDocs rendered documentation: https://py-neuromodulation.readthedocs.io/en/latest/auto_examples/index.html

**Comment by larsoner** [comment]
We might have some bug... if you nest one more directory level like `../../examples/test/plot_*` does it work? It's possible we are only nesting subsections (e.g., `examples/test/*`) properly and not sections (e.g., `examples/*`)

**Comment by timonmerk** [comment]
Thanks for the comment @larsoner. Unfortunately the added subsection did not fix it.

I also checked if I put random paths with non-existent examples, and it still does not give a warning or an error.

I would be happy to debug this further. How do you commonly debug the sphinx-build? I just used the makefile `make html` or `sphinx-build` command. It would be helpful to run this in Python to check the ordering of the examples at some point.

Just for completeness:
 - sphinx version: 7.2.4
 - sphinx-gallery version: 0.14.0 (and also 0.13.0 tested)

**Comment by timonmerk** [comment]
Thanks a lot @larsoner. I found the issue, I did not want to sort gallery subsections but only the gallery examples. Therefore I used the wrong keyword `subsection_order` instead of `within_subsection_order`.

The documentation is actually clear abou that. I just overlooked the difference between the two. Thanks again!
