### ISSUE TITLE
Question: how to remove Notebook download?

### ISSUE THREAD

**Issue by jeertmans** [sphinx-gallery/sphinx-gallery#1205]
Hello,

I checked the docs and the issues, but I could not find information about how to remove the "Download Jupyter Notebook". My point is that the code provided in my examples gallery is likely going to fail when run in a notebook, so I just want to remove the download button, and keep the Python files only.

Is it possible?

**Comment by larsoner** [comment]
Did you try https://sphinx-gallery.github.io/stable/advanced.html#hide-the-download-buttons-in-the-example-headers ? FWIW linked issues searching "hide download" for me turned up https://github.com/sphinx-gallery/sphinx-gallery/pull/1131 and https://github.com/sphinx-gallery/sphinx-gallery/issues/949, perhaps you searched only the open issues? Github defaults to prepending `is:issue is:open ` to the issue search field so it might have caused you to miss them

**Comment by jeertmans** [comment]
Well, yes I found the first one, but I thought it was a bit of a hacky solution,
and thought there would be a more "Pythonic" way (i.e., using the `conf.py`).

But it works :-)

```css
div.sphx-glr-download-jupyter {
    display: none;
}
```

in `docs/source/_static/custom.css` and

```python
html_static_path = ["_static"]
html_css_files = ["custom.css"]
```

in `docs/source/conf.py`.

Thanks!
