### ISSUE TITLE
Rename README.rst to gallery_header.rst

### ISSUE THREAD

**Issue by timhoffm** [sphinx-gallery/sphinx-gallery#1209]
Using the name `README` for the gallery header is slightly misleading. READMEs typically contain instructions/context information directed at the user of the source code. But as it is used in sphinx gallery, it’s just regular content to be inserted into the gallery overview page.

I suggest to introduce a more telling name, e.g. `gallery_header.txt/rst` and advertise it as the recommended name. README may continue as a fallback to maintain backward compatibility.

**Comment by lucyleeow** [comment]
I'm okay with this.

**Comment by larsoner** [comment]
Agreed I think we can look for `gallery_header.txt/rst` first and if there, use it, if not, use `README.txt/rst`.
