### ISSUE TITLE
Order dependence with Jupyterlite

### ISSUE THREAD

**Issue by vnmabus** [sphinx-gallery/sphinx-gallery#1211]
I am used to assume that the order in which Sphinx extensions are listed does not matter. That does not seem to be the case with extensions "jupyterlite_sphinx" and "sphinx_gallery.gen_gallery".  At least for me "jupyterlite_sphinx" needs to be listed after "sphinx_gallery.gen_gallery".

Either this dependence on the order should be removed, or it should be clearly noted in the documentation (maybe with a warning box). I wasted too much time on figuring this on my own.

**Comment by lesteve** [comment]
Thanks for reporting this, I'll try to have a look!

**Comment by lesteve** [comment]
I am not able to reproduce the issue, could you add some more info, in particular:

- how does the issue manifest itself, is this an error during the build (in which case add the full error), is this something else?
- conda list or pip list output, in particular to see the version of sphinx-gallery and jupyterlite-related package
- a project where you reproduce the issue

**Comment by vnmabus** [comment]
Sorry, I have not been very clear. It was not an issue during compilation, but a 404 error when loading the notebook on Jupyterlite, as the file was missing (maybe because the Jupyterlite extension executed itself before sphinx-gallery creates the file?). If you do another compilation without cleaning beforehand it works, which also points in that direction.

I cannot access my Python environment right now, I will add the version details when I can.

**Comment by lesteve** [comment]
OK thanks for the additional details, I have managed to reproduce, I think this is a priority thing between the sphinx extensions.

**Comment by lesteve** [comment]
I opened #1213 to fix this, not sure if this is easily testable.
