### ISSUE TITLE
Doc: document testing

### ISSUE THREAD

**Issue by story645** [sphinx-gallery/sphinx-gallery#1222]
I'm struggling with figuring out how to add tests using the tinybuild framework and would find it really useful if there was a paragraph or two explaining how the tinybuild tests work and how to add to them.

**Comment by larsoner** [comment]
TL;DR is that tinybuild is designed as a minimal full sphinx doc build that you can run with `make html` from the tinybuild/doc to get a traditional build experience, but also gets run in test_full.py so you can check for html or rst output. So basically you can think of stuff in test_full.py as pytests that have access to a full site built with sphinx-build.

One gotcha at the moment is that you might need to run `make clean` in tinybuild/doc for the pytest version to run properly

**Comment by lucyleeow** [comment]
We don't really have a guide to contributing section, but docs welcome. Maybe as a first step we could add some notes to the start of `test_full.py`

**Comment by lucyleeow** [comment]
Sounds good to me, thanks!
