### ISSUE TITLE
[Maint] Add HTML parsing library as a testing dependency

### ISSUE THREAD

**Issue by story645** [sphinx-gallery/sphinx-gallery#1228]
Not sure where to ask about this, but would it be ok to add beautifulsoup as a dependency for testing? My question is cause the line-number based parsing in `test_full` is a bit brittle. I'm trying to write a line-independent parser for #1226, but figure beautifulsoup or a similar tool would be cleaner.

**Comment by larsoner** [comment]
Sure beautifulsoup or scrapy or whatever makes the job easy seems okay
