### ISSUE TITLE
Sub-folder gallery TOC header missing in PST theme

### ISSUE THREAD

**Issue by lucyleeow** [sphinx-gallery/sphinx-gallery#1262]
I noticed that in the LHS contents menubar there is no sub-folder gallery name. E.g. our `examples/no_output` examples start with 'A short Python script', but there is no header to indicate the start of the 'no output' sub-gallery. (The RHS 'on this page' menu does show the 2 galleries but I think that's because that is what the headings in that `index` page are.)

![image](https://github.com/sphinx-gallery/sphinx-gallery/assets/23182829/83afa90c-2a8f-4a27-bbf3-dc286fefdd87)

Having a look at wayback machine, this is what it used to look like in the old theme:

![image](https://github.com/sphinx-gallery/sphinx-gallery/assets/23182829/9204c906-281e-41cc-b8f1-95190cad6ff1)

So maybe it's a CSS change? I'm not very familiar with this, maybe @drammock would have an insight?

**Comment by larsoner** [comment]
So you want it to look more like https://mne.tools/dev/auto_tutorials/intro/15_inplace.html ?

![image](https://github.com/sphinx-gallery/sphinx-gallery/assets/2365790/a3a74a0d-3925-42ba-85b7-c251c2b596fd)

If so then it must be something about us using PST differently in MNE-Python than in SG

**Comment by lucyleeow** [comment]
After more time than I care to admit it seems that `"nested_sections": True,` fixes the problem:

![image](https://github.com/sphinx-gallery/sphinx-gallery/assets/23182829/8f79ea0e-ff90-4a77-b04d-c060dc6f4751)

and the gallery seems to render fine.

@alexisthual you describe why you set `"nested_sections": False,` here: https://github.com/sphinx-gallery/sphinx-gallery/pull/944#discussion_r916603188

I'm not exactly sure what you meant by the 'two toc trees' but with `"nested_sections": True,` I got the following 2 toc trees:

```rst
.. toctree::
   :hidden:

   /auto_examples/local_module
   /auto_examples/plot_0_sin
   /auto_examples/plot_1_exp
   /auto_examples/plot_2_seaborn
   /auto_examples/plot_3_capture_repr
   /auto_examples/plot_4_choose_thumbnail
   /auto_examples/plot_4b_provide_thumbnail
   /auto_examples/plot_5_unicode_everywhere
   /auto_examples/plot_6_function_identifier
   /auto_examples/plot_7_sys_argv
   /auto_examples/plot_8_animations
```
and
```rst
.. toctree::
   :hidden:
   :includehidden:


   /auto_examples/no_output/index.rst
```

`"nested_sections": False,` gives the following 2 toc trees:

```rst
.. toctree::
   :hidden:

   /auto_examples/local_module
   /auto_examples/plot_0_sin
   /auto_examples/plot_1_exp
   /auto_examples/plot_2_seaborn
   /auto_examples/plot_3_capture_repr
   /auto_examples/plot_4_choose_thumbnail
   /auto_examples/plot_4b_provide_thumbnail
   /auto_examples/plot_5_unicode_everywhere
   /auto_examples/plot_6_function_identifier
   /auto_examples/plot_7_sys_argv
   /auto_examples/plot_8_animations
```
and
```rst
.. toctree::
   :hidden:

   /auto_examples/no_output/just_code
   /auto_examples/no_output/plot_raise
   /auto_examples/no_output/plot_strings
   /auto_examples/no_output/plot_syntaxerror
```
Do you remember what the problem was in more detail? There were 2 toctrees for me in both cases. What does nilearn root `index.rst` look like?

**Comment by alexisthual** [comment]
> Do you remember what the problem was in more detail? There were 2 toctrees for me in both cases. What does nilearn root `index.rst` look like?

Sorry, I don't remember precisely what the problem was. I quickly went through the issue and PR again, and saw that I had mentioned these 2 toctrees elsewhere https://github.com/sphinx-gallery/sphinx-gallery/issues/935#issuecomment-1089382208 but I'm hazy on the details now.

Adopting nilearn's organization could indeed make things simpler: the root `index.rst` file is a simple `README.txt` containing only the gallery's title, and each example is stored in a sub-folder grouping all examples of a given sub-category. Each sub-category has its own `README.rst` file containing only the sub-category's title.

**Comment by alexisthual** [comment]
Oh, ok! Looking at generated files from about 1 year ago on my local machine, the only toctree in nilearn's root `index.rst` file looks like this:

```
.. toctree::
   :hidden:
   :includehidden:


   /auto_examples/00_tutorials/index.rst
   /auto_examples/01_plotting/index.rst
   /auto_examples/02_decoding/index.rst
   /auto_examples/03_connectivity/index.rst
   /auto_examples/04_glm_first_level/index.rst
   /auto_examples/05_glm_second_level/index.rst
   /auto_examples/06_manipulating_images/index.rst
   /auto_examples/07_advanced/index.rst
```

Moreover, the only toctree in `00_tutorials/index.rst` looks like this:

```
.. toctree::
   :hidden:

   /auto_examples/00_tutorials/plot_python_101
   /auto_examples/00_tutorials/plot_nilearn_101
   /auto_examples/00_tutorials/plot_3d_and_4d_niimg
   /auto_examples/00_tutorials/plot_decoding_tutorial
   /auto_examples/00_tutorials/plot_single_subject_single_run
```

I hope this helps!

**Comment by lucyleeow** [comment]
Interesting, it must be a theme thing then...
