### ISSUE TITLE
Section labels should be inserted in the index.rst of the gallery

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#127]
Right now, it is not possible to point to the different sections of the gallery using the :ref:`label` syntax of sphinx.

Sphinx-gallery should insert section labels in the index.rst. It should probably prefix the names with sphx_glr, as it does in the examples.

**Comment by Titan-C** [comment]
This is not entirely true. You actually write for each example section a README.txt file which has all RestructuredText syntax and you can put the labels you require.

It is nevertheless possible to put an additional label before it section following the name of the directory that generates the example.
