### ISSUE TITLE
Get access to comment-based configuration in the scraper

### ISSUE THREAD

**Issue by almarklein** [sphinx-gallery/sphinx-gallery#1274]
sphinx-gallery has some per-file configuration using comments that start with `# sphinx_gallery_xxx`. This can also be leveraged for using custom configuration, e.g. to benefit from the option to remove such comments from the source shown in the gallery.

I also noticed that sphinx-gallery "sees" my custom comments, and is parsing them. At one time I had something like `# sphinx_gallery_pygfx_docs = screenshot` and Sphinx produced a warning: `sphinx_gallery_pygfx_docs value is not valid Python: screenshot`: I should've put quotes around it.

Since Sphinx parses my custom config comments, I expected them to be available in the scraper, saving me from detecting and parsing these comments myself. However, I could not find how to do this.

Would it be feasible to add this information, e.g. to the `block_vars`?

**Comment by lucyleeow** [comment]
Would using our [`extract_file_config`](https://github.com/sphinx-gallery/sphinx-gallery/blob/fda9674f1d279f26859d0c0221868f6bbdae8b66/sphinx_gallery/py_source_parser.py#L133) on the `block` argument work?

**Comment by almarklein** [comment]
Yes! That works!

**Comment by almarklein** [comment]
Thanks! 🙏
