### ISSUE TITLE
Create a zip file with all examples as Python scripts and notebooks

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#128]
It would be useful to have a zip file accessible from the top of the gallery containing all examples as Python scripts and notebooks.

This zip file should be inserted in the index.rst using the download sphinx command (http://www.sphinx-doc.org/en/stable/markup/inline.html#referencing-downloadable-files)

**Comment by banilo** [comment]
+1 That would be very helpful IMHO, not only for workshops, but also individual users.

**Comment by Titan-C** [comment]
closed with #132
