### ISSUE TITLE
Allow configuration of sort orders in a way that does not mess with the sphinx cache

### ISSUE THREAD

**Issue by maxnoe** [sphinx-gallery/sphinx-gallery#1286]
Using a configuration like this:

```
sphinx_gallery_conf = {
    "within_subsection_order": FileNameSortKey,
}
```

Results in unecessary rebuilds and also in a warning using the latest sphinx, because this config is not serializable:

```
from sphinx.confing import is_serializable
assert is_serializable(sphinx_gallery_conf)
```

The warning emitted with sphinx 7.3.5 is:

```

looking for now-outdated files... none found
WARNING: cannot cache unpickable configuration value: 'sphinx_gallery_conf'
pickling environment... done
checking consistency... done
preparing documents... done
```

One way would be using strings with a registry of types:

```
sphinx_gallery_conf = {
    "within_subsection_order": "filename_sort_key",
}
```

to still allow users to pass their own implementations, you could use something like:

```
sort_keys = {}

class SortKey:
    def __init_subclass__(cls, config_name):
        if config_name in sort_keys:
            raise ValueError("config_name must be unique")
       sort_keys[config_name] = cls

class FilenameSortKey(SortKey, config_name="filename_sort_key"):
    def __call__(self, filename):
         return filename
```

**Comment by larsoner** [comment]
I'd rather make the `SortKey` class (and subclasses) pass `is_serializable` if at all possible. Any idea if it's doable? I haven't looked at the Sphinx code yet to see what they require

**Comment by larsoner** [comment]
Okay looks like the `class` stuff probably won't work well.

> One way would be using strings with a registry of types:

Thinking about how to support `str` cleanly, maybe we can get away without a registry:

1. If there are no dots in the string then we could pull it out of the namespace of `conf.py` (I assume there's a way to get access to this namespace?)
2. If there are dots in the name assume you import get the function/whatever `"x.y.z"` as `from x.y import z` or similar.

I think this allow people to get a compatible config with by changing `'within_subsection_order': FileNameSortKey,` to `'within_subsection_order': "FileNameSortKey",` for example, i.e., just stringify the thing if it's in the namespace. And if it's something custom `"my_module.utils.MySortKey"` or whatever could be used.

**Comment by AA-Turner** [comment]
> (I assume there's a way to get access to this namespace?)

The ``conf.py`` is stored as ``Config._raw_config`` (``app.config._raw_config``). This is private, though, so if you do use it please add some sort of guard in case the name or type changes.

We do intend at some point to move to static configuration (``Sphinx.toml`` or etc), so the fully-qualified import style might be preferable.

A
