### ISSUE TITLE
ENH: Allow a plain list as subsection_order configuration

### ISSUE THREAD

**Issue by timhoffm** [sphinx-gallery/sphinx-gallery#1293]
https://sphinx-gallery.github.io/stable/configuration.html#sorting-gallery-subsections suggests

```
from sphinx_gallery.sorting import ExplicitOrder
sphinx_gallery_conf = {
    ...
    'examples_dirs': ['../examples','../tutorials'],
    'subsection_order': ExplicitOrder(['../examples/sin_func',
                                       '../examples/no_output',
                                       '../tutorials/seaborn']),
}
```

I propose to make this work without `ExplicitOrder` and accept the following as well for convenience.
```
sphinx_gallery_conf = {
    ...
    'examples_dirs': ['../examples','../tutorials'],
    'subsection_order': ['../examples/sin_func',
                         '../examples/no_output',
                         '../tutorials/seaborn'],
}

```

**Motivation:** It's simpler and more readable. Option to later deprecate `ExplicitOrder` and make the public interface smaller.

Implementation-wise it would be sufficient to add

```
if isinstance(sortkey, list):
    sortkey = ExplicitOrder(sortkey)
```
right below

https://github.com/sphinx-gallery/sphinx-gallery/blob/8af7edba9439ed000eeb5c4f216535becea54a35/sphinx_gallery/gen_gallery.py#L490

**Comment by lucyleeow** [comment]
+0

**Comment by larsoner** [comment]
Sure, worth adding after #1289 lands. The logic might have to be tweaked a little bit

**Comment by lucyleeow** [comment]
We can update this to a serializable:

https://github.com/sphinx-gallery/sphinx-gallery/blob/0b243bf714bd15a8d9c7b0a472e6ea442f7a7d01/doc/configuration.rst?plain=1#L376-L378

I don't think there would be a serializable way to do this currently.

**Comment by larsoner** [comment]
I *think* an instance of that class would already be serializable. That command might still work fine actually.

What's problematic are classes themselves, and instances of classes where the classes themselves are defined in conf.py.

The big push toward strings also has to do with future compatibility with a static configuration, though, which this would help with

**Comment by larsoner** [comment]
... or to put it in code:
```
>>> from sphinx.config import is_serializable
>>> from sphinx_gallery.sorting import ExplicitOrder
>>> x = dict(a=ExplicitOrder(['b']))
>>> is_serializable(x)
True
```
So this change wouldn't be necessary for serialization purposes. But it would be nice for static `.toml` purposes (and for simplicity / readability as pointed out above).

**Comment by timhoffm** [comment]
On a side note, there are likely not too many other classes used out there:

Trying to regex "instantiation of a class `*Order`" that is not `ExplicitOrder` only yields `SubSectionTitleOrder` used in scikit-learn

https://github.com/search?q=%2F%27subsection_order%27%3A+%5B%5EE%5D%5Cw%2BOrder%5C%28%2F&type=code&p=2

Others seem to only have moved ExplicitOrder in a variable

/'subsection_order': [^E]\w+Order,/

And there is https://github.com/matplotlib/matplotlib/blob/eb62d6951a5d7657fe006bb919cbae08481023e2/doc/sphinxext/gallery_order.py which extends ExplicitOrder so that one can put files at the end explicitly.

While this is not an exhaustive survey, practical usage custom ordering classes seems limited.

---

Semi-OT: One could consider enhancing the list semantics.

1. Use `'*'` as a placeholder for not listed elements. This achieves the same thing as the `MplExplicitOrder` subclass. One could then specify `['first_section', 'second_secion', '*', 'last_section']`
2. If we have `'*'`, we could also error out on not-listed sections. Currently there's the danger that sections were renamed or added without updating 'subsection_order'. We could change the behavior to make it mandatory to specify all subsections in the list and error out if there is a subsection that is not listed or if there is a listed subsection that does not exist. - I believe usually, there are little enough subsections so that an explicit listing of all is desireable. And the people, who don't care, can simply add '*' to the list to indicate "all not given sections go here".

I believe this would only require a couple of lines of additional code inside sphinx gallery. But should make subsections more managable.

**Comment by larsoner** [comment]
Sounds like useful changes/additions to me!

**Comment by lucyleeow** [comment]
For future reference sphinx specifies un-serializables as:

```python
UNSERIALIZABLE_TYPES = (type, types.ModuleType, types.FunctionType)
```
