### ISSUE TITLE
Add some output to stdout in one of the plot_ example

### ISSUE THREAD

**Issue by lesteve** [sphinx-gallery/sphinx-gallery#13]
in order to show the functionality that the stdout is captured and shown on the example page.

Also while I am at it seems that nilearn gen_rst.py has a small tweak to restrict the max-height of the output div (I am guessing around [there](https://github.com/nilearn/nilearn/blob/master/doc/sphinxext/gen_rst.py#L792)). For example this [example](http://nilearn.github.io/auto_examples/connectivity/plot_adhd_covariance.html#example-connectivity-plot-adhd-covariance-py) has a lot of output.

**Comment by Titan-C** [comment]
Example included in SHA: d5a8b2dbf56cad7362c5ffe31c8b89975452fe5e
