### ISSUE TITLE
WARNING: duplicate label computation times, other instance in ...

### ISSUE THREAD

**Issue by MLopez-Ibanez** [sphinx-gallery/sphinx-gallery#1302]
For this setup: https://github.com/multi-objective/mooplot/tree/main/python

`sphinx-gallery` creates two `sg_execution_times.rst`, one under `doc/source/` and another under `doc/source/auto_examples/`.

This causes:

```
reading sources... [100%] sg_execution_times
/home/manu/work/perfassess/mooplot/python/doc/source/sg_execution_times.rst:8: WARNING: duplicate label computation times, other instance in /home/manu/work/perfassess/mooplot/python/doc/source/auto_examples/sg_execution_times.rst
```

I am not sure how to avoid this warning since those files are completely generated by `sphinx-gallery`.

**Comment by lucyleeow** [comment]
Does any of these help: https://stackoverflow.com/questions/62631362/get-rid-of-duplicate-label-warning-in-sphinx

Both these files have the same header (which makes sense) and it seems like `autosectionlabel` may be the cause?

**Comment by lucyleeow** [comment]
Any update?

**Comment by MLopez-Ibanez** [comment]
Indeed, `autosectionlabel` was the issue. Sorry for the noise.
