### ISSUE TITLE
`minigallery` does not look at `.examples.new`

### ISSUE THREAD

**Issue by Charlie-XIAO** [sphinx-gallery/sphinx-gallery#1309]
As described in the title, `minigallery` does not seem to look at only `.examples` but not `.examples.new`. By the way I'm wondering in which conditions will I have contents only in `.examples.new` while having an empty `.examples`?

**Comment by lucyleeow** [comment]
> I'm wondering in which conditions will I have contents only in .examples.new while having an empty .examples

I don't think this should happen unless there was an error/problem. It could happen due to file system case insensitivity:

https://github.com/sphinx-gallery/sphinx-gallery/blob/85f9a3a315917a1f6c6099ebabccafde4ed2db54/sphinx_gallery/backreferences.py#L440-L446

**Comment by Charlie-XIAO** [comment]
Okay thanks, I'll take a look :)

**Comment by Charlie-XIAO** [comment]
It still sometimes happens on my local Windows machine, but never happens in the GitHub workflow. I would think it's some issue with my computer instead of with `sphinx-gallery`, so I'm closing :)

**Comment by lucyleeow** [comment]
I think windows is case insensitive so that makes sense?
