### ISSUE TITLE
requirements.txt not completely removed

### ISSUE THREAD

**Issue by AlexSzatmary** [sphinx-gallery/sphinx-gallery#1316]
Several sphinx-gallery source files mention `requirements.txt` but that file is not in the repo. I think it was removed in connection to adopting `pyproject.toml`. As a result, some instructions do not work, such as,

`pip install -r requirements.txt -r dev-requirements.txt `
in `README.rst`.

Instructions could be revised to instead say something like, `pip install sphinx-gallery "sphinx>=4.0" pillow` (also in `README.rst`).

It would be better if the requirements were only listed in one place. I think that would be possible and if done correctly, you could tell devs to do something like, `python -m pip install --verbose --no-build-isolation --editable ".[dev]"` (which is how Matplotlib does it).

**Comment by lucyleeow** [comment]
+1

**Comment by drammock** [comment]
this was fixed by #1317 and can be closed.
