### ISSUE TITLE
The minigallery directive always resolves empty

### ISSUE THREAD

**Issue by TamaraAtanasoska** [sphinx-gallery/sphinx-gallery#1340]
I have been trying to implement an example `minigallery` in `fairlearn`, a project I contribute to.
The discussion started as part of [this PR](https://github.com/fairlearn/fairlearn/pull/1359), which already proposed a solution that wasn't correctly resolving. 

I explored ways to fix this [in this branch](https://github.com/TamaraAtanasoska/fairlearn/tree/example-gallery), most relevant commit with the changes that didn't help [can be found here](https://github.com/fairlearn/fairlearn/commit/fe21af16b1a9771a21f442633e8cc2909a08e7e9).

Compared to the implementation in other projects I can't find something that is greatly different. Do you maybe have an idea what the issue could be? Maybe an interaction with another extension, `autodoc` structure, or some path that is off?

Thanks in advance for looking into it!

**Comment by larsoner** [comment]
One thing to check is do the `modules/generated/backreferences/*.examples` files exist? For example here is what the directory looks like for sphinx-gallery's `tinybuild`:
```
sphinx_gallery/tests/tinybuild/doc$ ls gen_modules/backreferences/
sphinx_gallery.backreferences.DummyClass.examples                       sphinx_gallery.gen_rst.execute_code_block.examples
sphinx_gallery.backreferences.DummyClass.prop.examples                  sphinx_gallery.gen_rst.execute_script.examples
sphinx_gallery.backreferences.DummyClass.run.examples                   sphinx_gallery.gen_rst.extract_intro_and_title.examples
...
```

**Comment by TamaraAtanasoska** [comment]
> One thing to check is do the `modules/generated/backreferences/*.examples` files exist? For example here is what the directory looks like for sphinx-gallery's `tinybuild`:
> 
> ```
> sphinx_gallery/tests/tinybuild/doc$ ls gen_modules/backreferences/
> sphinx_gallery.backreferences.DummyClass.examples                       sphinx_gallery.gen_rst.execute_code_block.examples
> sphinx_gallery.backreferences.DummyClass.prop.examples                  sphinx_gallery.gen_rst.execute_script.examples
> sphinx_gallery.backreferences.DummyClass.run.examples                   sphinx_gallery.gen_rst.extract_intro_and_title.examples
> ...
> ```

Thanks for replying so fast! They exist, found in `docs/modules/generated/` in our case, as specified in `conf.py`.

**Comment by larsoner** [comment]
One possibility is that your templates are not actually being used, so I would next check that your templates are actually being used by putting some text in them like `TEST SHOULD BE HERE` that you should see in the output. FWIW I typically just put them in `templates/autosummary/*.rst` then they automatically get used instead of you needing to specify them with `:template:` in your autodoc.

**Comment by TamaraAtanasoska** [comment]
> TEST SHOULD BE HERE

All the templates are being used. Everything seems to resolve right that is set there, just the `minigallery` doesn't. I have also tried to follow the example of directly specifying it in files and hardcoding the example, but it doesn't resolve outside of the templates too. I found another comment that hints to another person having a similar problem [here](https://github.com/pvlib/pvlib-python/blob/55e0a36fac1e3931b92f5f11508f6c09d903e0cc/docs/sphinx/source/_templates/autosummary/class.rst?plain=1#L31) when lurking around the available repos on GitHub, although they didn't provide a solution :)

**Comment by lucyleeow** [comment]
I tested the docs in fairlearn, adding to the `config.py`:

```python
    "backreferences_dir": os.path.join("modules", "generated"),
    "doc_module": ("fairlearn",),
```

and using your `class.rst` template from: https://github.com/fairlearn/fairlearn/commit/fe21af16b1a9771a21f442633e8cc2909a08e7e9 . This is `fairlearn.preprocessing.CorrelationRemover`:

![image](https://github.com/sphinx-gallery/sphinx-gallery/assets/23182829/e16d4cd1-5492-4a3c-a239-630eb2514635)

Note that if there are no examples that have used a specific function, the `.examples` file will be empty.

**Comment by TamaraAtanasoska** [comment]
> I tested the docs in fairlearn, adding to the `config.py`:
> 
> ```python
>     "backreferences_dir": os.path.join("modules", "generated"),
>     "doc_module": ("fairlearn",),
> ```
> 
> and using your `class.rst` template from: [fairlearn/fairlearn@fe21af1](https://github.com/fairlearn/fairlearn/commit/fe21af16b1a9771a21f442633e8cc2909a08e7e9) . This is `fairlearn.preprocessing.CorrelationRemover`:
> 
> ![image](https://private-user-images.githubusercontent.com/23182829/343008604-e16d4cd1-5492-4a3c-a239-630eb2514635.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzY5NDAsIm5iZiI6MTcxOTM3NjY0MCwicGF0aCI6Ii8yMzE4MjgyOS8zNDMwMDg2MDQtZTE2ZDRjZDEtNTQ5Mi00YTNjLWEyMzktNjMwZWIyNTE0NjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA0MzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YzQ4NGMxZmRlNDdhMGEwMWI2YWU0NmRkY2RhZmU2ZmNhZDk3MGYzZWMxMGU3ZTAwNjY1MDg4ODNjYzM5MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MxAZQPpWoCYgzrP2sDykdSg__iVU7hjM3O9awcTI7z4)
> 
> Note that if there are no examples that have used a specific function, the `.examples` file will be empty (and nothing will be added).

Thank you for checking! For me building the branch it still looks completely empty everywhere. I tried also just the minimal changes that work for you without the `index.rst` restrcuture and it is still not showing anywhere. Is it maybe a package versioning issue? Below the sphinx related packages and their versions:
```

# Name                    Version                   Build  Channel
pydata-sphinx-theme       0.14.1                   pypi_0    pypi
sphinx                    7.2.6                    pypi_0    pypi
sphinx-autodoc-typehints  2.0.1                    pypi_0    pypi
sphinx-copybutton         0.5.2                    pypi_0    pypi
sphinx-gallery            0.16.0                   pypi_0    pypi
sphinx-prompt             1.8.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.8                    pypi_0    pypi
sphinxcontrib-bibtex      2.6.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.6                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.5                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.7                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.10                   pypi_0    pypi
```

**Comment by TamaraAtanasoska** [comment]
Update: I cloned the conda env and upgraded everything that was a bit behind, but it doesn't solve the issue. I am sure this isn't just the case for me, as the person starting the PR that I took over had the same issue ([relevant comment](https://github.com/fairlearn/fairlearn/pull/1359#issuecomment-2115660617)),

**Comment by lucyleeow** [comment]
My environment seems similar to yours:
```
pydata-sphinx-theme       0.14.1                   pypi_0    pypi
sphinx                    7.2.6                    pypi_0    pypi
sphinx-autodoc-typehints  2.0.1                    pypi_0    pypi
sphinx-copybutton         0.5.2                    pypi_0    pypi
sphinx-gallery            0.16.0                   pypi_0    pypi
sphinx-prompt             1.8.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.8                    pypi_0    pypi
sphinxcontrib-bibtex      2.6.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.6                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.5                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.7                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.10                   pypi_0    pypi
```

Not sure why it's not working for you. Is the `.example` file of functions, e.g., `fairlearn.preprocessing.CorrelationRemover` empty for you? Maybe you are not building the examples?

**Comment by lucyleeow** [comment]
Not sure what could be different for you. Maybe you could try a fresh environment? 

Have you tried a `make clean` followed by `make doc` ?

I don't think it's a sphinx-gallery issue, as it worked for me but for info, the back references are built when we generate the galleries [here](https://github.com/sphinx-gallery/sphinx-gallery/blob/40f758994e6b76ea62cb67db547b4b2f39e55549/sphinx_gallery/gen_rst.py#L1353).

**Comment by TamaraAtanasoska** [comment]
> Not sure what could be different for you. Maybe you could try a fresh environment?
> 
> Have you tried a `make clean` followed by `make doc` ?
> 
> I don't think it's a sphinx-gallery issue, as it worked for me but for info, the back references are built when we generate the galleries [here](https://github.com/sphinx-gallery/sphinx-gallery/blob/40f758994e6b76ea62cb67db547b4b2f39e55549/sphinx_gallery/gen_rst.py#L1353).

I have tried several times unfortunately to `make clean` and `make doc`. I did use a cloned env to my base one to test different package versions, but I didn't try with a completely new one yet. I will spend some more time on it tomorrow and report back.

**Comment by lucyleeow** [comment]
> They are generated and exist, but empty. It must be why nothing is showing! 

FYI we generate `.examples` files for all functions as it prevents some errors:

https://github.com/sphinx-gallery/sphinx-gallery/blob/40f758994e6b76ea62cb67db547b4b2f39e55549/sphinx_gallery/gen_gallery.py#L1389-L1390

So some `.examples` files are *meant* to be empty

**Comment by TamaraAtanasoska** [comment]
> > They are generated and exist, but empty. It must be why nothing is showing!
> 
> FYI we generate `.examples` files for all functions (/other objects) as it prevents some errors:
> 
> https://github.com/sphinx-gallery/sphinx-gallery/blob/40f758994e6b76ea62cb67db547b4b2f39e55549/sphinx_gallery/gen_gallery.py#L1389-L1393
> 
> So some `.examples` files are _meant_ to be empty

Oooh good to know! I got it to work now, not sure what was with my env 🥳 . Thank you again for working this through with me, and pointing to the `.examples` files contents.
