### ISSUE TITLE
Doc "copy" feature is not robust to ellipses

### ISSUE THREAD

**Issue by JPelamatti** [sphinx-gallery/sphinx-gallery#1341]
When code snippets in the documentation contain ellipses ("..."), the copy feature ignores the associated lines.
See for the example the snippets in the following [page](https://openturns.github.io/openturns/master/user_manual/_generated/openturns.UserDefinedCovarianceModel.html)

**Comment by larsoner** [comment]
Can you link to the source doc that's supposed to be copied etc.? It's not obvious what's supposed to be there and what's missing based on just the linked rendered HTML.

**Comment by JPelamatti** [comment]
I am extremely sorry, I posted on the wrong github. This was supposed to go on the OpenTURNS project github which uses sphinx features....

**Comment by larsoner** [comment]
No problem, hope the Sphinx folks can help 👍
