### ISSUE TITLE
download buttons .ipynb: force download on click

### ISSUE THREAD

**Issue by remy-abergel** [sphinx-gallery/sphinx-gallery#1343]
Hi, 

Looking at the many examples available in the sphinx-gallery documentation (e.g., [this one](https://sphinx-gallery.github.io/stable/auto_examples/plot_0_sin.html#sphx-glr-auto-examples-plot-0-sin-py)), the download buttons towards the jupyter notebooks trigger file download.

This is not the case with my own example galleries. Instead of triggering file download, the content of the .ipynb file is displayed in my navigator (Firefox). This is for instance the case for [this demonstration package](https://github.com/user-attachments/files/15752783/pypkg.zip).

Could you please tell me if a particular setting is needed to force download on click for those buttons? 

Thanks

**Comment by drammock** [comment]
can you provide a link to a live site where you experience this issue (for easy testing/verification), and a link to its source repository (for easy examination of the config)?  Downloading the zip, verifying the files are safe to run, and building the site locally *before* we can even verify/reproduce the issue... it's a lot of steps

**Comment by lucyleeow** [comment]
Thanks!
