### ISSUE TITLE
Variable 'indexst' is undefined when using custom index.rst

### ISSUE THREAD

**Issue by greschd** [sphinx-gallery/sphinx-gallery#1382]
When using a custom `index.rst` for the gallery, the following exception is thrown:

```
Traceback (most recent call last):
  File "/home/runner/work/ansys-tools-local-product-launcher/ansys-tools-local-product-launcher/.tox/doc/lib/python3.12/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/ansys-tools-local-product-launcher/ansys-tools-local-product-launcher/.tox/doc/lib/python3.12/site-packages/sphinx/application.py", line 292, in __init__
    self._init_builder()
  File "/home/runner/work/ansys-tools-local-product-launcher/ansys-tools-local-product-launcher/.tox/doc/lib/python3.12/site-packages/sphinx/application.py", line 366, in _init_builder
    self.events.emit('builder-inited')
  File "/home/runner/work/ansys-tools-local-product-launcher/ansys-tools-local-product-launcher/.tox/doc/lib/python3.12/site-packages/sphinx/events.py", line 109, in emit
    raise ExtensionError(
sphinx.errors.ExtensionError: Handler <function generate_gallery_rst at 0x7f98e601d440> for event 'builder-inited' threw an exception (exception: cannot access local variable 'indexst' where it is not associated with a value)
```

From [this CI run](https://github.com/ansys/ansys-tools-local-product-launcher/actions/runs/11121042825/job/30899262996?pr=186), associated code: https://github.com/ansys/ansys-tools-local-product-launcher/tree/maint/remove_upper_limits [1]

I believe this was introduced in #1332, by removing this code block https://github.com/sphinx-gallery/sphinx-gallery/pull/1332/files#diff-016e2fd897b8720412d190b7936fb295e31dc953c73fcb912ca1362ec8ca2191L660-L663

```python
        else:
            # we are not going to use the index.rst.new that gets made here,
            # but go through the motions to run through all the subsections...
            indexst = "Never used!"
```

However, I'm not sure if the correct fix is to simply re-introduce the code block, or if there is a better solution.

[1] this branch updates `sphinx-gallery` from `0.15.0` to `0.17.1`

**Comment by larsoner** [comment]
It would be good to try first writing a test that replicates the problem somehow (maybe using `tests/tinybulid`?) and then see if adding those lines back in do indeed fix the problem. True TDD!

**Comment by lucyleeow** [comment]
Does reverting the code fix the doc failure?

In the old code (before the refactor), `indexst` was never used if custom `index.rst` was provided, so I am not sure how the changes would cause problems.

Looking at the CI, is the 'The server is down.' relevant?

>  Output from /home/runner/work/ansys-tools-local-product-launcher/ansys-tools-local-product-launcher/examples/example_scripts/py_configure.py
The server is down.

**Comment by greschd** [comment]
> It would be good to try first writing a test that replicates the problem somehow

As a starting point, the `tinybuild` shows this exception if the `example_dirs` other than `"../examples_rst_index",` are commented out. See this commit: https://github.com/greschd/sphinx-gallery/commit/5883b2de77104291cded9335a1c00f25897a91b6

That leads me to think the error only occurs if the custom `index.rst` is in the _only_ (or maybe _first_) examples directory.

> Does reverting the code fix the doc failure?

Adding in an `else` block does fix the immediate exception. In the `tinybuild` case above, I also had to _remove_ the other examples directories and comment out "expected failing examples" to make the build run again (due to commenting out the other `example_dirs` entries). See https://github.com/greschd/sphinx-gallery/commit/b4b93d1362139f5c6f03861e59d2d0fe3060904a

>  so I am not sure how the changes would cause problems

In the current code, the (undefined) `indexst` variable is still passed on to `_finish_index_rst`. I'm not sure if that's intentional though, or if this should also be behind an if-statement.

> Looking at the CI, is the 'The server is down.' relevant?

No, that's expected output from the example.
