### ISSUE TITLE
custom within-subsection sorting doesn't work as documented

### ISSUE THREAD

**Issue by drammock** [sphinx-gallery/sphinx-gallery#1389]
The [example in the docs](https://sphinx-gallery.github.io/stable/configuration.html#custom-sort-keys) of using `FunctionSortKey`:

```py
"minigallery_sort_order": FunctionSortKey(lambda filename: filename[:10])
```

is guaranteed not to work, because non-string values are tested with `inspect.isclass()` wihtin the `_get_class` helper --- but `isclass()` returns `False` for class *instances* (and the recommended usage always generates a class instance).

If instead I follow [the other recommendation in the docs](https://sphinx-gallery.github.io/dev/configuration.html#importing-callables) to use a FQN of an importable function, I still get an error:

```
In [1]: from sphinx_gallery.gen_rst import _get_class
In [2]: sphinx_gallery_conf = {
   ...:     "doc_module": "mne_bids",
   ...:     "reference_url": {
   ...:         "mne_bids": None,
   ...:     },
   ...:     "backreferences_dir": "generated",
   ...:     "examples_dirs": "../examples",
   ...:     "within_subsection_order": "mne_bids.utils.example_sorter",  # <---- HERE
   ...:     "gallery_dirs": "auto_examples",
   ...:     "filename_pattern": "^((?!sgskip).)*$",
   ...: }
   ...: 
In [3]: _get_class(sphinx_gallery_conf, "within_subsection_order")
---------------------------------------------------------------------------
ConfigError                               Traceback (most recent call last)
Cell In[3], line 1
----> 1 _get_class(sphinx_gallery_conf, "within_subsection_order")

File /opt/sphinx-gallery/sphinx_gallery/gen_rst.py:1645, in _get_class(gallery_conf, key)
   1640         raise ConfigError(
   1641             f"{what} must be a fully qualified name string, could not import "
   1642             f"{attr} from {mod}"
   1643         )
   1644 if not inspect.isclass(val):
-> 1645     raise ConfigError(
   1646         f"{what} must be 1) a fully qualified name (string) that resolves "
   1647         f"to a class or 2) or a class itself, got {val.__class__.__name__} "
   1648         f"({repr(val)})"
   1649     )
   1650 return val

ConfigError: sphinx_gallery_conf['within_subsection_order'] must be 1) a fully qualified name (string) that resolves to a class or 2) or a class itself, got function (<function example_sorter at 0x7d99b40f2160>)
```

I suspect that this error was introduced in #1289 (but haven't dug deeply, maybe it's older)

I'll submit a PR shortly

**Comment by drammock** [comment]
hmm.  In order to write a test that fails on main / passes on my PR, I was hoping to be able to pass `confoverrides` to the Sphinx app --- in order to test different sort functions in action. That's the basic approach to testing taken by PyData Sphinx Theme: expose a factory fixture that gives each test its own "app", but each test function actually instantiates the app (possibly passing some `confoverrides` along the way) and then calls `.build()`. We combine this with several distinct test "sites" like your `tinybuild`, so that a single test site doesn't have to cover all possible test cases --- except that most of our test sites are *much* smaller (think a single page) because a lot of things we want/need to test don't require a 10-20 page site to test.

IIUC, y'all take the opposite approach of having *one* test site (`tinybuild`) that tries to cover all possible test cases, gets built once, and the built app gets passed into all the test functions in order to check something about it.  This is hard for the present case, because I want to test both `FunctionSortKey(some_func)` and `"mymod.utils.custom_example_sorter"` approaches to custom sorting --- both are documented to work, and both seem to be failing! --- and I think the best I can do under the current testing regime is to test one of them with `minigallery_sort_order` and the other with `subsection_order`, which means the other built-in sorters won't get tested anymore (to the extent that they even are at present).

Is changing the big-picture approach to fixtures/test-sites something you're willing to consider?  It's a pretty big change, will probably slow down your test suite, but would make it much easier to test lots of different gallery configs.

Alternatively, can you think of a way I can test `FunctionSortKey` *in action* without a massive refactor of your test suite?  I'd prefer (for now at least) to write a single test that fails on main and passes on my PR, and save the big testing refactor for another day.

**Comment by lucyleeow** [comment]
> in order to test different sort functions in action

Would making 2 tests and using `add_conf` pytest mark work? E.g.:

https://github.com/sphinx-gallery/sphinx-gallery/blob/9947c26a7457f7ef35b41cee7d6fa89e1f36c67d/sphinx_gallery/tests/test_gen_gallery.py#L314-L322

Note `sphinx_app_wrapper` builds the gallery in `sphinx_gallery/tests/testconfs/src`.

I'm fuzzy on this as @larsoner did all the work for supporting the new sphinx serialization. Is using classes for `within_subsection_order` soley for the purpose of a stable `__repr__` ? Could we move to using functions and FQN? We would support the old classes for backwards compatibility of course. (this doesn't fix the `isclass` instance problem of course)

**Comment by drammock** [comment]
that looks like it should work!  Thanks, I hadn't noticed the `add_conf` pytest mark before. I'll give it a shot.

**Comment by drammock** [comment]
this turns out to be a rather deep rabbit hole. IIUC, there's a fundamental difference between how `FunctionSortKey` and the other builtin `*SortKey` classes work:

- builtin classes inherit from `_SortKey`, meaning that *when initted* they get the `src_dir` baked in. Then when their instances are called with a `filename` argument, the path to that filename is constructed relative to `src_dir` (in order to `os.stat` its size, etc)
- `FunctionSortKey` does not inherit from `_SortKey`, and is initted with a user's custom function. The function is expected to take a filename and return something sortable with a `<` operator. It has no notion of the `src_dir`.

This is a problem, because `generate_dir_rst()` *tries to init the class by calling it with the `src_dir`:

https://github.com/sphinx-gallery/sphinx-gallery/blob/9947c26a7457f7ef35b41cee7d6fa89e1f36c67d/sphinx_gallery/gen_rst.py#L569

But in the case of `FunctionSortKey`, that line is triggering `__call__` instead of `__init__` (because the user has *already* initted FunctionSortKey by passing in their custom sorter function).

I think then that `FunctionSortKey` needs to be reworked to be a *class factory*, such that the resulting class will get initted with `src_dir` like the other `*SortKey` classes do.
