### ISSUE TITLE
Duplicate labels clash when including multiple galleries

### ISSUE THREAD

**Issue by bernardopacini** [sphinx-gallery/sphinx-gallery#1392]
I am trying to use multiple galleries in my documentation (with the PNG scraper) using:

```python
sphinx_gallery_conf = {
    "examples_dirs": examples_dirs,  # path to your example scripts
    "gallery_dirs": gallery_dirs,  # path to where to save gallery generated output
    "reference_url": {
        "matplotlib": None,
        "plotly": None,
    },
    "image_scrapers": ('imag_scraper.png_scraper'),  # Scrape images from Matplotlib and Plotly
}
```

This generates the figures correctly and places them in the right folders, but I get the error:

```
doc/plotly/auto_examples/index.rst:6: WARNING: duplicate label auto_examples, other instance in doc/matplotlib/auto_examples/index.rst
```

I do use this label in my general `index.rst` to reference the file using:

```
* :ref:`auto_examples`
```

I would like to be able to do:

```
* :ref:`auto_examples_matplotlib`
* :ref:`auto_examples_plotly`
```

What can I do to fix this? How can I specify the `auto_examples` label in the automatically generated `index.rst` file?

**Comment by lucyleeow** [comment]
I am not sure what you mean by "my general index.rst" as you also mention "the automatically generated index.rst file"?

Are talking about using the label in the gallery header (or readme) file which gets added to the automatically generated index.rst file?

**Comment by bernardopacini** [comment]
Thank you for the quick response!

Having set up my docs using the example for one gallery and then copying it over for the second gallery, I did not realize that the `README.rst` file where my scripts / plots are dictates the label on my page. Both had the name `auto_examples`. Updating the `README.rst` to `auto_examples_matplotlib` and `auto_examples_plotly` fixed the issue.
