### ISSUE TITLE
[QUESTION] Is it possible to ignore the output of a specific cell?

### ISSUE THREAD

**Issue by tpvasconcelos** [sphinx-gallery/sphinx-gallery#1397]
## Question

I tried looking in the docs for this but I could not find any options on how to hide the output of a specific notebook cells. Did I miss something?

## Motivation

The reason I'm asking is because I'm [currently working on](https://github.com/tpvasconcelos/ridgeplot/pull/267/files#diff-ca4940391ff4423ef59f4c827f3ccc447a492b08698c9860d3efb4c134ca4f17) an examples gallery with Plotly and I sometimes want to have cells with something like:

```python
fig.update_layout(
    foo="Bar",
    bar="Foo",
)
```

but since `update_layout` return a plotly figure, this is automatically captured by Sphinx-Gallery and include in the output.

A workaround would be to assign it back to a variable:

```python
fig = fig.update_layout(
    foo="Bar",
    bar="Foo",
)
```

but I want to be consistent and follow the same standards used throughout the Plotly official docs (they always threat the `Figure` object as mutable and never reassign back to a `fig` variable). See [this](https://plotly.com/python/creating-and-updating-figures/) for instance.

**Comment by larsoner** [comment]
Seems like the same issue as discussed here

https://discourse.matplotlib.org/t/custom-plot-function-in-jupyter-notebooks/23185/12

One workaround is to do `_ = fig.update_layout(...)`, another (I think) is to do `fig.update_layout(...);`

**Comment by tpvasconcelos** [comment]
Hey @larsoner thanks a lot for the speedy response! 

Yeh both work indeed but not ideal as both can be confusing for the less experienced users trying to understand the examples. 

So to answer my question, there isn't any configuration option or overrides available to toggle-off capturing the output of a given notebook cell right?

If not, is this something the project would be interested in?

Thanks in advance!

**Comment by larsoner** [comment]
No option, no. I'm inclined not to add an option, since the current behavior mimics what happens in notebooks, or at least it should. If you do `fig.update_layout` like that in a notebook, does the output appear? If not, then we should figure out why it doesn't

**Comment by tpvasconcelos** [comment]
No, it definitely does mimic the behaviour of a Jupyter notebook. 

From the top of my head, I can't really think of other instances where this would be useful.

From what I can see in the docs, you're right and the only option I see that would somewhat go against what you're saying is the [sphinx_gallery_start_ignore](https://sphinx-gallery.github.io/stable/configuration.html#hiding-lines-of-code) flag but the motivation there is stronger.

If you change your mind, let me know because I wouldn't mind taking a crack at it and I believe it would be pretty useful (both for Plotly and matplotlib galleries)

Cheers!

**Comment by larsoner** [comment]
Wait... I think you can you already use `# sphinx_gallery_capture_repr` to do what you want:

https://sphinx-gallery.github.io/stable/configuration.html#controlling-what-output-is-captured

```
# sphinx_gallery_capture_repr = ()
```

If this currently only works at the file level, maybe we "just" need to make this block-level settable.

**Comment by tpvasconcelos** [comment]
Documentation says [no](https://www.youtube.com/watch?v=x0YGZPycMEU)...

![image](https://github.com/user-attachments/assets/ecde74f1-4af9-4d4d-8091-7d3ddaf82411)

Should I take a look?

**Comment by larsoner** [comment]
What I mean is first check to make sure at the file level that it works to suppress capturing in that block (and all the other blocks). Then if it does, all we need to do (which hopefully isn't too bad!) is make it work as a block-level configurable option as well

**Comment by larsoner** [comment]
> Should I take a look and open a draft PR on how to make this block-level?

Yes that would be great!
