### ISSUE TITLE
RST directives remain in ipynb

### ISSUE THREAD

**Issue by Eric89GXL** [sphinx-gallery/sphinx-gallery#141]
The IPython ipynb downloads don't strip all irrelevant stuff e.g. links:

http://martinos.org/mne/dev/_downloads/plot_background_filtering.ipynb

Looks like this:

![screenshot from 2016-08-30 10-01-29](https://cloud.githubusercontent.com/assets/2365790/18092077/e9e5ebf0-6e98-11e6-9d29-781e6f6461d3.png)

Should we remove lines starting with `.. `?

**Comment by Eric89GXL** [comment]
Although I guess that would break `.. note::` and `.. warning::`, so maybe just some lines starting with `..`, such as `.. _` (links) and `.. contents::`, and we could expand the list later?

**Comment by GaelVaroquaux** [comment]
> Should we remove lines starting with ..?

We should do 'something' about them. Ideally for notes, topics or warnings,
create a div with a class given class. Looking at an example Jupyter
notebook, it seems that it's the standard way of doing these things (see
eg
https://raw.githubusercontent.com/jorisvandenbossche/pandas-tutorial/master/04b%20-%20Advanced%20groupby%20operations.ipynb,
and search for 'div').

**Comment by Eric89GXL** [comment]
That seems pretty straightforward. In the rendered html we get `<div class="admonition warning">` for warning and `<div class="admonition note">` for note. I could try making a PR adding those and removing links as a start.

**Comment by GaelVaroquaux** [comment]
> That seems pretty straightforward. In the rendered html we get <div
> class= "admonition warning"> for warning and <div class="admonition
> note"> for note. I could try making a PR adding those and removing
> links as a start.

That would be very nice!
