### ISSUE TITLE
The following example code snippet makes sphinx-gallery crash

### ISSUE THREAD

**Issue by NelleV** [sphinx-gallery/sphinx-gallery#149]
matplotlib has a fairly long and complicated example that makes sphinx-gallery crash. Here is the smallest example I extracted from i:

``` python
"""title

docstring
"""

from __future__ import print_function

import code


class Class(code.InteractiveConsole):
    """docstring"""

    def method(self, source):
        """docstring.
        """
        code = self.compile(source)

    def compile(self, source):
        return source
```

The traceback is:

```
Exception occurred:
  File "/home/nelle/.miniconda3/lib/python3.5/site-packages/sphinx_gallery/backreferences.py", line 106, in identify_names
    module, attribute = full_name.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)
The full traceback has been saved in /tmp/sphinx-err-fosv6f05.log, if you want to report the issue to the developers.
```

The full example that makes sphinx-gallery crash is here:
https://github.com/matplotlib/matplotlib/blob/master/examples/user_interfaces/interactive.py

**Comment by lesteve** [comment]
I can reproduce. A work-around is to use another name than `code`. It seems like that the reference resolver is confused between the `code` module and the `code` local variable for some reason I haven't really understood yet.

**Comment by lesteve** [comment]
Full disclosure: #173 fixes the obvious error but I am not sure what will happen with the reference solver when the same name refers to two different objects. I don't believe the reference solver knows about scope and I don't think this is a priority to make it aware of scope.
