### ISSUE TITLE
Awkward looking download buttons with alabster theme

### ISSUE THREAD

**Issue by anntzer** [sphinx-gallery/sphinx-gallery#155]
From the sphinx-gallery docs but switching to using the builtin "alabaster" theme: the "download Python source code" / "download Jupyter notebook" buttons look rather awkward.

![screenshot_20161022_075908](https://cloud.githubusercontent.com/assets/1322974/19620252/25e2c5e2-982e-11e6-8a36-03b1780f6af5.png)

**Comment by lesteve** [comment]
Are you using the alabaster theme or were just trying it for curiosity's sake? Is alabaster a popular theme?

There was some back on forth on these buttons, while trying different themes and the conclusion from what I could gather was that it was very difficult to support multiple themes that we would do our best to look decent on a few themes but that it would be up to users to write a bit of CSS if they wanted to improve the default look.

Look at the discussion in https://github.com/sphinx-gallery/sphinx-gallery/pull/144 for more details.

**Comment by lesteve** [comment]
Actually it works fine on master. Here is what I am seeing for the plot_colors.html example:

![sphinx-gallery](https://cloud.githubusercontent.com/assets/1680079/19620963/0bc52ae2-9888-11e6-9d8c-ca8fe30f7665.png)

**Comment by lesteve** [comment]
Actually semi-scratch that I don't think I was using the latest master. Here is the snapshot with the alabaster theme, the download buttons still look fine:

![sphinx-gallery](https://cloud.githubusercontent.com/assets/1680079/19620998/d1138d02-9888-11e6-9c75-6da216fb63f5.png)

**Comment by anntzer** [comment]
alabaster is the default theme in sphinx nowadays (see note just *before* http://www.sphinx-doc.org/en/1.4.8/theming.html#creating-themes or just try running `sphinx-quickstart` yourself).
I can confirm that master fixes that issue, feel free to close it.
Any chance for a release soon?  Thanks.

**Comment by lesteve** [comment]
> alabaster is the default theme in sphinx nowadays (see note just before http://www.sphinx-doc.org/en/1.4.8/theming.html#creating-themes or just try running sphinx-quickstart yourself).

Indeed from the page you linked:
> Changed in version 1.3: The ‘default’ theme has been renamed to ‘classic’. ‘default’ is still available, however it will emit notice a recommendation that using new ‘alabaster’ theme.

I did not know that. We should use alabaster then in our conf.py as the default rather than 'default'.

> Any chance for a release soon? Thanks.

@Titan-C maybe that would be a good idea. Also CHANGES.rst is missing an entry about improved CSS for buttons. It looks like there were more work on top of the changes that are listed in 0.1.4.

**Comment by Titan-C** [comment]
I just released v0.1.5 that includes the fixed dowload buttons across all themes. I updated the CHANGES.rst too.
Can download the new release in PYPI too.

**Comment by lesteve** [comment]
Greath, thanks!

**Comment by Titan-C** [comment]
>> Any chance for a release soon? Thanks.
>
> @Titan-C maybe that would be a good idea. Also CHANGES.rst is missing an entry about improved CSS for buttons. It looks like there were more work on top of the changes that are listed in 0.1.4.

Ok. I'll do a release today with the CSS fixes and the updates to CHANGES.rst
