### ISSUE TITLE
Add "fork me on github" banner

### ISSUE THREAD

**Issue by anntzer** [sphinx-gallery/sphinx-gallery#159]
Right now there seems no link to the github repo on the home page https://sphinx-gallery.readthedocs.io/

**Comment by GaelVaroquaux** [comment]
The big diagonal banner that is fashioned by some is, in my opinion, ugly
and too obstructive. That said, I agree that the information should be
added somewhere.

**Comment by anntzer** [comment]
(I don't feel strongly about how you put it.  All I really care is to have an easy way to get to the sources (hopefully not a small "the sources are on github" link that you have to search for).)

**Comment by GaelVaroquaux** [comment]
> All I really care is to have an easy way to get to the sources

+1

**Comment by amueller** [comment]
+1

**Comment by lesteve** [comment]
There is a link to the documentation "Generated by Sphinx-Gallery" at the bottom that points to readthedocs. Is this issue about having a link that points to github on top of it?

**Comment by amueller** [comment]
the issue is about getting from the readthedocs to the github repo if I understood correctly. That's what I was +1'ing
