### ISSUE TITLE
Gallery directory without README.txt is skipped from execution but nevertheless generate an index

### ISSUE THREAD

**Issue by Titan-C** [sphinx-gallery/sphinx-gallery#164]
Directories without a README.txt are not considered for the gallery and skipped from parsing or execution. This is the case when we want to have directories dedicated to hold data files that shall not be transformed into a gallery but are nevertheless needed nearby.

If the user forgets to put the readme.txt file in the main examples folder, a warning is printed and the build continues. The generated website is a page with the download buttons of the examples.

My expected behavior would be, since is the case of the main gallery directories, to stop the build immediately.

**Comment by lesteve** [comment]
Yeah "error with user-friendly message" a lot greater than "warning" IMHO.
