### ISSUE TITLE
More informative messages when skipping an example

### ISSUE THREAD

**Issue by lesteve** [sphinx-gallery/sphinx-gallery#167]
I think that is slightly confusing, even if the timing of the examples make it clear that the execution took no time. Excerpt from the output:

```
Executing file ../examples/just_code.py
../examples/just_code.py ran in : 0 seconds

Executing file ../examples/plot_choose_thumbnail.py
../examples/plot_choose_thumbnail.py ran in : 0 seconds

Executing file ../examples/plot_colors.py
../examples/plot_colors.py ran in : 0 seconds

Executing file ../examples/plot_exp.py
../examples/plot_exp.py ran in : 0 seconds

Executing file ../examples/plot_function_identifier.py
../examples/plot_function_identifier.py ran in : 0 seconds

Executing file ../examples/plot_gallery_version.py
../examples/plot_gallery_version.py ran in : 0 seconds

Executing file ../examples/plot_quantum.py
../examples/plot_quantum.py ran in : 0 seconds

Executing file ../examples/plot_raise.py
../examples/plot_raise.py ran in : 0 seconds

Executing file ../examples/plot_seaborn.py
../examples/plot_seaborn.py ran in : 0 seconds

Executing file ../examples/plot_strings.py
../examples/plot_strings.py ran in : 0 seconds

Executing file ../examples/plot_test.py
../examples/plot_test.py ran in : 0 seconds

Executing file ../examples/sin_func/plot_sin.py
../examples/sin_func/plot_sin.py ran in : 0 seconds

Executing file ../examples/sin_func/plot_sin_black_background.py
../examples/sin_func/plot_sin_black_background.py ran in : 0 seconds

Executing file ../tutorials/plot_notebook.py
../tutorials/plot_notebook.py ran in : 0 seconds

Executing file ../tutorials/plot_parse.py
../tutorials/plot_parse.py ran in : 0 seconds

Executing file ../tutorials/plot_seaborn_notebook.py
../tutorials/plot_seaborn_notebook.py ran in : 0 seconds

Computation time summary:
        - plot_test.py : 0 sec
        - plot_strings.py : 0 sec
        - plot_sin_black_background.py : 0 sec
        - plot_sin.py : 0 sec
        - plot_seaborn_notebook.py : 0 sec
        - plot_seaborn.py : 0 sec
        - plot_raise.py : 0 sec
        - plot_quantum.py : 0 sec
        - plot_parse.py : 0 sec
        - plot_notebook.py : 0 sec
        - plot_gallery_version.py : 0 sec
        - plot_function_identifier.py : 0 sec
        - plot_exp.py : 0 sec
        - plot_colors.py : 0 sec
        - plot_choose_thumbnail.py : 0 sec
```

**Comment by markroxor** [comment]
I am facing similar issues and can't proceed without it being resolved please check this [https://travis-ci.org/markroxor/gensim/jobs/179861166](this travis output.) Hence any graphs/thumbnails are not being generated.

**Comment by lesteve** [comment]
@markroxor can you open a new issue please? This issue does not describe a bug but an improvement in the messages that sphinx-gallery creates. Please provide a way that we can reproduce for example a link to github with your project.

**Comment by markroxor** [comment]
I sorted it out. Sorry for any inconvenience.

**Comment by lesteve** [comment]
What was the issue out of interest?

**Comment by markroxor** [comment]
All the py examples were executed in 0.0 seconds.  Then I renamed the files to plot_xx.py. Now the Travis build is terminated automatically because it is taking over 45 minutes to complete. I'll try altering the content of the notebooks.

**Comment by lesteve** [comment]
Ah, I guess the printout could be better for skipped examples so I guess your problem is kind of related to this issue after all ;-).

Note you can define your own regex for examples, `plot_` is historical from scikit-learn. Have a look at this [section of the doc](https://sphinx-gallery.readthedocs.io/en/latest/advanced_configuration.html#building-examples-matching-a-pattern) for more details.

**Comment by lesteve** [comment]
> Now the Travis build is terminated automatically because it is taking over 45 minutes to complete

Travis build maximum time is 50 minutes it seems. We are using CircleCI to build documentation because it is a little bit less restrictive: two hours according to [this](https://discuss.circleci.com/t/timeout-more-than-120-minutes/640).

Also some scikit-learn examples that take a long time to run do not start with `plot_` on purpose so that is another approach if some examples take a really long time. The example is not run so there is no thumbnail in the gallery and no output in the example HTML.

**Comment by markroxor** [comment]
I am just testing sphinx-gallery [here.](https://markroxor.github.io/gensim/auto_examples/) so to begin with I am not bothered about the renaming part (I will sort that out later :) ) but I have got to remove `plot_` from some of the `py` files. I am working on it. Thanks for clarification :)

**Comment by markroxor** [comment]
There is one thing I am afraid of. If I remove `plot_` most certainly the py notebook will not be executed so I won't know whether there are any errors in the py notebook or not in either case the Travis CI will pass the notebook without raising any error which is not intended. Am I right?

**Comment by Titan-C** [comment]
> There is one thing I am afraid of. If I remove `plot_` most certainly the py notebook will not be executed so I won't know whether there are any errors in the py notebook or not in either case the Travis CI will pass the notebook without raising any error which is not intended. Am I right?

Exactly, if the example does not hold the `plot_` prefix(or your chosen
regular expression for execution), the script will not be executed(thus
no true way of testing it) it will just put directly in to the html
page. You wont get any notification of it having any error.

**Comment by markroxor** [comment]
Then the whole purpose of using a CI is defeated. Anyways thanks I will try to figure a way out :)

**Comment by GaelVaroquaux** [comment]
But your core problem is that what you're trying to run on CI is taking
too long. It's not a problem of sphinx-gallery, it's a problem of your
setup.

**Comment by markroxor** [comment]
@GaelVaroquaux yes you're totally right. I'll figure out a workaround.

**Comment by lesteve** [comment]
The discussion went a bit astray, compared to the intitial issue.

To focus back to the original issue the idea of the issue would be to have a more explicit message when not running an example like: "Skipping example <filename> because <reason>" where reason can be either 
1. plot_gallery=False  in your conf.py
2. <filename> does not match regex <regex>

Not sure whether you want this info in both the example run and the summary or only one one.

**Comment by lesteve** [comment]
Maybe actually an option would be not printing anything during the example if the example is skipped but mention that it has been skipped in the summary.

**Comment by lesteve** [comment]
Although not exactly what I had in mind #187 is close enough, so closing.
