### ISSUE TITLE
Need to ship LICENSE file in pypi release

### ISSUE THREAD

**Issue by opoplawski** [sphinx-gallery/sphinx-gallery#169]
BSD license requires to ship the license file with the package, but it isn't in the pypi tarball.

**Comment by lesteve** [comment]
@Titan-C, just curious, why not add the files in setup.py? We had a similar request for joblib and I am wondering about the best way to do it.

**Comment by Titan-C** [comment]
> @Titan-C, just curious, why not add the files in setup.py? We had a similar request for joblib and I am wondering about the best way to do it.

I did try to use the setup.py, to pack it the same way I pack the
scripts to download sphinx-gallery of the notebook converter. But it did
not work. I tryed other ways proposed for the setup.py in stackoverflow
but none of them worked. Only using the Manifest.in packed the license.

**Comment by lesteve** [comment]
For the record, I found that adding `''` to `packages` and then the license to `package_data` seems to make `setuptools` happy:

```py
          package_data={'joblib.test': ['data/*.gz',                                                                                  
                                        'data/*.gzip',                                                                                
                                        'data/*.bz2',                                                                                 
                                        'data/*.xz',                                                                                  
                                        'data/*.lzma',                                                                                
                                        'data/*.pkl',                                                                                 
                                        'data/*.npy',                                                                                 
                                        'data/*.npy.z'],                                                                              
                        '': ['LICENSE']},                                                                                             
          packages=['', 'joblib', 'joblib.test', 'joblib.test.data'],  
```

**Comment by Titan-C** [comment]
now I see my mistake. I did add the license to `package_data` but `packages = find_packages()` does not include the `''` entry.

**Comment by lesteve** [comment]
Yeah I have to say it's not very intuitive at all and it took me a few trial and errors before getting it right ...
