### ISSUE TITLE
backreferences processing breaks if module accessed without attribute

### ISSUE THREAD

**Issue by jnothman** [sphinx-gallery/sphinx-gallery#172]
The scikit-learn docs fail to build at https://circleci.com/gh/scikit-learn/scikit-learn/7314?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link due to https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/backreferences.py#L106 where it is assumed that a module being referenced is always referenced with an attribute. It should be possible to reference a module without its attribute and hence for no `.` to be present.

**Comment by lesteve** [comment]
Simple snippet reproducing the problem:

```py
from sphinx_gallery.backreferences import identify_names

code_str = """
import os
hasattr(os, 'bla')
"""

identify_names(code_str)
```

**Comment by jnothman** [comment]
With apologies for not providing a snippet in the first place. I was being
a bad citizen.

**Comment by lesteve** [comment]
No worries, the issue was well explained so it took me five minutes tops to reproduce in a stand-alone snippet.
