### ISSUE TITLE
Conda packages for sphinx-gallery

### ISSUE THREAD

**Issue by leouieda** [sphinx-gallery/sphinx-gallery#174]
Are there any plans to build conda packages for sphinx-gallery in conda-forge? 

I could set this up and wouldn't mind being one of the maintainers for the feedstock.

**Comment by GaelVaroquaux** [comment]
> Are there any plans to build conda packages for sphinx-gallery in conda-forge?

What's the added value compared to pip?

**Comment by leouieda** [comment]
Another option for users to choose the package manager they want. Frankly, aside from that I can't think of much since this is a pure Python package.

**Comment by lesteve** [comment]
I am a conda user but it doesn't bother me to use pip for smaller projects if they are not available from conda. A few projects I use pip for: elpy, jedi, line-profiler, memory-profiler.

I am not convinced the advantage is worth the maintenance cost, so I am going to close this one.

Note: this is not too much work to make a pure Python available on conda-forge but then it is still an additional thing to remember to do on each release, plus all the possible unexpected complications that can arise (for example the nilearn conda-forge package currently suffers from a problem that has not been fully understood).

**Comment by dfroger** [comment]
Hi, there is now a [sphinx-gallery feedstock](https://github.com/conda-forge/sphinx-gallery-feedstock) on [conda-forge](https://conda-forge.github.io).

**Comment by GaelVaroquaux** [comment]
> Hi, there is now a sphinx-gallery feedstock on conda-forge.

Do you know who created it / maintains it? I cannot easily find the
information.

**Comment by dfroger** [comment]
I created it and maintained it, the info is actually in the [recipe](https://github.com/conda-forge/sphinx-gallery-feedstock/blob/master/recipe/meta.yaml#L48-L49)

**Comment by GaelVaroquaux** [comment]
Thanks a lot for doing this ! 

⁣Sent from my phone. Please forgive brevity and mis spelling​

**Comment by dfroger** [comment]
you're welcome!
