### ISSUE TITLE
Exception occurred in _get_data (IOError)

### ISSUE THREAD

**Issue by sciunto** [sphinx-gallery/sphinx-gallery#184]
I'm a developer for scikit-image and we are using sphinx-gallery. Recently, with sphinx 1.5, we got warnings treated as errors. I tackled some of them and then, I got this:

```
Exception occurred:

  File "/home/travis/build/scikit-image/scikit-image/doc/source/../ext/sphinx_gallery/docs_resolv.py", line 48, in _get_data

    with open(url, 'r') as fid:

IOError: [Errno 2] No such file or directory: '/home/travis/build/scikit-image/scikit-image/doc/build/html/api/skimage.color.rst.html'

The full traceback has been saved in /tmp/sphinx-err-yAUWXd.log, if you want to report the issue to the developers.

Please also report this if it was a user error, so that a better error message can be provided next time.

A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

```

Is it something you are aware of? despite the message, I have the feeling that it's more related to sphinx-gallery.

Original issue: https://github.com/scikit-image/scikit-image/pull/2395#issuecomment-265766099

Many thanks!

**Comment by GaelVaroquaux** [comment]
Indeed, sphinx 1.5 broken sphinx-gallery. We will be releasing a fix
soon.

**Comment by sciunto** [comment]
Thanks @GaelVaroquaux :)

**Comment by Titan-C** [comment]
Sphinx-Gallery 0.1.7 is released. There is a git tag and the package is also available on PyPI for download

**Comment by sciunto** [comment]
great. Thank you @Titan-C

**Comment by lesteve** [comment]
Great stuff @Titan-C, thanks a lot !
