### ISSUE TITLE
Add conda environment.yml with mayavi on readthedocs

### ISSUE THREAD

**Issue by lesteve** [sphinx-gallery/sphinx-gallery#200]
mayavi has been added to conda-forge recently, which means that we can have an environment.yml with mayavi using the `conda-forge` channel:
http://read-the-docs.readthedocs.io/en/latest/conda.html#activating-conda

This way we feature the mayavi support on readthedocs.

**Comment by Titan-C** [comment]
> mayavi has been added to conda-forge recently, which means that we can have an environment.yml with mayavi using the `conda-forge` channel:
> http://read-the-docs.readthedocs.io/en/latest/conda.html#activating-conda
>
> This way we feature the mayavi support on readthedocs.

Not really, I did try having a environment.yml for readthedocs. It
indeed installs but on read the docs there is no support for the X
server like we have on travis. And read the docs does not seem to be
really trying to enable this. see https://github.com/rtfd/readthedocs.org/issues/1951

My best guess to enable mayavi in our docs is to build them in Circle
CI, and push them to github pages. That means dropping read the docs and
the pagerank we have we have with them.

**Comment by lesteve** [comment]
OK thanks for the details I did not remember the complications involved with this. 

Out of interest is there a way to test things on readthedocs without pushing into master ?

**Comment by lesteve** [comment]
OK I convinced myself that this was not going to be easy, basically `from mayavi import mlab` exits if there is no `DISPLAY`, so closing.

> My best guess to enable mayavi in our docs is to build them in Circle CI, and push them to github pages. That means dropping read the docs and the pagerank we have we have with them.

This could well be a possibility long-term. scikit-learn build the doc on each push into master and upload the doc to scikit-learn.org/dev.

**Comment by Titan-C** [comment]
> Out of interest is there a way to test things on readthedocs without pushing into master ?

What I do is to make readthedocs build from my personal fork of
Sphinx-gallery. Thus Commits to Titan-C/sphinx-gallery get published in
https://sphinx-gallery-local.readthedocs.io

This is a just an unofficial build, but let's me test on their
environment. You could also open a read the docs account, and let it
build your fork as well. Other than this I have not been able to test
their on environment.

Then there is the option if we only want to test their theme to build
with

```
make html theme=rtd
```
