### ISSUE TITLE
CSS class of images is a bit generic

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#209]
It seems like the rendered images in the HTML have a class of `align-center`. It might be helpful for some projects to set a class that is a little bit more sphinx-gallery specific (e.g. `sg-inline`). That way projects could write CSS rules for the output. Any reason not to implement something like this at least as an option in the config file? e.g. `{'img_class': 'something'}`

**Comment by Titan-C** [comment]
`align-center` is sphinx default class for images. But there is no reason in my opinion to not allow images to have a specific CSS class. In PR #210, I have added  the classes `sphx-glr-img` and `sphx-glr-li-img`, which use our standard namespace.

**Comment by choldgraf** [comment]
Cool! Thanks for the quick turnaround!

**Comment by larsoner** [comment]
@choldgraf this can be closed

**Comment by choldgraf** [comment]
ah yes, #210 is now merged!
