### ISSUE TITLE
No active exception to raise

### ISSUE THREAD

**Issue by dopplershift** [sphinx-gallery/sphinx-gallery#213]
Due to docs.scipy.org being down/slow (I think) I'm seeing this message:
```pytb
Exception occurred:
  File "/Users/rmay/miniconda3/envs/py36/lib/python3.6/site-packages/sphinx_gallery/docs_resolv.py", line 264, in _get_link
    raise
RuntimeError: No active exception to reraise
```

That traces back to this block:
```python
            for fname in fnames:
                try:
                    if self._is_windows:
                        fname = fname.replace('/', '\\')
                        link = os.path.join(self.doc_url, fname)
                    else:
                        link = posixpath.join(self.doc_url, fname)

                    if hasattr(link, 'decode'):
                        link = link.decode('utf-8', 'replace')

                    if link in self._page_cache:
                        html = self._page_cache[link]
                    else:
                        html = get_data(link, self.gallery_dir)
                        self._page_cache[link] = html
                except (HTTPError, URLError, IOError):
                    pass
                else:
                    break
            else:
                raise
```
`raise` is being called from the `else` clause from the `for` loop, so clearly there's no exception to be raised at that point. I have no idea what the code should be doing, but (as the interpreter indicates) there's no way that code can operate correctly.

**Comment by lesteve** [comment]
I can reproduce this on sphinx-gallery.

From quickly looking at the code, I think it should break on no-exception so the only way the `else` clause of the for loop is executed is if there was an exception at one point. Clearly I must be missing something ...

I am trying to reproduce

**Comment by lesteve** [comment]
I naively thought that this would work but it does not:

```py
try:
    1/0
except Exception:
    pass
raise
```

**Comment by lesteve** [comment]
For completeness this works in Python 2 but not Python 3:
```py
def foo():
    try:
        1/0
    except Exception as e:
        pass
    raise
foo()
```

**Comment by dopplershift** [comment]
Seems to be covered in this [stackoverflow question and answer](http://stackoverflow.com/questions/23707530/previous-error-being-masked-by-current-exception-context).
