### ISSUE TITLE
Allow option to not display total running time in the rendered docs

### ISSUE THREAD

**Issue by anntzer** [sphinx-gallery/sphinx-gallery#221]
For non-computationally-heavy projects, the running times will usually all be in the order of milliseconds, and thus mostly irrelevant noise.

**Comment by Titan-C** [comment]
We can do this but I still like to see that the example runs fast. And that trying it out won't take much time. Do you want to deactivate this measure for the complete gallery of only for the quick examples?
@lesteve , @GaelVaroquaux any opinions?

**Comment by anntzer** [comment]
A configurable threshold would be fine too.  Usually if one is writing examples that take milliseconds to run that should be pretty obvious.  Notifying for the opposite (unexpectedly slow examples) may be more relevant.

**Comment by GaelVaroquaux** [comment]
I think that a switch to globally turn off could be an option. Another
solution would be to give a specific CSS class, and CSS could then be
used to hide. But many users would have a hard time figuring this out, so
the switch is probably better (both would be useful, for theming
purposes).

**Comment by anntzer** [comment]
Essentially closed by #290.
