### ISSUE TITLE
Replace examples/README.txt by examples/README.$conf.source_suffix

### ISSUE THREAD

**Issue by anntzer** [sphinx-gallery/sphinx-gallery#223]
sphinx's conf.py has a source_suffix field, which can be set (e.g.) to .txt or .rst.  If it is set to .rst (i.e., doc sources have that extension), it would make sense to also look for examples/README.rst instead of examples/README.txt -- this would keep the extension consistent with the rest of the docs.

source_suffix can also be set to a list of extensions, in which case you may just use the first one, or if you really want to do it perfectly, try them one at a time until one matches or raise an error if there are multiple matches -- but that's really not as important, I'd guess.

**Comment by GaelVaroquaux** [comment]
I think that such a change would break many packages already using
sphinx-gallery.

It's a cosmetic change that has some logic. But is it worth breaking
downstreaming packages?

**Comment by anntzer** [comment]
You could still look for README.txt and emit a deprecation warning if it's not the "expected" extension -- or not even emit a warning and just keep everything backcompatible.

**Comment by anntzer** [comment]
(An additional benefit is that this allows the README to be correctly syntax-highlighted as rst by many editors.)

**Comment by choldgraf** [comment]
So it sounds like it'd be straightforward to allow for `README.rst` without breaking `README.txt`? As in, we are giving users an extra choice but not forcing them either way? If that's the case then I think it'd be fine to do so, as long as it's clearly documented that this is the user's choice. I do agree that having `.rst` files feels more natural in the docs, especially since what is inside those files is always rST format anyway.

**Comment by Titan-C** [comment]
I guess the historical reason to use README.txt originates from having
the examples inside the documentation folder. Then, one needed to use an
extension which Sphinx will not use. Now we prefer to have the examples
outside the doc folder but the initial configuration remained.

I do agree having the .rst extension will even reduce the mental
overhead, as that is our default format for documentation. Also github
will parse this readme file correspondingly.

PR welcome, as long as the old behavior is not broken.
