### ISSUE TITLE
Code getting run even though it doesn't match the pattern?

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#224]
So this is a really weird behavior that I'm not sure how to explain. But, when building the matplotlib examples, I ran across one example that would cause SG to fail on build. The failure didn't produce any kind of error message, it simply jumped straight to "html failed to build". Here's what I figured out:

1. The failing example is *not* matched to the SG pattern (aka it shouldn't be run). I confirmed that it didn't run by inserting code that writes to a temporary file, and this file was never created when building sphinx gallery.
2. However, the file still causes the build to fail.
3. I narrowed down the problem to one line of code, which, when commented out, causes the build to work smoothly again.
4. The line is a PyQT5 import.
5. However, if I put *just* that line into another file by itself (uncommented), then that file builds just fine with SG.

So...anybody have an idea what might be going on? Somehow that line of code is getting touched even though the python file is not being run. Maybe it's finding the import and trying to link it with sphinx or something? And it's hard to tell what's going on because there's no error message whatsoever. Is there a place I could look to for more log files or something?

**Comment by Titan-C** [comment]
It is a strange problem you describe. Sphinx keeps a log of the build
and another for the errors. If the build has failed Sphinx tells you
where you can find the file with the complete traceback so you can
analyze the traceback more carefully.

As you say that if you find the file giving the problem and comment the
evil line it work. And that line in another file gives no issue. It
might also be that you have some cached data of previous builds and
those are giving you the error.

If you can provide me a minimal gallery that fails I could go over it on
the weekend.

**Comment by choldgraf** [comment]
I can try to put together a little gallery today that shows off the problem.

re: log files, that's what was weird, I didn't get the usual sphinx error message, it just prints "building HTML failed" and dumps you back to the command line, that's it. Weird!

**Comment by tacaswell** [comment]
This might also be due to conflicts between various GUI toolkits and depend if you have previously imported pyqt4 in the same process

**Comment by choldgraf** [comment]
but the thing is that none of those imports should actually be happening - the code doesn't get run :P

**Comment by larsoner** [comment]
@choldgraf still seeing this one?

**Comment by choldgraf** [comment]
Hmmm, I think in distanced enough from this really weird bug that we should close this as not actionable
