### ISSUE TITLE
Is there a way to specify custom backreferences in a docstring?

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#228]
A couple of backreferences issues popping up on the MPL conversion!

I'm trying to get SG to replicate the backreferences style of plotting that MPL uses. But I'm running into two main things:

1. Backreferences for any methods are not getting picked up (e.g. `ax.scatter` doesn't have any examples generated for it in the backrefs folder, while `plt.scatter` does, even though there are examples that use both)
2. An issue I'm running into with matplotlib is that there are duplicates of many things. For example, there is the `plt.scatter` function, as well as the `ax.scatter` function, which is pretty much the same in spirit. In these cases, backreferences to one should really also be backreferences to another.

For #2 I'm not sure if / how to do this elegantly. Maybe one could specify a "link" between one function and another in the docstring, such that any backrefs for one function also show for another. So in the `ax.scatter` docstring I could put something like `See also: matplotlib.pyplot.scatter  <SG>` and when generating backrefs it would find the `<SG>` and know to generate the plt.scatter backref examples for that method?

LMK if there are any thoughts or ideas on this issue! Slowly bringing the matplotlib docs towards sphinx gallery one error at a time :)

**Comment by GaelVaroquaux** [comment]
References are handled with the intersphinx protocol. Basically, if
intersphinx gets it right, so does sphinx-gallery.

**Comment by choldgraf** [comment]
Ah I see. I wonder if this is actually a problem of imports then. Eg many if the mpl examples create an axis object with 'plt.subplots'. I don't think Sphinx Gallery would know to connect that axis object's methods with the Axes class in that case. Hmm.

**Comment by choldgraf** [comment]
and in this case, I'm going to close this in favor of #205 because I think that's actually the culprit
