### ISSUE TITLE
"image file not readable" with 0.1.9

### ISSUE THREAD

**Issue by dopplershift** [sphinx-gallery/sphinx-gallery#229]
I'm having problems now building our docs with 0.1.9. The warning is:
```
Warning, treated as error:
/Users/rmay/repos/metpy/docs/examples/Advanced_Sounding.rst:None: WARNING: image file not readable: Users/rmay/repos/metpy/docs/examples/images/sphx_glr_Advanced_Sounding_001.png

make: *** [html] Error 1
```
It looks like for some reason now sphinx-gallery is embedding the full absolute path in the rst file:

```rst
.. image:: /Users/rmay/repos/metpy/docs/examples/images/sphx_glr_Advanced_Sounding_001.png
    :align: center
```

Looking over the PRs in the latest release, I'm guessing that [this block](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/gen_rst.py#L304) is the problem; `figure_paths` is created twice there, but the first one, which handles making relative paths, isn't used. I'm guess copy/paste problem.

**Comment by dopplershift** [comment]
cc @jrleeman

**Comment by choldgraf** [comment]
I have the same problem in trying to build the MPL docs.

In my case, it's not including the `/` at the beginning of the path. So it starts with `Users/choldgraf/etc`, and doesn't start with `/Users/choldgraf/etc`.

**Comment by dopplershift** [comment]
Yeah, I think that relates to `lstrip()` in the same block above--it's probably fine if you actually have a relative path, but not for absolute.

**Comment by choldgraf** [comment]
FWIW this seems to be the case for the SG website too ;-)

![image](https://cloud.githubusercontent.com/assets/1839645/25251737/33015c1e-25cf-11e7-8d79-56660eb9d8f9.png)

http://sphinx-gallery.readthedocs.io/en/latest/auto_examples/plot_exp.html#sphx-glr-auto-examples-plot-exp-py

**Comment by Titan-C** [comment]
I'm terribly sorry on this one. I did not notice this because cached builds of the gallery in my pc and not having good test and not reviewing the output on travis, very irresponsible on my side. This bug came in by PR #218 to deal with windows path and I only checked on the generated html for windows not even the RST files. I'm working on a fix now

**Comment by dopplershift** [comment]
No worries, it happens.

**Comment by choldgraf** [comment]
is this updated in pip?

**Comment by Titan-C** [comment]
This should be fixed. Is fixed in my PC, and on Circle CI, even on my personal readthedocs build. But somehow on the sphinx-gallery website it is not updated even if shows being build from the latest commit. Does someone have experience with that?

**Comment by choldgraf** [comment]
does readthedocs build from pip? I just tried a pip upgrade and it didn't change any of the code

**Comment by Titan-C** [comment]
Now is on pip. And read the docs should be working now

**Comment by dopplershift** [comment]
Seems to have fixed our problems. Thanks for the quick turnaround! 🎉

**Comment by jrleeman** [comment]
Thanks indeed!

**Comment by choldgraf** [comment]
You're awesome, @Titan-C ! Thanks!

**Comment by Ayesha2788** [comment]
Hi  I am a beginner to Sphinx and restructured Text can anyone guide me how to resolve this error:
/Users/user/documentation/docs/source/index.rst:: WARNING: image file not readable: picture.jpeg

I don't know where to save this image. and I am using Sphinx and visual studio code editor on Mac

this is the code I have written on Mac

.. image:: picture.jpeg
   :height: 100px
   :width: 200 px
   :scale: 50 %
   :alt: alternate text
   :align: right

**Comment by rrigdon** [comment]
I'm having issues with image files getting a not readable error. 

I'm trying to replace images in VS Code with Sphinx 2.2.1. When using `make html`, I get the error:
`WARNING: image file not readable: img/nav-new-env.png`. This error only refers to the new image files. Why won't it show the images?

**Comment by larsoner** [comment]
@rrigdon are you actually using this project (`sphinx-gallery`), or just `sphinx`? Your error looks related just to `sphinx` as we should not mess with any `img/nav-new-env.png` sort of filenames

**Comment by rrigdon** [comment]
Ah, you're right. Sorry about that!
