### ISSUE TITLE
Some text is being handled differently by SG

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#231]
I just noticed that sphinx gallery is doing some weird stuff with my text. For example put this in both a regular sphinx `.rst` file, and then the same thing in a python file that sphinx gallery generates.

`r'$\left(\frac{5 - \frac{1}{x}}{4}\right)$'`

BUT - there's one extra thing. This only seems to happen if the `rst` is in the original docstring section within the `"""`. If it's embedded in an inline code segment then it the error doesn't occur.

e.g., the above line gets rendered to this if it's within `"""`:

`r'$\left(rac{5 - rac{1}{x}}{4}
ight)$'`

but to this if it's inline code:

`r'$\left(\frac{5 - \frac{1}{x}}{4}\right)$'`

**Comment by QuLogic** [comment]
Is the outside `"""` also raw? I'm not sure this is a SG thing.

**Comment by choldgraf** [comment]
Ah ha, that's a good point. No it's not raw. Maybe this is something that can't be dealt with the. Does that just mean that people can't put raw text blocks in their docstrings without them being rendered by sg?

**Comment by QuLogic** [comment]
If the outer string is not raw, then the backslashes need to be escaped. Python doesn't know anything about text-that-looks-like-code inside a string; it'll interpret the backslashes just the same.

**Comment by Titan-C** [comment]
> No it's not raw. Maybe this is something that can't be dealt with the. Does that just mean that people can't put raw text blocks in their docstrings without them being rendered by sg?

I don't fully understand your use case. But Sphinx-Gallery recognizes
the docstring with Python's AST. And it sees it exactly the way you have
defined. Thus if you want it to understand the backslashes you need to
escape them or make the entire docstring raw.

**Comment by choldgraf** [comment]
Sounds good - looks like this is intended behavior so I'm closing this issue. Just bringing it up in case it was an obscure bug :)
