### ISSUE TITLE
Use `bbox_inches="tight"` in savefig

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#235]
Right here

https://github.com/sphinx-gallery/sphinx-gallery/blob/d9b90ed93877b6e0004af6fcfed43e92376d0d02/sphinx_gallery/gen_rst.py#L260 

I think it would be good to use `bbox_inches="tight"`. This will make sure that the saved figure is fit to the data contained within it. Otherwise you often accidentally get text that's cut off. It's also consistent with what happens when figures get rendered in the notebook. Friendly to a PR that adds this flag?

**Comment by Titan-C** [comment]
This issue has annoyed me too from time to time. I don't understand why
`bbox_inches="tight"` is not matplotlib's default. And if there is a
good reason for that not to be the default, maybe there is a good reason
for us not to have that as default. So I have left that aside.

I have a personal work around, that I would prefer. That is to change
here

https://github.com/sphinx-gallery/sphinx-gallery/blob/d9b90ed93877b6e0004af6fcfed43e92376d0d02/sphinx_gallery/gen_rst.py#L530

to :

```python
matplotlib.rc_file_defaults()
```
Then I keep my matplotlibrc file with my personal defaults. And we
should of course document this in the FAQ section.

@GaelVaroquaux @lesteve any comments?

**Comment by GaelVaroquaux** [comment]
When we tried this (a few years ago) some layout of some figures where
completely broken (I seem to remember that it was with the colorbar going
inside the figure instead of staying outside. So we settled down to
adding the tight_layout in the scripts on a case-to-case basis. In
addition, it seemed that having code give the same figure inside and
outside sphinx-gallery is the right thing to do.

**Comment by lesteve** [comment]
> In addition, it seemed that having code give the same figure inside and outside sphinx-gallery is the right thing to do.

+:100:

**Comment by choldgraf** [comment]
Yeah - that makes sense. What often confuses people is that jupyter notebooks don't adhere to this, they save figures with `bbox_inches="tight"` before embedding them inline in the notebook, I believe. So this has caused some confusion w people, I agree that's not really sphinx-gallery's problem though :)

**Comment by choldgraf** [comment]
So, sounds like we're agreed upon that bbox_inches="tight" won't be used, then? If so feel free to close the issue
