### ISSUE TITLE
Unable to use `https` in `reference_url`

### ISSUE THREAD

**Issue by dopplershift** [sphinx-gallery/sphinx-gallery#236]
If you try to point to an https URL for referencing other documentation (using the `reference_url` key), you get a `FileNotFoundError`. This is due to a bad [`startswith` line](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/docs_resolv.py#L35) in docs_resolve.py.

**Comment by lesteve** [comment]
Hmmm this seems a bit fragile indeed. PR more than welcome! Something based on `urllib.parse.urlparse` (or `urlparse.urlparse` for Python 2) seems like a good solution.
