### ISSUE TITLE
Possible to show the same figure multiple times?

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#240]
Sometimes you want to iteratively build up a figure, showing its current state multiple times. Something like this:

```
fig, (ax1, ax2) = plt.subplots(1, 2)
ax1.plot(x, y)

##########################
# Here I explain ax1

ax2.scatter(x, y)

##########################
# Here I explain ax2
```
I believe that currently, the figure will only show up in the first call to plot, and nothing will show up in the second call. In addition calling things like `plt.tight_layout` will raise errors unless you call it once before each ####### block.

Is this something that's on the roadmap to support? It can be cumbersome (and use a lot of code) to have to re-build the whole figure from scratch each time you do want to show it.

**Comment by GaelVaroquaux** [comment]
I am not sure how we can address that. Not only would it lead to
non-trivial semantics, but also it would break the link with IPython
notebooks.

**Comment by choldgraf** [comment]
> Not only would it lead to non-trivial semantics

Do you mean on the coding side? At least from the perspective of authors, the reason I bring this issue up is because I've now seen many authors of sphinx-gallery-style tutorials make the same mistake I describe above. Obviously it depends on the use-case, but for many at least it feels natural to iteratively build figures in this way...

> but also it would break the link with IPython notebooks.

Can't jupyter notebooks re-display figures at any cell within the notebook, so long as the last line returns a `figure` instance, or if the user calls `plt.show`? I can see how this would cause weird results if, e.g., the author only called `plt.show` once and suddenly a bunch of figures popped up in one cell.

Personally this is not something I think is a critical feature, but am curious if it would be non-trivial to implement (in which case it's probably not worth it).

**Comment by GaelVaroquaux** [comment]
>     but also it would break the link with IPython notebooks.

> Can't jupyter notebooks re-display figures at any cell within the notebook, so
> long as the last line returns a figure instance, or if the user calls plt.show?
> I can see how this would cause weird results if, e.g., the author only called
> plt.show once and suddenly a bunch of figures popped up in one cell.

Can they? If they can, we should mimic the behavior. But I don't know
this semantic. Hence, my comment on non trivial semantics.

**Comment by choldgraf** [comment]
> Can they? If they can, we should mimic the behavior. 

I just tested it out and, in true Jupyter form, its...complicated :-P

It looks like running `fig.show` *doesn't* work, though if you just put the `fig` object at the end of a cell, it *does* work. Which is dumb. :-/

https://github.com/choldgraf/misc/blob/master/test_multiple_show.ipynb

Until that jupyter behavior gets sorted out I agree it doesn't make sense to implement anything like this in SG. Telling users to call `fig.show` before each `########` block seems reasonable, telling them to put just `fig` on the last line before `########` seems dumb.

**Comment by Titan-C** [comment]
We already went through a debate on this refer to PR #161. It is true
that for a tutorial it would be useful to iteratively construct the
example and have a cached figure. But doing it on Sphinx-Gallery is not
so easy although PR#161 already has an implementation. Nevertheless
getting the same behavior on a Jupyter notebook requires a different
implementation. For now, I think is not a good idea to cache the figures
until the end of the script.

**Comment by choldgraf** [comment]
Sounds good - that makes sense to me! I'm going to close this since it's already discussed elsewhere
