### ISSUE TITLE
sphinx 1.6.1

### ISSUE THREAD

**Issue by lheagy** [sphinx-gallery/sphinx-gallery#241]
It appears that sphinx 1.6.1 might have made a namespace change that is now causing the sphinx-gallery construction to fail for our docs (https://travis-ci.org/simpeg/simpeg/jobs/232691854#L1325) 
```
 File "/home/travis/miniconda/lib/python2.7/site-packages/sphinx_gallery/gen_gallery.py", line 297, in setup
    if 'sphinx.ext.autodoc' in app._extensions:
AttributeError: 'Sphinx' object has no attribute '_extensions'
```

thanks for your help!

**Comment by choldgraf** [comment]
see #242
