### ISSUE TITLE
Confusing line numbers in traceback

### ISSUE THREAD

**Issue by anntzer** [sphinx-gallery/sphinx-gallery#248]
When building e.g. the s-g docs, one gets the traceback
```
/home/antony/src/extern/sphinx-gallery/examples/plot_raise.py failed leaving traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 472, in execute_code_block
    exec(code_block, example_globals)
  File "<string>", line 2, in <module>
NameError: name 'iae' is not defined
```
but the error actually occurs at line 23 of the .py file (I realize this is probably the line number *within the cell*, but this can make troubleshooting a bit trickier).

**Comment by Titan-C** [comment]
I agree is confusing. Unfortunately we can not keep full track of line
numbering on the file when dealing with codeblocks. I nevertheless
believe having the traceback corresponding to the line inside the cell
level makes more sense. What we could enforce is that codeblocks in the
html have line-numbers for each cell, it is just an extra flag in the
rst.

**Comment by Titan-C** [comment]
In fact I just gave it a try to put line numbers, see:
https://127-26191147-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/rtd_html/auto_examples/plot_raise.html#sphx-glr-auto-examples-plot-raise-py
or
https://127-26191147-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/rtd_html/auto_examples/plot_syntaxerror.html#sphx-glr-auto-examples-plot-syntaxerror-py

But the lines that Sphinx proposes don't always match with the line counting of the Python execution.

**Comment by anntzer** [comment]
It seems clear that it is the traceback lines that are incorrect.

Speaking of the traceback, I would also get rid of the first two lines
```
  File "/home/ubuntu/sphinx-gallery/sphinx_gallery/gen_rst.py", line 473, in execute_code_block
    exec(code_block, example_globals)
```
which are of no interest to the user.

This could be done e.g. by locally overriding sys.excepthook (https://docs.python.org/3/library/sys.html#sys.excepthook) to your own formatter (traceback.format_list (https://docs.python.org/3.6/library/traceback.html#traceback.format_list) may be helpful).

**Comment by lesteve** [comment]
Rather than correcting the line number, the most useful thing to have in the traceback would be the actual line that causes the error. Not sure how easy this is.
