### ISSUE TITLE
UnicodeDecodeError on Windows when building doc

### ISSUE THREAD

**Issue by pllim** [sphinx-gallery/sphinx-gallery#253]
Windows 7, Anaconda, Python 3.5.3, Astropy 2.0.dev19112, Sphinx 1.5.6

<img width="530" alt="untitled" src="https://user-images.githubusercontent.com/2090236/27345321-3e6b74dc-55b7-11e7-83c3-729f94bdfc36.png">

**Comment by pllim** [comment]
Please re-open this, as #257 was reverted.

**Comment by pllim** [comment]
#254 definitely fixed this error for me but was rejected. So until you can find a better fix, this is still a problem.

**Comment by Titan-C** [comment]
I agree, it remains a bug. I had to revert #257 since backreferences, and mini galleries stopped working on python 2.

**Comment by pllim** [comment]
This same problem was fixed in another package, please see astropy/sphinx-automodapi#33 .

**Comment by lesteve** [comment]
We should definitely add a CI build where we use a ASCII locale.

**Comment by larsoner** [comment]
We now build with ASCII locale and things pass, so I think this is fixed. Feel free to reopen if it's not
