### ISSUE TITLE
Test embeding of links in source blocks

### ISSUE THREAD

**Issue by Titan-C** [sphinx-gallery/sphinx-gallery#260]
Link embedding is fragile. It stopped working in python 2 after #257 thus it is reverted in  #259
Need a test with little html to check links are being embedded.

**Comment by lesteve** [comment]
I think we have something like this already:
https://github.com/sphinx-gallery/sphinx-gallery/blob/ebe1ca3cbdd7a410c2a45b22cb374af08d4912d5/sphinx_gallery/tests/test_full.py#L48-L64

Closing, @Titan-C feel free to reopen if I missed something.
