### ISSUE TITLE
Support Tagging examples

### ISSUE THREAD

**Issue by Cadair** [sphinx-gallery/sphinx-gallery#261]
It would be nice to be able to have some kind of categories that examples in multiple sections could be assigned to (i.e. all these examples use one subpackage).

sunpy/sunpy#2164

**Comment by Titan-C** [comment]
Could you elaborate on the idea. I'm not sure what you are asking nor I understand from the issue in sunpy.
- Tagging is a feature you can add yourself with a custom sphinx directive, or the index directive, see: https://stackoverflow.com/questions/18146107/how-to-add-blog-style-tags-in-restructuredtext-with-sphinx
 Just use that syntax in the docstring of the examples, or the comment blocks. Sphinx should take care
 I don't think we should ship this as a feature in Sphinx-Gallery. Though we can document a link to it or any good implementation you provide  
- You want to sort the subsections of a gallery, matplotlib style? It can be done naming the folders alphabetically and a sort key is being worked on #234 . To get  the table of contents at the beginning include the toctree directive in the readme.txt
- You what to group examples using a specific function. Done with backreferences https://readthedocs.org/projects/sphinx-gallery/builds/5627339/
- You whant to group at module or submodule level? That would require a complex re-implementation of the back-references to build those custom subgalleries. I don't see that happening soon, but PR's are welcome

**Comment by Eric89GXL** [comment]
In some sense #205 could be made to take care of this using backreferences.

**Comment by story645** [comment]
@Titan-C can you elaborate a bit on the tagging? For example, I'd love to push for tags to be integrated into https://matplotlib.org/gallery/ in a way that the tags can be searched & all examples w/ a given tag surfaced.

**Comment by larsoner** [comment]
@story645 did you look at the first suggestion?

https://stackoverflow.com/questions/18146107/how-to-add-blog-style-tags-in-restructuredtext-with-sphinx

You can use either of these solutions to tag/index examples just by adding RST to the example text somewhere (probably beneath the description paragraph? Or maybe right under the title if we properly support ignoring `..`-starting lines when looking for the description paragraph)

**Comment by story645** [comment]
I did, but I'm not sure how to go from that to on the fly galleries of examples w/ the same tag.

**Comment by lucyleeow** [comment]
@story645 Is the index solution (https://stackoverflow.com/a/19837140) a reasonable solution for you?

**Comment by melissawm** [comment]
Hi folks - I have created a small Sphinx extension to do this. Feel free to give feedback or ask for features. Thanks!

https://github.com/melissawm/sphinx-tags

**Comment by larsoner** [comment]
Awesome, thanks @melissawm !

FWIW if you'd rather have that repo live under an org account at some point rather than your personal one, I'm happy to help move that repo over to sphinx-gallery's org if you think it's a good fit, and give you appropriate permissions, etc.

Closing as fixed by sphinx-tags extension rather than SG

**Comment by melissawm** [comment]
@larsoner about that 😄 I just cut a release that I think makes sphinx-tags usable: https://github.com/melissawm/sphinx-tags

If you think this fits sphinx-gallery I'm happy to move - it would give the project more visibility and I'd love to help support sphinx-gallery, too. Cheers!

**Comment by larsoner** [comment]
@lucyleeow WDYT?

**Comment by lucyleeow** [comment]
Sounds great to me! I would maybe just suggest to make it clear that the tags work on all documentation pages, not just gallery examples?
