### ISSUE TITLE
Possible to ignore a file with sphinx-gallery?

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#262]
I'm trying to get SG set up with a project that needs an `__init__.py` file inside of the examples folder. This is giving sphinx-gallery issues because if there's no docstring it will error, and if I add a docstring then I get an empty image in the gallery for the init file. Is there a way to tell SG to totally ignore a file (e.g., with a regex or something?)

**Comment by Titan-C** [comment]
We support which python files are executed by the regex:

https://sphinx-gallery.readthedocs.io/en/latest/advanced_configuration.html#building-examples-matching-a-pattern

But you can't omit python files. The main idea of SG is for teaching
purposes, and thus everything should be visible by the user. So if you
need an __init__.py file in you project your user certainly does too and
I would advise you give it a docstring to the file to justify its
presence.

Python scripts which are not executed on purpose, or don't produce any
output should get a default thumbnail. If you are getting an empty
image, eg. white box that is a bug. If you wish to change the default
thumbnail. You can use:

https://sphinx-gallery.readthedocs.io/en/latest/advanced_configuration.html#using-a-custom-default-thumbnail-image

**Comment by choldgraf** [comment]
ah ok - we'll have to figure out something else then. The package was using the `examples` directory as a part of its test suite, so it needs `__init__.py` files in all of the folders to do imports etc. FWIW I could see this being something other packages do as well...

**Comment by Titan-C** [comment]
You mean you run the examples twice? First to build the gallery, Second to run the tests?

**Comment by choldgraf** [comment]
It's not my project so unfortunately I don't have a ton of say in how their tests get run (though I'm working on it). They do stuff in tests like `from examples import xxxfunction` and test that function. I agree it's a little bit weird :-)

**Comment by nicain** [comment]
I just hit exactly this use case.  The idea here is to leverage CI workflow to ensure that examples that don't actually work don't get checked in, and that example-breaking changes made to the package send up a flag ASAP to the example-maker.

I am happy to take a stab at this in a PR if I get the blessing of a core dev, and a little guidance about the best way to make it happen.

**Comment by lesteve** [comment]
@nicain I am not 100% sure I understand how what you say is related to @choldgraf original problem. Can you elaborate a bit?

**Comment by nicain** [comment]
@lesteve Sorry about that.  I am actually exactly in @choldgraf 's original use case: I have a repository with the examples file inside of the project dir.  The examples folder contains __init__.py, and I have built tests around these examples to ensure that they always run, given the current state of the repo.  I just started playing with a sphinx-gallery branch, and was able to gallerify the examples folder with minimal changes (yay!), but wasen't able to exclude the __init__.py file: https://github.com/nicain/dipde/tree/sphinx-gallery.  HTH; also, if you can suggest an alternative workflow that will allow me to sweep in my examples with CI to ensure they run, I'm totally OK with that alternative too.

**Comment by choldgraf** [comment]
FWIW, I found out the reason that the initial package includes `__init__.py` in their examples folder. It's because they want users to be able to do `from mypackage.examples import plot_example; plot_example()`

**Comment by lesteve** [comment]
@nicain if you just want to run the examples in the CI, you just need to do something like:

```
python setup.py install
cd doc
make html
```

Look at https://github.com/sphinx-gallery/sphinx-gallery/blob/master/.travis.yml for how we do it in sphinx-gallery.

> FWIW, I found out the reason that the initial package includes __init__.py in their examples folder. It's because they want users to be able to do from mypackage.examples import plot_example; plot_example()

@choldgraf it would make sense to have an additional variable to completely exclude files from the gallery. I would not say this is very high priority though. I don't see a good reason what you gain from having the examples inside the package. In particular it feels like `from mypackage.examples.some_example import plot_example; plot_example()` is kind of the same as `ipython mypackage/examples/some_example.py`. Do you have a link for the project you are mentioning out of curiosity?

**Comment by nicain** [comment]
Here is a package that does this: https://github.com/nicain/dipde/tree/release/0.2.1

`conda install -c nicholasc dipde`
`from dipde.examples.singlepop import example`

**Comment by choldgraf** [comment]
> I don't see a good reason what you gain from having the examples inside the package. In particular it feels like from mypackage.examples.some_example import plot_example; plot_example() is kind of the same as ipython mypackage/examples/some_example.py. Do you have a link for the project you are mentioning out of curiosity?

here's another: https://github.com/SciTools/cartopy

My 2 cents on the "from xxx import examples" topic. While this is not how I would personally structure my package, I don't think we should be in the business of telling users "your workflow is wrong".

**Comment by nicain** [comment]
Another use-case for ignoring a file would be to place a pre/post "make html" hook scripts into the gallery, that are not meant to be examples themselves.  Although these could live elsewhere, I guess...

**Comment by Titan-C** [comment]
I don't see the point in this. The entire idea of Sphinx-Gallery is to
teach. Yes, we are not in a place to tell users "Your workflow is
wrong". If they want to expose the example files as modules is totally
fine. I even do that having a module in the examples that has commonly
used plotting functions.

This module does nothing on its own. And it looks ugly to have an
example that does nothing. But there is the value in having it there. In
the same way the '__init__.py' you want to hide has a reason to be there
and I feel one should not be hiding it. It's part of the tool/workflow
and writing an extra doctring might be more useful for the student of
the package than having that file hidden.

**Comment by lesteve** [comment]
I am in favour of allowing to ignore completely a file based on a regex (based on `re.search` applied to the full absolute path). It does not seem too hard to do, I am guessing we can just skip files when we walk the examples folders. I may even be in favour of skipping `__init__.py` files by default.

**Comment by lesteve** [comment]
The main argument for me: we should not error with empty `__init__.py` files and in most cases there is very little point in showing the code of `__init__.py` files in the gallery.

**Comment by choldgraf** [comment]
I'd be +1 on either:

* Treating `__init__.py` files as "special" and just skipping (not erroring) on these if they don't have a header.
* Letting users create a regex to skip some files entirely.

This would be a pretty simple addition and I think it'd meet both usecases described here (where you do or you don't want to include those files)

**Comment by nicain** [comment]
+1

**Comment by larsoner** [comment]
Makes sense to me, and the value could default to `ignore='__init__.py'`, too.
