### ISSUE TITLE
Problem compiling from py to rst with unicode when local is not defined on mac

### ISSUE THREAD

**Issue by NelleV** [sphinx-gallery/sphinx-gallery#269]
Someone at the matplotlib sprint had a problem compiling the matplotlib documentation because of an example with utf8 character. His local was not set, but the encoding was defined correctly at the top of the file and thus the example ran fine.
When sphinx-gallery attempted to compile this python file into an rst file, it failed to detect the unicode encoding.

This problem was encountered on mac os x. We have not tried to reproduce it.

**Comment by lesteve** [comment]
This kind of problem with encoding has been noted a few times. I think we should add a test to make sure that the tests pass fine with an ASCII locale as I commented in https://github.com/sphinx-gallery/sphinx-gallery/issues/253#issuecomment-313123210.

**Comment by lesteve** [comment]
See how it was done there for example: https://github.com/astropy/sphinx-automodapi/pull/33/files#diff-354f30a63fb0907d4ad57269548329e3R46

**Comment by Titan-C** [comment]
I did stat work on this in my branch https://github.com/Titan-C/sphinx-gallery/tree/encoding
It is not only failing to build because of ASCII encoding, but at the same time recognizing the used functions does not work on python 2(Reason to revert #257 ) and issue #260 currently.

**Comment by anntzer** [comment]
Shouldn't you use https://docs.python.org/3/library/tokenize.html#tokenize.detect_encoding or https://docs.python.org/3/library/tokenize.html#tokenize.open to detect the encoding?  That should work as is on Py3; I see that you need to pass a bytestring to ast on Py2 so I'd suggest just reencoding the unicode string back to UTF-8 for Py2.

**Comment by lesteve** [comment]
Closed by #311.

**Comment by NelleV** [comment]
Thanks!
