### ISSUE TITLE
Attribute error on sphinx master

### ISSUE THREAD

**Issue by amueller** [sphinx-gallery/sphinx-gallery#270]
``AttributeError: 'Sphinx' object has no attribute 'status_iterator'``

from
```
  File "/home/andy/checkout/scikit-learn/doc/sphinxext/sphinx_gallery/docs_resolv.py", line 373, in _embed_code_links
```
It looks like these will be removed in 1.7:
https://github.com/sphinx-doc/sphinx/blob/master/CHANGES

**Comment by QuLogic** [comment]
Is this not fixed by #250?

**Comment by Titan-C** [comment]
I'll do a new release of the gallery today. I has already accumulated a lot of fixes. You can try with the new version again.

**Comment by amueller** [comment]
@QuLogic hm weird, maybe I didn't update master? I was pretty sure I did, or I messed up which version I build sklearn with and used the one we ship? I'll give it another go later.

**Comment by amueller** [comment]
Ah, I was using the sphinx-gallery release, not dev version. sorry!
