### ISSUE TITLE
DOC: List all `conf` options in one place

### ISSUE THREAD

**Issue by Eric89GXL** [sphinx-gallery/sphinx-gallery#276]
I'm not 100% sure e.g. #275 is valid (maybe something to do it exists already in SG?) because I couldn't find one place where all SG conf options were listed. I propose adding a single place that lists all options, and linking to the relevant advanced- or basic-doc sections to describe each entry as necessary.

I can take a stab at this if people agree it would help.

**Comment by Eric89GXL** [comment]
... for example, I couldn't find anywhere in the docs that mentioned how to set the thumbnail size. ~~There is probably some way to do it but I don't know after some looking at docs and code searching.~~ After [looking at the code](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/gen_rst.py#L357) I finally figured out there probably is no way to set it. Having a list in one place would have made it obvious.

**Comment by choldgraf** [comment]
This I think is a good idea - I found discovering the various functionality in sphinx-gallery to be a bit difficult as well. I think there should be one place that gives a docstring-style explanation of each possible configuration option.

**Comment by Titan-C** [comment]
> I can take a stab at this if people agree it would help.

I agree our docs are not the most discoverable. Thus at least explaining all our defaults in one place and having the link to the docs on how to modify them is extremely helpful.
