### ISSUE TITLE
BUG: pillarboxes are added to square images when scaling thumbnails

### ISSUE THREAD

**Issue by Eric89GXL** [sphinx-gallery/sphinx-gallery#282]
I couldn't figure out why I couldn't get my square-figure output to be size 250x250, then I looked at the actual thumbnail image, and it looked like this (ignore the improperly captured static image, this is a Mayavi problem that I need to track down), which I have put in a quoted bit of text so you can see the offset:

> ![sphx_glr_plot_fmri_activation_thumb](https://user-images.githubusercontent.com/2365790/28897143-9e5b9fc8-779c-11e7-92e8-3cc5655dfa22.png)

This gets created from this original image, which has no such offset:

> ![sphx_glr_plot_fmri_activation_001](https://user-images.githubusercontent.com/2365790/28897194-d46e8256-779c-11e7-8748-fc33669d9eb2.png)

In other words, SG adds white pillars on either side of the otherwise square image. It seems like this shouldn't be necessary and that CSS should be able to take care of whatever purpose this would serve (e.g., centering the element) instead. Can the rescaling routines be changed to fix this?

**Comment by Eric89GXL** [comment]
... alternatively, we could expose a `thumbnail_size` parameter, since the current code will force all real thumbnail images to be 400x280 [here](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/gen_rst.py#L356) and uses pillar / letterboxing to fill any gaps.

I'm also not sure why the "failing example" ones get set to a different size. I guess both sizes are bigger than the default that CSS forces them to be, but I don't see much point in them being different.

**Comment by choldgraf** [comment]
I guess another option would be to add (yet another) configuration parameter (e.g. `pillar_width:`). Dunno how I feel about that though...

**Comment by Eric89GXL** [comment]
Just setting the thumbnail size (tuple) would be sufficient here. And in
the docs say the image is scaled, respecting aspect ratio, to this size,
which might necessitate adding pillar or letterboxing.
