### ISSUE TITLE
Caching the "Embedding documentation hyperlinks in examples"

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#286]
The step "Embedding documentation hyperlinks in the examples" takes a lot of time. It would be great to cache it.

**Comment by Titan-C** [comment]
We already cache the database of links. What takes time is truly the
parsing of the HTML and rewriting it. This got a lot faster after
merging #272 if I remember correctly. Which version are you using?

**Comment by GaelVaroquaux** [comment]
> This got a lot faster after merging #272 if I remember correctly. Which version are you using?

Good point. I was on an old version. I updated, and it broke the build
:$.

I am closing this issue, but I opened a new one: #287.

The logic in #272 might be broken.
