### ISSUE TITLE
Fails on non-standard doc build location

### ISSUE THREAD

**Issue by hanke** [sphinx-gallery/sphinx-gallery#29]
The get_data() function in docs_resolv.py tries to open a cache file at ``_build/searchindex``. If a project uses a non-standard output location the ``_build`` directory may not present. As a result the build fails with:

````
DBNoSuchFileError: (2, 'No such file or directory')
````

caused by ``shelve.open(...)``

At present, there is no way to tweak this default location from the outside. As a workaround it is sufficient to create a dummy ``_build`` directory.

**Comment by Titan-C** [comment]
This comes indeed as a design question to where to store the cached files. Sphinx provides `app.builder.outdir` but there one shall include only final output files.
Should we make a temporary folder for sphinx-gallery cache files? @lesteve

**Comment by lesteve** [comment]
Disclaimer: I don't know too much about sphinx but it feels like one thing we could do would be to pass the BUILDDIR from the Makefile into sphinx, similarly to what is done for plot_gallery.

At the moment the python code uses a hardcoded '_build' in a couple of places: docs_resolv.py and gen_gallery.py.
