### ISSUE TITLE
Error when building examples

### ISSUE THREAD

**Issue by glemaitre** [sphinx-gallery/sphinx-gallery#299]
~~I got into the following issue after upgrading from 0.1.11 to 0.1.12~~

I just recently get the following error.

```
...
...
Embedding documentation hyperlinks in examples ...
auto_examples[  3%] index.html
auto_examples[  6%] plot_ratio_usage.html
auto_examples[  9%] plot_multi_class_under_sampling.html

Exception occurred:
  File "/home/ubuntu/miniconda/envs/testenv/lib/python3.6/site-packages/sphinx_gallery/docs_resolv.py", line 48, in _get_data
    data = StringIO(data)
TypeError: initial_value must be str or None, not bytes
```

~~Checking blaming it seems that #246 modified those line in the meantime.
I am not really familiar with the internal of sphinx-gallery but I am willing to make a PR if something need to be changed.~~

Does anybody have an idea where it is coming from.

#### System info

```
Linux-4.8.17-040817-generic-x86_64-with-debian-stretch-sid
Python 3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 17:14:46) 
[GCC 7.2.0]
Sphinx 1.6.3
Sphinx-Gallery 0.1.12
```

**Comment by glemaitre** [comment]
Uhm this is not linked to the version.

**Comment by larsoner** [comment]
These were fixed in #293 and then (even better, use `intersphinx`) in #296, can you try latest `master`? See updated docs [here](http://sphinx-gallery.readthedocs.io/en/latest/advanced_configuration.html#link-to-documentation).

**Comment by glemaitre** [comment]
Thanks @larsoner, there is not problem in master using intersphinx.
I will upgrade our CI :)

**Comment by Titan-C** [comment]
I'm doing a release today. There are plenty of improvements since the last release and #287 which was a blocker is now fixed.
