### ISSUE TITLE
ipynb file not created

### ISSUE THREAD

**Issue by NelleV** [sphinx-gallery/sphinx-gallery#306]
Setting up a new project to use sphinx-gallery, I ran into this issue (the ipynb file is not found).

```
(goldwrap) nelle@tamaris> make html                                                                                                                                                         ~/Projects/2017genomic_times_series_bnp/bin/tritonis/doc
Running Sphinx v1.6.3
making output directory...
loading pickled environment... not yet created
generating gallery...
generating gallery for auto_examples... [100%] plot_splines_regression.py                                                                                                                                                                            

Exception occurred:
  File "/home/nelle/.miniconda3/envs/goldwrap/lib/python3.6/zipfile.py", line 482, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/nelle/Projects/2017genomic_times_series_bnp/bin/tritonis/doc/auto_examples/plot_splines_regression.ipynb'
```

**Comment by NelleV** [comment]
It's now working, and I am not able to reproduce the bug with the changes I made since…

**Comment by GaelVaroquaux** [comment]
I've already seen this after a half-successful build (and half-broken
build)

**Comment by tfardet** [comment]
I'm having the exact same issue except that I cannot seem to get it to work again...
I deleted all files in the gallery (except .py of course) and sphinx build folder, as well as __pycache__... I'm at a loss.

Any idea where gallery may be storing files that would still have this hypothetical "half broken" build in memory?

**Comment by larsoner** [comment]
> I deleted all files in the gallery (except .py of course) and sphinx build folder, as well as pycache... I'm at a loss.

Sounds like you cleared out `examples/*` (except Python files) and `doc/build/*`, but did you remove `doc/auto_examples`?

**Comment by tfardet** [comment]
Yeah, I must have been tired, I was just looking at the wrong level and deleting generated files instead of original files, sorry for the noise
