### ISSUE TITLE
Is there a poster for sphinx-gallery?

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#309]
I'm going to the MSDSE retreat in about 1.5 weeks (it's the joint project between data science centers at Berkeley, UW, and NYU). I was planning to have a poster there to show off sphinx-gallery and try to drum up some interest in adoption, as there will be many open-sourcey people there.

Does anybody have a poster that they put together for the project? Or slides? Trying to not duplicate efforts on this front :-)

**Comment by GaelVaroquaux** [comment]
Not that I know of. There have been presentations (slides), but I don't
know of a poster.

**Comment by choldgraf** [comment]
do you have links to presentations by any chance? :-)

**Comment by choldgraf** [comment]
(obv if I put together a poster I'll share it with you all)

**Comment by GaelVaroquaux** [comment]
> do you have links to presentations by any chance? :-)

@titan-C?

I found this: http://oscarnajera.com/sphinx-gallery-slides/

**Comment by Titan-C** [comment]
I'm jumping in quite late.

This are the slides for the presentation I made for Euroscipy 2016
http://oscarnajera.com/sphinx-gallery-slides/

The source is on
https://github.com/Titan-C/sphinx-gallery-slides

I prepared a poster for EuroPython 2017, but Sphinx-Gallery wasn't its
main focus. But that I'm putting my PhD work onto a platform where you can reproduce my work using Sphinx-Gallery.

[poster2.pdf](https://github.com/sphinx-gallery/sphinx-gallery/files/1420216/poster2.pdf)

**Comment by lesteve** [comment]
I didn't know about your poster at EuroPython. Nice poster showcasing sphinx-gallery!

**Comment by choldgraf** [comment]
Hey all - just in case you'd like it, here's the poster that I used at the BIDS summit in New Orleans:

Illustrator:
https://www.dropbox.com/s/f6q16eblt71oms0/sphinx_gallery.ai?dl=0

PDF:
https://www.dropbox.com/s/o0lvgab8mf48uf3/sphinx_gallery.pdf?dl=0

Happy for folks to re-use/edit/etc

**Comment by lesteve** [comment]
@choldgraf looks very nice, thanks for sharing! Nitpick I think reST (rather than rST) is used as an acronym for reStructuredText.

**Comment by choldgraf** [comment]
that is good to know :-) will change it next time I have the occasion to present the poster somewhere!
