### ISSUE TITLE
Failure : 'Sphinx' object has no attribute '_extensions'

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#310]
We're getting a failure that I don't understand on the CI of a project:

https://circleci.com/gh/nistats/nistats/45?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by KamalakerDadi** [comment]
I think it depends on the sphinx version.
Please have a look at this
https://github.com/nilearn/nilearn/commit/07455aadd202ac32cd4d72937682d2a72c0b7e1b

**Comment by Titan-C** [comment]
This was already fixed in PR #242 to for version of Sphinx>1.6. You need a version upgrade.

**Comment by larsoner** [comment]
@GaelVaroquaux it sounds like this has been fixed, okay to close?

**Comment by lesteve** [comment]
Closing this one.
