### ISSUE TITLE
Option to insert a preamble in index.rst

### ISSUE THREAD

**Issue by jnothman** [sphinx-gallery/sphinx-gallery#315]
Not having a top-level heading for an example gallery with many sections seems a bit awkward. One result is that we have a 7-page table of contents for the scikit-learn PDF docs, most of which are examples, only because there is a *chapter* for each examples section (i.e. of equal weight as the user guide).

An introductory paragraph wouldn't hurt either, pointing, for instance, to the source directory from which the gallery is compiled.

I think there should be an option that inserts (or `.. include::`s) custom reST in `index.rst` before the gallery listing begins.

**Comment by jnothman** [comment]
I also note that we had such a top-level heading at scikit-learn previously, so this is a regression relative to the pre-sphinx-gallery era: http://scikit-learn.org/0.17/auto_examples/

**Comment by GaelVaroquaux** [comment]
Am I wrong to think that this can be done via the README.rst of the main
example folder?

Maybe this should be documented better.

**Comment by jnothman** [comment]
Ahh of course. I'd forgotten the headings were coming from readme too.

I can't say I looked for the docs, and it would probably be obvious to a newcomer. I was merely trying to solve the regression and placed blame incorrectly!
