### ISSUE TITLE
What is SKLEARN_DOC_OPTIPNG about?

### ISSUE THREAD

**Issue by jnothman** [sphinx-gallery/sphinx-gallery#319]
We no longer seem to apply optipng in scikit-learn doc builds, while sphinx-gallery apparently allows for an undocumented [`SKLEARN_DOC_OPTIPNG` environment variable](https://github.com/sphinx-gallery/sphinx-gallery/blob/dbd4b7b1a9bea7338e94854535bca6b79993042e/sphinx_gallery/gen_rst.py#L343). Should we be using this in Scikit-learn's Circle CI? Should it be removed? Should the `SKLEARN_` prefix be removed?

**Comment by jnothman** [comment]
Also, unlike the former use of optipng when building scikit-learn docs, it only seems to be applied here to thumbnails and mayavi images.

**Comment by lesteve** [comment]
Well spotted! You may remember better than me why we were using it in scikit-learn. I found this:
https://github.com/scikit-learn/scikit-learn/blob/08ec7be764e43f63454acd2553badd9beb9dc0cb/doc/README.md.

> It's recommended to run OptiPNG, before uploading the website. The PNG files generated by Matplotlib tend to be ~20% too big, and they're costing us bandwidth.

I don't think we are using it anymore in scikit-learn on CircleCI for good or bad. Not sure whether we should keep it in sphinx-gallery. If yes, environment variable should be renamed to remove SKLEARN from it.

**Comment by lesteve** [comment]
Another one I found, from a one year younger version of @jnothman ;-) in https://github.com/scikit-learn/scikit-learn/pull/7671#issuecomment-254486587

> Yes, but the PDF without optipng is enormous, IIRC... Will we need to extend the timeout as in #7693?
> PDF without optipng is 45MB
