### ISSUE TITLE
Add example scripts in 'examples' subfolders

### ISSUE THREAD

**Issue by lesteve** [sphinx-gallery/sphinx-gallery#32]
Just to show the feature of grouping examples in diferent subsections.

The simplest is to create a few subfolders in `examples/` and move the current example scripts there.

**Comment by Titan-C** [comment]
done in #26

**Comment by lesteve** [comment]
Thanks for this! Sorry to repeat myself and be a pain but it's always a good idea to have different features in different branches.

**Comment by florian-wagner** [comment]
@Titan-C Is it possible to have subsubfolders or specify more than one `examples` directory? (our project differentiates between examples and tutorials)
