### ISSUE TITLE
Not clear that README.txt should contain a title

### ISSUE THREAD

**Issue by dstansby** [sphinx-gallery/sphinx-gallery#320]
Just spent a while trying to reference the sphinx-gallery index page, and realised that my `README.txt` file only contained:

```
Examples
```

Changing this to 
```
Examples
=======
```

made everything work as expected - it would be good mention in the docs that the `README.txt` file should have a title and is eventually interpreted as markup.

**Comment by GaelVaroquaux** [comment]
Sounds right. Do you want to send a pull request?

Thanks!

**Comment by lesteve** [comment]
Maybe we should move to README.rst to make it clearer that this is rst ... I think @Titan-C mentioned this at one point. Of course backward-compatibility is needed at least for a few sphinx-gallery versions.

**Comment by larsoner** [comment]
+1 from me, I was surprised (had to be reminded) that it wasn't .rst the
most v recent time I set up SG

**Comment by owlas** [comment]
It would actually be ideal if the user could configure the name of this file in `conf.py`. For example, repositories that use `readme.md` as a convention would rather follow that convention.

**Comment by dstansby** [comment]
Looking at https://sphinx-gallery.github.io/stable/getting_started.html#structure-the-examples-folder I think this is now fixed 🎉
