### ISSUE TITLE
Run sphinx-gallery on just one file?

### ISSUE THREAD

**Issue by nicain** [sphinx-gallery/sphinx-gallery#321]
My use case is that I would like an executable to convert a single python file, with appropriate sphinx-gallery header and comments to deliniate cells, and build an associated .html file.  Of course I could build out a template, inject that one file into the examples dir, turn the crank on the whole thing, and extract out just the one file, but this is pretty hacky.  Is there a relatively easy solution for "gallerify-ing" a single file?

The use-case is to allow individual contributors to a project a development workflow where they can rapidly prototype their example (fast, and no knowledge of the full sphinx html-building workflow), and then simply insert their build-out example into the appropriate gallery directory when its time to deploy.

**Comment by nicain** [comment]
CC @NileGraddis

**Comment by lesteve** [comment]
Short answer: I haven't tried it and I would think this is not this easy.

Longer answer: I don't really see your point.
* you can prototype your example rapidly by running `python your_example.py`
* if you are adding or tweaking a single example and care about the HTML ouput, you need to run `make html` once to run all the examples and then `make html` will only run the example you changed. This does not feel like you need to know a lot about sphinx-gallery to do that. If you want to avoid running all the examples once, you can run single example using [this](https://sphinx-gallery.readthedocs.io/en/latest/advanced_configuration.html#building-examples-matching-a-pattern).

> and then simply  insert their build-out example into the appropriate gallery directory  when its time to deploy.

If I am following you (you want the user to copy his generated example HTML into the html doc) this seems like a manual and brittle process, and the example code and example HTML is likely to go out of sync. This is pretty much what sphinx-gallery is trying to avoid.

**Comment by larsoner** [comment]
SG requires running sphinx with a proper setup. And if you use Sphinx hooks in your doc building (e.g., `intersphinx`) you probably want those checked in the examples, too -- so I'd expect you want some sort of near-full build anyway.

FWIW over in MNE we do something like this in an automated way using CircleCI -- we examine the `git diff` for any changed files and build with a `PATTERN` for SG builds only the changed file(s). In other words, users who want to add some example just do so in the proper directory, and it gets built and saved as an artifact anyone can view (e.g., [here](https://github.com/mne-tools/mne-python/pull/4799#issuecomment-348307068)). From your description it sounds like this would also work for your use case.

**Comment by lesteve** [comment]
> FWIW over in MNE we do something like this in an automated way using CircleCI -- we examine the git diff for any changed files and build with a PATTERN for SG builds only the changed file(s)

Nice (we build the doc fully in scikit-learn) !

**Comment by larsoner** [comment]
For us the time difference is something like 1.5 hours to build the entire thing vs 10 minutes to build a single example, so it was worth it :)

**Comment by nicain** [comment]
@lesteve 
> (you want the user to copy his generated example HTML into the html doc)
Sorry, what I meant is user to copy the .py file into the exampels folder, once they have it looking the way they want.

**Comment by nicain** [comment]
Following up:

> Longer answer: I don't really see your point.
> 
> you can prototype your example rapidly by running python your_example.py
> if you are adding or tweaking a single example and care about the HTML ouput, you need to run make html once to run all the examples and then make html will only run the example you changed. This does not feel like you need to know a lot about sphinx-gallery to do that. If you want to avoid running all the examples once, you can run single example using this.

I meant prototyping the layout of the example in html, not just the py file.  It can be tricky (esp with latex markdown) to see what the final rendered html will look like.

Imagine several contributors building examples for a project.  Currently for an example contributor to test the html layout resulting from a given .py example, they have to have the whole documentation package to run `make html`, and if they want to build only their example, nee to use regex to manipulate `filename_pattern` in the conf.py file.  It would be much easier to allow the individual example contributor to run a single command that would generate the html for their example, and after they tweak it to get the rendered html the way they want, ship the .py file into the repo.

**Comment by choldgraf** [comment]
this was a huge PITA with matplotlib, we had a hell of a time getting new contributors to work on documentation because:

1. They had to run the whole doc build each time to demo their results
2. They often didn't have any experience with Sphinx.

IMO users shouldn't *have* to know about sphinx builds, makefiles, etc in order to see what sphinx-gallery is gonna do to their python file. Those feel like two separate things (obviously with the exception of things like backreferences, but my guess is that iteratively prototyping the output isn't for the purpose of double-checking backreferences anyway)

**Comment by nicain** [comment]
Exactly what I am hitting as well.  rst2html.py (installed with docutils) is close, except it takes the rst file not the py file, and it doesn't know about SG.

**Comment by nicain** [comment]
> IMO users shouldn't have to know about sphinx builds, makefiles, etc

For example, if the contributor is on windows (this happened to my team yesterday); no make (we customize our make-html, and we don't have a parallel make.bat).

**Comment by choldgraf** [comment]
@nicain if you run rst2html on the rST that's generated from sphinx-gallery, how does it look? I wonder if this could be addressed by:

1. Giving a CLI to run sphinx-gallery on one python file, outputting the rST to some location. 
2. Creating documentation to suggest to users how to preview the rendered rST as HTML

**Comment by nicain** [comment]
wget https://gist.githubusercontent.com/nicain/50d65440482e568512fc6a8c2277b7e2/raw/d5d8132b76944bc4671f4f5f2eeb5d9079b6fe1d/out.html

**Comment by choldgraf** [comment]
hmmm, that's not great as the rst for images isn't picked up.

What if you tried following the commands here:

https://stackoverflow.com/questions/10692228/simplest-way-to-run-sphinx-on-one-python-file

aka, navigate to teh folder w/ `conf.py` in it and run `sphinx-build` on the rst file

**Comment by larsoner** [comment]
To me it seems like what you two are talking about already exists. Did you look at the code I linked to above?

> Currently for an example contributor to test the html layout resulting from a given .py example, they have to have the whole documentation package to run make html, and if they want to build only their example, use regex to manipulate filename_pattern in the conf.py file. 

That is one way but not the only one...

> It would be much easier to allow the individual example contributor to run a single command that would generate the html for their example, and after they tweak it to get the rendered html the way they want, ship the .py file into the repo.

... a one-liner like this should work when run from the `doc` directory:

```
sphinx -D sphinx_gallery_conf.filename_pattern=plot_my_example.py -b html -d _build/doctrees . _build/html
```
This is what the code I linked to above does.

If this is too long, you might be able to omit some arguments (haven't checked). In MNE we just wrap this in a `Makefile` so the user can just do:
```
PATTERN=plot_my_example.py make html-pattern
```
(With the `circle.yml` file I linked, of course the file gets built as part of the PR so maintainers can see it (i.e., with *no* user interaction required), but this is an optional step. But this is laborious for iteration and thus more useful as a final check / review step.)

> For example, if the contributor is on windows (this happened to our team yesterday); no make

I do Sphinx(-gallery) builds with the Windows `git` bash command prompt without problems, I'd suggest giving it a try as a solution for Windows users. Or you just explicitly give them the longer one-liner above.

> IMO users shouldn't have to know about sphinx builds, makefiles, etc in order to see what sphinx-gallery is gonna do to their python file.

I'm not sure how you expect get a useful/complete output without having `sphinx` working. (Is this really a burden with Anaconda nowadays?) Here "knowing a Makefile" means telling users to write something that seems short and simple to me. What interface do you hope for that would be simpler than the 26-character (plus filename) example `PATTERN=XXX make html-pattern`?

**Comment by choldgraf** [comment]
that's a good point @larsoner , on this point:

> IMO users shouldn't have to know about sphinx builds, makefiles, etc in order to see what sphinx-gallery is gonna do to their python file.

after thinking about it a bit more, I agree w/ you and @lesteve that this is kind of hard to avoid. @nicain what do you think about the workflow that @larsoner proposes?

**Comment by nicain** [comment]
Seems good at first glance.  But I just tried it, and cannot seem to build a conf.py file that will run through, without building the rest of the website (index.rst, etc.)

**Comment by larsoner** [comment]
Yes it will build the rest of the site, too, is that a limiting factor?

**Comment by larsoner** [comment]
@nicain okay to close this one?

**Comment by larsoner** [comment]
FYI @nicain I added a `.. note::` in the doc update to #346 that should make it clearer to future folks how to do it:

https://366-25860190-gh.circle-artifacts.com/0/home/ubuntu/sphinx-gallery/rtd_html/advanced_configuration.html#parsing-and-executing-examples-based-on-matching-patterns

Feel free to look and comment if it's not clear.
