### ISSUE TITLE
name string_replace trips on projects with ".py" in path

### ISSUE THREAD

**Issue by nicain** [sphinx-gallery/sphinx-gallery#322]
https://github.com/sphinx-gallery/sphinx-gallery/blob/fb2da9af8c3c9282150b26c356f97fdddfcefb82/sphinx_gallery/notebook.py#L193

This code will trip on projects that have '.py' as a substring.  I found this because I am working on a project called "aibs.pyproject_template".  This will need a more exclusive replacement string.

**Comment by lesteve** [comment]
Oops sorry about that ... PR more than welcome! You may want to double-check that there are not more instances of this pattern across the whole codebase.

**Comment by nicain** [comment]
@lesteve See https://github.com/sphinx-gallery/sphinx-gallery/pull/331
