### ISSUE TITLE
I'm gonna be in paris tomorrow :-)

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#323]
Apologies that this is not really sphinx-gallery related, but I'm not sure how to get ahold of you all otherwise :-)

I'm boarding a flight for Paris today, will arrive Friday and will be around the city for most of next week. It'd be great to have a cafe or a drink if anyone is around!

(I'll close this issue soon :-P )

**Comment by GaelVaroquaux** [comment]
OK, where will you be in Paris?

**Comment by choldgraf** [comment]
For the weekend / first few days, north of the city near Saint Denis. During the week I think we'll stay near Nation. Then it's down to the ⛰ Friday :-D  

That said, each day I'll probably be in Paris finding coffee shops to work at etc, probably going to spend some time with Sylvain who has an office near nation as well

**Comment by GaelVaroquaux** [comment]
OK, we're all located in the South (the deep South, actually). On
Wednesday end of afternoon, I'll be in Paris.

**Comment by choldgraf** [comment]
cool - I may come down there to see @agramfort at some point too, will let you know plans to head that direction as they become more clear! You're off of the RER yea?

**Comment by GaelVaroquaux** [comment]
> You're off of the RER yea?

Absolutely. The RER is the source of the cool!

**Comment by choldgraf** [comment]
haha - looking forward to it ;-)

**Comment by choldgraf** [comment]
closing this issue since you all know about my existence in your city now :-)

**Comment by Titan-C** [comment]
Just read this. I'm leaving Paris next Wednesday, we can still manage to meet
over the weekend or Monday.

**Comment by agramfort** [comment]
ping me on hangout when you're around.

**Comment by lesteve** [comment]
Interested to meet as well, keep me posted! I work in Paris near gare de Lyon but I can venture in the deep south if that's more convenient for everybody involved.

**Comment by choldgraf** [comment]
Starting Tuesday I'll be staying near Nation, so maybe it'd be easiest to meet up tues or wed or thurs?

**Comment by agramfort** [comment]
wed or thurs would work for me

**Comment by choldgraf** [comment]
sounds like Wednesday evening is a good plan - I'll be somewhere near either telecom paristech or nation, not sure which, but can make it wherever you all would like to meet. How does that sound?

**Comment by choldgraf** [comment]
Headed to Télécom now if anybody would like to meet this evening for a
bière. I think @agramfort is gonna join me and Tom in a few hours

**Comment by GaelVaroquaux** [comment]
Hey,

I couldn't be there on Wednesday: I was at a meeting until late.

I am close to ENS at lunch and after this taking a train. @choldgraf :
are you still around?

**Comment by choldgraf** [comment]
no worries! Yesterday I took a train down to Chambery, so I'll hopefully be busy eating raclette + foie gras and skiing for the rest of the holidays. I'll be in Paris plenty of more times in the future! :-)

**Comment by GaelVaroquaux** [comment]
> Yesterday I took a train down to Chambery, 

Taking a train to Briancon in a couple of hours :)

**Comment by choldgraf** [comment]
🎿 ⛰ 🧀
