### ISSUE TITLE
Documenting strings within the script

### ISSUE THREAD

**Issue by florian-wagner** [sphinx-gallery/sphinx-gallery#33]
Great! Thanks for making this a dedicated package. The only thing I miss in comparison to http://tonysyu.github.io/mpltools/auto_examples/sphinx/plot_plot2rst.html is the ability to add documenting strings that hold rst and the option to place figures within the text/code examples.

This would allow for more notebook-like examples that walk the user through each step.

**Comment by lesteve** [comment]
We were planning to do something similar in the medium-term in order to allow richer text explanations inside examples. I didn't know about plot2rst and we'll definitely take a closer look and see how this is implemented. I really like the idea of using strings for the rst parts as well to be honest!

**Comment by Titan-C** [comment]
@florian-wagner Would you be an early adopter of sphinx-gallery for documenting strings in examples?
PR #36 already contains this feature.

**Comment by florian-wagner** [comment]
Sure, I will try it out asap.

Am 28.06.2015 um 10:28 schrieb Óscar Nájera:

**Comment by florian-wagner** [comment]
@Titan-C I have a minimal working example, which does exactly what I want. I will try to adapt it for my project. Is it possible to specify the path/name of the examples folder(s) as config variables or do they have to be at ../examples from the doc folder?

I like that long output is collapsed. In this regard, it would be nice to set the number of maximum output lines as a configuration variable and one-line outputs still have the scrollbar appearing, which can be removed.

Thanks for implementing this feature!

**Comment by Titan-C** [comment]
On Monday, June 29, 2015 02:06:03 AM Florian Wagner wrote:
> @Titan-C I have a minimal working example, which does exactly what I want. I
> will try to adapt it for my project. Is it possible to specify the
> path/name of the examples folder(s) as config variables or do they have to
> be at ../examples from the doc folder?
Yes you can.
http://sphinx-gallery.readthedocs.org/en/latest/advanced_configuration.html#changing-default-directories
> 
> I like that long output is collapsed. In this regard, it would be nice to
> set the number of maximum output lines as a configuration variable and
> one-line outputs still have the scrollbar appearing, which can be removed.
> 
This is completely CSS styling. so you just need to override the default
.sphx-glr-script-out pre {
  overflow-y: scroll;
  max-height: 30em; }

You can see how to override CSS, in our conf.py as I override the gallery
default to work nicer with the read the docs template.
I prefer to override CSS that setting configuration variables for styling.

**Comment by Titan-C** [comment]
PR #36 has changed the syntax for the documenting strings. Now they follow a more pythonic style in which they are comments in the code and not free strings.

**Comment by lesteve** [comment]
Closing this one, since it has been addressed by #36.
