### ISSUE TITLE
No support for numpydoc

### ISSUE THREAD

**Issue by corinnebosley** [sphinx-gallery/sphinx-gallery#333]
I have been trying to switch to sphinx-gallery rendering for our library cartopy (http://scitools.org.uk/cartopy/docs/latest/index.html) but all our docstrings are in numpydoc (https://numpydoc.readthedocs.io/en/latest/format.html#overview), which is not being rendered properly by sphinx-gallery.

Specifically, anything underlined inside a docstring is not being rendered at all; it just disappears (although that is not the case in rst files, in which the rendering of these text objects works just fine).

**Comment by Titan-C** [comment]
I'm really confused. Sphinx-Gallery is completely independent of
numpydoc, we don't document functions but make the web gallery.
Sphinx-Gallery does document its function docstrings using numpy syntax,
and for that to work you need to load the napoleon sphinx extension, you
can also load numpydoc sphinx extension.

Can you be more specific on where you docstrings are failing? Link to
your code?

**Comment by lesteve** [comment]
I was just about to post something similar to @Titan-C. Do you have a snapshot or even better a way to reproduce the problem?

FWIW a lot of projects that use sphinx-gallery follow the numpydoc convention for docstring as well (scikit-learn, scikit-image, matplotlib, etc ...) and that doesn't seem to be a problem.

**Comment by lesteve** [comment]
Can you explain why you closed the issue? Did you manage to fix your problem? Was it just a misclick?

**Comment by corinnebosley** [comment]
I think this must be a general sphinx thing, not sphinx-gallery.  Apologies.

**Comment by lesteve** [comment]
OK, thanks! Do let us know how in case sphinx-gallery turns out to be the culprit or if you bump into other problems while trying to use sphinx-gallery!
