### ISSUE TITLE
Surprising interaction between file_pattern and expected_failing_examples

### ISSUE THREAD

**Issue by lesteve** [sphinx-gallery/sphinx-gallery#335]
If through filename_pattern you are not running an example that is expected to fail you will get an error that the example has not failed as expected.

I would expect that there is no error: in my use case I just want to run one example I could not care less about examples that are expected to fail.

To reproduce apply this diff (set filename_pattern to seaborn essentially):
```diff
diff --git a/doc/conf.py b/doc/conf.py
index ac53cf6..24c4cfe 100644
--- a/doc/conf.py
+++ b/doc/conf.py
@@ -339,6 +339,7 @@ sphinx_gallery_conf = {
                                        '../tutorials/seaborn']),
     'within_subsection_order': NumberOfCodeLinesSortKey,
     'find_mayavi_figures': find_mayavi_figures,
+    'filename_pattern': 'seaborn',
     'expected_failing_examples': ['../examples/no_output/plot_raise.py',
                                   '../examples/no_output/plot_syntaxerror.py'],
     'binder': {'org': 'sphinx-gallery',
```

Relevant part of the output:
```
Examples expected to fail, but not failling:
Please remove these examples from
sphinx_gallery_conf['expected_failing_examples']
/home/local/lesteve/dev/sphinx-gallery/examples/no_output/plot_syntaxerror.pyin your conf.py file
/home/local/lesteve/dev/sphinx-gallery/examples/no_output/plot_raise.py
```

**Comment by jnothman** [comment]
xpass should probably not be a fatal error in any case. Here we are using xfail because passing is unreliable.

**Comment by lesteve** [comment]
I agree that a xpass could only be a warning. It definitely has some value, for example when mldata.org misbehaves and some examples may or may not fail almost randomly.

Having said that, it is slightly orthogonal to this issue which is about interaction between filename_pattern and expected_failing_examples.

I think we did it like this because we were worried that people would eventually fix their example and forget to remove it from the 'expected_failing_examples' configuration value.

Side-comment: interestingly pytest has a [strict=True parameter](https://docs.pytest.org/en/latest/skipping.html#strict-parameter) for xfail, when you are sure that this test should fail.

**Comment by choldgraf** [comment]
ping on this one - it's a minor blocker on the next release :-)
