### ISSUE TITLE
Enhancement binder: more flexibility with filepath

### ISSUE THREAD

**Issue by nicain** [sphinx-gallery/sphinx-gallery#338]
Currently the filepath is hard coded to live in a directory `_downloads`:

https://github.com/sphinx-gallery/sphinx-gallery/blob/b12868d32bb295e5518265fb184e549c3f5c79c2/sphinx_gallery/binder.py#L47

Is it true that this directory will always be an element of `sphinx_gallery_conf['gallery_dirs']`? I was able to get my example working by replacing `_downloads` with my `gallery_dirs` setting , but I think that modifying the call to `gen_binder_rst` in `generate_file_rst` could make this general.  

I can come up with a PR if this proposal course of action will still be relevant (Are there major changes that would make me hold off on this?). @choldgraf

**Comment by lesteve** [comment]
AFAIR _downloads is a magical sphinx folder where downloadable files live. This is used on the website to be able to download .ipynb and .py files when looking at an example. I found this:
http://www.sphinx-doc.org/en/stable/markup/inline.html#role-download

**Comment by Titan-C** [comment]
_downloads folder is just a limitation of how Sphinx works, I don't
think we can do any better for the sake of organizing the .ipynb files
in a nicer location or to keep the structure of the gallery. All
downloadable files will be relocated over there the same way images are
all moved to the _images folder.

**Comment by lesteve** [comment]
I'd be inclined to close this one. @nicain do you have a use case where controlling the output folder of the notebooks is really important?

**Comment by lesteve** [comment]
See https://github.com/sphinx-gallery/sphinx-gallery/issues/353#issuecomment-381655543 but this is my understanding as well that this would tackle @nicain's feature request.

**Comment by choldgraf** [comment]
closed by #368 !
