### ISSUE TITLE
The "floating buttons box" still needs some work

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#340]
Or some documentation on how to disable it / change its behavior.

E.g., the matplotlib theme doesn't quite get the floating correct:

![sphinx_gallery_float](https://user-images.githubusercontent.com/1839645/35309427-556cfcb4-0061-11e8-9ad9-16ffa616729e.gif)

**Comment by lesteve** [comment]
Not 100% great I agree. As someone with a very limited CSS-fu, I would be enclined to follow a low-tech approach, basically put something like this (in a visible yet not too intrusive manner that is left as an exercise to the reader) before the beginning of the example: "To launch binder or download the example code click here" with a link to the bottom of the page where you have all the download links.

**Comment by lesteve** [comment]
As always better suggestions more than welcome!

**Comment by choldgraf** [comment]
Alternatively we could add a section to the configuration page that explains how to modify the CSS for these elements. E.g., it could have a section on removing the "floating right" behavior and defaulting to putting the buttons at the end. Maybe that's a simpler short-term solution than changing the code?

**Comment by lesteve** [comment]
> E.g., it could have a section on removing the "floating right" behavior and defaulting to putting the buttons at the end.

I am OK with this as a stop-gap solution. The not so great part is that it goes against the original goal of the "float right" functionality which was to make the download buttons more prominent because they are easy to miss.

**Comment by GaelVaroquaux** [comment]
Is the matplotlib theme a simple modification of a classic sphinx theme?
If so, we should detect it with CSS rules and change the behavior
accordingly.

If not, we should just document how to override this behavior and let
matplotlib do it in their CSS.

**Comment by choldgraf** [comment]
I believe so, but not sure how to check for it since I do think they've customized it quite a bit

**Comment by Titan-C** [comment]
My CSS is very limited too. But my guess is that trying to get a generic CSS right to any theme our users may want to use might be beyond the time we have for this. I once prepared the build script to test with all available Sphinx themes, needless to say we don't always check that all themes are working in a compatible manner.
My suggestion would be to return to our default and not fancy download buttons at the end by default and document as a user enabled feature how to extend the CSS of the download buttons to get the "floating right" behaviour. We can of course continue to have our dog food and put such CSS override in our read the docs theme.

**Comment by choldgraf** [comment]
yeah I'm +1 on "solve this with documentation" one way or another...I'm .5/.5 on whether we the default floating or make the default at the bottom

**Comment by GaelVaroquaux** [comment]
One of the values of sphinx-gallery is that it is useable. Defaulting to
the buttons down decreases that usability, so it's a loss.

I'll try to see if I can find time to add a special rule for the culprit
here, but documentation will be needed, because we cannot catter for
every theming in the world.

**Comment by larsoner** [comment]
Just noticed over at PySurfer these buttons overlap with the `sphinxdoc` theme when the right sidebar is enabled (PySurfer does not do any fancy formatting so this could be a common problem among SG users):

![screenshot from 2018-02-05 11-33-43](https://user-images.githubusercontent.com/2365790/35816592-14ae5166-0a69-11e8-8609-b9147a2cd17c.png)

For me to disable this floating I 1) added an `extrahead` entry to `_templates/layout.html` to ensure that my `css` file was higher priority (later in the HTML) than the SG one, then 2) added this to my CSS:
```
@media only screen and (min-width: 140ex) {
    div.sphx-glr-footer-example  {
	position: unset;
	right: unset;
	top: unset;
	background: unset;
	padding: unset;
	border: unset;
	max-width: unset;
	width: unset;
	}
    div.sphx-glr-footer-example code {
	max-width: unset;
	overflow: unset;
    }
    div.sphx-glr-footer-example a {
	max-width: unset;
	overflow: unset;
	padding: 1ex;
    }
    div.sphx-glr-footer-example a code span:last-child {
	font-size: unset;
    }
}
```

**Comment by choldgraf** [comment]
hey all - has there been any movement on this?

If so, can we close this issue?
If not, it sounds like the latest agreement was to make the "floating right" behavior optional and disabled by default, so the path forward would be to expose this as a kwarg in the configuration, then change the CSS based on that kwarg. Does that sound correct?

Either way, I'll update the top-comment of this issue so it's more actionable (once I know what's the right path forward)

cc @lesteve @larsoner @GaelVaroquaux

**Comment by lesteve** [comment]
My attempt at this is #362. To sum up:
* remove the floating button CSS because I am slightly skeptical about floating buttons being a good enough default for a wide set of sphinx themes.
* add a note at the top of the example that has a link to go to the bottom of the example to find the download links.

Do comment on #362 if you have an opinion on it!

**Comment by choldgraf** [comment]
closing this, since @lesteve has the buttons back on the bottom now. I think it's worth thinking more in the future about what's the best way to structure the buttons / layout / etc, but I think that should happen in a different, more specific issue!
