### ISSUE TITLE
Rendering issues with scripts using `docopt`

### ISSUE THREAD

**Issue by tamasgal** [sphinx-gallery/sphinx-gallery#341]
I have a problem with rendering scripts in the gallery which uses docopt.
The problem is that docopt requires a specific docstring format, which of course is also used by sphinx-gallery to generate the first paragraph.

You can see the issue here: http://km3pipe.readthedocs.io/en/latest/auto_examples/offline_analysis/qk40calib.html

One workaround is putting in "two docstrings", since the first will be taken by sphinx-gallery and then the script is rendered correctly and the user can copy-paste it. However, if a user hits the download button, he of course will obtain the file with two docstrings, which will obviously not execute.

Any ideas how to solve this?

Update: I added two screenshots...
![screen shot 2018-01-24 at 11 53 33](https://user-images.githubusercontent.com/1730350/35328676-7047f6b4-00fd-11e8-867e-2c90b4f02a54.png)

![screen shot 2018-01-24 at 11 55 57](https://user-images.githubusercontent.com/1730350/35328731-9c4255de-00fd-11e8-84fe-fd55a4216751.png)

**Comment by tamasgal** [comment]
This is another workaround, although not really nice...

```
#!/usr/bin/env python
# coding=utf-8
# vim: ts=4 sw=4 et
"""
================================
Title
================================

Description

"""

docopt_str = __doc__ + """
Usage:
    foo (-h | --help)

Options:
    -h --help    Show this screen.

"""
from docopt import docopt


def main():
    args = docopt(docopt_str)
    ...
```

**Comment by lesteve** [comment]
I think your second workaround is fine. Actually maybe you don't even need `__doc__` in `docop_str`, i.e. you can do something like this:

"""
=====
Title
=====

Description
"""

docopt_str = """
Usage:
"""

args = docopt(docopt_str)
```

**Comment by tamasgal** [comment]
Actually I also would like to have the description of (which is in `__doc__`) in the docopt output, that's why I included that.

A friend of mine suggested playing around with `####` lines to enforce the code block parsing but I did not manage to get it working.

**Comment by lesteve** [comment]
> Actually I also would like to have the description of (which is in __doc__) in the docopt output, that's why I included that.

Can you elaborate why?

**Comment by tamasgal** [comment]
Yeah sure: docopt is printing the whole string if you use run the script with `-h`. If I'd cut it in half, I'd only see the usage part.

**Comment by Titan-C** [comment]
I find your workaround nice enough. I can also propose you as an alternative workaround to declare the options inside a code block. That is:
```python
#!/usr/bin/env python
# coding=utf-8
# vim: ts=4 sw=4 et
"""
================================
K40 Calibration Batch Processing
================================

Standalone job submitter for K40 offline calibrations with KM3Pipe.

.. code-block:: bash

    Usage:
        qk40calib.py OUTPUT_PATH [options]
        qk40calib.py (-h | --help)

    Options:
        OUTPUT_PATH  Folder to store the calibration data.
        -d DET_ID    Detector ID [default: 29].
        -t TMAX      Coincidence time window [default: 10].
        -n N_RUNS    Number of runs to process per job [default: 10].
        -e ET        Estimated walltime per run in minutes [default: 8].
        -m VMEM      Estimated vmem for a job [default: 8G].
        -s RUNSETUP  Match [default: PHYS.1710v5-TUNED.HRV19.3D_T_S_MX.NBMODULE].
        -j JOBNAME   The name of the submitted jobs [default: k40calib].
        -l LOG_PATH  Path of the job log files [default: qlogs].
        -q           Dryrun: don't submit jobs, just print the first job script.
        -h --help    Show this screen.

Keep trying
"""
import os
import re
from glob import glob
import time
...
```
Sphinx-Gallery will then nicely render the documentation text in html. The options are a 'bash' script which respects indentation and remains nicely formatted. Everything remains in the first string of documentation and docopt continues to work you don't loose information. When you call the docs with '-h', you'll see the `code-block` directive in the printed output.

**Comment by tamasgal** [comment]
> Completely unrelated but I like the image you used for examples that don't produce any plots!

😆 thanks ;)

@Titan-C aah thanks, that's very nice, I'll try that immediately. I don't care about that `code-block` line showing up in the console...

**Comment by lesteve** [comment]
It feels like your question has been answered so I am going to close the issue. Shout if you strongly disagree.

**Comment by tamasgal** [comment]
Yep, just tried and wanted to answer/close.

There is one little down-side with the `code-block` approach: you still can't copy paste since the `"""` are lost during the rendering.

Anyways, thanks  :)
