### ISSUE TITLE
Notebook style issues with indentation

### ISSUE THREAD

**Issue by glemaitre** [sphinx-gallery/sphinx-gallery#342]
We are using the notebook style to write some examples in joblib. One pattern that we are using which make the example readable in both code and example is the following.

```python

##################################################
# A title
##################################################
#(no space)
# A paragraph

```

Due to the lack of a whitespace, the full paragraph is indented. There is currently 2 workarounds.

```python

##################################################
# A title
##################################################
# (trailing space)
# A paragraph

```

or

```python

##################################################
# A title
##################################################

##################################################
# A paragraph

```

However, the first one introduces some trailing whitespace and the second one is less readable.
Is there anyway to include the first pattern without having to use trailing whitespace or clutter the example code?

**Comment by lesteve** [comment]
This seems to work for me (no space in the empty line after the title).

```
##################################################
# A title
# -------
#
# A paragraph
```

I don't really know what is happening with the second line of hashes I have to admit. In my mind, a line of hashes start a text cell, and then you write rst like you would normally except you add `# ` on each line.

**Comment by glemaitre** [comment]
I forgot to mention this solution. I think that @GaelVaroquaux found it less readable.

**Comment by lesteve** [comment]
The fact that the double line of hashes almost work is just pure luck if you ask me.

I quickly grepped the doc and this is the only thing I found is from this [example](https://sphinx-gallery.github.io/tutorials/plot_notebook.html#sphx-glr-tutorials-plot-notebook-py):

> The sphinx-gallery parser will assume everything after this splitter and that continues to start with a comment hash and space (respecting code style) is text that has to be rendered in html format. Keep in mind to always keep your comments always together by comment hashes. That means to break a paragraph you still need to commend that line break.

**Comment by GaelVaroquaux** [comment]
> The fact that the double line of hashes almost work is just pure luck if you ask me.

Not completely, the line of hashes is a valid title line in rst.

I think that what breaks sphinx-gallery is that we are not starting by "# #####..."

**Comment by lesteve** [comment]
> I think that what breaks sphinx-gallery is that we are not starting by "# #####..."

This should work indeed.

**Comment by lucyleeow** [comment]
Closing this as I don't think it is worth amending the code to allow `#######` as well as `# #####`
