### ISSUE TITLE
Error with Sphinx 1.7 due to changes in DOCUMENTATION_OPTIONS

### ISSUE THREAD

**Issue by astrofrog** [sphinx-gallery/sphinx-gallery#351]
The following code:

https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/docs_resolv.py#L95

Now fails:

```
Exception occurred:
  File "/Users/tom/tmp/sphinx-gallery/sphinx_gallery/docs_resolv.py", line 99, in parse_sphinx_docopts
    raise ValueError('Documentation options could not be found in index.')
ValueError: Documentation options could not be found in index.
```

Due to the following change in Sphinx 1.7:

https://github.com/sphinx-doc/sphinx/blob/6cf0698b0c6bde9fdcf4a606838552e1e7e20663/CHANGES#L237

**Comment by lesteve** [comment]
@QuLogic it seems like you wrote this piece of code, any suggestion how to fix it for sphinx 1.7 (looking at https://github.com/sphinx-doc/sphinx/pull/4295/files, this could be by looking at _static/documentation_options.js on top of index.html). Any suggestions on how to make it less brittle would be more than welcome!

**Comment by lesteve** [comment]
@QuLogic thanks a lot for your input! Let's stick to the straightforward fix for now and revisit potentially next time it breaks ...

**Comment by flothesof** [comment]
Hi, 
I'm running into exactly this problem.
I'm using the latest Sphinx (1.7.2) and sphinx-gallery and it crashes after completing the HTML generation:
```python-traceback
build succeeded.

The HTML pages are in _build\html.
embedding documentation hyperlinks...

Exception occurred:
  File "c:\anaconda3\lib\site-packages\sphinx_gallery\docs_resolv.py", line 97, in parse_sphinx_docopts
    raise ValueError('Documentation options could not be found in index.')
ValueError: Documentation options could not be found in index.
```
Since it appears that this was fixed back in February, would it be possible to release a new version including this fix? Alternatively, could you mention when you expect this to be pushed?

Thank you for your help.
Best regards
Florian

**Comment by lesteve** [comment]
Would installing sphinx-gallery directly from master be an option for you? Detailed instructions in https://github.com/sphinx-gallery/sphinx-gallery/pull/352#issuecomment-367090938.
