### ISSUE TITLE
JupyterLab support on binder

### ISSUE THREAD

**Issue by lesteve** [sphinx-gallery/sphinx-gallery#353]
I just heard about urlpath=lab. Maybe it would be nice to support at one point. I could not find a way to point to a given file with JupyterLab, i.e. using both urlpath=lab&filepath=myipnb. Is this correct @choldgraf?

Thinking about it out loud, in a multi-notebook context (at the moment we are just opening a single notebook in binder but you could imagine pointing to a folder e.g. in the main gallery or it seems like urlpath=lab works like this by default) it feels like the notebooks should be in auto_examples as well as in _downloads. This way the notebook folder structure mirrors the example folder (maybe that does get rid of the duplicated filename problem).

I am not sure why .ipynb can not be seen in https://github.com/sphinx-gallery/sphinx-gallery.github.io/tree/master/auto_examples but this can probably be fixed (at the cost of duplicating .ipynb in the repo, once in _downloads, once in auto_examples which is probably fine ...).

**Comment by choldgraf** [comment]
That's a great point - it seems like there are a few things to unpack:

* Enable `urlpath=` in the binder links (this is easy)
* Pointing to a specific file (this is possible but not well documented (use the pattern `http://localhost:8888/lab/tree/my-notebook.ipynb`
* Duplicating notebooks so that they follow the same folder hierarchy as examples (I am +100 on the hierarchy mirroring. -1 on duplicating notebooks, but that leaves +99 remaining so I am for it :-)  )

**Comment by choldgraf** [comment]
@lesteve have your thoughts on this topic changed at all? I might have a few cycles in the coming weeks to polish this up, so making sure that we're still in agreement on it :-)

**Comment by lesteve** [comment]
Great to hear you may have some time to tackle this indeed !

I haven't investigated this in detail but my plan was:
* have a configurable output folder for notebooks. This probably needs to be a subfolder of the build output folder
* not use the `:download:` directive for notebooks, and just use a normal link with the `href` pointing to the URL of the notebook (which will be part of the repo if we add the notebooks to the build folder). In the quick tests I ran, it seems to "just work".
* probably we need a bit of styling to have something that looks like what you get with the `:download:` directive

As all simple plans there may be unforeseen problems ... let me know in case something is not clear enough!

Of course there

**Comment by choldgraf** [comment]
Why not keep the download directive as-is, and use the notebook hierarchy folder for Binder links? At least as a first step. There'd be unnecessary duplication, but this could be spot-checked in subsequent PRs.

**Comment by lesteve** [comment]
This is certainly fine with me as a first step.

**Comment by Titan-C** [comment]
I'll prefer data duplication. Storage is getting really cheap nowadays
and bandwidth too. Messing around with sphinx and getting links to
behave correctly is very time consuming.
