### ISSUE TITLE
A grant for sphinx-gallery?

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#355]
Has the sphinx-gallery team ever thought about getting some $$$ to work on the project? I don't think it has a size that'd attract a big grant, but perhaps it'd be useful to look for $$ to fund a specific part of the project like refactoring/modularizing/etc? Just throwing the idea out there.

cc @ericholscher who I think was interested in getting some funding for docs infrastructure in the sciences

**Comment by larsoner** [comment]
Maybe a `numfocus` grant for a sprint? It wouldn't be a ton of money but a 1-week sprint with sufficient dev attendance could move a lot of things forward.

**Comment by choldgraf** [comment]
I believe that @tacaswell was in touch with folks at the moore foundation about documentation grants as well

**Comment by ericholscher** [comment]
I'd love to hear more about anyone willing and able to give grants to OSS Python doc tools, and how we might be able to manage to get some of that funding applied in this direction.

**Comment by lesteve** [comment]
It would be more than welcome of course, I don't think too much thinking has been put into that on the sphinx-gallery front. @GaelVaroquaux may have more inputs on that side of things or maybe have more clever longer-term plans in his head ;-).

For completeness, the Paris-Saclay Center for Datascience has a little bit of funding to pay PhD students to spend 10% on their time on open-source software. @Titan-C was working on sphinx-gallery as part as this program. Now that @Titan-C has completed his PhD I don't think we have reapplied for one.

**Comment by choldgraf** [comment]
hey all - I'm gonna close this one - it was mostly aimed at sparking a little conversation (or getting some thoughts moving in people's heads ;-) ) so I don't want it to just stay open indefinitely...feel free to re-open if anyone would like to!
