### ISSUE TITLE
ignore code-blocks

### ISSUE THREAD

**Issue by ajtritt** [sphinx-gallery/sphinx-gallery#361]
Please add the ability to ignore code blocks.

I am trying out sphinx-gallery as a way of building a set of tutorials for [PyNWB](https://github.com/NeurodataWithoutBorders/pynwb) that can also serve as integration tests. Since the Python code I am writing is going to be an integration test, I would like to clean up any files that get written after running the test; however, I don't want this code to show up in the tutorial, so I would like sphinx-gallery to ignore these code-blocks. 

I've done some snooping through the sphinx-gallery documentation and code base, and I don't see anything that would suggest this functionality exists. 

I am happy to add this feature myself, but I'm not sure what your procedure around contributing is.

**Comment by lesteve** [comment]
I am afraid I don't understand what you mean. Can you give us a better idea of what you have in mind when you say a tutorial that serves as integration test? How would a `.py` look like?

**Comment by ajtritt** [comment]
The integration test part of this is orthogonal to the problem, you can ignore that. 

I want to be able to add a comment to a code-block that tells sphinx-gallery to ignore this code-block.

```python
"""
Header Docstring
================

This is a test
"""


import os

####################
# First RST block
# ---------------
# This is the first ReStructured Text block
#


with open("test.txt") as f:
    f.write("Hello World\n")

####################
# Final RST block
# ---------------
# This is the final ReStructured Text block
#


# IGNORE THIS FOLLOWING CODE BLOCK WHEN GENERATING RST
os.remove("test.txt")


####################
# the final ReStructured Text block picks up here.
```

**Comment by ajtritt** [comment]
If it helps, I added code to accomplish this. Here's a PR I made on my own fork https://github.com/ajtritt/sphinx-gallery/pull/1

**Comment by lesteve** [comment]
Thanks a lot for the details! The reason I asked about integration test is I wanted to understand better what your motivation for hiding blocks is. When we need to clean up files we tend to do it towards the end of the example with a comment. The alternative is to leave the generated file alone. Maybe you can explain why these two approaches are lacking in your particular use case?

One of the primary goal of sphinx-gallery is to make sure that the output HTML is synchronized with the python code that generated it. This is quite at odds with hiding blocks.

**Comment by ajtritt** [comment]
> When we need to clean up files we tend to do it towards the end of the example with a comment. 
If the clean up is in a comment, then it will not actually remove the file when the script gets executed.

> The alternative is to leave the generated file alone. 
Sometimes I want to clean up the generated file. 

> One of the primary goal of sphinx-gallery is to make sure that the output HTML is synchronized with the python code that generated it.
If this is the primary goal of sphinx-gallery, what features does sphinx-gallery offer that are not already available in Jupyter, apart from integrating with sphinx?
