### ISSUE TITLE
plot_gallery=False working as expected?

### ISSUE THREAD

**Issue by fredrik-1** [sphinx-gallery/sphinx-gallery#366]
It seems that the gallery is generated also when plot_gallery is set to 0, or False or 'False' and this is due to a missing if statement at line 194 in `gen_gallery.py`. The only difference I see are that the calculation times are not printed. 

Am I missing something?

**Comment by fredrik-1** [comment]
Thanks, I guess that it works as expected and I got confused. I have not seen a page that that though because it seems that the old plots are saved somewhere even after a `make clean`.

**Comment by lesteve** [comment]
Hmmm I think it should work as long as your Makefile `clean` target deletes $BUILDDIR. Maybe have a look at the `Makefile` in sphinx-gallery for inspiration or maybe it is related to https://github.com/sphinx-gallery/sphinx-gallery/pull/364#issuecomment-382322097 and we are not really doing it the modern "sphinx way" not completely sure.
