### ISSUE TITLE
Create `output` folder configurable option

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#368]
In both #353 and #338 there are requests to allow for an "output" folder in the sphinx gallery configuration. This would be a folder where all generated SG content would live *in addition to* the traditional sphinx "downloads" folder.

An important difference is that this output folder should mirror the structure that the examples folders take.

**Comment by lesteve** [comment]
In my mind this should be only for generated notebooks. Do you have other kind of content in mind?

**Comment by choldgraf** [comment]
closed by #371 !
