### ISSUE TITLE
Feature request: Different ordering options

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#369]
We should really support a switch to order examples by alphabetic order.

It's been requested before by others, and I've finally hit a situation where this was crucial :).

**Comment by lesteve** [comment]
You can sort examples within a gallery sub-section through [this](https://sphinx-gallery.github.io/advanced_configuration.html#within-gallery-order). Not tested but it seems like something like this sould do what you want:

```py
from sphinx_gallery.sorting import FileNameSortKey
sphinx_gallery_conf = {
    ...
    'within_subsection_order': FileNameSortKey ,
}
```

**Comment by Titan-C** [comment]
This was a solved problem. At least for the alphabetical and some
other options.

**Comment by GaelVaroquaux** [comment]
> You can sort examples within a gallery sub-section through this.

OK. My bad.

I can't even blame our documentation, it's clear that this option exists
from a quick glance at it.

Good job, team! And my apologies!
