### ISSUE TITLE
Feature request: Add an option for different cell separations

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#370]
We should add an option so that to give equivalent to what currently is "########################", used as a cell separated.

Candidates:

* "\n\n" to have lighter source files

* "# %%" to be compatible with other softwares such as atom hydrogen, as mentioned below by @lesteve 

Thanks to @ogrisel for having suggested this a while ago.

**Comment by lesteve** [comment]
I'll mention this here, but it seems like `# %%` seems to be a common way of creating cells (probably taken from [Matlab](https://www.mathworks.com/help/matlab/matlab_prog/run-sections-of-programs.html) actually), see:
* [Pycharm](https://www.jetbrains.com/help/pycharm/matplotlib-tutorial.html#d163906e80)
* [Jupyter VS code plugin](https://marketplace.visualstudio.com/items?itemName=donjayamanne.jupyter)
* [Hydrogen plugin](https://nteract.gitbooks.io/hydrogen/content/docs/Usage/GettingStarted.html#hydrogen-run-cell)
* [Spyder](https://pythonhosted.org/spyder/editor.html#how-to-define-a-code-cell)
