### ISSUE TITLE
Can this work for files other than .py ?

### ISSUE THREAD

**Issue by stuaxo** [sphinx-gallery/sphinx-gallery#378]
In shoebot (a python creative coding environment) we have python in a .bot file .... when run with ```sbot {filename}``` we can do thinks like output a png file for each frame.

How hard would it be to get sphinx gallery to render our examples by running shoebot?

**Comment by Titan-C** [comment]
There was an attempt to support other languages in PR #197 maybe you can
look at it.

Currently sphinx-gallery loads the script to be executed into its
running process. Thus it is not friendly to loading other interpreters
for the moment. It would be great if we could offload the execution of
the script to a different process. That would help us with
multiprocessor support, and clearing from memory what every example
loads, currently we unload modules in a very nasty way. Offloading to a
different execution engine will also help running other languages or
environments.

**Comment by stuaxo** [comment]
That's interesting, I'll check it out.

Shoebot is python... - we put various things into the namespace though, so it might be simpler than adding proper support for other interpreters.

**Comment by GaelVaroquaux** [comment]
I am closing this issue, as it was a question, and it's a question, and has been answered.
