### ISSUE TITLE
How to link the gallery

### ISSUE THREAD

**Issue by GkAntonius** [sphinx-gallery/sphinx-gallery#380]
Hello. I'm fairly new to sphinx-gallery and sphinx in general, and here is my problem.

I created a `plot_example.py` script and placed it in my `examples_dirs` folder. As a result, I do see it copied in the `gallery_dirs` folder, that is, I get the file `auto_examples/plot_example.py`. Then, to include a link to the gallery in my main documentation page (`index.rst`), I have the line
`` :doc:`Gallery <auto_examples/index>` ``
However, when building the doc, I get:
`WARNING: undefined label: sphx_glr_auto_examples_plot_example.py (if the link has no caption the label must precede a section header)
`
and indeed the link to this example is broken. What am I doing wrong?

**Comment by lesteve** [comment]
I don't know off the top of my head. Could you point us to a github repo for your project so that we can try to reproduce the problem ?

**Comment by Titan-C** [comment]
With a minimal example we can try to debug the problem. But the warning
is strange like you wouldn't have a title for your example. But if I
remember correctly we still raise an exception if examples don't have
heading titles.

**Comment by GkAntonius** [comment]
[Here is a minimal working example that reproduces the problem.](https://github.com/GkAntonius/sphinx-gallery-mwe) Thank you for your quick reply!

**Comment by GkAntonius** [comment]
That's it! Thank you Titan-C. Looking back at the sphinx-gallery documentation, the instructions were unequivocal:
> The structure follows a leading docstring that must follow reStructuredText syntax and a header. Then the executable code of your script.

Yet, an example would have been helpful for sphinx newbies. Cheers!
