### ISSUE TITLE
Capture HTML output as in Jupyter

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#396]
More and more objects can do nice html rendering in the jupyter notebook. For instance pandas dataframe, but also plotting libraries use this.

The way it works is that the jupyter kernel calls the "_repr_html_" on an object, if present, to get the HTML to display:
https://ipython.readthedocs.io/en/stable/config/integrating.html#rich-display

I think that sphinx-gallery could and should do that. It would make examples better looking. Also, it would enable other plotting libraries to work well with sphinx-gallery.

This should be fairly easy. The only technical difficulty that I am seeing is to capture the last object. I confess that I don't know how to do this. But given that ipython and jupyter have been doing it since a long time, it should be feasible.

**Comment by choldgraf** [comment]
I know @SylvainCorlay and @maartenbreddels would probably be happy to see this

**Comment by GaelVaroquaux** [comment]
Great!

Our execution line is at:
https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/gen_rst.py#L544

What would be the easiest way to change it so that it captures the
_repr_html of the returned object?

**Comment by GaelVaroquaux** [comment]
The difficult step is to exec and capture the last returned value. This is difficult, because fundamentally it is mixing the "exec" and "eval" semantics of Python. I had a look at the IPython codebase, and it does this in a fairly involved way.

However, I think that the necessary logic is summarized in the following stackoverflow answer:
https://stackoverflow.com/a/38615712/413856

**Comment by maartenbreddels** [comment]
That would be really great!

I think the exec/eval is being done here quite elegantly: https://github.com/jupyter-widgets/jupyter-sphinx/blob/b1d5a4568fc697e8ffb07d669432592e5f0f3aa0/jupyter_sphinx/embed_widgets.py#L65

**Comment by GaelVaroquaux** [comment]
That's very neat. Thank you !

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by SylvainCorlay** [comment]
Some context about the `jupyter-sphinx` extension and the added `rst` directives:

It solves a slightly more complicated problem than what Gael was asking (which is to enable the use of _repr_html_), since we also gather the state of all the widgets instantiated in the special code blocks.

Although, I would love sphinx gallery to also be able to do that. I have been looking at it for making a gallery for widgets-based visualization libraries but never took a stab at it.

**Comment by SylvainCorlay** [comment]
We are working on separating how we monkey patch `IPython.display` in https://github.com/martinRenou/jupyter-sphinx/, maybe separating it into a new package, so that `jupyter-sphinx` and `sphinx-gallery` don't step on each other's toes in that regard.

**Comment by SylvainCorlay** [comment]
For reference: https://github.com/jupyter-widgets/jupyter-sphinx/pull/19

**Comment by choldgraf** [comment]
A quick thought - could we use a try/except block somewhere around here: https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/gen_rst.py#L569 that'd try to call the `_repr_html_` method of the last line in the code block, and if it returns something real then attach it to the rST output with whatever necessary wrappings we'd need in a `.. raw-html` block?

**Comment by GaelVaroquaux** [comment]
I have in mind some similar, but I think that the exec/eval dance isn't
that bad, based on the code shared above.

**Comment by SylvainCorlay** [comment]
hey all, we actually might have a more elegant discussion which should enable capturing rich outputs of non-python kernels, using a similar method as the execute preprocessor of nbconvert.

**Comment by choldgraf** [comment]
@SylvainCorlay nice - do you have a writeup of it somewhere? I tried hacking on this a bit after scipy and made some progress but not enough to add a PR :-)

**Comment by SylvainCorlay** [comment]
sorta. I am working on a common-line utility to visualize notebook files including live widgets and kernel, but non-editable, and disallowing arbitrary code execution.

Basically, it uses a modified version of the nbconvert execute preprocessor.

Most of what we need here is already in nbconvert. There is a discussion with minrk on the jupyter/jupyter gitter channel right now about this.

**Comment by lucyleeow** [comment]
@GaelVaroquaux are you happy to close this issue for now?

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux are you happy to close this issue for now?

Yes, thank you very much. You did amazing work!!
