### ISSUE TITLE
How to get the `.css` files to copy over on building the docs?

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#399]
This is only tangentially related to sphinx-gallery, but I have a quick question for @Titan-C (or whoever might know)

I'm having a heck of a time figuring out how sphinx-gallery is able to get its `.css` file copied over to the built `_static` directory (so that it can be linked in pages). I see that https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/gen_gallery.py#L116 seems to be adding the path to the static folder in this repo, but I demoed this on a different repo and none of the files were copied over.

Anyone know how we accomplish this in sphinx-gallery?

**Comment by Titan-C** [comment]
This is one of Sphinx's dark magic(you need to do 2 things). Sphinx
should copy anything that is on its _static directory, or any directory
in the list html_static_path.

Nevertheless to actually use it you need to use a link to it. We do it
with

app.add_stylesheet('gallery.css')

https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/gen_gallery.py#L360

**Comment by choldgraf** [comment]
so in my case, I have both `add_stylesheet` there (which adds the relevant line to the `<head>` section, and I've added to the static path with `app.html_static_path.append(path_to_my_files)`, but those files aren't actually copied over on build. It's super confusing to me :-P

In the end I just pushed those files to github and am using github as a CDN to load them, but this is quite hacky :-/

**Comment by maartenbreddels** [comment]
I didn't understand this as well, and found a solution: https://github.com/sphinx-doc/sphinx/issues/2090
(also knowing sphinx-gallery could do it)

**Comment by yjmantilla** [comment]
@maartenbreddels Thank you! I think your solution should be in the sphinx gallery documentation. It doesn't make sense for such a basic functionality to be so hidden away in an issue. 

Btw, there was an API change to your solution, instead of app.add_stylesheet() it should be app.add_css_file() 

https://github.com/sphinx-doc/sphinx/issues/7747

**Comment by lucyleeow** [comment]
I recently added some documentation here: https://sphinx-gallery.github.io/stable/advanced.html#altering-sphinx-gallery-css but did not detail the `app.add_css_file()` part

Please feel free to put in a PR to make it more clear/accessible. This can be a bit tricky as I wasn't sure how much to document as it is sphinx functionality.

**Comment by yjmantilla** [comment]
@lucyleeow  Thanks, I did see that documentation but was a bit frustrated as a newcomer since I didn't know what was wrong despite doing what it said. Will try to do the PR tomorrow.

**Comment by lucyleeow** [comment]
Pointing to the Sphinx docs, in our docs, may also be helpful: https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_css_file

**Comment by lucyleeow** [comment]
For anyone that encounters this problem, the cause is documented here: https://github.com/sphinx-gallery/sphinx-gallery/pull/845#issuecomment-913130302
