### ISSUE TITLE
Support for absolute paths in 'examples_dir' and 'gallery_dir'

### ISSUE THREAD

**Issue by florian-wagner** [sphinx-gallery/sphinx-gallery#40]
Is it possible to allow absolute paths to be set for `examples_dir` and `gallery_dir`? Or in other words: Is it necessary to transform the input variables to paths relative to app.build.srcdir? If not, this would enable a bit more flexibility when using cmake.

**Comment by Titan-C** [comment]
Yes they have to be relative to app.build.src because this then becomes
the absolute root for the website and sphinx relies on this local root to
resolve all link addresses

**Comment by florian-wagner** [comment]
Okay, thanks a lot. Then I have to rearrange a bit on my side.
