### ISSUE TITLE
Inspiration from new gallery package for sphinx: sphinx-exhibit

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#402]
hey folks - I just found out about an interesting project that @anntzer from the Matplotlib community is working on. It's called "sphinx-exhibit" and replicates many of the things that sphinx-gallery does with a few improvements:

https://github.com/anntzer/sphinx-exhibit

The main differences to me seem to be:

1. sphinx-exhibit does more introspection of the code to generate intersphinx links for methods etc, similar to what @larsoner was working on in a recent PR (don't remember which one).
2. sphinx-exhibit exposes some sphinx directives so you can embed a gallery of specific examples files.

Anyway, worth keeping an eye on the project! Maybe the build process of sphinx-exhibit is different enough that it isn't possible to mimic in sphinx-gallery, but worth checking nonetheless!

**Comment by anntzer** [comment]
See https://github.com/matplotlib/matplotlib/pull/11936 for some examples of the difference in generated docs and https://github.com/matplotlib/matplotlib/pull/11936#issuecomment-416043980 for the "why" of sphinx-exhibit.

**Comment by GaelVaroquaux** [comment]
Post processing sphinx output for the notebooks is something that I had been thinking about for a while. It seems very useful.

Of course the deeper inspection for better linking is useful and great!

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by GaelVaroquaux** [comment]
@larsoner : what is the reference to your PR that does deeper inspection?

**Comment by larsoner** [comment]
Mine merely parsed the docs for refs and added them. But in theory something similar could be used on objects themselves: #347

**Comment by choldgraf** [comment]
It sounds like @anntzer has already figured out much of the machinery for this, it's mostly a matter of adapting it to how sphinx-gallery builds things. However I'm not sure how incompatible the approaches of the two projects are.
