### ISSUE TITLE
Multiple galleries or subsubfolders

### ISSUE THREAD

**Issue by florian-wagner** [sphinx-gallery/sphinx-gallery#41]
Is it possible to have **subsub**folders or specify more than one `examples` directory? (our project differentiates between examples and tutorials, which themselves are structured into topics)

**Comment by florian-wagner** [comment]
Is that already possible or can anyone point me to a starting point to implement it? Thanks a lot.

**Comment by agramfort** [comment]
you can have multiple subfolders in examples. They just need to contain a
README.txt file

**Comment by Titan-C** [comment]
This is more a design choice that @GaelVaroquaux made to only have   a depth up to 2(that is subfolders)
For subsubfolder you need to nest one more loop here
https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinxgallery/gen_gallery.py#L72-L82

although I'm unsure if one should better provide a list for `example_dir` and allow multiple galleries

**Comment by Titan-C** [comment]
@florian-wagner So we run in the same need of having Multiple galleries, and implemented them. It still belong to PR #36 which soon will be merged

**Comment by florian-wagner** [comment]
Looks great, thanks a lot!

**Comment by lesteve** [comment]
Closing since #36 has been merged.
