### ISSUE TITLE
Broken binder links

### ISSUE THREAD

**Issue by betatim** [sphinx-gallery/sphinx-gallery#418]
If you visit https://sphinx-gallery.readthedocs.io/en/latest/auto_examples/plot_sys_argv.html#sphx-glr-auto-examples-plot-sys-argv-py and click on the Binder badge you get sent to:

https://mybinder.org/v2/gh/sphinx-gallery/sphinx-gallery.github.io/master?urlpath=lab/tree/notebooks/auto_examples/plot_sys_argv.ipynb

The idea (inferred from the link) is to open a particular notebook in Jupyter lab, I think. However right now you just get a plain jupyter lab view. As a newcomer to the repo it isn't clear that auto_examples is the place to go.

If you modify the URL to be:

https://mybinder.org/v2/gh/sphinx-gallery/sphinx-gallery.github.io/master?urlpath=tree/notebooks/auto_examples/plot_sys_argv.ipynb

the notebook opens as expected.

I think this problem happens because the newest Jupyter lab doesn't support the URL scheme anymore? I propose to switch the links to use the classic notebook. It doesn't seem like jupyter lab has much to offer for simple examples like a gallery and because it is still in beta they can/promise/reserve the right to keep breaking things. There is also some homework here for the mybinder.org team in terms of deciding when/if/how we keep updating lab and classic notebook as time passes.

What do you think?

**Comment by minrk** [comment]
This is a bug [in jupyterlab](https://github.com/jupyterlab/jupyterlab/pull/5340) where tree links are encoded as url *components* instead of urls, so the link would have to be `urlpath=lab/tree/notebooks%2Fauto_examples%2Fplot_sys_argv.ipynb`. This should be fixed in jupyterlab 0.35.

**Comment by choldgraf** [comment]
lab 0.35 is out now, right? If so we should push to master and see if that fixes the path updating problem

**Comment by lesteve** [comment]
Closing this one, I don't think this is relevant anymore.
