### ISSUE TITLE
'make html' does not attempt to run examples

### ISSUE THREAD

**Issue by mueslo** [sphinx-gallery/sphinx-gallery#425]
I'm trying to get started with sphinx-gallery. As far as I can tell I followed the instructions exactly. The issue is that sphinx does not even try to execute the example scripts, so no previews or images are being generated.

```
$ LC_ALL=C make html
Running Sphinx v1.8.1
loading pickled environment... done
generating gallery...
generating gallery for gallery... [100%] project.py                                                                                  
computation time summary:
        - test.py: 0 sec
        - project.py: 0 sec
        - dos.py: 0 sec
        - bz_plot.py: 0 sec
        - band_plot.py: 0 sec
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 6 source files that are out of date
updating environment: [] 0 added, 6 changed, 0 removed
reading sources... [100%] gallery/test                                                                                               
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                       
generating indices... genindex
writing additional pages... search
copying images... [100%] gallery/images/thumb/sphx_glr_project_thumb.png                                                             
copying downloadable files... [100%] gallery/test.ipynb                                                                              
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.
embedding documentation hyperlinks...
embedding documentation hyperlinks for gallery... [100%] bz_plot.html
```

This generates all the galleries, code snippets, etc. just fine, but as you can see from the zero-second computation time, the example scripts aren't touched. I can literally add a `raise Exception` at the start of an example file and nothing will change.

The relevant parts of my `conf.py`:

```
extensions = [
    'sphinx_gallery.gen_gallery',
]

sphinx_gallery_conf = {
        'examples_dirs': '../examples',
        'gallery_dirs': 'gallery',
}
```

The versions I'm running are
```
Sphinx==1.8.1
sphinx-gallery==0.2.0
```

**Comment by choldgraf** [comment]
by default, SG will only run examples that begin with `plot_`...is that true in your case? I've been burned by this before...

**Comment by mueslo** [comment]
Yeah, that fixed it, thank you!

I'm leaving this issue open because this seems to be a rather glaring oversight in the documentation. Nowhere I can find does it state that this is the default behaviour.

**Comment by larsoner** [comment]
@mueslo can you open a PR to add a note about the default here:

https://sphinx-gallery.readthedocs.io/en/latest/getting_started.html#structure-the-examples-folder

And here:

https://sphinx-gallery.readthedocs.io/en/latest/configuration.html#parsing-and-executing-examples-based-on-matching-patterns

These HTML files are built based on files in `doc/*.rst`.

**Comment by choldgraf** [comment]
@mueslo agreed - we should definitely do this.

Actually, maybe a controversial statement, but I'd think that it's more important to use a regex to define examples to *skip* rather than examples to plot. Wouldn't most people assume what @mueslo did, which is that SG will by default run all of the examples in a folder that you specify?

**Comment by Titan-C** [comment]
There was a hint to it in the previous documentation. 
https://github.com/sphinx-gallery/sphinx-gallery/pull/403/files#diff-88b99bb28683bd5b7e3a204826ead112L145

@choldgraf the "plot_" pattern is there for legacy reasons, but I do see a great value on having that as the default. I do understand that a new project adopting Sphinx-Gallery will have a bunch of files that don't begin with `plot_` and would consider it a bad choice. But doing batch renaming of files is very simple in linux you have the `rename` command, putting a prefix is simple. Renaming a file to test out is a simple thing, I wouldn't like trowing all my scripts to sphinx-gallery and realizing either the build takes forever or half of the examples where broken, I rather have the incremental approach. Also think about debugging a script, you can always set the pattern to the specific filename you want to work on. making a skip list would mean thinking a regular expression to skip all but the file I want.

It can all go into a vote, I prefer the current way. But we should absolutely bring the documentation telling about the defaults.
