### ISSUE TITLE
realtive paths in github.io

### ISSUE THREAD

**Issue by rschmaelzle** [sphinx-gallery/sphinx-gallery#434]
Hi, 
i am not sure this belongs here. I am stuck with setting up sphinx-gallery in my github.io. I managed to create the gallery locally, but when I serve it to github.io, the paths are getting messed up: e.g. one cannot navigate to (../_images/sphx_glr_plot_notebook_thumb.png) because it is misinterpreted.  If i navigate manually to https://github.com/username/projectname/blob/master/_images/sphx_glr_plot_notebook_thumb.png , it works, so somehow I must have missed where to plumb this up the right way. sorry if it is obvious, but I couldn't find where...
best r

**Comment by rschmaelzle** [comment]
I am closing this myself. It has to do with a .nojekyll file being needed for static gitub pages. Couldn't find it in the documentation though. r

**Comment by choldgraf** [comment]
woot! good to hear you figured it out...I've been burned by `.nojekyll` many times :-)

**Comment by rschmaelzle** [comment]
@choldgraf still: thank you very much!

**Comment by larsoner** [comment]
@rschmaelzle if you can think of a suitably place in the `configuration.rst` or other file to have a RST `.. note::` about `gh-pages` nojekyll, a PR would be appreciated
