### ISSUE TITLE
Won't display stdout

### ISSUE THREAD

**Issue by Artemis-R** [sphinx-gallery/sphinx-gallery#435]
I want to implement a new gallery for a python package I am working on. To start of I wrote a very simple python script to generate an example where I wanted the standard output to be displayed.

my example script:

```
# -*- coding: utf-8 -*-
"""
simple example
==============

mydocstring

"""
print('hi')
```

When I build my documentation though it ends up looking just like this:
![image](https://user-images.githubusercontent.com/15019107/49086417-bef98b80-f254-11e8-8e1a-aa16787e6099.png)

Maybe I am simply not finding the relevant section in the documentation, but I assumed that all standard output was automatically captured and displayed. What do I need to change to get it working to display the text like in your example [here](https://sphinx-gallery.readthedocs.io/en/latest/auto_examples/no_output/plot_strings.html#sphx-glr-auto-examples-no-output-plot-strings-py).

I've tried looking at your source code but I can't find any differences between your example and mine.

**Comment by choldgraf** [comment]
@Titan-C what if we just added something like:

```
.. note::

   Sphinx-Gallery will only run files that begin with `plot_` by default. If you'd like to 
   change this behavior, see [link to section on changing the regexp]
```

**Comment by larsoner** [comment]
And also if no examples match, a stdout print at the end saying "\nSphinx gallery did not find any examples to run matching the pattern {0}.\n" or so, so people see it in their sphinx output.

**Comment by Artemis-R** [comment]
Yes this was indeed the issue. Thanks! I think both of those suggestions would be helpful and would have aided me in solving this issue by myself.
