### ISSUE TITLE
Better way of separating the stdout in the notebook style examples

### ISSUE THREAD

**Issue by lesteve** [sphinx-gallery/sphinx-gallery#44]
When #36 is merged, it would be good to find a better way to separate stdout from the input.

![sphinx_gallery_output](https://cloud.githubusercontent.com/assets/1680079/8701338/74c043f0-2b11-11e5-97c4-05a65415945a.png)

Not sure about the best way how to do that at the moment, but just putting "Script output:" doesn't seem to cut it for me ...

**Comment by florian-wagner** [comment]
I changed the background in my CSS, but I agree that a more sensible default would probably avoid confusion.

**Comment by lesteve** [comment]
Do you have a snapshot to give us a feeling how it looks ?
