### ISSUE TITLE
Remove the readthedocs version of sphinx gallery docs

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#444]
Right now there are two sets of documentation for sphinx-gallery:

One on gh-pages (the "official" one): https://sphinx-gallery.github.io/
One on readthedocs (an outdated one): https://sphinx-gallery.readthedocs.io/en/latest/

as far as I can see, the RTD one isn't being built anymore, which means that it'll get quite confusing to people if we have two versions of the docs floating around on the internet. Can we delete the RTD one? (or delete the GH-pages one, I don't mind which is used, but there should only be one)

**Comment by larsoner** [comment]
Agreed there should only be one, +1 for deleting RTD since the other one is automatically updated already

**Comment by Titan-C** [comment]
Yes, I also agree. I first took the project down. But then, brought it back up to try to make a redirect page to the github docs. Still working on it. Does some of you have readthedocs account so that I can make you a maintainer too?

**Comment by GaelVaroquaux** [comment]
> Does some of you have readthedocs account so that I can make you a maintainer too?

I am gael.varoquaux@normalesup.org

**Comment by Titan-C** [comment]
Hi @GaelVaroquaux, read the docs does not take your email as user.

**Comment by Titan-C** [comment]
Doesn't seem like readthedocs allows for complete redirects. https://github.com/rtfd/readthedocs.org/issues/3577

**Comment by GaelVaroquaux** [comment]
> Hi @GaelVaroquaux, read the docs does not take your email as user.

OK. Apparently, my user name is GaelVaroquaux

**Comment by Titan-C** [comment]
I created a new orphan branch `readthedocs`, that one build a documentation that redirects to github from read the docs.

**Comment by GaelVaroquaux** [comment]
@Titan-C : great job. It works well!!

**Comment by GaelVaroquaux** [comment]
It's still alive!

https://sphinx-gallery.readthedocs.io/en/latest/

**Comment by choldgraf** [comment]
it's alive but at least redirects to `github.io` for me (and also has text on it saying "go to github.io"), which I think is an OK solution

**Comment by GaelVaroquaux** [comment]
Indeed. Maybe it was a cashing problem on my side: I had to hard refresh to see the redirect.

Closing again.
