### ISSUE TITLE
The build process should abort if one of examples fails to execute

### ISSUE THREAD

**Issue by chrisfilo** [sphinx-gallery/sphinx-gallery#45]
We are trying to build docs (and run examples) in CI setting, but it's hard to figure out if the docs run or failed since sphinx-gallery is ignoring errors. See https://circleci.com/gh/chrisfilo/nilearn/17

**Comment by GaelVaroquaux** [comment]
The challenge is to find a way to control the exit value of sphinx from
our code base. Should be doable.

**Comment by lesteve** [comment]
FWIW allowing this behaviour through a sphinx configuration variable was actually done in the mayavi PR, see this [commit](https://github.com/agramfort/sphinx-gallery/commit/c68036d47a0900c910d88a8a579037d2b9b74c72).

**Comment by GaelVaroquaux** [comment]
That said, I am not sure that abortion is the right behavior. You might
want all the examples to run, the doc to build, and an error message at
the end. The reason is that to inspect a run on CircleCI you'd like to
try to run all the examples.

**Comment by lesteve** [comment]
I agree. I guess it's good to have the choice to fail early, like nosetests -x but at the same time if you don't fail early it would be good to have a summary at the end mentioning the examples that have failed plus an non zero exit code.

**Comment by jnothman** [comment]
The exit value from sphinx doesn't contain this information because https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinxgallery/gen_rst.py#L434

@chrisfilo If you want it to abort, perhaps you could add something like `! grep -qR "is not compiling" doc/_build/html/stable/auto_examples` to your makefile.

**Comment by Titan-C** [comment]
This is now a configurable option since #77
