### ISSUE TITLE
SG not respecting highlight_lang in conf.py

### ISSUE THREAD

**Issue by drammock** [sphinx-gallery/sphinx-gallery#452]
If I specify `highlight_language = 'python3'` in my `conf.py`, sphinx-gallery nonetheless outputs code blocks starting with:
```
.. code-block:: python
```
...presumably because of [default `lang=python` arg in `codestr2rst`](https://github.com/sphinx-gallery/sphinx-gallery/blob/40aec52de43e4c27b000e054ae50eae6fb0f30e2/sphinx_gallery/gen_rst.py#L178).  This leads to errors where plain RST files get lexed as python3, but the gallery files get lexed as python2 (which chokes on the `@` operator), as evidenced by these two errors:
```
/opt/mne-python/doc/auto_tutorials/preprocessing/working_with_projectors.rst:48: WARNING: Could not lex literal_block as "python". Highlighting skipped.
/opt/mne-python/doc/manual/gui/browse.rst:2533: WARNING: Could not lex literal_block as "python3". Highlighting skipped.
```
(note: the second is an intentional error that I left in manual/gui/browse.rst to demonstrate that it is being lexed as py3, unlike the SG-generated rst files)

**Comment by larsoner** [comment]
if we just use `.. code-block::` instead of `.. code-block:: python` it should automatically use the current default. I assume this isn't done because someone might have changed the highlight language for a specific file (?), such as if there are going to be more `bash` commands or something. So maybe the thing to do is look at the current default `highlight_language` (which should almost always be python or python3), if it's a Python variant use it, if it's not then use `sys.version` to choose.

**Comment by drammock** [comment]
Just confirming I understand you correctly: the downside to in this case use `.. code-block::` without specifying a language (or `::` on a line by itself) is that, if someone had a block like
```
###############
# .. highlight:: console
#
# blah blah blah::
#
#     $ cowsay "sphinx gallery"
#
# etc...
```
then the `.. highlight:: console` directive would apply to the python code following that RST block, yes?  So the SG-generated code blocks must be marked for language to guard against this.  I guess the alternative would be to output blocks that are unmarked for language, and just state that bad things will happen if you use `..highlight::` directives in the RST chunks of python files, so that people won't use them.  but I think your solution is better.  Testing now.

**Comment by larsoner** [comment]
Indeed that's my thinking @drammock
