### ISSUE TITLE
On some computers, plot_gallery=False is ignored

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#46]
mfpgt@lab-01:~/Documents/PHD_research/open_source_contributions/nilearn/doc$
make
sphinx-build -D plot_gallery=False -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.1
WARNING: invalid number u'False' for config value 'plot_gallery', ignoring
loading translations [en]... done
loading pickled environment... not yet created
plotting plot_nifti_simple.py
Downloading data from http://www.nitrc.org/frs/download.php/1071/
NYU_TRT_session1a.tar.gz ...

**Comment by lesteve** [comment]
I seem to remember I have seen that before and it is due to the fact that with sphinx 1.3 you need plot_gallery=0. To be double-checked.

**Comment by GaelVaroquaux** [comment]
> I seem to remember I have seen that before and it is due to the fact
> that with sphinx 1.3 you need plot_gallery=0. To be double-checked.

We can fix that in our Makefile. Let me try.

**Comment by GaelVaroquaux** [comment]
It works:
https://github.com/nilearn/nilearn/commit/001ffeda0f75cb9ae7302e78cb6ef763d2a496a4

I'll close this issue.
