### ISSUE TITLE
Change output format of images

### ISSUE THREAD

**Issue by steffengraber** [sphinx-gallery/sphinx-gallery#463]
I haven't found a way to change the output format for images yet. My goal would be SVG. How to do this?

**Comment by choldgraf** [comment]
I don't believe it's possible currently - see the scraper documentation for how this is implemented, and could potentially be extended:

https://sphinx-gallery.github.io/advanced.html#writing-a-custom-image-scraper

and here's the matplotlib scraper that gets called:

https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/scrapers.py#L59

**Comment by larsoner** [comment]
There is no config param for this, but it should be fairly straightforward to copy the `matplotlib` scraper and make the appropriate changes. Feel free to give it a shot and let us know how it goes.
