### ISSUE TITLE
pythonhosted.org seems to be still up and running

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#465]
https://pythonhosted.org/sphinxgallery/ : it is a vastly outdated version of the documentation. We should take it down.

Related to #86

ping @Titan-C

**Comment by Titan-C** [comment]
https://pythonhosted.org/sphinxgallery/

Unfortunately I don't have access to this. That project was deleted and
I can't take the docs down. Not sure what to do in this case.

**Comment by larsoner** [comment]
A quick search yielded:

https://stackoverflow.com/questions/6521931/how-to-delete-documentation-from-pypi/6531582

If nobody beats me to it, I can try tomorrow.

**Comment by larsoner** [comment]
... oh I get it, you deleted the package completely.

I would try re-creating the package, then doing a doc upload, then a doc delete. If this does not work, we can try emailing the Pypi people. I'll try these steps tomorrow.

**Comment by larsoner** [comment]
Hmm, https://pypi.org/project/sphinxgallery/ does exist but it looks like it is not real...

**Comment by larsoner** [comment]
See https://github.com/pypa/warehouse/issues/5641

**Comment by larsoner** [comment]
Emailed the (likely) white-hat namesquatter for permissions

**Comment by larsoner** [comment]
Docs have been removed

**Comment by GaelVaroquaux** [comment]
Great job!!

⁣Sent from my phone. Please forgive typos and briefness.​
