### ISSUE TITLE
Rename package to sphinx_gallery rather than sphinxgallery?

### ISSUE THREAD

**Issue by lesteve** [sphinx-gallery/sphinx-gallery#47]
A very minor annoyance, but I thought I would vent it out and ask for opinions, it seems to me that sphinx_gallery for the package name is more in line with sphinx-gallery as the project name.

Basically if people agree it would be wise to fix that sooner rather than later, to reduce the impact on potential users.

**Comment by agramfort** [comment]
I am fine with sphinxgallery so +0 on this.

**Comment by Titan-C** [comment]
I don't remember when we discussed this, but the package was already named sphinx_gallery and we changed for the one without the underscore. I don't have the reason in mind anymore.

**Comment by lesteve** [comment]
> I don't remember when we discussed this, but the package was already named sphinx_gallery and we changed for the one without the underscore. I don't have the reason in mind anymore.

You are right actually, interesting that was not what I remembered at all ... That was done in the first PR: https://github.com/sphinx-gallery/sphinx-gallery/pull/1 but there is no reason given in the PR or the commit message.

**Comment by lesteve** [comment]
Anyway let's ask @GaelVaroquaux if he has any opinion about this.

If I am the only one to be slightly annoyed by this, I am more than happy to close the issue.

**Comment by GaelVaroquaux** [comment]
> Anyway let's ask @GaelVaroquaux if he has any opinion about this.

No strong opinion.

> If I am the only one to be slightly annoyed by this, I am more than happy to close the issue.

I am actually slighlty annoyed too.

**Comment by lesteve** [comment]
> I am actually slighlty annoyed too.

OK glad to know I am not completely on my own. Let's try to merge the mayavi PR first and then see whether there is enough annoyance between all of us to make the change.

**Comment by lesteve** [comment]
Just remembered about this one. I think we should do it before the next release and I am even volunteering to do it.

Anyone strongly disagrees?

**Comment by GaelVaroquaux** [comment]
> Just remembered about this one. I think we should do it before the next
> release and I am even volunteering to do it.

> Anyone strongly disagrees?

No

**Comment by Titan-C** [comment]
For the module name it kind of feels simpler not to have underscores. Its an extra hard to reach key in the keyboard. Neverteless the aren't many calls to the module itself, only 2 in the conf.py file and that's all.
Now for consistency, you might want to also update the name of the configuration dictionary to sphinx_gallery_conf

**Comment by lesteve** [comment]
> Its an extra hard to reach key in the keyboard.

Even on a Dvorak keyboard? If that's the case we just need a Dvorak keyboard designed especially for Python.

I opened a PR, comments welcome.

**Comment by Titan-C** [comment]
> Even on a Dvorak keyboard? If that's the case we just need a Dvorak keyboard designed especially for Python.

no on Dvorak the underscore is just by the right pinky finger, close to no effort

**Comment by lesteve** [comment]
> no on Dvorak the underscore is just by the right pinky finger, close to no effort

Great to know that all is well is the Dvorak world ;-)
