### ISSUE TITLE
Adding a ReST block immediately after the module docstring breaks the generated .rst file

### ISSUE THREAD

**Issue by timhoffm** [sphinx-gallery/sphinx-gallery#473]
## Bug

It appears that both module docstring and ReST blocks are stripped of blank lines at the beginning and end.

Thus the example from https://sphinx-gallery.github.io/syntax.html

~~~
"""
This is my example script
=========================

This example doesn't do much, it just makes a simple plot
"""

###############################################################################
# This is a section header
# ------------------------
~~~

would result in an .rst file with
~~~
This example doesn't do much, it just makes a simple plot
This is a section header
------------------------
~~~

resulting in incorrect rendering of the section due to a missing line before it. A similar effect happens if you have just plain text paragraphs: They will be joined.

This appears to be a common pitfall:
https://github.com/matplotlib/matplotlib/pull/13911
https://github.com/matplotlib/matplotlib/pull/13950

## Proposed fix

Probably the correct fix would be to always add a blank line after the module docstring text in the generated .rst file.

**Comment by larsoner** [comment]
Agreed extra blank lines should fix it without hurting anything.

Can you make a PR with regression test for this?

**Comment by timhoffm** [comment]
I'm quite busy right now. I won't be getting to this within the next 1-2 weeks. If this is still open then, I will look into it.
