### ISSUE TITLE
binder requirements with Dockerfile?

### ISSUE THREAD

**Issue by jasmainak** [sphinx-gallery/sphinx-gallery#476]
I was trying to set up binder links for the MNE documentation with sphinx-gallery and got this error:

```py
ValueError: Did not find one of `requirements.txt` or `environment.yml` in the "dependencies" section of the binder configuration for sphinx-gallery. A path to at least one of these files must exist in your Binder dependencies.
```

Unfortunately, it's not straightforward to have headless mode work with pysurfer with just a requirements.txt / environment.yml but it's possible to do this with Dockerfile. @choldgraf do you have a sense of whether this feature can be implemented easily? I can help if so ...

**Comment by choldgraf** [comment]
Yep, good call
