### ISSUE TITLE
Should ``image_scrapers`` be renamed (to ``output_scrapers`` for example)? 

### ISSUE THREAD

**Issue by emmanuelle** [sphinx-gallery/sphinx-gallery#485]
Very nitpicky stuff, but the ``image_scrapers`` name in the configuration directory conveys the idea that image files are scraped, whereas it's rather figures or any kind of useful output. Therefore, should it be renamed to ``output_scrapers`` (or ``figure_scrapers``)?

**Comment by larsoner** [comment]
At this point it only deals with images. At some point it might do more, so perhaps it was not the best naming. However, IMO correcting this misnomer (now or in the future) is probably not worth the backward compat break to change the name.

**Comment by emmanuelle** [comment]
Sure, I get your point. It's also that I'm planning to work on a plotly scraper, in which case it would be html content which would be scraped, not images :-).

**Comment by emmanuelle** [comment]
But once again it's very minor stuff, so feel free to close this issue.

**Comment by larsoner** [comment]
Okay I'll close this in favor of continuing discussion of non-Python renderers in #441 and #421
