### ISSUE TITLE
Matplotlib raises warning when 'pyplot.show()' is called

### ISSUE THREAD

**Issue by padix-key** [sphinx-gallery/sphinx-gallery#488]
Whenever `matplotlib.pyplot.show()` is called in an example script, the following warning is displayed:

`UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.`

I am using `matplotlib 3.0.3` and `sphinx-gallery 0.3.1` at Python 3.6.

**Comment by padix-key** [comment]
Possible solutions could be
- filtering the warning out
- temporarily replacing the `show()` function with an empty function

**Comment by larsoner** [comment]
I think we should add a note to the docs about how to use simplefilter or something similar to do this (for projects that want to).
