### ISSUE TITLE
ENH: easy linking to "examples using my_function"

### ISSUE THREAD

**Issue by drammock** [sphinx-gallery/sphinx-gallery#496]
Is there a way to cross-link to the "Examples using..." mini-galleries in the API docs?  I know it auto-generates a URL anchor 
`module.name_of_function.html#examples-using-module-name-of-function` so I can add a normal URL link, but it would be cleaner if I could just do something like
```
:func:`module.name_of_function#minigallery`
```
or similar. Any suggestions (either how to do it in user code, or general approach / possible pitfalls to implementing it in sphinx-gallery)?

**Comment by larsoner** [comment]
It seems like we should add a `.. _sphx_glr_<name>_backreferences::` link or so if we don't already. Seems like an uncontroversial and quite useful thing to add.

**Comment by larsoner** [comment]
(following whatever internal linking conventions we use)

**Comment by lucyleeow** [comment]
@larsoner to clarify, do you mean adding something like:
```
.. _sphx_glr_backreferences_nump_exp::
```
to the top of the file `gen_modules/backreferences/numpy.exp.examples` so you can reference the mini gallery with:

```
:ref:`sphx_glr_backreferences_nump_exp`
```

**Comment by larsoner** [comment]
Yeah that's what I have in mind, @drammock would that indeed help?

**Comment by drammock** [comment]
> you can reference the mini gallery with:
> 
> ```
> :ref:`sphx_glr_backreferences_nump_exp`
> ```

That would work for me.  Although TBH I made that request long enough ago that I don't remember which page or tutorial I wanted it for :)  But I'm sure I'd find uses for it soon enough.

**Comment by lucyleeow** [comment]
I'm not sure if this works. The reference link will work only if the 'examples' file (e.g., `gen_modules/backreferences/numpy.exp.examples`) has been included (with `.. include:: ...`) elsewhere in the documentation. For our docs it only works as our autodoc template ([`doc/_templates/module.rst`](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/doc/_templates/module.rst)) includes 'examples' files for every fun/class, and this is then included our documentation. Further linking is not deterministic if you have included an examples file more than once in the documentation.

I could instead replace some config `sphx_glr_backref_<>` with:
```
.. include:: <>
.. raw:: html

    <div class="sphx-glr-clear"></div>
```
but this is not very elegant.

**Comment by larsoner** [comment]
I just realized that in MNE we should just modify the `class.rst` and `function.rst` templates. We already modify them to include the `.examples` file, we should add a `.. whatever::` before them, and that should work.

**Comment by larsoner** [comment]
... though if it does work, we should also do this in our templates here and in the docs

**Comment by larsoner** [comment]
@lucyleeow do you want to see if it's possible?

**Comment by lucyleeow** [comment]
It should be possible to add the reference label (`.. _my_fun:`) to the top of our `doc/_templates/module.rst` file but sphinx-gallery doesn't ship this file? We only have .css and some images in our `_static`: https://github.com/sphinx-gallery/sphinx-gallery/tree/master/sphinx_gallery/_static

**Comment by larsoner** [comment]
I mean in our internal `conf.py` and also in docs here

https://sphinx-gallery.github.io/stable/configuration.html#auto-documenting-your-api-with-links-to-examples

**Comment by lucyleeow** [comment]
Oh that makes sense now!

**Comment by larsoner** [comment]
Seems to work in https://github.com/mne-tools/mne-python/pull/7748
