### ISSUE TITLE
Extending figure_rst to support html figures?

### ISSUE THREAD

**Issue by emmanuelle** [sphinx-gallery/sphinx-gallery#498]
Following #493 and #494, I've submitted a PR to plotly.py (https://github.com/plotly/plotly.py/pull/1577). However, in this PR I had to rewrite the ``figure_rst`` function of ``scrapers.py`` for html figures and html directives added to the rst string. I was thinking I could instead submit a PR to sphinx-gallery to extend ``figure_rst`` so that it handles also html figures, which could benefit other libraries. What do you think of this?

**Comment by larsoner** [comment]
So the idea I have in mind (so far) is that we have:

- scrapers: things that get images/content/stuff that we want to be embedded, and
- `figure_rst`-like functions (no name for this: functions that return `rst` code that actually embeds the things that were scraped

In this conceptualization, it makes the most sense to have libraries that implement (and maintain) custom scrapers also implement (and maintain) the custom RST generation code. It's entirely possible if they choose to update how the scaper works, they'll want to update the RST generator.

WDYT?

**Comment by choldgraf** [comment]
this seems reasonable to me - I like the idea of people being in charge of their own scrapers (though we could / should document where community scrapers exist)

**Comment by emmanuelle** [comment]
Makes sense, thanks! Feel free to close unless somebody else wants to add something.

**Comment by larsoner** [comment]
@emmanuelle I'll close but if this arrangement ends up being problematic don't hesitate to reopen. We're still trying to sort out the best way to do this!
