### ISSUE TITLE
Binder integration and Read the docs

### ISSUE THREAD

**Issue by StanczakDominik** [sphinx-gallery/sphinx-gallery#503]
Hi, after doing some tinkering trying to incorporate binder links into our into our example gallery - am I right in saying that there's currently no way of getting that working with readthedocs as a documentation builder, since binder needs a repository with hosted notebooks? If that's the case, I'll update the docs with a note on that.

**Comment by StanczakDominik** [comment]
Also, if I simply misconfigured something and anyone would like to take a look: here's the relevant Sphinx-gallery config edit https://github.com/PlasmaPy/PlasmaPy/commit/b8286b428a467c23d4f7c48643f3f42ca8edcfcb 

and here's an example of an example that doesn't find notebooks:

http://docs.plasmapy.org/en/master/auto_examples/particle_stepper.html

I think I was confused and thought the Docker building step would somehow incorporate notebooks generated by sphinx-gallery into the Docker image, thus allowing Binder to find them there. But I guess I simply have no idea how Binder works!

**Comment by choldgraf** [comment]
well, it's sort-of correct. You could host your notebooks on a github repository separately from your readthedocs deployment, and just make sure that the two are mirrored properly. But I agree that's a bit hacky, and other than this you're correct that readthedocs by itself wouldn't be able to provide links to the notebooks on its own
