### ISSUE TITLE
Intro text gets truncated on '-' character

### ISSUE THREAD

**Issue by martinfiers** [sphinx-gallery/sphinx-gallery#517]
Hello,

We have a sample that we'd like to document, which has a sentence: "This is a Mach-Zehnder Interferometer used for [...]".

However, in gen_rst.py, extract_intro_and_title, the regex defined is this:

`match = re.search(r'([\w ]+)', title_paragraph)`

This will truncate on the '-' sign because of this specific regex. Would it be safe/ok to add the '-' symbol here, too? I can imagine there will be other sentences where a hyphen will be present.

Thanks for this nice project, btw!

**Comment by larsoner** [comment]
Maybe that dash, colon, semicolon, apostrophe, backtick, and quote would be a good PR. There are other punctuation marks that matter (e.g., en dash or fancy quotes) but this would probably be a good start. Any regex experts feel free to chime in as well.

Can you make a PR to add this with a small test?
