### ISSUE TITLE
Show memory usage in build output

### ISSUE THREAD

**Issue by banesullivan** [sphinx-gallery/sphinx-gallery#522]
The `show_memory` option is cumbersome to work with - I want to see which examples have high memory consumption and I do not want to look through each page in the gallery to find out the memory usage. 

Can you all output the memory usage in the build output similar to how execution times are shown and perhaps sort them from high to low useage?

It'd be nice if the output was formatted more clearly into a raw text table. Maybe something like:

```txt
example execution summary:
            Filename                        Time        Memory
    - ../examples/02-plot/orbit.py         39 sec       282 MB
    - ../examples/02-plot/opacity.py       22 sec       250 MB
    - ../examples/02-plot/lighting.py      21 sec       300 MB
    - ../examples/02-plot/texture.py       20 sec       133 MB
    - ../examples/01-filter/slicing.py     19 sec        85 MB
```

-----

Also, every so often I run into an issue with zombie threads - anyone else experience ths when using `'show_memory': True`:

```zsh
(dev) ➜  docs git:(patch/subplot) ✗ rm -r examples
(dev) ➜  docs git:(master) ✗ make html
Running Sphinx v2.1.2
Adding copy buttons to code blocks...
loading pickled environment... done
generating gallery...

Exception occurred:
  File "/Users/bane/.local/lib/python3.7/site-packages/psutil/_psosx.py", line 370, in catch_zombie
    raise ZombieProcess(proc.pid, proc._name, proc._ppid)
psutil.ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=71575)
The full traceback has been saved in /var/folders/2x/4df66vz13pv4hj_ysv23tyyc0000gn/T/sphinx-err-8aw1_qos.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

**Comment by larsoner** [comment]
I'd rather add them to this page:

https://sphinx-gallery.github.io/auto_examples/sg_execution_times.html

It's documented here in a `.. note::`, perhaps not prominently enough:

https://sphinx-gallery.github.io/configuration.html#manage-multiple-galleries

Maybe we should actually reformat it as a table with name/time/memory (if applicable) as columns.

I have not seen this zombie thread warning that I know of. Then again I have not spent much time building docs on macOS machines.

**Comment by banesullivan** [comment]
Thanks, @larsoner - I did not realize that page was created... this page is not automatically added in the docs is it?

> Maybe we should actually reformat it as a table with name/time/memory (if applicable) as columns.

👍

**Comment by banesullivan** [comment]
> I'd rather add them to this page: https://sphinx-gallery.github.io/auto_examples/sg_execution_times.html

I'd really like to have a table both on that page and in the build output... personal preference though

**Comment by larsoner** [comment]
> I did not realize that page was created... this page is not automatically added in the docs is it?

It's generated but not linked to from anywhere, e.g.:

https://docs.pyvista.org/examples/00-load/sg_execution_times.html

> I'd really like to have a table both on that page and in the build output... personal preference though

Seems reasonable given we already output the times. +1 for adding it both places.

Regarding sorting, we could add a config value `computation_sort_key` that takes a 1- or 2-element tuple of `(time[, memory],)` values and returns the key with which to sort. By default and current behavior is just `lambda x: x`). Your use case would be `'computation_sort_key': lambda x: x[::-1]` (but really you'd want to use some trivial class with a stable `__repr__` to avoid Sphinx always forcing a full rebuild due to config change).

Workable?

**Comment by banesullivan** [comment]
That sounds good to me!

If sorting is more work than anyone has time to implement, I'd be happy leaving it sorted by execution time as long as the table has the time and memory use
