### ISSUE TITLE
Small regression in 0.4.1: print(__doc__) creates empty output block 

### ISSUE THREAD

**Issue by lesteve** [sphinx-gallery/sphinx-gallery#528]
Seen in https://github.com/scikit-learn/scikit-learn/pull/14507#issuecomment-516466110, `print(__doc__)` creates empty output box (yellowish box in the output below). 

![image](https://user-images.githubusercontent.com/1680079/62141734-5f74e380-b2ed-11e9-9796-4ff96ae33d63.png)

This was introduced by https://github.com/sphinx-gallery/sphinx-gallery/pull/475. A simple fix would be to not have an output box if `my_stdout.isspace()` and add a test similar to the one introduced in #475 to check that `print(__doc__)` does not create an output box.

Small reminder: many scikit-learn examples have `print(__doc__)` at the beginning, so inside sphinx-gallery we set `__doc__ = ''` (`__doc__` is already rendered at the top of the example HTML so you don't want it captured in stdout as well).

ping @lucyleeow who is interested to work on this.

**Comment by larsoner** [comment]
We are in a similar situation in MNE-Python. I'm fine with showing the output of a given block if and only if `isspace()` is False.
