### ISSUE TITLE
consider looking also for 'readme.*' instead of only 'README.*'

### ISSUE THREAD

**Issue by revesansparole** [sphinx-gallery/sphinx-gallery#534]
Is there any reason to consider only 'README.*' in uppercase and not include any other variation in lower case?

It would be of great help to all our projects which are constructed around 'readme.rst' files.

I assume it's only a matter of changing the function '_get_readme' in 'gen_rst.py' but maybe there is a non technical reason for not doing it.

Thanks

**Comment by choldgraf** [comment]
it's fine with me, I'm not sure what's the benefit of requiring CAPS for files...

**Comment by larsoner** [comment]
> I assume it's only a matter of changing the function '_get_readme' in 'gen_rst.py' but maybe there is a non technical reason for not doing it.

Some general "community uniformity" around particular practices would be another reason, but I don't think it's worth trying to enforce that here, `readme.rst` should be fine.
