### ISSUE TITLE
ENH capture 'repr's of last expression

### ISSUE THREAD

**Issue by lucyleeow** [sphinx-gallery/sphinx-gallery#540]
Relates to #396 (pretty html rendering) which can be implemented in 2 steps:

1. (this issue) `eval()` last line if it is an expression. This removes the need to use `print()` to output the value of expressions.
2. Capture html output if there is a `__repr_html__`. This allows nice rendering of e.g. pandas dataframes, plots and reports (currently implemented via a 'image' scraper in [nilearn](https://github.com/nilearn/nilearn/pull/2019), [nistats](https://github.com/nistats/nistats/pull/387), [mne](https://github.com/mne-tools/mne-python/pull/6433))

There has been discussion at #421 (and a WIP PR #422) about using nbconvert to execute code blocks, which would address both issues above, however there were concerns about adding dependencies and no work around was agreed upon.

The plan for this issue would be to implement the same ['exec/eval' logic ](https://github.com/jupyter/jupyter-sphinx/blob/b1d5a4568fc697e8ffb07d669432592e5f0f3aa0/jupyter_sphinx/embed_widgets.py#L65) from jupyter-sphinx (as suggested by @maartenbreddels) in [`execute_code_block()`](https://github.com/sphinx-gallery/sphinx-gallery/blob/master//sphinx_gallery/gen_rst.py#L456:5). Thoughts welcome.

(cc @GaelVaroquaux)

**Comment by larsoner** [comment]
Sounds reasonable to me. And if someday we do decide to use `nbconvert` we can probably still do it without breaking backward compatibility.
