### ISSUE TITLE
ENH Add CSS for pandas dataframe

### ISSUE THREAD

**Issue by lucyleeow** [sphinx-gallery/sphinx-gallery#544]
With #541, Sphinx-Gallery can capture raw HTML (using the `_repr_html_()` of an object) and embed in rst. In some cases, where the captured raw HTML does not include CSS (e.g. pandas dataframes), this can be added to make the output look better. For reference [this](https://1052-25860190-gh.circle-artifacts.com/0/rtd_html/auto_examples/plot_capture_repr.html) (scroll down) is what a pandas dataframe looks like with just the raw HTML.

For example, Jupyter notebook seems to take CSS from their own [`renderedhtml.less`](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/less/renderedhtml.less) (see @larsoner's [post](https://github.com/sphinx-gallery/sphinx-gallery/pull/541#issuecomment-539196065)). For reference this [SO](https://stackoverflow.com/questions/49324569/replicating-jupyter-notebook-pandas-dataframe-html-printout) question describes how to get pandas dataframes to look like those in Jupyter notebook. 

One solution is that we can include our own CSS for common objects like pandas dataframes (I think this might be beyond the scope of SG).

~Another solution is to obtain CSS from the objects we capture `_repr_html_` from, if possible.~

Another solution would be to add a  `add_css` configuration to allow the user add their own CSS file (e.g. pandas dataframes have specific HTML tags that can be used to write CSS specifically for dataframes), a reference to which would be added at the end of raw HTML embedded.

**Comment by choldgraf** [comment]
I kinda like the idea of letting objects bring their own CSS with them - that would give folks the ability to customize on a per-object basis

**Comment by lucyleeow** [comment]
This is what I thought when I was writing #541. 

For pandas dataframes, I am not sure if there is pandas CSS that is just not output with `_repr_html_` or if jupyter is adding all the CSS itself. If it is the latter, then I agree that it may not be worthwhile to add our own but it may be worthwhile to give the user the option to write their own CSS so they can dictate how objects, which do not come with their own CSS, are styled.

**Comment by jorisvandenbossche** [comment]
For pandas, the styling is mostly done by the frontend (eg jupyter notebook er lab). 
See eg how nbsphinx includes such css as well to let dataframes look ok in their generated rst/html: https://github.com/spatialaudio/nbsphinx/blob/fb3ba670fc1ba5f54d4c487573dbc1b4ecf7e9ff/src/nbsphinx.py#L587-L619

**Comment by jorisvandenbossche** [comment]
You can see in the output of `df._repr_html_()` that we include a little bit of css:

```In [42]: print(df._repr_html_())                                                                                                                                                                                   
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>a</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
    </tr>
  </tbody>
</table>
</div>
```

but that is only to have correct alignment for index/column labels, not for the overall appearance.

**Comment by lucyleeow** [comment]
Thanks @jorisvandenbossche, good to know.

I think it might be useful to add a 'CSS' config option to give the user the option to write a CSS document and add reference to this in all raw HTML output...but depends on the demand.

**Comment by jorisvandenbossche** [comment]
We currently don't have that CSS in pandas. I am personally not fully sure it is up to pandas to provide this, but you're certainly welcome to to open an issue on the pandas issue tracker.

**Comment by lucyleeow** [comment]
@jorisvandenbossche I agree with you - I don't think it is up to pandas to provide this. You have already added [Styling](https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html) which is pretty cool.

For me this issue is about whether we should add a CSS config to allow users to provide their own - I don't think SG or pandas should provide CSS (for objects that don't have their own).

**Comment by larsoner** [comment]
I think it should be up to the `_repr_html_` provider rather than SG to give a suitable CSS class (the CSS class is a HTML attribute after all). Fortunately, it's already possible to stylize Pandas outputs because they do give their `table` the `dataframe` class:

https://github.com/mne-tools/mne-python/pull/7138/files#diff-1a451631fe18f4ca156584c3c67928ffR446-R448

So I'd say let's close for now, @lucyleeow feel free to reopen if you disagree or think something is still missing.

**Comment by larsoner** [comment]
(@lucyleeow feel free to open a quick doc PR with these example lines using `Pandas` as an example if you think it would help)

**Comment by GaelVaroquaux** [comment]
Well, honestly more than one person has complained to me that the
dataframes look bad while they look good in jupyter. I wouldn't mind
adding a bit of CSS for this specific case.

**Comment by larsoner** [comment]
Okay with me if we add to `gallery.css` something that makes the Pandas ones look reasonable in most envs. I'll reopen and maybe someone can take a look

**Comment by lucyleeow** [comment]
I've amended the issue title to just be about pandas dataframes.

If anyone wishes to add CSS for other elements, another issue can be opened.
