### ISSUE TITLE
Last word in rst used as code

### ISSUE THREAD

**Issue by lucyleeow** [sphinx-gallery/sphinx-gallery#546]
If an example `.py` file ends with an rst block, Sphinx-Gallery thinks the last word of the rst block is code and tries to execute it, unless there is an empty line after the rst block.

For example:

```Python
"""
Test
####

test
"""

print('hello')

#%%
# This is a sentence.
```

Gives: 
![Screenshot_2019-10-09 Test — mwe 0 documentation](https://user-images.githubusercontent.com/23182829/66478789-7416ea00-ea9b-11e9-8324-593f335ca405.png)

If there is an empty line at the end, this does not happen. Is it expected to just add a new line to the end of the document?

MWE [here](https://github.com/lucyleeow/Sphinx-Gallery-MWE).

**Comment by larsoner** [comment]
> Is it expected to just add a new line to the end of the document?

In general people do, probably because it's part of PEP8. But it shouldn't cause an error in SG if one isn't there, so this is indeed a bug we should fix
