### ISSUE TITLE
Support pyqtgraph plots

### ISSUE THREAD

**Issue by Cadair** [sphinx-gallery/sphinx-gallery#553]
I haven't looked into how practical this would be but it came up in https://github.com/heliophysicsPy/gallery/pull/21 so I thought I would register interest in it. It would be nice to support images generated by https://github.com/pyqtgraph/pyqtgraph

**Comment by larsoner** [comment]
With the `scraper` interface this can be added by the PyQtGraph library itself, so please feel free to open an enhancement request on their issue tracker. 

To learn how to do it, see:

https://sphinx-gallery.github.io/advanced.html#write-a-custom-image-scraper

`pyvista` recently did this and it did not sound too painful, see:

https://github.com/pyvista/pyvista/pull/150/files#diff-78840ea3f4585438ec92ca3814597639R14-R41
https://github.com/pyvista/pyvista/pull/228/files
