### ISSUE TITLE
Making sphinx-gallery parallel_write_safe

### ISSUE THREAD

**Issue by astrofrog** [sphinx-gallery/sphinx-gallery#560]
At the moment, sphinx-gallery is marked as not being ``parallel_write_safe`` (it is explicitly set to ``False``), but it's not clear what the blocker is there. Is this something that is potentially fixable, or are there fundamental limitations in how sphinx-gallery works? (at the moment sphinx-gallery is the only extension that is stopping docs in several packages I work on to be built in parallel in the write step).

**Comment by larsoner** [comment]
@astrofrog I added the `parallel_write_safe=False` but I'm not sure if we need it. I think I did it because I wasn't sure if we required it and wanted to be safe. But from a tiny bit of reading it does not seem to be required. Want to make a quick PR to change it? If not I can do it later today

**Comment by astrofrog** [comment]
I don't **think** it's needed. One thing is for sure - if we leave it as ``False``, we'll never know :) The fact that sphinx considers this to be ``True`` if not declared tells me that it's probably reasonable to assume it's parallel unless there are good reasons why not.

See #561 for a PR.
