### ISSUE TITLE
How best to handle data files?

### ISSUE THREAD

**Issue by jarrodmillman** [sphinx-gallery/sphinx-gallery#565]
In NetworkX, several of our examples read data files, which are stored in the same directory as the corresponding example script:
- https://github.com/networkx/networkx/blob/master/examples/drawing/plot_knuth_miles.py
- https://github.com/networkx/networkx/blob/master/examples/drawing/plot_sampson.py
- https://github.com/networkx/networkx/blob/master/examples/drawing/plot_lanl_routes.py
- https://github.com/networkx/networkx/blob/master/examples/graph/plot_roget.py
- https://github.com/networkx/networkx/blob/master/examples/graph/plot_words.py

For `plot_knuth_miles.py`, you can see that we added the following to the docstring:
``` 
The data file can be found at:
https://github.com/networkx/networkx/blob/master/examples/drawing/knuth_miles.txt.gz
```

But as you can see in issue https://github.com/networkx/networkx/issues/3692, we didn't add it to `plot_sampson.py`.
I can easily add links to all the example scripts that need it, but I was wondering if there is a better solution that would be helpful to other projects.

More specifically:
1. Is adding a link in the docstring the best solution?
2. Should the examples require internet access?  If so, should we grab data files from the network in our script?
3. Should something be added to the sphinx-gallery documentation suggesting "best practice"?
4. Should sphinx-gallery auto-create download links in the gallery?
5. @choldgraf also brought up how to best handle this for Binder links for gallery notebooks.

**Comment by larsoner** [comment]
> 1. Is adding a link in the docstring the best solution?
>
> 2. Should the examples require internet access? If so, should we grab data files from the network in our script?

Over in MNE-Python we have dataset downloaders that by default download to `mne_data`:

https://github.com/mne-tools/mne-python/blob/master/tutorials/intro/plot_10_overview.py#L50

I think `nilearn` has something similar. Pretty sure `vispy` does something similar, as well (though it does not use SG). It facilitates users running scripts easily. In PySurfer, by contrast, we assume people have the data used in the examples and have set a path to it. If I were you, I'd probably set up the downloaders.

In MNE when our docs build on CircleCI, we have it download the data (probably amounts to something like 20GB in our full-build case) and build the docs. So far it hasn't had too much maintenance burden.

> 3. Should something be added to the sphinx-gallery documentation suggesting "best practice"?

It might make sense to roll this into #555 pretty easily. But as a first pass, at least linking to what `nilearn` and `mne` do might be a good start.

> 4. Should sphinx-gallery auto-create download links in the gallery?

To the data? I would say no. Maybe we should collaborate on generalizing / abstracting MNE and nilearn's data downloading utilities in a separate package instead.

> 5. @choldgraf also brought up how to best handle this for Binder links for gallery notebooks.

For MNE if you launch a notebook it will have to then download the ~1.5 GB dataset for the example to the running instance. It's not ideal but it works.
