### ISSUE TITLE
AttributeError: 'URLError' object has no attribute 'url'

### ISSUE THREAD

**Issue by EtienneCmb** [sphinx-gallery/sphinx-gallery#568]
Hi,

I updated to the latest 0.5.0 and I've an error message when building the documentation : 
```
File "/home/etienne/anaconda3/lib/python3.7/site-packages/sphinx_gallery/docs_resolv.py", line 260, in _handle_http_url_error
    msg, e.url, extra, e.msg)
AttributeError: 'URLError' object has no attribute 'url'
```

Error is occuring inside the function [_handle_http_url_error](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/docs_resolv.py#L260). I also tried to comment the logger.warning line and the doc is correctly build again

**Comment by larsoner** [comment]
@EtienneCmb can you look into the correct attribute to use instead and make a PR to fix the bug?
