### ISSUE TITLE
typing.TYPE_CHECKING is True at runtime in executed .py files

### ISSUE THREAD

**Issue by whoopnip** [sphinx-gallery/sphinx-gallery#570]
First, thanks for the great package. I'm already finding it very useful.

When trying to import a package in one of my .py files which I'm including in the gallery, it was hitting circular imports which are not there when importing the package normally. I tracked it down to the use of:

```
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    import my_module
```

I found that when my .py file for the gallery is importing the package, it is executing `import my_module` which should not happen at runtime. 

I then confirmed the behavior by modifying my .py for the gallery to have:
```
import typing
typing.TYPE_CHECKING
```

as the first cell, and it indeed shows `True` in the output. I was able to make my example run by adding:

```
import typing
typing.TYPE_CHECKING=False
```

as the first cell. Then the import of the package works normally. But I would prefer to not have this at the beginning of all my gallery .py files.

Any idea why `typing.TYPE_CHECKING` is being set to `True` while executing .py gallery files?

**Comment by larsoner** [comment]
@whoopnip we don't do anything with `typing` (`git grep typing` is empty) so I'm not sure. It does not sound like a SG bug. Maybe Sphinx itself does something, they have several `typing` imports. Does the problem persist if you remove SG from your extensions list?

**Comment by whoopnip** [comment]
@larsoner That makes sense, it looks like it is a Sphinx issue. In the Sphinx `conf.py`, `typing.TYPE_CHECKING` was False so I thought it was SG, but now I created a custom directive and from within that custom directive, indeed `typing.TYPE_CHECKING=True`, even if SG is excluded from extensions. I'll go ahead and raise an issue in Sphinx. Thanks for looking into it!

**Comment by whoopnip** [comment]
In case anyone else runs into this, turns out that this was caused by the extension `sphinx_autodoc_typehints`. There is a configuration option there `set_type_checking_flag` which controls this behavior. Setting `set_type_checking_flag = False` in Sphinx `conf.py` fixes this for me.
