### ISSUE TITLE
Remove the note linking to the download section at the beginning of the example from latex/pdf output

### ISSUE THREAD

**Issue by benvial** [sphinx-gallery/sphinx-gallery#572]
For latex/pdf output, this note at the beginning of the example linking to the download section does not link to anything (since there are no download buttons). Would it be possible to disable it in that case? The straightforward way would be wrap it into a `.. only:: html` directive.

**Comment by larsoner** [comment]
Sounds reasonable to me. @lucyleeow do you agree? If so @banesullivan PR welcome to fix it

**Comment by lucyleeow** [comment]
I agree! I think the execution line is [here](https://github.com/sphinx-gallery/sphinx-gallery/blob/9a79bd95de0e0496c04a50cf47c3677f6ce1977e/sphinx_gallery/gen_rst.py#L860). A PR with a test would be great!

(@larsoner did you mean to tag @banesullivan?)

**Comment by larsoner** [comment]
Whoops, nope I didn't. @benvial PR welcome (@banesullivan sorry for the noise)

**Comment by larsoner** [comment]
(BTW I'm not sure how easy it would be to add a test for this so I think just adding the `.. only:: html` directive with indentation plus a manual check of the built PDF on CircleCI is good enough)

**Comment by lucyleeow** [comment]
Good point @larsoner! Should be an easy PR then @benvial!

**Comment by lucyleeow** [comment]
@larsoner is it worth testing if the text '.. only:: html' is included in the output rST?

**Comment by larsoner** [comment]
> is it worth testing if the text .. only:: html is included in the output rST?

Ahh yeah, that would probably be decent. And actually it's possible that some existing test will fail without adding that line to some existing expected output string.

**Comment by benvial** [comment]
Great I'll work on a PR and add some tests

> > is it worth testing if the text .. only:: html is included in the output rST?
> 
> Ahh yeah, that would probably be decent. And actually it's possible that some existing test will fail without adding that line to some existing expected output string.

Indeed two tests are failing. will fix that also

**Comment by benvial** [comment]
> Great I'll work on a PR and add some tests
> 
> > > is it worth testing if the text .. only:: html is included in the output rST?
> > 
> > 
> > Ahh yeah, that would probably be decent. And actually it's possible that some existing test will fail without adding that line to some existing expected output string.
> 
> Indeed two tests are failing. will fix that also

My bad, actually all tests passed, probably an issue with my testing environment initially.

Just made a PR ( #573 )

Thanks @larsoner and @lucyleeow for your quick reply.
