### ISSUE TITLE
Improve the junit xml

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#576]
Sphinx-gallery uses junit.xml files to provide very useful summaries, that are for instance, displayed by circle-ci (https://sphinx-gallery.github.io/stable/configuration.html#using-junit-xml-files)

It would be great to use this to help contributors. I see the following potential additions that would be very useful:

- When there is a failure in an example, add the traceback there
- Link to the artifacts (this might or might not require a configuration switch).

Cc @larsoner who did the original junit.xml support, and @lucyleeow who might have the energy to tackle this

**Comment by larsoner** [comment]
> When there is a failure in an example, add the traceback there

The tracebacks are in the JUnit output, and show up in the CircleCI interface, e.g.:

https://circleci.com/gh/mne-tools/mne-python/17090

<img width="1352" alt="Screen Shot 2019-12-06 at 19 05 08" src="https://user-images.githubusercontent.com/2365790/70364631-61325300-185b-11ea-82a4-62d8204743fd.png">

Is this what you are looking for?

> Link to the artifacts (this might or might not require a configuration switch).

For this I would say we would want to:

1. Detect being run inside a CircleCI environment (CircleCI has env vars for this)
2. Extract the artifact URL from this (also accessible from env vars I think)
3. Make use of a new SG config var like `circleci_artifacts_path` that tells how to construct the url based on where your `circle.yml` saves the artifacts (for MNE it would be for example `'0/dev'`, because our artifacts live at URLs like [this](https://17090-1301584-gh.circle-artifacts.com/0/dev/index.html)). The default for this would be None, meaning "don't do it", and setting it to a `str` activates the feature
4. Append this URL to the end of the existing traceback above

**Comment by GaelVaroquaux** [comment]
> The tracebacks are in the JUnit output, and show up in the CircleCI interface, e.g.:

> https://circleci.com/gh/mne-tools/mne-python/17090

OK, great! I seem not to get enough failure, as I had not noticed.

Actually, the failures that we were getting at the brainhack were sphinx
failures in the examples, and not sphinx-gallery. This is why they were
not caught.

> For this I would say we would want to:

Agreed with the plan. However, I would add the link to the artifact for
every example generated, and not only those that fails.

Thanks!!!

**Comment by larsoner** [comment]
> Actually, the failures that we were getting at the brainhack were sphinx failures in the examples, and not sphinx-gallery. This is why they were not caught.

It would be great to add something like sphinxext.junit to output a separate file to track these problems. I think that circle allows displaying multiple junit file statuses.

> I would add the link to the artifact for every example generated, and not only those that fails

Sure it might actually be simpler to do this anyway. Circle might only show outputs of failures, though. At least that's all I've seen thus far.

**Comment by GaelVaroquaux** [comment]
> sphinxext.junit

That extention doesn't exist, right?

> Circle might only show outputs of failures

The current junit.xml also sows the slowest examples, no? I don't know how it was done, but is there a window to use here?

**Comment by larsoner** [comment]
Correct, I'm thinking it wouldn't be too hard to write such an extension. Though maybe it would be easier to have it live under this organization.

Regarding customization I don't know of any way to configure the junit result rendering.

https://circleci.com/docs/2.0/collect-test-data/

**Comment by lucyleeow** [comment]
>  However, I would add the link to the artifact for every example generated,

@GaelVaroquaux can you clarify this? I understand this:

> * Make use of a new SG config var like `circleci_artifacts_path` that tells how to construct the url based on where your `circle.yml` saves the artifacts (for MNE it would be for example `'0/dev'`, because our artifacts live at URLs like [this](https://17090-1301584-gh.circle-artifacts.com/0/dev/index.html)). The default for this would be None, meaning "don't do it", and setting it to a `str` activates the feature
> 
> * Append this URL to the end of the existing traceback above

but I don't understand what artifact you mean.

**Comment by GaelVaroquaux** [comment]
> but I don't understand what artifact you mean.

The generated html of the example.

Also, it would be really great if, even with any failure, there was a
link to the artifacts (for instance to the index.html of the main
gallery). It would facilitate review a lot.

**Comment by lucyleeow** [comment]
For failing and successful builds add the URLs of all the generated html to the output/traceback. Why not just add the URL of the index then?

> Also, it would be really great if, even with any failure, there was a link to the artifacts (for instance to the index.html of the main gallery). It would facilitate review a lot.

You mean the 'build_docs artifact'?
![image](https://user-images.githubusercontent.com/23182829/70452832-10636a00-1aa8-11ea-8292-5b4ee27cb29a.png)

**Comment by GaelVaroquaux** [comment]
Yes!

How do we get this? Maybe it's already there and it's a question of working on our documentation (which does need work).

**Comment by lucyleeow** [comment]
@GaelVaroquaux I wish I knew...I tried searching but couldn't find it documented anywhere. Please enlighten us @larsoner

**Comment by larsoner** [comment]
You can get it using the older circleci-artifacts-redirector:

https://github.com/larsoner/circleci-artifacts-redirector

But the better way nowadays would be to use circleci-artifacts-redirector-action:

https://github.com/larsoner/circleci-artifacts-redirector-action

If you really want more detail, the thing to do might be what sklearn does, which is make a static page after the sphinx build where you link to the things of interest. In their case, it's pages that have changed, in your case you could parse the JUnit XML, find errors, and create a list of links. And then you'd tell `circleci-artifacts-redirector-action` to give a link to this HTML file.

But maybe just having a link to the index is enough already.

**Comment by larsoner** [comment]
I think this is not a SG issue so I'll close, but feel free to reopen if there is more to do
