### ISSUE TITLE
Error when using two image scrappers together

### ISSUE THREAD

**Issue by jorgepiloto** [sphinx-gallery/sphinx-gallery#579]
Hi all,

at [poliastro project](https://github.com/poliastro/poliastro) we are moving our based jupyter notebooks examples to a beautiful sphinx-gallery. Since we are using both plotly and matplotlib I made use of both image scrappers. However, when combining them such as `'image_scrapers' = ('matplotlib', plotly_sg_scraper)` I get the following error on a simple example Python file:

```bash
generating gallery...
generating gallery for auto_examples... [ 25%] plot_sin.py                                                                                                                                       
Exception occurred:
  File "/home/lobo/anaconda3/envs/poliastro/lib/python3.7/site-packages/plotly/io/_sg_scraper.py", line 91, in figure_rst
    figure_name = figure_paths[0]
IndexError: list index out of range
```

You can better check my `docs/` configuration at [my working branch](https://github.com/jorgepiloto/poliastro/tree/sphinx-gallery/docs/source).

Any kind of help would be extremely useful! Thank you so much for this project :100:

**Comment by larsoner** [comment]
This looks like a plotly bug (traceback is in their code) so they'll probably need to fix it. Internally we use multiple scrapers (mpl and mayavi) and I'm using three in another project so in principle it's possible to do it without issue. It's possible that we do have some bug but the plotly people should probably investigate their end first.

**Comment by GaelVaroquaux** [comment]
Cc @emmanuelle

But she is on vacations

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by emmanuelle** [comment]
Thank you @jorgepiloto, I will take a look. Could you please open an issue on https://github.com/plotly/plotly.py/issues/new with the same message you posted here? It's likely to be more a plotly problem indeed, so let's carry on from there. Thanks!

**Comment by jorgepiloto** [comment]
Thank you for your fast answers @larsoner and @emmanuelle! I will open an issue as you  suggested in the official `plotly` repository with a deeper explanation on what is going on :smile:

**Comment by jorgepiloto** [comment]
Following issue is being tracked in the official plotly repository at https://github.com/plotly/plotly.py/issues/2014

**Comment by larsoner** [comment]
Okay I'll close for now but let's reopen if there is something we should do at this end
