### ISSUE TITLE
Reduce the amount of hard dependencies?

### ISSUE THREAD

**Issue by mgeier** [sphinx-gallery/sphinx-gallery#597]
In `setup.py`, there seem to be a lot of requirements in `install_requires` (which is populated from `requirements.txt`).

* [x] `setuptools` seems to be a strange requirement, since `setup.py` already imports it (before reading the list of requirements).

* [x] `matplotlib` is of course an important use case for SG, but is it really required? AFAICT, it's not used in the code, only in tests. There are use cases for SG without Matplotlib, right?

* [x] `pillow` seems to be needed for `scale_image()`. But what if no scaling is needed (for example when using only SVG images)?
   Also, why is this a hard requirement but in the code it looks like a soft requirement:

   https://github.com/sphinx-gallery/sphinx-gallery/blob/dff998dc51eb1c718be900e12aaa6394f61e5218/sphinx_gallery/utils.py#L23-L27

* [x] `sphinx>=1.8.3` I guess is justified because of the specific version. But I'm not quite sure.

* [x] `seaborn` is only included on `READTHEDOCS`, but it still seems strange. It would probably be better to use a `.readthedocs.yml` with probably a few "extra" requirements. Or probably a separate `requirements.txt` only for the docs?

**Comment by larsoner** [comment]
> setuptools seems to be a strange requirement, since setup.py already imports it (before reading the list of requirements).

I'm not sure the right thing to do here

> matplotlib is of course an important use case for SG, but is it really required? AFAICT, it's not used in the code, only in tests. There are use cases for SG without Matplotlib, right?

We set the renderer to Agg:

https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/scrapers.py#L26-L52

In principle we should be able to refactor it not to be this way, though. We should really only do this if `matplotlib` is in the list of scrapers.

> Also, why is this a hard requirement but in the code it looks like a soft requirement:

It's not hard versus soft here, IIRC at some point the module was renamed so it's trying the old and new names.

> sphinx>=1.8.3 I guess is justified because of the specific version. But I'm not quite sure.

Yes IIRC how we hook into the functionality / update styles etc. require it.

> seaborn is only included on READTHEDOCS, but it still seems strange. It would probably be better to use a .readthedocs.yml with probably a few "extra" requirements. Or probably a separate requirements.txt only for the docs?

Yes we should probably better separate what's required to build SG's documentation from what's required for using SG in downstream projects

**Comment by mgeier** [comment]
Thanks, #598 is great!
