### ISSUE TITLE
Sphinx treats gallery images as headers

### ISSUE THREAD

**Issue by Titan-C** [sphinx-gallery/sphinx-gallery#6]
As mentioned in #2. Gallery images show the header permanent link in red background.
This depends entirely on the sphinx version used. It does not happens in the read the docs default sphinx version or my conda environment with sphinx 1.2.3, but if build with sphinx 1.3 it happens.

Put an extra CSS instruction to avoid this from being displayed?

**Comment by larsoner** [comment]
@Titan-C is this still an issue with modern Sphinx (1.5+)?

**Comment by lesteve** [comment]
Closing this one. @Titan-C please reopen if you are still seing this. Full disclosure: I don't understand what this issue is about.
