### ISSUE TITLE
Perhaps should support parallel build

### ISSUE THREAD

**Issue by jnothman** [sphinx-gallery/sphinx-gallery#60]
Sphinx experimentally supports parallel building. But plotting can take as much time as the rest of the documentation generation when starting from scratch. Adopting sphinx's parallelisation for all plotting may be a nice option to have.

**Comment by agramfort** [comment]
+1

**Comment by Titan-C** [comment]
At some point I did have this in mind #25 It can be revisited later on

**Comment by jnothman** [comment]
closing as duplicate
