### ISSUE TITLE
MAINT: Better error messages

### ISSUE THREAD

**Issue by larsoner** [sphinx-gallery/sphinx-gallery#600]
As [pointed out](https://github.com/sphinx-gallery/sphinx-gallery/pull/599/files#r369287580) by @mgeier, raising plain Python errors is not as nice as raising Sphinx-specific variants. We should update our internal exceptions.

**Comment by GaelVaroquaux** [comment]
Huge deal! It would be great. I didn't know about these. 

⁣Sent from my phone. Please forgive typos and briefness.​
