### ISSUE TITLE
last_notebook_cell

### ISSUE THREAD

**Issue by banesullivan** [sphinx-gallery/sphinx-gallery#605]
Could a `last_notebook_cell` option be added much like the `first_notebook_cell` option for adding snippets that we want executed at the end of the downloaded notebook? This would be used to perhaps report on the user's environment with a tool like [`scooby`](https://github.com/banesullivan/scooby):

```py
sphinx_gallery_conf = {
    ...
    'last_notebook_cell': ("# Report on the environment specs\n"
                            "import scooby\n",
                            "scooby.Report()",)
}
```

With something like this, a user could download the example, run it, and encounter an error then immediately share the environment report... I imagine this will be useful for PyVista (`pv.Report`) and `mne-python` (`mne.sys_info()`)

**Comment by larsoner** [comment]
Sounds like a reasonable simple addition to me
