### ISSUE TITLE
thumbnails from loaded figures

### ISSUE THREAD

**Issue by prisae** [sphinx-gallery/sphinx-gallery#607]
I have a couple of examples where I compare one code to other, similar codes. These examples produce all very similar figures. I would therefore prefer the thumbs to be more informative, e.g. the logo of the code I am comparing to.

In other cases each example presents a method. Again, the plot itself is not very informative, but a little figure/sketch/drawing of the method would be great.

I can load figures easily in the examples with the `.. figure ::`-directive. However, these figures are not chosen even if they are the first figure in the example.

Is there any way how one can specify a, per-example-basis, figure for the thumbnail?

Or do you think it would be possible to extend the following directive
```# sphinx_gallery_thumbnail_number = 2```
 to also accept strings? E.g.,
```# sphinx_gallery_thumbnail_number = 'path/to/figure.png'```

These are some related issues/PRs I found, but none of them resolves it. #5 actually already suggested similar things, but it was closed then referring to the then introduced scraper API. However, I don't think the scraper API addresses this particular use-case.
- https://github.com/sphinx-gallery/sphinx-gallery/issues/5
- https://github.com/sphinx-gallery/sphinx-gallery/issues/110
- https://github.com/sphinx-gallery/sphinx-gallery/pull/114

**Comment by larsoner** [comment]
I don't see why we couldn't at least try to support this. @prisae do you want to try implementing it and see how difficult it is?

**Comment by prisae** [comment]
I had a quick try @larsoner, but without success. It is the first time that I looked at the sphinx-gallery code, and I am lost in the jungle of all the directories, where are the static files, where should what be stored, etc. The adjustment has to be in the function `save_thumbnail` of the file `gen_rst.py`. However, I couldn't figure it out.

I guess the image should be stored in `mymodule/docs/_static/`, right?

**Comment by larsoner** [comment]
> It is the first time that I looked at the sphinx-gallery code, and I am lost in the jungle of all the directories, where are the static files, where should what be stored, etc.

It is part our mess, part Sphinx's mess (understanding and making use of how Sphinx organizes things). The combination yields something that is a pain to understand, at least at first :)

So feel free to try as long as you want and I can take over at the point you lose interest insuffering through it...

> I guess the image should be stored in mymodule/docs/_static/, right?

I think the way to go would be to have the `str` version be a path relative to the documentation root. That way you can do `_static/whatever.jpg` (or whatever your project's Sphinx static path is) or `_images/sphx_glr_plot_artifact_detection_001.png` (generated by SG during the build process).

**Comment by prisae** [comment]
I had another go and implemented two versions. They are both very hacky, but I guess they are a start. Could you please have a look and say which one you prefer (if any at all)? Then I could make with that one a PR, and we can work on that.

This was the first attempt, to abuse the `# sphinx_gallery_thumbnail_number` to provide a path instead of a number.
https://github.com/sphinx-gallery/sphinx-gallery/compare/master...prisae:thumbnail-string

This is a second attempt, using a new `# sphinx_gallery_thumbnail_path` config. It is included such that `thumbnail_number` has priority over `thumbnail_path` in case both are provided.
https://github.com/sphinx-gallery/sphinx-gallery/compare/master...prisae:thumbnail-path

**Comment by larsoner** [comment]
The second one seems cleaner to me

**Comment by prisae** [comment]
I agree. The first one was my initial thought. Then I realized that the sphinx-gallery will pick-up any new parameter called `# sphinx_gallery_...`, so I thought it might be better to define a new one. Down the road it will be easier to maintain (and track down issues).

I'll create a PR with that and post the link here, so we can continue the discussion there.

**Comment by prisae** [comment]
Link to PR is above.

I will add an example to the docs now.

**Comment by prisae** [comment]
Fantastic, thanks again @larsoner .

Here an example.

### Before
Many of the examples have very similar figures (because they are simply comparisons of different codes and of different methods), so they are visually hard to distinguish what-is-what

![Gallery — emg3d-gallery 0 9 3 documentation - Mozilla Firefox_001](https://user-images.githubusercontent.com/8020943/74479692-e2d3dc00-4eaf-11ea-9a87-be740f07ddf0.png)

### After
Now it is much clearer using some external figures.

![Gallery — emg3d-gallery 0 9 3 documentation - Mozilla Firefox_002](https://user-images.githubusercontent.com/8020943/74479690-e23b4580-4eaf-11ea-9367-addf21aa2771.png)

**Comment by echedey-ls** [comment]
Do this configure options interpret multiline values? Like:

```python
# sphinx_gallery_thumbnail_path = \
#     "../../_images/a_very_long_name_that_with_a_lot_of_characters.png"
```

**Comment by larsoner** [comment]
No but in theory the parsing could be improved to allow this
