### ISSUE TITLE
Mention the support for _repr_html_ on custom scraper doc

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#614]
On the page about custom scrapers (
https://sphinx-gallery.github.io/stable/advanced.html#write-a-custom-image-scraper )

we should add a clear note that supporting the _repr_html_ is the easiest method to control the display of object in sphinx gallery, and that it is the same process that works for other html-base displays, such as jupyter. Maybe it can save some people the work of implementing a scraper.

Suggested by @emmanuelle

**Comment by larsoner** [comment]
Sounds good to me

**Comment by emmanuelle** [comment]
thank you @GaelVaroquaux !

**Comment by GaelVaroquaux** [comment]
🤙
