### ISSUE TITLE
Allow removal of "download jupyter notebook" link

### ISSUE THREAD

**Issue by anntzer** [sphinx-gallery/sphinx-gallery#622]
It would be nice if it was possible to globally remove the "download jupyter notebook" links (e.g. if one only wants to support examples run from the command-line).

**Comment by larsoner** [comment]
Can you just add something like this to your CSS overrides:
```
div.sphx-glr-download {
  display: none;
}
```
?

**Comment by GaelVaroquaux** [comment]
> div.sphx-glr-download {
>   display: none;
> }

I think that this hides both downloads

**Comment by larsoner** [comment]
Ahh yes it would.

Maybe we should just add more specific classes like `sphx-glr-download-python` and `sphx-glr-download-jupyter` in that case.

**Comment by larsoner** [comment]
PR opened in #623
