### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mgeier** [sphinx-gallery/sphinx-gallery#627]
Are there any plans for a new release?

I'd like to release my `nbsphinx` gallery feature (https://github.com/spatialaudio/nbsphinx/pull/392), but this only makes sense with #595 and #601 available in the latest SG release.

But apart from that there seem to by many more improvements in `master` ...

**Comment by lucyleeow** [comment]
@larsoner I could do this by end of this week - I suspect you might have your hands full with MNE release?

**Comment by larsoner** [comment]
Yes please go ahead

**Comment by mgeier** [comment]
Thanks a lot for the release!

Now my gallery feature is ready for review: https://github.com/spatialaudio/nbsphinx/pull/392
