### ISSUE TITLE
Sphinx-Gallery Binder links: environment.yml does not get "installed"

### ISSUE THREAD

**Issue by sappelhoff** [sphinx-gallery/sphinx-gallery#628]
In our mne-bids package we want to generate binder links for each sphinx gallery example, according to the [sphinx gallery binder docs](https://sphinx-gallery.github.io/stable/configuration.html#binder-links).

We followed the docs closely, everything builds without issues, and at a first glance everything seems to work.

**The issue**: the `environment.yml` file that we supply does not seem to get installed ... all packages we think should be there are giving import errors.

Here is the binder spec ([link to conf.py](https://github.com/mne-tools/mne-bids/blob/6a5fff726f52b36e3cb86b6c35a3601b9aa5e146/doc/conf.py#L139-L148)):

```Python

# filepath_prefix='v0.3'
    'binder': {
        # Required keys
        'org': 'mne-tools',
        'repo': 'mne-bids',
        'branch': 'gh-pages',  # noqa: E501 Can be any branch, tag, or commit hash. Use a branch that hosts your docs.
        'binderhub_url': 'https://mybinder.org',  # noqa: E501 Any URL of a binderhub deployment. Must be full URL (e.g. https://mybinder.org).
        'filepath_prefix': filepath_prefix,  # noqa: E501 A prefix to prepend to any filepaths in Binder links.
        'dependencies': [
            './environment.yml',
        ],
```

The html build of our docs is then pushed to a subdirectory on the `gh-pages` branch, see [GitHub view here](https://github.com/mne-tools/mne-bids/tree/gh-pages/v0.3).

As expected, our `environment.yml` got copied to a [binder](https://github.com/mne-tools/mne-bids/blob/gh-pages/v0.3/binder/environment.yml) directory and our notebooks have been nicely built and are in [`/notebooks/auto_examples`](https://github.com/mne-tools/mne-bids/tree/gh-pages/v0.3/notebooks/auto_examples).

For each notebook a link has been inserted, such as this one (which seems correct):

[`https://mybinder.org/v2/gh/mne-tools/mne-bids/gh-pages?filepath=v0.3/notebooks/auto_examples/rename_brainvision_files.ipynb`](https://mybinder.org/v2/gh/mne-tools/mne-bids/gh-pages?filepath=v0.3/notebooks/auto_examples/rename_brainvision_files.ipynb)

clicking on the link opens binder ... everything is fine --> until we try to import things like "matplotlib", which is defined in our supplied [environment.yml](https://github.com/mne-tools/mne-bids/blob/a54f028cde14e2016621a971666de46e688d449a/v0.3/binder/environment.yml#L12) and which thus SHOULD have been installed for binder.

buuut :disappointed:  it's not installed.

Is Binder somehow not finding the `binder/environment.yml` file and thus assuming there is nothing to install?

What's the issue here? How can I solve it?

Feel free to browse our [stable docs](https://mne.tools/mne-bids/stable/auto_examples/rename_brainvision_files.html#sphx-glr-auto-examples-rename-brainvision-files-py) if that helps you find the issue.

**Comment by choldgraf** [comment]
I think the problem is that the docs are being hosted in a sub-directory, and not in the root of the repository. Binder will only be able to detect environment files that are in the root, or in a `binder/` folder in the root :-/

**Comment by sappelhoff** [comment]
Perhaps I should also look into `repo2docker` more. Specifically this sentence from their [docs](https://repo2docker.readthedocs.io/en/latest/config_files.html#configuration-files):

> repo2docker looks for configuration files in the repository being built to determine how to build it.

it'd be really interesting to know *how* repo2docker looks for configuration files exactly :thinking:

**Comment by choldgraf** [comment]
this section in particular is relevant: https://repo2docker.readthedocs.io/en/latest/usage.html#where-to-put-configuration-files

**Comment by sappelhoff** [comment]
I see, thanks. Do you think it'd be a reasonable feature request to `repo2docker` then to explicitly tell it where to look for the configuration file? ... and then of course pass that behavior down to binder and eventually sphinx-gallery?

Or do you see another way how I can get my wanted/needed behavior?

The basic issue is that each of my subdirectories needs different dependencies.

The hack that I'll do for now will be to supply the dependencies working with the "stable" release. But that will of course (potentially) break previous docs and/or the dev docs examples.

**Comment by choldgraf** [comment]
It's actually a fairly commonly-requested feature - see here for the latest conversation around it: https://github.com/jupyter/repo2docker/issues/853

**Comment by sappelhoff** [comment]
Okay, that's helpful and it even provides a solution, albeit effortful and complicated to implement.

Thanks a lot @choldgraf

**Comment by choldgraf** [comment]
no problem! yep, currently it is just workarounds, sorry that there's not an easy / straightforward solution :-/
