### ISSUE TITLE
TypeError when creating links from gallery to documentation

### ISSUE THREAD

**Issue by david-zwicker** [sphinx-gallery/sphinx-gallery#634]
I'm using the excellent sphinx-gallery extension in my python project [`py-pde`](https://github.com/zwicker-group/py-pde). The [documentation is hosted on readthedocs](https://py-pde.readthedocs.io) and things worked perfectly until very recently. Since a few days every documentation build fails with the following traceback:

```
[...]
copying static files... done
copying readthedocs static files... done
copying searchtools... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 3 warnings.

The HTML pages are in _build/html.

Sphinx-gallery successfully executed 0 out of 0 files subselected by:

    gallery_conf["filename_pattern"] = '/'
    gallery_conf["ignore_pattern"]   = '.*movie.*'

after excluding 16 files that had previously been run (based on MD5).

embedding documentation hyperlinks...
embedding documentation hyperlinks for examples_gallery... [  5%] simple.html

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/py-pde/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/py-pde/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 369, in build
    self.emit('build-finished', None)
  File "/home/docs/checkouts/readthedocs.org/user_builds/py-pde/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/py-pde/envs/latest/lib/python3.7/site-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/py-pde/envs/latest/lib/python3.7/site-packages/sphinx_gallery/docs_resolv.py", line 442, in embed_code_links
    _embed_code_links(app, gallery_conf, gallery_dir)
  File "/home/docs/checkouts/readthedocs.org/user_builds/py-pde/envs/latest/lib/python3.7/site-packages/sphinx_gallery/docs_resolv.py", line 340, in _embed_code_links
    for modname in (cobj['module_short'], cobj['module']):
TypeError: string indices must be integers

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/py-pde/envs/latest/lib/python3.7/site-packages/sphinx_gallery/docs_resolv.py", line 340, in _embed_code_links
    for modname in (cobj['module_short'], cobj['module']):
TypeError: string indices must be integers
The full traceback has been saved in /tmp/sphinx-err-osihz662.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

The documentation builds without any problem on my own computer, where I sue Sphinx v2.4.4. Readthedocs reports that it uses Sphinx v1.8.5, which is certainly not the newest but should be sufficient per the sphinx-gallery documentation. Is there anything I can do on my side? Do you require more information?

**Comment by lucyleeow** [comment]
I've seen that error as well and `make clean` (deleting files in `_build` and the generated gallery dirs) before building again worked. Could you see if this works for you?

I avoided looking into it because `_embed_code_links` is complicated but I should look into it now. Maybe @larsoner has an idea of the reason...?

**Comment by david-zwicker** [comment]
Yes, I noticed that the error does not always appear and that it often works when I manually start the build on readthedocs. However, this is less than ideal and it looks like there is a bug deeper in the code.

**Comment by lucyleeow** [comment]
Yes I think it happens when no example files has been changed  - I'll look into it.

**Comment by lucyleeow** [comment]
@david-zwicker Is it possible to obtain the pickle file (ending with `codeobj_pickle`) for `simple.py` (since it failed at this example) for a failing build on readthedocs? It would be in the gallery dir `examples_gallery`.

**Comment by david-zwicker** [comment]
Unfortunately, I don’t have access to the build files. I can only obtain the log file that I sent you.

On 31. Mar 2020, at 15:24, Lucy Liu <notifications@github.com> wrote:

﻿

@david-zwicker<https://github.com/david-zwicker> Is it possible to obtain the pickle file (ending with codeobj_pickle) for simple.py (since it failed at this example) for a failing build on readthedocs? It would be in the gallery dir examples_gallery.

**Comment by lucyleeow** [comment]
I can't seem to replicate the error. It doesn't happen when nothing changes or when only rst files changed but not example files and I can't remember what the circumstances were when I got this error. I suspect it is a problem with the pickle file, thoughts @larsoner ?

**Comment by larsoner** [comment]
From looking at `identify_names` and the code I'm not sure how you could end up in a situation where `cobj` is a string here. I guess that we could add some sanity checks that our data are the right types and skip if they're not. But really this seems less than ideal because we should be able to rely on consistency.

Is it possible that some of these files were produced by an older version of sphinx-gallery? It's possible that at some point we updated what's in the pickled files to be list of dict instead of list of str or something. In that case, being able to do a "clean build" and not run old and new versions of SG would be the recommendation (which seems reasonable and CI platforms should allow doing this sort of thing).

**Comment by lucyleeow** [comment]
> From looking at `identify_names` and the code I'm not sure how you could end up in a situation where `cobj` is a string here.

Exactly.

I've have had the error:
```
  File "/home/lucy/Documents/sphinx-gallery/sphinx_gallery/docs_resolv.py", line 442, in embed_code_links
    _embed_code_links(app, gallery_conf, gallery_dir)
  File "/home/lucy/Documents/sphinx-gallery/sphinx_gallery/docs_resolv.py", line 331, in _embed_code_links
    example_code_obj = pickle.load(fid)
ValueError: unsupported pickle protocol: 5
```
 which I think is due to previously building with an environment with a different Python version (since we use [`pickle.dump(example_code_obj, fid, pickle.HIGHEST_PROTOCOL)`](https://github.com/sphinx-gallery/sphinx-gallery/blob/23f44fdcd6530b8ee7d8b3e153d15448b407b3a6/sphinx_gallery/gen_rst.py#L813). Potentially it is pickling problem though I can't think what kind of problem it could be.

@david-zwicker do you know what doc files had changed between the build working and when it first failed?

**Comment by david-zwicker** [comment]
The documentation fails building almost every single time I push a change to the repository. Building the documentation even fails when I edit the documentations in places that do not use `sphinx-gallery`.

Luckily, I was now able to reproduce the error locally, so I in principle have access to all the files. Here is the traceback from the error in my local environment:

```
# Sphinx version: 2.4.4
# Python version: 3.7.7 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.1
# Last messages:
#   done
#   dumping object inventory...
#   done
#   build succeeded, 1 warning.
#   
#   The HTML pages are in build/html.
#   Sphinx-gallery successfully executed 0 out of 0 files subselected by:

    gallery_conf["filename_pattern"] = '/'
    gallery_conf["ignore_pattern"]   = '.*movie.*'

after excluding 16 files that had previously been run (based on MD5).
#   embedding documentation hyperlinks...
#   embedding documentation hyperlinks for examples_gallery... [  5%] sg_execution_times.html
#   embedding documentation hyperlinks for examples_gallery... [ 11%] custom_pde_1d.html
# Loaded extensions:
#   sphinx.ext.mathjax (2.4.4) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (2.4.4) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (2.4.4) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (2.4.4) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.intersphinx (2.4.4) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.coverage (2.4.4) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.viewcode (2.4.4) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.napoleon (2.4.4) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx_simplify_typehints (unknown version) from ./sphinx_simplify_typehints.py
#   sphinx.ext.graphviz (2.4.4) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx/ext/graphviz.py
#   sphinx.ext.inheritance_diagram (2.4.4) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx/ext/inheritance_diagram.py
#   sphinx_gallery.gen_gallery (0.6.0) from /Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx_gallery/gen_gallery.py
Traceback (most recent call last):
  File "/Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx/application.py", line 384, in build
    self.events.emit('build-finished', None)
  File "/Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx/events.py", line 99, in emit
    results.append(callback(self.app, *args))
  File "/Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx_gallery/docs_resolv.py", line 442, in embed_code_links
    _embed_code_links(app, gallery_conf, gallery_dir)
  File "/Users/dzwicker/.local/share/virtualenvs/env-nfwgTljw/lib/python3.7/site-packages/sphinx_gallery/docs_resolv.py", line 340, in _embed_code_links
    for modname in (cobj['module_short'], cobj['module']):
TypeError: string indices must be integers
```

I attached a copy of the `simple_codeobj.pickle` file. Is there anything else that you're interested in?

**Comment by lucyleeow** [comment]
Hmm I can't see the `simple_codeobj.pickle`  file?

**Comment by david-zwicker** [comment]
I attached it to the email, but it didn't go through :) Here is a zipped version, since GitHub does not like the pickle extension:

[spherical_grid_codeobj.pickle.zip](https://github.com/sphinx-gallery/sphinx-gallery/files/4410975/spherical_grid_codeobj.pickle.zip)

**Comment by larsoner** [comment]
`example_code_obj` should be a dict of list of dict. For some reason yours is a dict of dict (not embedded within a list). I'm not sure how this could happen from the code:

1. `example_code_obj` in the code comes from `identify_names`:

    https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/gen_rst.py#L809-L813

2. `identify_names` only creates dict of list of dict:

    https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/backreferences.py#L195-L231

3. This file simply gets loaded and parsed assuming it's a dict of list of dict:

    https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/docs_resolv.py#L324-L340

Can you try on the branch from #637, which explicitly checks the types in a couple of places?

**Comment by david-zwicker** [comment]
Now I cannot reproduce the error in my local environment anymore :( However, re-triggering the build on readthedocs does now always lead to issues. Somehow things got worse and I don't understand why it does not behave very deterministically.

**Comment by lucyleeow** [comment]
@david-zwicker would you be able to upload the `spherical_grid_codeobj.pickle` file of a build that worked (i.e. you didn't get the error)? Thanks!

**Comment by david-zwicker** [comment]
Please find the archive with two codeobj.pickle files of a (local) build that worked without problems:

[codeobj_pickle.zip](https://github.com/sphinx-gallery/sphinx-gallery/files/4414196/codeobj_pickle.zip)

**Comment by david-zwicker** [comment]
Sorry, the previous file was wrong. I noticed that I now run into trouble of creating the gallery. I managed to get pickle files for both a working and a non-working situation:

[codeobj_pickle_notworking.zip](https://github.com/sphinx-gallery/sphinx-gallery/files/4414234/codeobj_pickle_notworking.zip)
[codeobj_pickle_working.zip](https://github.com/sphinx-gallery/sphinx-gallery/files/4414235/codeobj_pickle_working.zip)

**Comment by lucyleeow** [comment]
The pickle objects that are failing were created by Sphinx-Gallery < v0.5.0, as suggested by @larsoner.
Example old/not working `example_code_obj`:
```
             ('grid',
              {'name': 'UnitGrid',
               'module': 'pde.grids.cartesian',
               'module_short': 'pde'}),
```
Example new/working `example_code_obj`:
```
             ('grid',
              [{'name': 'UnitGrid',
                'module': 'pde.grids.cartesian',
                'module_short': 'pde',
                'is_class': False},
               {'name': 'UnitGrid',
                'module': 'pde.grids',
                'module_short': 'pde',
                'is_class': False},
               {'name': 'UnitGrid',
                'module': 'pde',
                'module_short': 'pde',
                'is_class': False}]),
```
Prior to v0.5.0, `example_code_obj` did not include `is_class`, was a dict of dict and did not loop through all possible module paths.

If no changes were made to *any* of the example files, I think no new pickle object would be created for that example ([`generate_file_rst`](https://github.com/sphinx-gallery/sphinx-gallery/blob/acffdaa9c1fe4581e917fe3fc93f11d5655a8f26/sphinx_gallery/gen_rst.py#L720) would just return `intro, (0, 0)`) and SG would try to read the old pickle file in `_embed_code_links` [here](https://github.com/sphinx-gallery/sphinx-gallery/blob/acffdaa9c1fe4581e917fe3fc93f11d5655a8f26/sphinx_gallery/docs_resolv.py#L330) - resulting in the error. In the error given above no changes were made to any example files:
```
Sphinx-gallery successfully executed 0 out of 0 files subselected by:

    gallery_conf["filename_pattern"] = '/'
    gallery_conf["ignore_pattern"]   = '.*movie.*'

after excluding 16 files that had previously been run (based on MD5).
```
I am not sure how readthedocs works so I don't know if this can explain why it is consistently failing. If you have reset it, does it delete the gallery dir (pickle) files? Is it possible that some of the pickle files were made by an older version of Sphinx-Gallery? Locally, is it possible that you have have an older version of Sphinx-Gallery or had previously used an older version?

@larsoner whats the best way to add a check for this? Maybe in [`generate_file_rst`](https://github.com/sphinx-gallery/sphinx-gallery/blob/acffdaa9c1fe4581e917fe3fc93f11d5655a8f26/sphinx_gallery/gen_rst.py#L720) get SG to run just `identify_names` if md5sum is the same but pickle is old (is a dict of dict instead of dict list dict)?

**Comment by david-zwicker** [comment]
I don't know how readthedocs works internally, but I also obtained this error locally after deleting all files generated by the `sphinx-gallery` and without updating the package.

However, if it is a problem with different versions, would it be possible to accept the old format for a while in the newer versions of `sphinx-gallery`?

**Comment by lucyleeow** [comment]
I think a better solution would be to create new pickle files - there was a lot done to make sure backreference links work correctly (see https://github.com/sphinx-gallery/sphinx-gallery/issues/587). Though considering 

> I also obtained this error locally after deleting all files generated by the `sphinx-gallery` and without updating the package.

I'm not certain this is the problem. What version of sphinx-gallery are you using locally?

**Comment by david-zwicker** [comment]
I use version 0.5.0. However, I cannot reproduce the error consistently. The last few times, creating the documentation locally worked without any problems.

**Comment by lucyleeow** [comment]
Yes that part is confusing as well. The 'not working' pickle objects really do look like the older version of `example_code_obj` but I can't understand why this would happen and non-deterministically as well...

**Comment by larsoner** [comment]
> I can't understand why this would happen and non-deterministically as well...

Do you have more than one Python version on your system? Could the Python paths get messed with when you change things? What I would do is add something like this to `conf.py`:
```
from distutils.version import LooseVersion
import sphinx_gallery
if LooseVersion(sphinx_gallery.__version__) < LooseVersion('0.6'):
    raise RuntimeError('sphinx-gallery is too old, got version %s but need 0.6'
                       % (sphinx_gallery.__version__,))
```
0.6 is out now so I'd upgrade everything to that.

**Comment by lucyleeow** [comment]
But if @david-zwicker deleted *all* the build outputs and built again -  he shouldn't get the error as we would not expect sphinx-gallery to produce the older version of `example_code_obj` but at the same time 'expect' the newer version to be read in.

**Comment by lucyleeow** [comment]
Does your `make clean` delete the gallery dirs as well?

**Comment by david-zwicker** [comment]
I actually didn’t use `make clean` but simply removed the folder `docs/source/examples_gallery`.

**Comment by david-zwicker** [comment]
I updated my codebase so it now uses version 0.6 or higher of `sphinx-gallery` and I changed all examples slightly, so they would be regenerated. Readthedocs compiled everything without problems and the results look perfect. I'm going to monitor the situation and see whether I run into problems in the future!

**Comment by larsoner** [comment]
Okay we'll close for now but feel free to reopen if it crops back up. Hopefully it's smooth sailing from here!
