### ISSUE TITLE
Allow pathlib.Path to backreferences_dir option

### ISSUE THREAD

**Issue by dstansby** [sphinx-gallery/sphinx-gallery#635]
https://github.com/sphinx-gallery/sphinx-gallery/pull/571 checks that `backreferences_dir` is either `None` or `str`. It would be nice to allow `pathlib.Path` objects too.

**Comment by lucyleeow** [comment]
That sounds reasonable and shouldn't break anything. I'll wait a while to see if there are any objections and if not I'll implement!

**Comment by choldgraf** [comment]
+1 to supporting pathlib-like objects 👍

**Comment by dstansby** [comment]
Thanks for the quick response!
