### ISSUE TITLE
How do I best cite sphinx-gallery?

### ISSUE THREAD

**Issue by arokem** [sphinx-gallery/sphinx-gallery#639]
I would like to cite sphinx-gallery in a paper that I am writing about (scientific) software that uses sphinx-gallery for automated examples. Is there a standard way to cite the software? Is there a Zenodo deposit of sphinx-gallery? I couldn't find one. 

Thank you, as always, for the excellent work!

**Comment by larsoner** [comment]
I'm fine with adding Zenodo integration and then cutting a 0.6.1 release so a DOI gets created (or even doing it manually for 0.6 somehow). @lucyleeow WDYT?

**Comment by lucyleeow** [comment]
Sounds good to me. I'm not familiar with Zenodo, do you have time to do this @larsoner? If not I can look into it.

**Comment by larsoner** [comment]
I've added Zenodo integration, now we need to release a new version for Zenodo to pick it up. I say we change the version in `master` to 0.6.1, cut a 0.6.1 release, then go back to 0.7.dev0. @lucyleeow are you up for doing this?

**Comment by lucyleeow** [comment]
Is it the same procedure as for minor/major release? I've done a patch release before but for that project a branch was created for each release (e.g., branch 0.5.0) and the commit of interest was added to that branch via `git cherry pick`, then patch pushed to pypi.

**Comment by lucyleeow** [comment]
Nevermind, I see it is the same procedure as minor/major - doing it now!

**Comment by lucyleeow** [comment]
I think this can be closed now! Thanks @larsoner
