### ISSUE TITLE
css not included in wheels?

### ISSUE THREAD

**Issue by richardliaw** [sphinx-gallery/sphinx-gallery#644]
Hi, 

I'm seeing a `gallery-dataframe.css` and `gallery-binder.css` not found error on my docs. It looks like `_static` only contains:
```
broken_example.png gallery.css        no_image.png
```
while on master the above css files are included. 

I think this is due to setup.py not listing all the expected static files to be included in the wheels.

**Comment by lucyleeow** [comment]
Thanks @richardliaw, you're right!

**Comment by larsoner** [comment]
Are you looking into it? Maybe adapt the check-manifest test from MNE (look at the Makefile) to see if it would have caught this?

**Comment by lucyleeow** [comment]
The 2 CSS files aren't included in the package on PyPI. No idea what is causing the `DistutilsExecError` Sphinx error in #645 though...do you know?

Will look into the test.

**Comment by lucyleeow** [comment]
Nevermind it's green now. Will look into adding a test then ping you. Thanks!

**Comment by lucyleeow** [comment]
@larsoner just to clarify - I should be able to write a test that uses [`check-manifest`](https://pypi.org/project/check-manifest/) and fails if there are any files under 'missing from sdist'. Does that sound reasonable?

**Comment by larsoner** [comment]
I would just add it to the Makefile like in MNE and run it in some CI run with `make check-manifest`. It should fail on master (at least because of the CSS problem) and pass on this PR

**Comment by lucyleeow** [comment]
There is no Makefile for sphinx-gallery? Just `doc/Makefile`?

**Comment by lucyleeow** [comment]
I could add it as a step in the release procedures in `maintainers.rst`?

**Comment by larsoner** [comment]
In that case you can just put the equivalent command directly in the Travis run

It's better than doing it at release time because it will immediately flag problems in PRs that create them

I can do it quickly if it's not clear

**Comment by lucyleeow** [comment]
Let me give it a go...
