### ISSUE TITLE
BUG Wrong pandas intersphinx URL

### ISSUE THREAD

**Issue by lucyleeow** [sphinx-gallery/sphinx-gallery#646]
Master is failing due to:
```
Warning, treated as error:

failed to reach any of the inventories with the following issues:

intersphinx inventory 'https://pandas.pydata.org/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://pandas.pydata.org/objects.inv
```
Indeed https://pandas.pydata.org/objects.inv gives 404 error. I think the correct link is: http://pandas.pydata.org/pandas-docs/stable/objects.inv

Will file a Sphinx issue.

**Comment by larsoner** [comment]
> Will file a Sphinx issue.

Why is this an issue with Sphinx? I think we just need to update the URL in `conf.py`

https://github.com/sphinx-gallery/sphinx-gallery/blob/master/doc/conf.py#L309

**Comment by lucyleeow** [comment]
According to [this](https://buildmedia.readthedocs.org/media/pdf/sphobjinv/v.doc/sphobjinv.pdf):

> It is not necessary to locate the objects.inv file before running ; for most Sphinx documentation sets, if you provide a URL to any page in the docs, it will automatically find and use the correct objects.inv

Looking at the [Sphinx doc](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) it says:

> Each target is the base URI of a foreign Sphinx documentation set and can be a local path or an HTTP URI

Our intersphinx mappings for other packages is just the base URL e.g., `'sklearn': ('https://scikit-learn.org/stable', None)`. 
Previous SG builds have used https://pandas.pydata.org/objects.inv without error. Maybe Pandas changed something?

Happy to change the intersphinx mapping and see if it works...but this wouldn't be robust to changes in location of the `objects.inv`.

**Comment by lucyleeow** [comment]
Hmm maybe I should just change to `http://pandas.pydata.org/pandas-docs/stable/` and call it a day. No idea why the current url worked fine previously :woman_shrugging:

**Comment by larsoner** [comment]
> for most Sphinx documentation sets, if you provide a URL to any page in the docs

This is the key part. `pandas.pydata.org` is no longer a Sphinx documentation page, and it's not the Sphinx docs. It's a landing page. The Sphinx docs live elsewhere under a subdirectory, so you have to at least point at that. I don't think that it means that, given a non-Sphinx-generated URL, it will crawl all of its subdirectories to search for `objects.inv` files.

> Our intersphinx mappings for other packages is just the base URL e.g., 'sklearn': ('https://scikit-learn.org/stable

I suspect the comparable base URL in this case would actually be `https://scikit-learn.org`, and I would expect this to also fail if it were also a landing page and not a redirect to `stable`

> No idea why the current url worked fine previously

My guess is that it was formerly a sphinx-generated page, and they changed it to be a landing page with Sphinx docs under a subdirectory

**Comment by lucyleeow** [comment]
Makes sense. Thanks!
