### ISSUE TITLE
Don't put examples output in sphinx-build stdout?

### ISSUE THREAD

**Issue by Titan-C** [sphinx-gallery/sphinx-gallery#65]
I was wondering if it is necessary to put the stdout of the examples in the build as is done. Would it be better to hide it and instead only output those which failed.
Currently I want to debug why some nilearn examples are not building https://github.com/nilearn/nilearn/pull/592 and I notice that in stdout there is no traceback, and in the rendered html example I only get the message that the script didn't compile.

**Comment by agramfort** [comment]
do you mean not show stdout in final pages? I like having them.

**Comment by GaelVaroquaux** [comment]
> do you mean not show stdout in final pages? I like having them.

So do I actually. When an example is very slow, it is good to have them
to show progress.

**Comment by lesteve** [comment]
> I notice that in stdout there is no traceback, and in the rendered html example I only get the message that the script didn't compile.

But the traceback should be in stderr, right ? I am pretty sure at one point you would see the traceback in the example HTML.

**Comment by GaelVaroquaux** [comment]
> But the traceback should be in stderr, right ? I am pretty sure at one point
> you would see the traceback in the example HTML.

That's certainly something that we would like to have.

**Comment by Titan-C** [comment]
> do you mean not show stdout in final pages? I like having them.
>So do I actually. When an example is very slow, it is good to have them
>to show progress.

stdout goes always to the final pages. I was claiming that during the build process you get all the stdout of all the examples in the same terminal and is just a mess of text. So, I think it might be nicer not to show it.
Maybe to show progress put an indicator(that might be to complex and not a priority)

> But the traceback should be in stderr, right ? I am pretty sure at one point
>  you would see the traceback in the example HTML.
> That's certainly something that we would like to have.

The traceback is printed but becomes hard to find among all the other successful stdout of the other examples. Also it might be possible to keep track of which file is failing because now the execution is done by blocks which have no link to the original file besides the stdout claiming before which file got executed(you also loose the line number correspondence)

Finaly, traceback is not printed in the rendered HTML. I'm starting to think that might be useful.

**Comment by lesteve** [comment]
> Finaly, traceback is not printed in the rendered HTML. I'm starting to think that might be useful.

I seem to remember it was the case in nilearn at one point but maybe I just dreamt about it!

**Comment by Titan-C** [comment]
After merging #97 closing this.
The output of a script is written to stdout during build to have the feeling of progress. Errors are written to stderr, and on the rendered example, plus a summary at the end with the traceback.
