### ISSUE TITLE
thumbnails cause heavy gallery pages and long loading time

### ISSUE THREAD

**Issue by sciunto** [sphinx-gallery/sphinx-gallery#655]
I would like to start a discussion regarding the loading time of galleries.

I opened here a [PR for scikit-image](https://github.com/scikit-image/scikit-image/pull/4613) showing that thumbnails are responsible for long loading time and large bandwidth consumption. Comments show that scikit-learn and matplotlib are also affected by this issue.

I made some tests and the mitigation I found on the user side is to reduce slightly the default resolution of the thumbnails. As our galleries are expected to grow, I think that a longer term solution would be appreciated.

I read the sphinx-gallery code and saw that you are using your own thumbnail generator, relaying on pillow. So far, thumbnails are saved in png (because our plots with matplotlib are so), which is particularly good for rendering edges and fonts. The drawback is the file size as explained above. I made some tests with pillow and I couldn't reach better performances while keeping a png format.

Have you ever considered to switch to jpg? Jpg has some advantages such as a good compression level (with loss) and also [progressive loading](https://www.infoq.com/news/2019/09/lazy-loading-http-range-requests/). I would like also to know whether svg could provide better performances for plots. 

I'm not a master in web optimization, so I'm open to other opinions.
Thank you!

CC @tacaswell @emmanuelle

**Comment by GaelVaroquaux** [comment]
jpeg tend to give really muddy images.

The best way to solve this would be to use optipng, if installed. optipng
typically gives a 2x size benefit on png images without loosing any
quality. The drawback is that it takes some time to run, and as a
consequence, we stopped using it in scikit-learn. However, with some
logic in sphinx-gallery, we could run it only on the newly-generated
images.

**Comment by larsoner** [comment]
We should indeed do `optpng`. We should also just check if `optimize=True` [in Pillow](https://pillow.readthedocs.io/en/5.1.x/handbook/image-file-formats.html) would do the same thing.

But even 2x might not be enough for large galleries, so I'm okay with opt-in JPEG behavior. I've noticed slow load times for very large galleries, too, so I might even use such a feature.

@sciunto would you be up for implementing it? Maybe something the API could be a str or tuple:

- `str`: `thumbnail_format = 'png' | 'jpeg'`, or
- `tuple`: `(format, kwargs)` like `thumbnail_format = ('jpg', dict(quality=80))`, where `kwargs` get passed to [pillow](https://pillow.readthedocs.io/en/5.1.x/handbook/image-file-formats.html#id13)

That should

**Comment by choldgraf** [comment]
Rather than modifying the pngs themselves, could we recommend best practices for lazy loading images? Eg https://www.sitepoint.com/five-techniques-lazy-load-images-website-performance/

**Comment by sciunto** [comment]
Quick reply. I tried `optimize=True` in pillow, no significant effect.

**Comment by GaelVaroquaux** [comment]
> Quick reply. I tried optimize=True in pillow, no significant effect.

Try optipng. It can have a bigger impact than jpg.

**Comment by larsoner** [comment]
optipng PR up at #656
