### ISSUE TITLE
Add whats_new/CHANGES file

### ISSUE THREAD

**Issue by lesteve** [sphinx-gallery/sphinx-gallery#67]
to list main changes in new releases.

From #66:

> Do a CHANGES.txt file and 'include' it somewhere in the docs. You can see how joblib does it for instance.

Maybe we want to do something similar as scikit-learn/nilearn and have a doc/whats_new.rst + include the rst in the doc somewhere.

**Comment by lesteve** [comment]
For the record joblib use a CHANGES.rst in the root folder of the project and then copies it into doc in doc/conf.py. I would say the doc/whats_new.rst solution seems simpler.

**Comment by jnothman** [comment]
What's new is a bit out of hand as a single file anyway... we could make a
file for each version and then simlink the dev one to CHANGES... except
Windows.

**Comment by lesteve** [comment]
Personally I would go for the single-file solution for now and revisit when it starts being an issue.

**Comment by jnothman** [comment]
Sorry, got confused, thought this was talking about scikit-learn!

**Comment by lesteve** [comment]
Yeah that's what I gathered too :-).

**Comment by Titan-C** [comment]
I would also use single file and put it in the root folder. Sphinx can import it in the same way we do now with the readme file

**Comment by lesteve** [comment]
> Sphinx can import it in the same way we do now with the readme file

Do you mean by including something with .. like this:

doc/getting_started.rst
```
.. include:: ../README.rst
```

That would work but I am not sure whether it squares up with the best sphinx documentation practices. I would kind of expect all the documentation rsts to be in the `doc` folder. That is probably why joblib does a copy of CHANGES.rst into doc/CHANGES.rst in doc/conf.py.

**Comment by Titan-C** [comment]
close with #79
