### ISSUE TITLE
Support for GPU memory logging

### ISSUE THREAD

**Issue by pmeier** [sphinx-gallery/sphinx-gallery#671]
The examples I'm building are mostly run on a GPU. Thus the memory recorded in the built does not reflect the reality. Is it possible to define a custom "`memory_logger`"?

If I understand I need to replace

https://github.com/sphinx-gallery/sphinx-gallery/blob/f0b505824b02a2725e6fa825caab64987ce278cd/sphinx_gallery/gen_rst.py#L465-L486

with my custom profiler. As far as I see this currently not possible since this is hard coded into the config:

https://github.com/sphinx-gallery/sphinx-gallery/blob/f0b505824b02a2725e6fa825caab64987ce278cd/sphinx_gallery/gen_gallery.py#L130-L138

**Comment by larsoner** [comment]
Indeed it's not currently possible. In theory we could refactor this to allow `show_memory : True | False | callable`, where the `callable` needs to take a single arg (a func to run) and return 1) the memory usage in MiB and 2) the output(s) of the function. This would be pretty easy to support since this is the API of the `memory_usage` function we use internally, so we'd just need to wrap `show_memory : True` to use `partial(memory_usage,  max_usage=True, retval=True, multiprocess=True)` or so.

Would that work for your use case?

**Comment by pmeier** [comment]
Sure, that would be great.

**Comment by larsoner** [comment]
> On a second thought: that would require me to write a memory profiler for the GPU and that is a lot of work I don't have time for.
>
> The framework I'm working with provides me with an easy interface to measure the peak memory usage since the run started. Is this something that could be embedded? 

It seems like what you can provide is just a special case of what the API I've described requires. Your function would just be something like:
```
def get_my_memory(func):
    out = func()
    return [peak_memory_usage()], out
```
And it should do the right thing, no?

**Comment by pmeier** [comment]
Could you elaborate what exactly `func` is here?

**Comment by larsoner** [comment]
it's the thing to be run while profiling, IIRC it's effectively some code block from the script

**Comment by larsoner** [comment]
... for reference, you can see that our internal `_memory_usage` does this:
```

def _memory_usage(func, gallery_conf):
    """Get memory usage of a function call."""
    if gallery_conf['show_memory']:
        from memory_profiler import memory_usage
        assert callable(func)
        mem, out = memory_usage(func, max_usage=True, retval=True,
                                multiprocess=True)
        try:
            mem = mem[0]  # old MP always returned a list
        except TypeError:  # 'float' object is not subscriptable
            pass
    else:
        out = func()
        mem = 0
    return out, mem
```
So the job of your `callable` would be to take a single `func` to run, and needs to return the (peak) memory in MiB found while running it (this is the API contract I'm talking about adding). Hence this sounds like it should work for you, assuming `peak_memory_usage_in_MiB` gets your peak GPU memory usage:
```
def get_my_memory(func):
    out = func()
    return peak_memory_usage_in_MiB(), out
```

Internally in SG we iterate over all code blocks calling `_memory_usage`, and take the max over those to say how much memory was used in a given script.

There is still the issue of how to get the initial memory usage, but we can just assume it's zero if you're using a custom memory getter and that you should adjust for the baseline memory usage yourself somehow (e.g., using a class with a callable).

**Comment by pmeier** [comment]
> Internally in SG we iterate over all code blocks calling `_memory_usage`, and take the max over those to say how much memory was used in a given script.

So basically you determine the memory usage of every `func` and after everything is run you take the maximum to determine the peak usage, correct? If yes, you are indeed right and your proposal should work for me. 

As a sanity check for me: by always returning the peak usage from `get_my_memory` `max(memory_usages) == memory_usages[-1]`, correct?

**Comment by larsoner** [comment]
Yes that should be the case! I'll give a stab at a little refactoring to let you try it out soon
