### ISSUE TITLE
check-manifest causing master to fail

### ISSUE THREAD

**Issue by lucyleeow** [sphinx-gallery/sphinx-gallery#675]
Master failing due to:

```
lists of files in version control and sdist do not match!

missing from VCS:

  sphinx_gallery/tests/testconfs/src/__pycache__/plot_1.cpython-37-pytest-5.3.5.pyc

  sphinx_gallery/tests/testconfs/src/__pycache__/plot_2.cpython-37-pytest-5.3.5.pyc

  sphinx_gallery/tests/testconfs/src/__pycache__/plot_3.cpython-37-pytest-5.3.5.pyc
```
I didn't realise these files are in sdist...??

**Comment by choldgraf** [comment]
yeah the same errors are popping up in your PR #673 as well...that's what's causing travis to be unhappy

**Comment by lucyleeow** [comment]
Locally I don't get this result from `check-manifest` and these files aren't even in the git repo..?

**Comment by larsoner** [comment]
check-manifest changed how `ignore` is handled, can you see if updating it fixes things? I had to do this in MNE

https://github.com/mne-tools/mne-python/pull/7722
