### ISSUE TITLE
Searching in docs v0.6.2 stable does not work

### ISSUE THREAD

**Issue by jankrepl** [sphinx-gallery/sphinx-gallery#689]
In the current [**stable** 0.6.2 docs](https://sphinx-gallery.github.io/stable/index.html) searching just yields `Searching...` but never actually shows results.

Switching to [**dev** 0.7.0.dev0](https://sphinx-gallery.github.io/dev/) makes it work

**Comment by lucyleeow** [comment]
Indeed. It works on the locally built docs and in the artifact from the last PR (https://1550-25860190-gh.circle-artifacts.com/0/rtd_html/index.html). Any idea @larsoner ?

**Comment by larsoner** [comment]
Looking at the dev console when searching `stable` I see:
```
jquery.js:2 Uncaught TypeError: Search.loadIndex is not a function
    at HTMLDocument.<anonymous> (search.html?q=sphinx&check_keywords=yes&area=default:232)
    at j (jquery.js:2)
    at k (jquery.js:2)
```
Then some more googling:

https://github.com/sphinx-doc/sphinx/issues/6244

So rebuilding should fix it. But really we could just release 0.7.0 because of animations, and maybe also once https://github.com/sphinx-gallery/sphinx-gallery/pull/656 is in

**Comment by lucyleeow** [comment]
> But really we could just release 0.7.0 because of animations, and maybe also once #656 is in

Sounds good, animations are big! Should I/we nag Gael about #656 or get someone else to review?

(Also master is broken with sphinx-dev build, seems to be something wrong with imports as `plot_future_imports_broken.py` isn't failing as it should and `plot_numpy_matplotlib.py` failing at `import matplotlib` line)

**Comment by lucyleeow** [comment]
Fixed with new release
