### ISSUE TITLE
DOC Builder types clarification

### ISSUE THREAD

**Issue by lucyleeow** [sphinx-gallery/sphinx-gallery#697]
Our doc intro says:

> Sphinx-Gallery is a Sphinx extension that builds an HTML gallery of examples from any set of Python scripts.

but technically once we make the .rst files Sphinx can convert them to many different outputs? Should we clarify?

**Comment by larsoner** [comment]
Other builders are not heavily tested AFAIK and in some places we have `.. raw:: html`, so I think some additional testing is needed if we want to claim that it's good for other builders

**Comment by lucyleeow** [comment]
Hmm good point. I should make some doc amendments then.
