### ISSUE TITLE
Hyperlinks in code don't work in current use of autosummary

### ISSUE THREAD

**Issue by Titan-C** [sphinx-gallery/sphinx-gallery#70]
The sphinx extension autosummary was incorporated to automatically generate the in-documentation galleries that display which examples use a specific function.

But this causes that the hyperlinks in code stop working. Aparently in the current inplementation of the autosummary no reference nodes are being created for each documented function. Thus sphinx-gallery can't find the documentation of the functions.

**Comment by lesteve** [comment]
Not sure I follow you completely.

Are you talking about this example: http://sphinx-gallery.readthedocs.org/en/latest/auto_examples/plot_function_identifier.html#sphx-glr-auto-examples-plot-function-identifier-py

```python
names = spback.identify_names(file_code)
```

The problem being that identify_names doesn't show up as a link?

**Comment by Titan-C** [comment]
Yes that is my current problem.

**Comment by Titan-C** [comment]
Well this issue was a sample size of one. Testing on nilearn and my own repositories. I notice that not all functions/classes are captured. On what it depends to have the function/class documentation in the JSON file that sphinx generates and that the gallery uses to resolve the links is beyond my understanding. There are some function links that will be missing from our modules or from the externals (numpy, scipy, matplotlib, scikit-learn).

**Comment by Titan-C** [comment]
I reference this to #113 because is on the issues on understanding what sphinx resolves as function documentation.

**Comment by Titan-C** [comment]
Closing this. After merging #214, sphinx-gallery does recognize our autosummary generated documentation for sphinx-gallery and the trouble function `spback.indentify_names` has a link to the docs
