### ISSUE TITLE
filename_pattern still doesn't work all that great for working on one tutorial

### ISSUE THREAD

**Issue by ezyang** [sphinx-gallery/sphinx-gallery#721]
Previously in #321 (fixed by #346) a user complained about the experience for running sphinx-gallery on one file. The docs were updated with documentation on `filename_pattern` and a new feature `ignore_pattern`. These seem like inverses but they are not: `filename_pattern` controls whether or not you execute the script (but doesn't affect if sphinx-gallery will parse and generate the file), while `ignore_pattern` controls whether or not you parse and generate the file at all.

The parsing and generating process can still take a considerable amount of time doing useless work (several seconds in pytorch/tutorial repository); to make matters worse, whenever the value of `filename_pattern` changes, Sphinx interprets this to mean that it needs to do a full rebuild of all of the documentation which means I also have to sit through the Sphinx doc generation process too.

It would be desirable when working on a single tutorial to bypasses parsing entirely for ALL other gallery files. Although it seems like `filename_pattern` should do this, it does not (and it has *zero* effect if you are building with  plot_gallery=0). This problem can be worked around  obliquely using a negative lookahead assert:

```
    'ignore_pattern': r'/(?!static_quantization_tutorial)[^/]+$',
```

to "invert" the sense of `ignore_pattern`, but in my opinion it would be much better to just change the default of `filename_pattern` to mean "skip parsing AND executing" (or introduce a new configuration directive for this case.) Furthermore, it would be preferable if these settings were kept in a separate configuration value than `sphinx_gallery_conf`  so that we can set a more appropriate `'rebuild'` parameter on them.

**Comment by larsoner** [comment]
> The parsing and generating process can still take a considerable amount of time doing useless work (several seconds in pytorch/tutorial repository)

I guess you mean "useless in your case", because in general it's not useless (see below about cross-linking) or it's fast (just md5sum). But really a few seconds is typically very small time-wise relative to even a single example build, so I'm not sure we should work too hard to optimize this further...

> whenever the value of filename_pattern changes, Sphinx interprets this to mean that it needs to do a full rebuild of all of the documentation which means I also have to sit through the Sphinx doc generation process too.

To build a single example, I usually do:
```
sphinx_build ... -D sphinx_gallery_conf.filename_pattern=...
```
and this does not cause a full rebuild (just double checked, it only rebuild the example I named plus the cross-ref API pages that doing so would change). Would this work for you?

In practice it's actually implemented by doing:
```
PATTERN=whatever_example make html-pattern
```
with a Makefile target
```
$(SPHINXBUILD) -D plot_gallery=1 -D sphinx_gallery_conf.filename_pattern=$(PATTERN) -b html $(ALLSPHINXOPTS) _build/html
```

> it would be much better to just change the default of filename_pattern to mean "skip parsing AND executing" 

Even the ones that it does not run get parsed for variables and cross-linking (they just don't get live-object inspection), so this would be a bad backward compat break.

> or introduce a new configuration directive for this case

Let's first see if the PATTERN idea will suffice before reworking the API

> hese settings were kept in a separate configuration value than sphinx_gallery_conf so that we can set a more appropriate 'rebuild' parameter on them.

I must be missing something -- how would having it in a different `conf.py` variable help?

**Comment by ezyang** [comment]
I guess I should give you a repro. The very big and annoying repro is:

```
# you probably want a fresh conda environment / venv for this
git clone https://github.com/pytorch/tutorials.git
cd tutorials
pip install -r requirements.txt
sphinx-build -D plot_gallery=0 -b html  "." "_build/html"
sphinx-build -D plot_gallery=0 -b html  "." "_build/html"
```

On the second build I observe 

```
generating gallery for beginner... [100%] chatbot_tutorial.py                                           
generating gallery for beginner/blitz... [100%] cifar10_tutorial.py                                     
generating gallery for beginner/examples_autograd... [100%] tf_two_layer_net.py                         
generating gallery for beginner/examples_nn... [100%] dynamic_net.py                                    
generating gallery for beginner/examples_tensor... [100%] two_layer_net_tensor.py                       
generating gallery for beginner/former_torchies... [100%] nnft_tutorial.py                              
generating gallery for beginner/hybrid_frontend... [100%] learning_hybrid_frontend_through_example_tutorial.py
generating gallery for beginner/nlp... [100%] advanced_tutorial.py                                      
generating gallery for intermediate... [100%] seq2seq_translation_tutorial.py                           
generating gallery for advanced... [100%] static_quantization_tutorial.py                               
generating gallery for recipes/recipes... [ 38%] warmstarting_model_using_parameters_from_a_different_mogenerating gallery for recipes/recipes... [100%] custom_dataset_transforms_loader.py   
```

again.

I can work on a minimal repro if that would help.

> Even the ones that it does not run get parsed for variables and cross-linking (they just don't get live-object inspection), so this would be a bad backward compat break.

Fair enough. New config parameter then.

> I must be missing something -- how would having it in a different conf.py variable help?

It's so you can do config without html https://www.sphinx-doc.org/en/master/_modules/sphinx/application.html#Sphinx.add_config_value

**Comment by larsoner** [comment]
> On the second build I observe ... again.

I did not use `requirements.txt` because it requires an old sphinx-gallery, and we should be looking at latest `master` performance. I just `pip install pytorch_sphinx_theme pytorch`, fixed `conf.py` to have `backreferences_dir=None` then ran:
```
$ time sphinx-build -D plot_gallery=0 -b html  "." "_build/html"
```
But this hits an error:
```
TypeError: _thumbnail_div() missing 2 required positional arguments: 'snippet' and 'title'
```
Using a private function is a no-no, we should really make it easier to do whatever it is you are actually trying to do here...

But in any case, fixing that, I then get ~8.5 sec for the first build, and ~2.5 sec for the second build:
```
$ time sphinx-build -D plot_gallery=0 -b html  "." "_build/html"
...
real	0m8.927s
user	0m8.638s
sys	0m0.214s
$ time sphinx-build -D plot_gallery=0 -b html  "." "_build/html"
...
real	0m2.626s
user	0m2.379s
sys	0m0.191s
```
This seems okay to me already, even though you do see the lines printed they go by quite quickly.

> It's so you can do config without html ...

Let's see if the PATTERN usage is enough already before trying to break apart our config. Or it's possible that you can just set `'sphinx_gallery_conf.filename_pattern'` already, like you can from the command line.

**Comment by ezyang** [comment]
On my machine, the difference between parsing and not parsing is:

```
# With generating gallery, `make html-noplot`
real	0m6.471s
user	0m5.959s
sys	0m0.464s

# Without generating gallery `make html-noplot`
real	0m2.771s
user	0m2.377s
sys	0m0.345s
```

That's an over 50% reduction, so I find it quite noticeable. This is on sphinx-gallery 0.3.1. As you suggest that the performance is master based, I tried upgrading to master. Now the timing is:

```
# With generating gallery
real	0m3.842s
user	0m3.954s
sys	0m0.640s

# Without
real	0m2.887s
user	0m2.480s
sys	0m0.374s
```

So the difference is much less pronounced, though it's still a 25% speedup (which ostensibly will get larger the more gallery python files you have. You can't beat doin nothing!)

Appendix: the patch I applied to make it work on master was:

```
diff --git a/conf.py b/conf.py
index 93cba840..b03597b3 100644
--- a/conf.py
+++ b/conf.py
@@ -65,7 +65,6 @@ sphinx_gallery_conf = {
     'examples_dirs': ['beginner_source', 'intermediate_source',
                       'advanced_source', 'recipes_source'],
     'gallery_dirs': ['beginner', 'intermediate', 'advanced', 'recipes'],
-    'backreferences_dir': False
 }
 
 if os.getenv('GALLERY_PATTERN'):
diff --git a/custom_directives.py b/custom_directives.py
index cfb11744..191dbcd2 100644
--- a/custom_directives.py
+++ b/custom_directives.py
@@ -91,8 +91,9 @@ class GalleryItemDirective(Directive):
                 _, blocks = sphinx_gallery.gen_rst.split_code_and_text_blocks(abs_fname)
                 intro, _ = sphinx_gallery.gen_rst.extract_intro_and_title(abs_fname, blocks[0][1])
 
-            thumbnail_rst = sphinx_gallery.backreferences._thumbnail_div(
-                dirname, basename, intro)
+            thumbnail_rst = ''
+            #sphinx_gallery.backreferences._thumbnail_div(
+            #    dirname, basename, intro)
 
             if 'figure' in self.options:
                 rel_figname, figname = env.relfn2path(self.options['figure'])
```

I didn't write most of the code here, so there is probably something very naughty going on here, I'll let the people who wrote it know :)

**Comment by larsoner** [comment]
True, but I really don't see 2s as a bottleneck. Even with many more examples (I work on a repo with hundreds) it's only effectively the bottleneck when modifying a single non-example rst file, and even then it's not so noticeable. If rather not need with the API to optimize this further, and would rather focus on usability issues that people are more affected by.

**Comment by ezyang** [comment]
Yeah, I guess it depends on workflow style. I'm one of those people who keeps mashing build to see what the html docs look like :)

**Comment by lucyleeow** [comment]
Closing this as I don't think there is much to be done here but @ezyang let me know if you want to re-open.
