### ISSUE TITLE
Q: how to have a couple of images with `bbox_inches='tight'`.

### ISSUE THREAD

**Issue by jklymak** [sphinx-gallery/sphinx-gallery#726]
More of a question than an issue.  Sorry if this is inappropriate place for this - feel free to close if you have a better channel. 

In https://matplotlib.org/tutorials/intermediate/constrainedlayout_guide.html#sphx-glr-tutorials-intermediate-constrainedlayout-guide-py I want to show the effect of both using `bbox_inches='tight'` and not using it.  Is it possible to make sphinx gallery do this?  

I've tried saving the file to `../../doc/_static/constrained_layout/` but circleCI doesn't like that, claiming there is no such directory (it works fine on a local build).  The simplest solution is to just comment out the save, and put the generated file in static and commit the file that way, but then if constrained layout changes, someone needs to remember to regenerate the static file.  

So, is there any way to get the tutorial to generate the file and switch the kwargs for `savefig`?

Thanks for any pointers...

**Comment by lucyleeow** [comment]
It might be possible to alter (your local) sphinx-gallery [matplotlib scraper code](https://github.com/sphinx-gallery/sphinx-gallery/blob/358c4c02834bc307d935db608aee0ad2a9300526/sphinx_gallery/scrapers.py#L86) to do this. Potentially you could use a specific comment key (more on comment keys [here](https://sphinx-gallery.github.io/stable/configuration.html#removing-config-comments)) to allow you to set the `savefig` arguments the scraper uses when it saves the plot. e.g., the following comment in a code block would add `bbox_inches='tight'` when the scraper is saving the fig.

```
# sphinx_gallery_matplotlib_savefig = bbox_inches: 'tight'
```

For an example of how we currently get file specific 'comment' configuration values see [here](https://github.com/sphinx-gallery/sphinx-gallery/blob/358c4c02834bc307d935db608aee0ad2a9300526/sphinx_gallery/py_source_parser.py#L133).

You can then add the argument when the scraper is saving the fig.

As I type this, maybe this could be a good addition to SG? WDYT @larsoner ?

Alternatively you could try saving the fig to where the scraper saves it - 'gallery_dirs'/images (e.g., `auto_examples/images`). Maybe CI would accept this.

**Comment by jklymak** [comment]
^ yes, something like that would be great!

**Comment by jklymak** [comment]
>Alternatively you could try saving the fig to where the scraper saves it - 'gallery_dirs'/images (e.g., auto_examples/images). Maybe CI would accept this.

Yeah, my problem is understanding what path to put into my `savefig` command.  

We have 
```
sphinx_gallery_conf = {
    'examples_dirs': ['../examples', '../tutorials'],
    'filename_pattern': '^((?!sgskip).)*$',
    'gallery_dirs': ['gallery', 'tutorials'],
    'doc_module': ('matplotlib', 'mpl_toolkits'),
    'reference_url': {
        'matplotlib': None,
        'numpy': 'https://docs.scipy.org/doc/numpy/',
        'scipy': 'https://docs.scipy.org/doc/scipy/reference/',
    },
    'backreferences_dir': 'api/_as_gen',
    'subsection_order': gallery_order.sectionorder,
    'within_subsection_order': gallery_order.subsectionorder,
    'remove_config_comments': True,
    'min_reported_time': 1,
    'thumbnail_size': (320, 224),
    'compress_images': ('thumbnails', 'images'),
    'matplotlib_animations': True,
}
```

This gets run via `make html` from `doc/` (where the conf.py file is).  If I look in `tutorials/intermediate/images` there are all the images created by the tutorial.  However, I cannot get a `savefig` command to put them there directly, presumably because I do not understand what relative path to use.

**Comment by jklymak** [comment]
OK, I figured out a solution.  The tutorial script gets run in place (in our case `../tutorials/intermediate/`), so `_static` is at `../../doc/_static/`.  The file needs to be put in `_static` because static is copied over as-is during the build process.  Like, there may be somewhere else to put it that is also copied over, but I couldn't figure it out.  I don't think there is a robust way to save the figure to the location where the docs will be built.  

These files are then added to `.gitignore` so that they aren't included in the repo.  

```
fig.savefig('../../doc/_static/constrained_layout_1b.png',
             bbox_inches='tight', dpi=100)

 #############################################
 # The saved file looks like:
 #
 # .. image:: /_static/constrained_layout_1b.png
```

This is fine, but a way to pass savefig kwargs to sphinx gallery would be a welcome addition.

**Comment by larsoner** [comment]
Another option would be to add a little custom [PNGScraper](https://sphinx-gallery.github.io/stable/advanced.html#example-2-detecting-image-files-on-disk) to your build, and actually do a `savefig` directly in the example. Seems a bit cleaner to me than messing with `_static` or anything else. You could even make `PNGScraper` only consider looking for files in specific example filenames if you don't want it to be applied everywhere...

**Comment by lucyleeow** [comment]
@larsoner, that is a better option. But would the output have 2 figures, one from the matplotlib scraper and one from the png scraper?

**Comment by jklymak** [comment]
I'm not really grokking the linked solution above to be honest.  I could just copy that code, but I'd have zero idea how to implement it in an example.

**Comment by larsoner** [comment]
> I'm not really grokking the linked solution above to be honest. I could just copy that code, but I'd have zero idea how to implement it in an example.

If the `fig.savefig(...)` command would outputs a PNG file, and the scraper would detect it and add it to the set of images.

> But would the output have 2 figures, one from the matplotlib scraper and one from the png scraper?

This seems fine to me, because in this case the difference is actually informative. But if you really didn't want it, a `plt.close(fig)` after the `fig.savefig` would prevent there from being two images in the output.

**Comment by jklymak** [comment]
> and the scraper would detect it and add it to the set of images.

Sure, I got that, but then how do I display the result in the example?

**Comment by larsoner** [comment]
> Sure, I got that, but then how do I display the result in the example?

You mean when the user runs, or when the gallery builds?

If you want it when the user runs, I would not add any scraper and just do some variant of:
```
fig.savefig(...)
plt.close(fig)
data = imread(...)
plt.imshow(data)
```

If you want it when the docs are built but don't care if the user sees the output when they run the script, I would add the PNG scraper and do:
```
fig.savefig(...)  # <- this will get written to disk; the PNGScraper will see it during sphinx-gallery run and ensure it shows up in the docs in this code block
plt.close(fig)
```

**Comment by lucyleeow** [comment]
@larsoner are you happy for this to be closed? I think your solutions were good.

**Comment by larsoner** [comment]
Fine with me
