### ISSUE TITLE
Binder icon is hardcoded, which causes a loading failure with on some browsers

### ISSUE THREAD

**Issue by sciunto** [sphinx-gallery/sphinx-gallery#735]
See https://github.com/scikit-image/scikit-image/issues/4748

It would be helpful if this line could be changed: https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/binder.py#L109
Because the icon is hosted on a third-party website, browsers with "prevent cross-site tracking" preferences remove the icon.

Thank you!

**Comment by larsoner** [comment]
@choldgraf what should we do here? Maybe include it directly in `sphinx-gallery` repo and add it to builds that use binder?

**Comment by choldgraf** [comment]
That seems reasonable to me, just save the asset as a part of the repository and reference the local version instead of the online one

(I probably don't have time to do this as I am going to be in baby land very soon 😬😬😬😬)

**Comment by lucyleeow** [comment]
@larsoner might do this tomorrow before release.

**Comment by lucyleeow** [comment]
Just to confirm, I'll add the svg to `sphinx_gallery/_static` and change [this line](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/binder.py#L109) to point to the local svg ?

**Comment by larsoner** [comment]
That sounds correct to me
