### ISSUE TITLE
_repr_html_ not shown on RTD

### ISSUE THREAD

**Issue by prisae** [sphinx-gallery/sphinx-gallery#736]
I am a bit puzzled on this, and wondered if anyone has come across the same.

So locally, sphinx-gallery captures my `empymod.Report()`, which is a `_repr_html_`-method:
![Selection_001](https://user-images.githubusercontent.com/8020943/90668216-035e6380-e250-11ea-8f8e-e5dd345eb5d3.png)

but on readthedocs, it doesn't:
![Selection_002](https://user-images.githubusercontent.com/8020943/90668230-08bbae00-e250-11ea-8f98-ad5ed9e4f1d0.png)

Has anyone come across that issue?
The `sphinx=3.2.1` and `sphinx-gallery=0.7.0` versions are the same.

Has anyone come across this?

(The full RTD-build is here: https://readthedocs.org/projects/empymod/builds/11697232/)

(I have not (yet) tested, if this only happens with the last cell or not.)

**Comment by larsoner** [comment]
Which example/URL should have it on https://empymod.readthedocs.io/en/dev/ ?

**Comment by prisae** [comment]
Sorry, missed that. Basically all examples, but the one I show above is
https://empymod.readthedocs.io/en/dev/examples/educational/dipoles_and_loops.html

**Comment by prisae** [comment]
While I wrote the issue I realized that it might be because it is the last cell. So I am currently running a test where I put other cells afterwards. I report as soon as I have the result.

**Comment by prisae** [comment]
Nope. It doesn't work either if it is not the last cell.

**Comment by larsoner** [comment]
I noticed you don't have `backreferences_dir` set. This might be necessary to trigger some global variable inspection. At the very least it should add more links to your generated HTML, which would be nice.

But that wouldn't explain why it works for you locally but not on RTD

**Comment by larsoner** [comment]
Locally with no modifications `make html` does locally embed the HTML report

**Comment by prisae** [comment]
> Locally with no modifications make html does locally embed the HTML report
Exactly

I have never looked at `backreferences_dir`, will do that. Do you know of any docs on RTD that has `_repr_html_`-outputs?

**Comment by sdhiscocks** [comment]
I think this was fixed in #700

**Comment by larsoner** [comment]
Ahh yes, we haven't released since that was merged, @prisae do you want to try a build pip on RTD installing latest master (or locally with 0.7 to confirm the bug)?

**Comment by prisae** [comment]
Nice, will do!

**Comment by prisae** [comment]
Yes, it works like a charm. Thanks for your help @larsoner , and thanks for pointing me to your issue and fix @sdhiscocks , my searching skills failed once more... (Will there be a release soon-ish?)
