### ISSUE TITLE
Add a mode that fails only for rst warnings and does not run examples

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#751]
Idea by @jeromedockes

Have a mode where the examples are built without running the code and the links to images are not inserted. This mode would be used to detect errors in the restructured text without waiting for examples to run, which can take a long time. It is important in such a mode that the links to images are not inserted, because when the examples are not run, the images are not present, and hence they lead to sphinx warnings that drown the important warnings.

@jeromedockes, did I explain well your ideas? @lucyleeow : does this make sense?

**Comment by jeromedockes** [comment]
Yes, thanks @GaelVaroquaux. For example a mode that treats warnings as errors *except* warnings about missing image files. the `-W` switch is very useful, but it requires running the examples because otherwise it stops at the first plot that hasn't been generated. I believe a mode similar to `-W` but compatible with `plot_gallery=0` would be useful. this way in our specific case (nilearn), contributors could quickly check locally that the documentation is correctly formatted. CI could also check this before building the full documentation with the plots -- and for this having a non-zero exit status as provided by `-W` is more convenient than filtering the printed warnings

**Comment by larsoner** [comment]
> This mode would be used to detect errors in the restructured text without waiting for examples to run, which can take a long time.

This can be done already with `sphinx-build ... -Dsphinx_gallery.plot_gallery=0

> It is important in such a mode that the links to images are not inserted, because when the examples are not run, the images are not present, and hence they lead to sphinx warnings that drown the important warnings.

I don't really understand this part. If you have links in your own RST (in examples or even in plain RST in your doc tree somewhere) that link to output images, sphinx-gallery isn't making these links. So it would be weird for sphinx-gallery to fix them.

If on the other hand you're talking about links that sphinx-gallery does create, I've never had a problem with these being wrong even in nitpicky, errors-as-warnings mode with the `-D` line above.

>  For example a mode that treats warnings as errors except warnings about missing image files

This to me sounds like you might want to enhance Sphinx to allow regex ignores, or keep a list in the Sphinx `suppress_warnings` config value.

> -W switch is very useful, but it requires running the examples because otherwise it stops at the first plot that hasn't been generated.

For MNE we use `-nWT --keep-going`, which means "nitpicky, warnings as errors, full traceback, but keep going to the end of the build even if you get a warning-as-error. Then it won't stop.

**Comment by jeromedockes** [comment]
I see, thank you. Indeed in the nilearn documentation there seem to be manually-written links to automatically-generated images, as [here](https://github.com/nilearn/nilearn/blob/master/doc/building_blocks/manual_pipeline.rst#applying-a-mask) .
only some of the warnings we need to ignore are in the list supported by `suppress_warnings` so I think I will open a Sphinx issue about that

**Comment by larsoner** [comment]
A low-effort solution to this is to add a:
```
# sphinx_gallery_minimum_images = 8
```
example line. When not executing an example, sphinx-gallery can put in the default image for all 8 images; when executing an example, it ensures that at least 8 examples are generated.

It shouldn't be too wasteful because hopefully there aren't that many examples that will need this.

**Comment by jeromedockes** [comment]
> A low-effort solution to this is to add a:
> ```
> # sphinx_gallery_minimum_images = 8
> ```
> example line. When not executing an example, sphinx-gallery can put in the default image for all 8 images; when executing an example, it ensures that at least 8 examples are generated.

That would solve our problem indeed!

**Comment by larsoner** [comment]
@lucyleeow do you want to give it a shot?

**Comment by lucyleeow** [comment]
>  When not executing an example, sphinx-gallery can put in the default image for all 8 images; when executing an example, it ensures that at least 8 examples are generated.

@larsoner can you expand on this.Do you mean changing the manually written links in rst to be our stock image. Or to copy over 8x stock images and naming each image file as `sphx_glr_plot_decoding_tutorial_001.png` to `sphx_glr_plot_decoding_tutorial_008.png`. Let me know if I have misunderstood the problem.

**Comment by jeromedockes** [comment]
> @larsoner can you expand on this.Do you mean changing the manually written links in rst to be our stock image. Or to copy over 8x stock images and naming each image file as `sphx_glr_plot_decoding_tutorial_001.png` to `sphx_glr_plot_decoding_tutorial_008.png`. Let me know if I have misunderstood the problem.

IIUC, the second one: copy an image as a placeholder where the generated
plot is supposed to be.

**Comment by larsoner** [comment]
> IIUC, the second one: copy an image as a placeholder where the generated plot is supposed to be.

Yes this is what I mean. That way all the `sphx_glr_*` images are created in the right places and doc linking works. Changing the links to go to the stock image would not help with the problem unfortunately.
