### ISSUE TITLE
Example gallery is down

### ISSUE THREAD

**Issue by stuaxo** [sphinx-gallery/sphinx-gallery#753]
I went to pypi and clicked on "sphinx gallery" in the list "who uses sphinx gallery" and got a 404

404 is here:  https://sphinx-gallery.github.io/auto_examples/index.html

![image](https://user-images.githubusercontent.com/179677/95320195-0a3d4600-0891-11eb-8935-ac02f222b7d6.png)

**Comment by lucyleeow** [comment]
Ah that url is old, it should be: https://sphinx-gallery.github.io/stable/auto_examples/index.html

I'll update it, thanks!
