### ISSUE TITLE
Option to disable note in example header

### ISSUE THREAD

**Issue by josephmure** [sphinx-gallery/sphinx-gallery#757]
Hello! Is there an option to disable the note linking to the download buttons in the example header?

**Comment by larsoner** [comment]
You can override the CSS in your own static CSS file like:
```
div.sphx-glr-download-link-note {
  height: 0px;
  visibility: hidden;
}
```

**Comment by larsoner** [comment]
(solution from https://github.com/mne-tools/mne-python/blob/master/doc/_static/style.css#L240-L244)

**Comment by josephmure** [comment]
Thanks @larsoner! That is exactly what I was looking for.
