### ISSUE TITLE
MNT: Stop using ci-helpers in appveyor.yml

### ISSUE THREAD

**Issue by pllim** [sphinx-gallery/sphinx-gallery#766]
To whom it may concern,

If you are using https://github.com/astropy/ci-helpers in your appveyor.yml , please know that the Astropy project has dropped active development/support for Appveyor CI. If it still works, good for you, because we did not remove the relevant files (yet). But if it ever stops working, we have no plans to fix anything for Appveyor CI. Please consider using native Windows support other CI, e.g., Travis CI (see https://docs.travis-ci.com/user/reference/windows/). We apologize for any inconvenience caused.

If this issue is opened in error or irrelevant to you, feel free to close. Thank you.

xref astropy/ci-helpers#464

**Comment by lucyleeow** [comment]
@larsoner I see we clone `git clone git://github.com/astropy/ci-helpers.git` in `appveyor.yml` but not sure what we use from it...

**Comment by larsoner** [comment]
We should transition to Azure anyway. @lucyleeow do you feel like taking this CI issue? If not, I can do it.

If you want to but don't have much experience, my plan was to start from here:

https://github.com/mne-tools/mne-python/blob/master/azure-pipelines.yml#L156-L254

And just use the `pip` version. (The `conda` one uses the deprecated `appveyor` path.)

**Comment by lucyleeow** [comment]
@larsoner sorry I really don't have much time at the moment. I have some other SG todos on my list already.
