### ISSUE TITLE
Adding an extended README

### ISSUE THREAD

**Issue by jarrodmillman** [sphinx-gallery/sphinx-gallery#771]
NetworkX recently added some gallery examples showing how to use NetworkX with several packages within the geospatial Python ecosystem.  We would like to have an extended description describing several important concepts in geospatial data analysis and the functionality of the various packages used in the examples.  

We were hoping to do something like the following:

`examples/geospatial/README.txt`:

```
Geospatial
----------

The following geospatial examples showcase different ways of performing
network analyses using packages within the geospatial Python ecosystem.
Example spatial files are stored directly in this directory. See
:doc:`extended_description` for more details.
```

With the remainder of the content moved to a new file, e.g. `examples/geospatial/extended_description.rst`:

```
:orphan:

Dependencies
~~~~~~~~~~~~

`GeoPandas <https://geopandas.readthedocs.io/>`__ provides
...
```

That at least makes the additional info readily available (and keeps it tightly coupled to the gallery) without adding all of the text directly to the gallery landing page.

We could move  `examples/geospatial/extended_description.rst` to `doc/extended_description.rst` and then have the following

`examples/geospatial/README.txt`:

```
Geospatial
----------

The following geospatial examples showcase different ways of performing
network analyses using packages within the geospatial Python ecosystem.
Example spatial files are stored directly in this directory. See
`extended_description <../extended_description.html>`_ for more details.
```

However, that is less than ideal for people (like me) who prefer to look at these files from the commandline rather than via html.  Is there a way to include additional text files in the examples directory without having them show up as boxes in the gallery, but still generate html that can be linked to in the gallery?

This is a pattern that we would like to use in several of our gallery sections.  For example, we have a Graphviz section that we would like to link to an extended README talking about Graphviz installation and other issues.  I also suspect this could be useful for other projects.

For more details see: https://github.com/networkx/networkx/pull/4417

**Comment by jarrodmillman** [comment]
I just added
```
mkdir -p auto_examples/geospatial/
cp ../examples/geospatial/extended_description.rst auto_examples/geospatial/
```
to my Makefile before the sphinx-builder call in my ``html`` target.  I am still interested in a cleaner solution.

**Comment by larsoner** [comment]
> to my Makefile before the sphinx-builder call in my html target. I am still interested in a cleaner solution.

I would do it in Python + Sphinx with something like the following in your `conf.py`:
```
def setup(app):
    app.connect('builder-inited', copy_gallery_rst)
    return {'parallel_read_safe': True, 'parallel_write_safe': True, 'version': 0.1}

def copy_gallery_rst(app)
    from_path = op.join(app.srcdir, 'examples')
    to_path = op.join(app.outdir, 'auto_examples')
    for fname in glob.glob(op.join(from_path, '*.rst'):
        shutil.copyfile(fname, op.join(to_path, op.basename(fname)))
```
```

**Comment by lucyleeow** [comment]
I think I'll close this, let me know if anyone thinks it should be re-opened.
