### ISSUE TITLE
Animation not show on Read the Docs

### ISSUE THREAD

**Issue by AntSimi** [sphinx-gallery/sphinx-gallery#772]
Hi,

I am very pleased to used sphinx-gallery.
For several days, i try to have a working animation in py-eddy-tracker documentation on ReadTheDocs.
I have activate animation [here](https://github.com/AntSimi/py-eddy-tracker/blob/40ce202feefa349b65aac0d2d5fe56fad1fc7f82/doc/conf.py#L54) in sphinx gallery options in conf.py.
I use sphinx-gallery 0.8.1 on my computer and on ReadTheDocs, on my computer example produce animation but not on RTD.
Nevertheless a [GIF thumbnails is produce ](https://py-eddy-tracker.readthedocs.io/en/latest/python_module/index.html#polygon-tools), but no [figure and buttons in example to play with](https://py-eddy-tracker.readthedocs.io/en/latest/python_module/14_generic_tools/pet_visvalingam.html#sphx-glr-python-module-14-generic-tools-pet-visvalingam-py).
If you have any suggestion, i will be very happy!

Antoine

**Comment by larsoner** [comment]
I cannot replicate locally with:
```
make html SPHINXOPTS=-Dsphinx_gallery_conf.filename_pattern="pet_visval"
```
I get:
![Screenshot from 2020-12-11 08-37-39](https://user-images.githubusercontent.com/2365790/101909886-2e1c5100-3b8c-11eb-805f-6614bd36d8e7.png)

Does it work for you locally? If so, then it must be something about your RTD doc build setup. I know people have had problems with SG and RTD before, can you search the issues and see if anything helps?

**Comment by sdhiscocks** [comment]
This should be fixed with #748, but looks like not in a release yet. Is another release planned soon @larsoner, as would be good to get this fixed.

**Comment by larsoner** [comment]
Makes sense, @lucyleeow do you have time to push out a release?

**Comment by lucyleeow** [comment]
Will do the release tomorrow. And I'll have some time over christmas to tackle a few other issues.

**Comment by lucyleeow** [comment]
Should be fixed in the new release!
