### ISSUE TITLE
ENH: Check for invalid sphinx_gallery_conf keys

### ISSUE THREAD

**Issue by rossbar** [sphinx-gallery/sphinx-gallery#774]
I made silly error of misspelling `examples_dirs` as `example_dir` in the `sphinx_gallery_conf` dict in the `conf.py` for a project.

The path to my gallery examples was not the default value of `../examples`, so I was confused by the following error:

```
Extension error:
Example directory proj/doc/source/../examples does not have a README file with one of the expected file extensions ['.txt', '.rst']. Please write one to introduce your gallery.
```

Of course, the *real* error was my misspelling. Everything behaves exactly as it should, but I probably would've been able to chase down my error faster if there had been a warning/exception drawing attention to the fact that I had passed an invalid key to the `sphinx_gallery_conf` dict.

**Comment by larsoner** [comment]
Indeed we should check that there are no keys in the dict that we don't support. @rossbar would you be up for adding a check for this to [gen_gallery.py](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/gen_gallery.py#L128-L129)?

**Comment by rossbar** [comment]
Sure, though it may be a couple days before I can get to it. If anyone else wants to take it up in the meantime don't let me block you!
