### ISSUE TITLE
test_rebuild and test_error_messages failing on travis

### ISSUE THREAD

**Issue by lucyleeow** [sphinx-gallery/sphinx-gallery#777]
`test_rebuild` is failing here:
https://github.com/sphinx-gallery/sphinx-gallery/blob/ce5a58cfde1c030364c0bd34b21f2ba00b83896f/sphinx_gallery/tests/test_full.py#L636

when checking that the example `plot_numpy_matplotlib` which we modify above, has a different mtime:
```
sphinx_gallery/tests/test_full.py:387: in _assert_mtimes

    assert np.abs(op.getmtime(orig) - op.getmtime(new)) > 0.1

E   AssertionError: assert 0.0 > 0.1

E    +  where 0.0 = <ufunc 'absolute'>((1607961214.223356 - 1607961214.223356))
```
`test_error_messages` failing here:
```
_ test_error_messages[plot_scraper_broken-.*ValueError.*zero-size array to reduction.*] _

sphinx_gallery/tests/test_full.py:661: in test_error_messages

    assert re.match(want, rst) is not None

E   AssertionError: assert None is not None
```

@larsoner you probably know more about this but otherwise I can take a look next week.

**Comment by larsoner** [comment]
I did not observe this on https://github.com/sphinx-gallery/sphinx-gallery/pull/775 . Sometimes those tests are a bit unreliable, I would try restarting the one that failed

**Comment by lucyleeow** [comment]
Gah it didn't run on #775 because we didn't have enough credits: https://travis-ci.com/github/sphinx-gallery/sphinx-gallery/requests

**Comment by lucyleeow** [comment]
I think we could apply for more credits, or switch e.g., to github actions?

**Comment by larsoner** [comment]
I would just switch to GitHub actions, or maybe easier make a more complete set of Azure runs that encompass what Travis does. Do you want to try @lucyleeow ?

**Comment by lucyleeow** [comment]
I can have a go this weekend. What do you think would be best, GitHub actions or Azure? Both would be of similar difficulty for me (I've fiddled a bit with GitHub actions but never really touched Azure, though we have existing Azure yml to build on).

**Comment by larsoner** [comment]
Azure has better single job restart control and we already have some YAML so let's just do that.

**Comment by lucyleeow** [comment]
Closing as it seems it's due to this test not being reliable in CI
