### ISSUE TITLE
Mayavi example crashes sphinx build - (think it's not tested by Travis)

### ISSUE THREAD

**Issue by emmanuelle** [sphinx-gallery/sphinx-gallery#78]
Hello sphinx-gallery people,

this issue might be not related to sphinx-gallery (but to mayavi instead), so feel free to close it if you think it's not relevant for the project.

I'm using sphinx-gallery master (24a11317ccf8), and I tried to build the doc running ``make html`` inside the ``docs`` folder. 

The build works fine until the mayavi example, that crashes the build
```
plotting code blocks in ../mayavi_examples/plot_3d.py
The program 'sphinx-build' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 55 error_code 2 request_code 154 minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Makefile:62: recipe for target 'html' failed
make: *** [html] Error 1
```
It might be a problem with my installation of Mayavi (but I tried both with mayavi 4.3 packaged by Ubuntu and with mayavi master 4.4.4dev) , since closing a Mayavi figure inside of IPython results in a segmentation fault. Adding 
```
from mayavi.core.engine import Engine
from mayavi import mlab

e = Engine()
e.start()
mlab.set_engine(e)
```
to the script solves the problem for me, since the build is not crashing any more. 

Also, it seems that Travis is not testing the build of mayavi gallery examples (I might be wrong, but a quick search through Travis logs convinced me that it is not tested). This example might be skipped on purpose, but since .travis.yml says "# This environment tests is for mayavi" (https://github.com/sphinx-gallery/sphinx-gallery/blob/master/.travis.yml#L18), I was a bit puzzled.

**Comment by Titan-C** [comment]
> Also, it seems that Travis is not testing the build of mayavi gallery examples (I might be wrong, but a quick search through Travis logs convinced me that it is not tested).

I can confirm this, we are not installing mayavi in the test environment and it is not getting tested.

I fixed the test issue on my branch https://github.com/Titan-C/sphinx-gallery/tree/mayavitest but I just noticed that as travis does not provide an X server, the build fails for mayavi. #56 Only avoid the pop-up of figure in build, but does not fix the need for the X server, like having the Agg matplotlib back end.

Regarding more into this issue. I tested in an anaconda venv with mayavi 4.4.0, and I have no problem running the mayavi example. But sphinx does gives me an error when parsing the examples,  a problem more linked to the pygments and pyface packages that do the syntax highlighting.

**Comment by GaelVaroquaux** [comment]
> I fixed the test issue on my branch https://github.com/Titan-C/sphinx-gallery/
> tree/mayavitest but I just noticed that as travis does not provide an X server,
> the build fails for mayavi. #56 Only avoid the pop-up of figure in build, but
> does not fix the need for the X server, like having the Agg matplotlib back
> end.

You'll need the X virtual frame buffer:
http://docs.enthought.com/mayavi/mayavi/tips.html#rendering-using-the-virtual-framebuffer

**Comment by Titan-C** [comment]
> You'll need the X virtual frame buffer:

Thank you. To get it to work in travis is a bit different, but now is done and the travis environment is tested. The mayavi example runs, but the build crashes as in my computer due to pygments and pyface.
