### ISSUE TITLE
Can sphinx_gallery_thumbnail_number support negative indexes?

### ISSUE THREAD

**Issue by seisman** [sphinx-gallery/sphinx-gallery#785]
Sometimes, the last figure in an example file is the best one. It's a little inconvenient to count the number of figures to choose the last figure.

I'm wondering if it's possible to let `sphinx_gallery_thumbnail_number` support negative indexes? For example, `sphinx_gallery_thumbnail_number = -1` means the last figure.

**Comment by lucyleeow** [comment]
All images from all the examples in one gallery are saved in the same `gallery_dir/images` folder. It would be possible to count how many image files are from one example, by matching the pattern `sphx_glr_<example_name>_<nnn>.` and use this to set `thumbnail_number` in `save_thumbnail()`, around here:

https://github.com/sphinx-gallery/sphinx-gallery/blob/d749c5261652380b281174d89f4ab18f2f299aa5/sphinx_gallery/gen_rst.py#L290-L296

(if `sphinx_gallery_thumbnail_number < 0`)

The thing to be careful about is ensuring that we match only the images from a single example, as example names can overlap (e.g., 'example' and 'example_one'). WDYT @larsoner ?

Would you be interested in putting a PR @seisman ?

**Comment by larsoner** [comment]
> The thing to be careful about is ensuring that we match only the images from a single example, as example names can overlap (e.g., 'example' and 'example_one'). WDYT @larsoner ?

The `script_vars` has an `ImagePathIterator` with a `len` property that can be used:

https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/gen_rst.py#L830-L832

So I don't think any glob/regex should be necessary

**Comment by lucyleeow** [comment]
Ah much better solution. I didn't realise that `ImagePathIterator` was available (thought you would have to amend scraper code for that).
