### ISSUE TITLE
Optuna project Uses Sphinx-Gallery

### ISSUE THREAD

**Issue by crcrpar** [sphinx-gallery/sphinx-gallery#795]
Optuna has incorporated Sphinx Gallery to provide executable tutorials as in https://optuna.readthedocs.io/en/stable/tutorial/index.html.

Could you add Optuna to "Who Uses Sphinx-Gallery" list?

**Comment by agramfort** [comment]
sure.

Can you send us a PR?

>

**Comment by crcrpar** [comment]
Of course yes!
