### ISSUE TITLE
Pandas _repr_html_ not captured in PDF output

### ISSUE THREAD

**Issue by kakila** [sphinx-gallery/sphinx-gallery#799]
The following example

```python
import pandas as pd

df = pd.DataFrame(data=dict(a=[1,2,3], b='abc'))
df
```

Woud print a nice HTML table when generating the dcos with html. However when the builder is latexpdf (or just latex) the tables are not included in any form. 
How could one capture the output to the PDF builder?

**Comment by lucyleeow** [comment]
Sorry for delay. I am not sure if there is a good solution to this. The output of `_repr_html_` is literally html e.g.,:
```html
'<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>a</th>\n      <th>b</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>abc</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>abc</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>3</td>\n      <td>abc</td>\n    </tr>\n  </tbody>\n</table>\n</div>'
```
which can be easily added when building with html.
I don't think there is a good repr method of pandas df that would render well with latex.

I think this is outside the scope of sphinx-gallery as it depends more on pandas or sphinx. Closing but feel free to comment if you disagree.

**Comment by kakila** [comment]
@lucyleeow thanks for the feedback. Currently I built a workaround sketched below.
I pass an argument to the examples and call print based on its value.

The example file:
```python
import sys
latex = True if len(sys.argv) > 1 else False

# %%
# Section
# ^^^^^^^
# A section with a data frame
# 

df = function_returns_dataframe()
if latex:
    print(df)
df

```

Extract of the `conf.py` file
```python
import sys

# Detect if latex is generated
latex = 'latex' in ' '.join(sys.argv)

# -- Options for Gallery extension ----------------------------------------------
class ResetArgv:
    def __repr__(self):
        return 'ResetArgv'

    def __call__(self, sphinx_gallery_conf, script_vars):
        return ['latex']

sphinx_gallery_conf = {
   # path to your example scripts
    'examples_dirs': ['..'],
    # path to where to save gallery generated output
    'gallery_dirs': ['gen_reports'],
    # directory where function granular galleries are stored
    'backreferences_dir': 'gen_modules/backreferences',
    # files executed
    'filename_pattern': r'/report_',
}
if latex:
    sphinx_gallery_conf['reset_argv'] = ResetArgv()

```

**Comment by lucyleeow** [comment]
I would be able to amend the [`capture_repr`](https://sphinx-gallery.github.io/stable/configuration.html#capture-repr) such that it outputs `_repr_html_` if the builder is html and `__repr__` if the builder is latex.

Does the print (which outputs the `__repr__` method) actually look okay in Latex?

**Comment by kakila** [comment]
@lucyleeow it is not a native latex table, but ti is definitely better than nothing (what one gets without the print). The latex renders exactly the output which in the case of pandas is quite acceptable.

**Comment by lucyleeow** [comment]
Thanks for the info. I will leave the config as is in that case.

**Comment by kakila** [comment]
@lucyleeow does that mean that latex will capture the output without the need to execute print or not?

**Comment by lucyleeow** [comment]
The current `capture_repr` config is not builder dependent. You can set it to capture `__repr__` or `_repr_html_` but this action will not vary depending on the builder (e.g., latex or html) used. See user guide linked above for more.
