### ISSUE TITLE
competition plot directive matplotlib/sphinx and the sphinx gallery

### ISSUE THREAD

**Issue by Titan-C** [sphinx-gallery/sphinx-gallery#8]
Because sphinx never deletes empties images in this directory. Sphinx in order to avoid overwriting images in this directory saves new images with a different name. As such html/_images grows larger every time, gen_rst has a hack to empty images in html/_images on every execution.
The problem arises if within the documentation one uses the plot directive from matplotlib `.. plot:: file.py`
in this case the code is executed once again and a new image is generated with a new filename. But once gen_rst comes to execution it deletes the gallery images(which are regenerated) and the images from the documentation directive. As such it happens that the end documentation does not display images from the plot directive.
Of course a simple `make clean` walks around the problem.

**Comment by agramfort** [comment]
this issue has bugged me many times especially when make doc takes a
while... if you have a fix you will deserve :beers:

**Comment by GaelVaroquaux** [comment]
How about we store a list of images generated by sphinx-gallery and delete only these. I suspect it's slightly harder than what I just said, but that's the spirit :)

**Comment by lesteve** [comment]
This should now be fixed since #31 has been merged.
