### ISSUE TITLE
Change DPI?

### ISSUE THREAD

**Issue by jklymak** [sphinx-gallery/sphinx-gallery#804]
Is there any way to change the DPI of the images generated?  I naively put `matplotlib.rcParams['savefig.dpi'] = 200` in `conf.py` but that didn't seem to do anything.  Sorry if this is obvious.  Thanks!

**Comment by larsoner** [comment]
Can you see if this makes sense:

https://sphinx-gallery.github.io/stable/configuration.html#reset-modules

In particular the link toward the end might help:

https://sphinx-gallery.github.io/stable/advanced.html#custom-reset

If it does solve your use case, any hints that you think we could/should have added to help discoverability for you would be appreciated (especially in the form of a docs update PR :) )!

**Comment by jklymak** [comment]
Hmmm, would have been a tough line to connect for me, though it makes sense in hindsight. Maybe "Prolog for each script execution"  ?

**Comment by larsoner** [comment]
Sounds reasonable to me to add somewhere
