### ISSUE TITLE
How to link from one example to another?

### ISSUE THREAD

**Issue by mfeurer** [sphinx-gallery/sphinx-gallery#805]
Hi,

first of all, I'm a huge fan of this package and I'm using for packages I'm working on such as [OpenML-Python](https://github.com/openml/openml-python/) and [Auto-sklearn](https://github.com/automl/auto-sklearn).

I'm currently trying to create links between examples by using rst references (to allow for automatic link checking by sphinx). However, I cannot find any mention of this in the documentation. The only thing I could find was https://github.com/sphinx-gallery/sphinx-gallery/pull/83 but the resulting example doesn't render the link: 

![image](https://user-images.githubusercontent.com/5320498/113837763-73ddd480-978e-11eb-852d-778244c3795a.png)

Therefore I was wondering what if it is possible at all to link between examples using rst references or whether this not being possible as suggested by https://github.com/sphinx-gallery/sphinx-gallery/pull/83 is simply a bug?

**Comment by lucyleeow** [comment]
What do you mean the resulting example doesn't render the link?
Inside the 'see also' box, we link to the example 'Syntax error' using the syntax described above, and I checked that the link does work.
I can see how the documentation is confusing though

**Comment by mfeurer** [comment]
Please excuse this issue, after you answered I tried again and now it works. I must have made a mistake before. Thanks a lot for your answer.

Regarding confusing documentation: I just didn't find this section which explains everything I needed to know: https://sphinx-gallery.github.io/stable/advanced.html#know-your-gallery-files but I'm not sure if this information could be put somewhere else or whether the heading could get a better name.

**Comment by lucyleeow** [comment]
No worries. Yes I agree about the documentation, if you have a suggestion feel free to put in a PR!
