### ISSUE TITLE
Generating the output notebooks together with data (folders) used for generating...

### ISSUE THREAD

**Issue by jkhoogland** [sphinx-gallery/sphinx-gallery#809]
I would like to have data folders as part of the output folder with the python scripts and notebooks.
I could not find any details on whether this is achievable or not.

I have roughly the following setup.

A bunch of folders `A, B, ...`, with python scripts as below.
The various python scripts use data, that is located in the various folders `A`, `B` as a subfolder `data`.
So a script `A/a1.py` will load data from `A/data/a1.csv` for example etc.

```
input
├── A
│   ├── a1.py
│   ├── a2.py
│   └── data
│       ├── a1.csv
│       └── a2.csv
└── B
    ├── b1.py
    └── data
        └── b1.csv
```

I would like to have the data files also copied over to the output directory,
as well as part of the generated zip files with the python scripts and notebooks.

```
output
├── A
│   ├── a1.py
│   ├── a1.ipynb
│   ├── a2.py
│   ├── a2.ipynb
│   ├── <all the other sphinx-gallery generated files>
│   └── data
│       ├── a1.csv
│       └── a2.csv
└── B
    ├── b1.py
    ├── b1.ipynb
    ├── <all the other sphinx-gallery generated files>
    └── data
        └── b1.csv
```

Is that possible to configure sphinx-gallery to do this ? And if so, any pointers would be great.

**Comment by larsoner** [comment]
> Is that possible to configure sphinx-gallery to do this ? And if so, any pointers would be great.

I don't think we should have SG do it, but fortunately it should be easy enough for you to do by hooking into a Sphinx event:

https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx-core-events

I would probably hook into `build-finished` for your use case

**Comment by jkhoogland** [comment]
Perfect, thanks for the link, I will have a look further look there.
