### ISSUE TITLE
Minigalleries are generated even for objects without examples

### ISSUE THREAD

**Issue by NicolasHug** [sphinx-gallery/sphinx-gallery#812]
For example in https://sphinx-gallery.github.io/stable/gen_modules/sphinx_gallery.scrapers.html#module-sphinx_gallery.scrapers the functions all have an empty minigallery saying "Examples using ...", but there's nothing to show.

As often minigalleries are automatically generated by adding the directive in a template, it'd be nice to only add it if there's actually a backreference to show.

**Comment by larsoner** [comment]
Yes, this has bothered me for a while in repos where I use SG!
