### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jacobolofsson** [sphinx-gallery/sphinx-gallery#817]
Is there a release planned anytime soon, or would it be possible to create one?
I would like to use the bug fix for SVG thumbnails (#810) .

**Comment by larsoner** [comment]
My inclination is to release now, and then merge #808 (switch to image-sg directive) right after release. That way matplotlib and MNE-Python can use the dev version (pinned to that commit for example) for a few months before springing it on everyone else. @jklymak @timhoffm would that work for you?

**Comment by jklymak** [comment]
I think thats fine?  Not sure if Matplotlib will want to use dev, but maybe for our dev docs.  We just released 3.4, so 3.5 will probably not be until early fall....

**Comment by larsoner** [comment]
> maybe for our dev docs. We just released 3.4, so 3.5 will probably not be until early fall....

That seems reasonable to me -- use dev on your dev docs, and then we can easily push out another SG release this summer or early fall before you're pushing out mpl 3.5.

@lucyleeow would you be up for making another release in the coming days?

**Comment by timhoffm** [comment]
That’s reasonable. Thanks!

**Comment by lucyleeow** [comment]
Will make the new release in the weekend

**Comment by GaelVaroquaux** [comment]
> Will make the new release in the weekend

Thanks!!!

**Comment by lucyleeow** [comment]
New release done.

**Comment by GaelVaroquaux** [comment]
Thanks!!
