### ISSUE TITLE
allow building single example / example directory

### ISSUE THREAD

**Issue by jasmainak** [sphinx-gallery/sphinx-gallery#82]
At mne-python, we have the issue that the entire examples directory takes more than 45 minutes to build (last I built it -- which was admittedly a long time ago). Sometimes, it is useful to link examples in the pages without having to build all the examples. See for instance [here](http://martinos.org/mne/stable/manual/datasets_index.html). If I use [``make html_dev-noplot``](https://github.com/mne-tools/mne-python/blob/f345a12aded9fda07de7cb15c707b84767091632/doc/Makefile#L20), the links to the examples are missing / broken.

I came up with a [quick hack](https://github.com/mne-tools/mne-python/pull/2761) which allows me to build only specific directories. Apart from the fact that it's a hack, it's probably not the best solution in any case. I think the cleanest solution would be something that scans the *.rst files and only builds examples which are linked there. What do you guys think? 

cc @agramfort

**Comment by agramfort** [comment]
in theory it should only rebuild the examples that have been modified.

so it should be way faster the second time you run the build.

does this at least work for you?

**Comment by Titan-C** [comment]
The gallery reruns the examples which have changed. If you are constantly switching between branches  that modifies the timestamps quite radically and many examples risk to be unnecessarily rerun.

PR #76 deals with this issue by checking file updates by md5sum, reducing the many unnecessary executions of scripts.

**Comment by jasmainak** [comment]
Yes. I know that in theory it should only rebuild the changed examples. But
I think it is an unnecessary overhead on people who just want to contribute
one section of the doc. And at least for me I often end up fetching the
same branch on three different computers and don't want to rebuild on each
computer.

On Saturday, January 2, 2016, Óscar Nájera <notifications@github.com> wrote:
> The gallery reruns the examples which have changed. If you are constantly
switching between branches that modifies the timestamps quite radically and
many examples risk to be unnecessarily rerun.
>
> PR #76 deals with this issue by checking file updates by md5sum, reducing
the many unnecessary executions of scripts.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci6.googleusercontent.com/proxy/3ViFiPOc7VqKm94FqezzF8VrMxd3w4lqPUKM1lnyFkhwMNgd8rZ4CMDz-A7mKx2dWqUNPxJmlHMTXhEv8Hsx1dyY3OsIm4O8-PFyeK9LXWa6G2YVQsEaR3M4_FBxuDMadIc3p40YZreQRTsgorY4AoIY-XnTbw=s0-d-e1-ft#https://github.com/notifications/beacon/APHionzx4CdIhgM3bV2-fOzLZySJ-mi5ks5pVtX8gaJpZM4G9cIg.gif
>

**Comment by jasmainak** [comment]
One other problem with rerunning only examples which have changed is that if you have an example failing the build (for missing package etc.), you end up having to recompute that example every time ... regardless of whether that's relevant to the section you are editing.

**Comment by GaelVaroquaux** [comment]
> One other problem with rerunning only examples which have changed is that if
> you have an example failing the build (for missing package etc.),

My point of view is that this is an anti-pattern, just like tests
failing: a project should strive never to be in this situation.

**Comment by jasmainak** [comment]
> My point of view is that this is an anti-pattern, just like tests failing: a project should strive never to be in this situation.

I agree. But I fail to see why you would want to force someone who wants to contribute one section about spatial filters (or whatever there expertise) to install all the optional dependencies.

**Comment by Titan-C** [comment]
> I agree. But I fail to see why you would want to force someone who
> wants to contribute one section about spatial filters (or whatever
> there expertise) to install all the optional dependencies. 

Because with an Anaconda virtual environment is to simple to set up a
specific environment to your project, and the travis.yml has the
information how those environments are to be configured.

**Comment by jasmainak** [comment]
hmm ... I'm not convinced it's _easy_ to build the docs. @agramfort we need to have a chat IRL :)

**Comment by jasmainak** [comment]
Often people who contribute to the docs are not git ninjas and you don't want to make their life tougher by asking them to set up anaconda virtual environment by copying information from travis.yml on the dev branch of sphinx-gallery and dev branch of sphinx. Sometimes, even people using the package can contribute good docs (not just seasoned developers) and getting all this set up is information overload :)

**Comment by GaelVaroquaux** [comment]
> Because with an Anaconda virtual environment is to simple to set up a
> specific environment to your project,

Not everybody works on Anaconda, and for good reasons.

**Comment by lesteve** [comment]
There has been complains about this in the past where the main use case is to be able to run a single example and check whether the documentation (example + narrative documentation with potentially links and figures) looks fine. Quite often people doing this are not developers and this feels like a massive PITA for them to have to run all the examples, even only once.

Maybe we could make this simple use case easier, by providing a variable in conf.py which is a regex that the example filename must match, e.g. right now we have `plot_.*.py` hardcoded somewhere in our code. If we match the full filename rather than only basename we could even make the per-directory use case possible.

Full disclosure: I have seen one very inventive person hitting Control-C on all the examples but his own to be able to run the single example he cared about faster ...

**Comment by jasmainak** [comment]
> There have been complains about this in the past where the main use case is to be able to run a single example and check whether the documentation (example + narrative documentation with potentially links and figures) looks fine. Quite often people doing this are not developers and this feels like a massive PITA for them to have to run all the examples, even only once.

yes exactly!

> Maybe we could make this simple use case easier, by providing a variable in conf.py which is a regex that the example filename must match, e.g. right now we have plot_.*.py hardcoded somewhere in our code. If we match the full filename rather than only basename we could even make the per-directory use case possible.

why not. Sounds like it could work.

> Full disclosure: I have seen one very inventive person hitting Control-C on all the examples but his own to be able to run the single example he cared about faster ...

Lol, I ended up renaming my example and example dir to start with an `a` so that it was the first thing processed ;) But I think a proper fix would be really nice.

**Comment by Titan-C** [comment]
> Lol, I ended up renaming my example and example dir to start with an a so that it was the first thing processed ;) But I think a proper fix would be really nice.

I'm also considering. If it is for testing purposes, and you want to nevertheless mess up with the `conf.py`, why not put the particular examples you are testing in a separate folder, and by using the gallery ability to build multiple galleries, just to select your test folder, and skip the regular ones.
Something in the lines of:

```python
sphinx_gallery_conf = {
    'examples_dirs': '../test_gallery', # '../examples'
    'gallery_dirs': 'auto_examples',
}
```

Later when it's all good, you put them in the desired place, remove the comment and all shall be fine.

**Comment by lesteve** [comment]
IMHO this seems like more messing around and more error prone than being able to specify a pattern that the example filename has to match.

**Comment by agramfort** [comment]
I like the idea of exposing the "plot_*" pattern so one can build a single
example.

**Comment by GaelVaroquaux** [comment]
> I like the idea of exposing the "plot_*" pattern so one can build a single
> example.

Indeed, I find that so far this is the pattern that makes most sense.

**Comment by jasmainak** [comment]
great, I think we converged upon a solution. Just so that I understand correctly, at the mne-python end it would mean using the `- D` option in [sphinx-build](http://sphinx-doc.org/man/sphinx-build.html) to specify a pattern of files to build?

Does any of you want to make the PR or do you want to be reviewers? :)

**Comment by lesteve** [comment]
> Just so that I understand correctly, at the mne-python end it would mean using the - D option in sphinx-build to specify a pattern of files to build?

This would be the same behaviour as the plot_gallery variable which is used to skip running the examples. So you can either set it in conf.py or with the -D option of sphinx-build.

> Does any of you want to make the PR or do you want to be reviewers? :)

If you manage to find some time to put together a PR it will be greatly appreciated of course ! It doesn't seem that hard to do. You need to add a variable in sphinx_gallery_conf for the pattern that the filename is supposed to match, then change this [line](https://github.com/sphinx-gallery/sphinx-gallery/blob/c2bdfa3cfee3d436e76c87033da0e1b4ba3560a2/sphinx_gallery/gen_rst.py#L501) in order to read the variable from app.config.sphinx_gallery_conf and use it in order to decide whether the example should be run.

For genericity's sake, I'd be in favour of using `re.search` with a regex pattern that matches the absolute path of the example.

Let us know if you decide to work on a PR so that we don't end up duplicating efforts !

**Comment by jasmainak** [comment]
Excellent, I'll give it a shot :)
