### ISSUE TITLE
Recycling resources at Tutorial boundary

### ISSUE THREAD

**Issue by tqchen** [sphinx-gallery/sphinx-gallery#853]
Hi Sphinx Gallery developers

We are building our tutorials using sphinx gallery. One thing we noticed is that all the tutorials are run under a single global session. So if we created example arrays under the global context in multiple tutorials, they wont be recycled until all the tutorial exits. This has becomes a problem in our tutorial build such that multiple tutorials causes out of GPU memory because the arrays are not being freed(where single tutorial is fine).

It would be super helpful if there is an option to wrap the tutorial in a function(such that contents get freed after running a single tutorial), use a multiprocessing to fork off tutorial execution, or gc the resources.

Would love to see if there are pointers that allows us to do so, or possible pointers to the code that can help to make such a change.

Thank you!

**Comment by lucyleeow** [comment]
Would this functionality work for you: https://sphinx-gallery.github.io/stable/advanced.html#define-resetting-behavior-e-g-for-custom-libraries ?

You could potentially have a function that cleans up at the start of each example .py file.

**Comment by tqchen** [comment]
we could insert a gc call, however the way that the code is being executed. The top level variables may not yet trigger the del, as a result may not be recycled.

**Comment by lucyleeow** [comment]
What do you mean by 'boundary'..?

**Comment by tqchen** [comment]
Oh i meant the at end of one tutorial(note book example). Right now if there are say five different `.py` files under a tutorial folder, it seems that they are running in a single python global session

**Comment by lucyleeow** [comment]
Yes I think they run in a single session but they do run one after the other (not all at the same time) - so a 'resetter' function that runs at the start of each `.py` file would be similar to "wrapping the tutorial body in a sub-function" ?

I guess the part I don't quite follow is:

> the top level variables may not yet trigger the del, as a result may not be recycled.

**Comment by tqchen** [comment]
To give a concrete example. suppose we have

file1:
```python
x = my_func1()
```
file2:
```python
y = my_func2()
```

I believe currently the behavior of the sphinx gallery is
```python
x = my_func1()
resetter_callback()
y = my_func2()
```

Note that the python interpreter won't trigger `x.__del__` until the very end, so resetter callback cannot recycle x. When there are a lot of the files like this, the resource that get into global variables becomes overwhelming.

If we instead run the things as separate functions, or run each tutorial as separate session(e.g. via multiprocessing). x will be recycled as soon as we finish the first tutorial

```python
def tutorial1():
   x = my_func1()
tutorial1()

def tutorial2():
   y = my_func2()
tutorial2()
```

**Comment by lucyleeow** [comment]
> Note that the python interpreter won't trigger x.__del__ until the very end, so resetter callback cannot recycle x.

Thanks, that makes sense. I guess I naively thought that you could manually delete created variables and then recycle but maybe there is no easy/good way of deleting only created variables?

**Comment by larsoner** [comment]
> I believe currently the behavior of the sphinx gallery is
>x = my_func1()
> resetter_callback()
> y = my_func2()

It should be more like (effectively):
```
x = my_func1()
del x
resetter_callback()
y = my_func2()
del y
resetter_callback()
```
i.e., no references are kept by sphinx-gallery. If references are kept by some other loaded library (like in a global state variable), then that library needs to clear its own references.

In MNE-Python we even ensure that no references to important, memory-hungry objects are kept around inside our `resetter_callback`, so I think the mechanism works as designed. Are you 100% sure whatever library/libraries you're loading aren't keeping objects around in some global state/variables that need to be cleared? If you want to try some code, you can look at what we use in MNE:

https://github.com/mne-tools/mne-python/blob/9b16524bc8b98211d351afb19efd264f04c18e60/doc/conf.py#L279-L317
https://github.com/mne-tools/mne-python/blob/9b16524bc8b98211d351afb19efd264f04c18e60/mne/utils/misc.py#L329-L363

**Comment by lucyleeow** [comment]
Good point, we do reset `example_globals` at the start of each example.

**Comment by tqchen** [comment]
Thank you @larsoner  for the clarification! I did a quick experiment and indeed it confirms what you said. So perhaps the problem was about the global package that we import then

**Comment by lucyleeow** [comment]
> is there an option for us to simply unload everything(including all the global packages involved?)

I'll let @larsoner answer because I don't use sphinx-gallery enough.

Otherwise I think this can be closed, thanks!

**Comment by tqchen** [comment]
Thank you!
