### ISSUE TITLE
Add ability to write nested `index.rst`

### ISSUE THREAD

**Issue by tacaswell** [sphinx-gallery/sphinx-gallery#855]
Currently sphinx-gallery writes output that looks like

```
- top_level
   - index.rst
   - subdir
      - example.rst
      - example2.rst
      - <lots of other non-rst files>
   - subdir2
      - example1.rst
      - example2.rst
      - <other stuff>
```

and in the top level `index.rst` there is a sub-section pre sub-directory and for each example there is a block that looks like

```rst
.. raw:: html

    <div class="sphx-glr-thumbcontainer" tooltip="See ~matplotlib.axes.Axes.plot.">

.. only:: html

 .. figure:: /plot_types/basic/images/thumb/sphx_glr_plot_thumb.png
     :alt: plot(X, Y)

     :ref:`sphx_glr_plot_types_basic_plot.py`

.. raw:: html

    </div>


.. toctree::
   :hidden:

   /plot_types/basic/plot
```

which puts in a hidden 1 element toc to include the underlying `.rst` files and then the logic to link to them.    However this plays very badly with extremely large gallerys and the pydata-sphinx theme and gives you side bars like https://matplotlib.org/devdocs/gallery/index.html which are just way too long.

I propose that inside of each of the sub-directories and `index.rst` also gets written that has the same html content and a 

```rest
.. toctree::
   :hidden:
   
   example1
   example2
```

and at the top level instead of writing many single-entry TOCs there is one

```rst
.. toctree::
   :hidden:
   
   subdir/index
   subdir2/index
```

I believe that this will correctly communicate to sphinx what the intended structure is and then will reflect that nesting in the left bar of the pydata theme.

**Comment by larsoner** [comment]
@drammock thoughts on this? You've messed with pydata-sphinx-theme + SG a bit

**Comment by drammock** [comment]
Without having looked in detail at the code, I'd say this is a good change for *large galleries* as @tacaswell says; MNE-Python would benefit from that change I think. (The one-left-sidebar-to-rule-them-all is particularly egregious on mobile devices.)  Do we know of any *small* projects that use SG? Will they want to keep the current behavior (or at least have a config option to allow it either way)?

**Comment by drammock** [comment]
Thinking more about this, it's not clear to me what content will be on the top-level `index` page versus what goes on the nested `index` pages.  Presumably `subdir/index` would have the gallery tiles for the two examples contained in `subdir`, and likewise for `subdir2`...  but what content is now on the top-level `index` page?  Are all the tiles for individual tutorials still there, but just not their TOC entries?  What happens to the content of the `README.txt` files which is currently used for section titles / introductory text?

**Comment by tacaswell** [comment]
I think all of the _content_ stays exactly as it is (with the sub-section content duplicated on the inner pages), the only difference is in what we tell to sphinx about the structure and a (slightly redundent) page with just 1 subdir's worth of content.

The conservative thing is to put in a toggle, but I am not sure I can think of a case where I would both want to have subdirectories and want to _not_ have that structure expressed in the sidebar.  If you really want that visually in the rendered output, then I think the solution could be to "not have sub-directories".

**Comment by drammock** [comment]
First let me say I agree that this is a good idea / valid use case; I think we'd make use of it. but:

>  If you really want that visually in the rendered output, then I think the solution could be to "not have sub-directories".

the gallery section divisions rely on having a `README.txt` in the separate subdirs.  In other words, the subdirs exist for the purpose of sectioning the content and I think were not meant to represent the kind of hierarchy that you (and also I) desire.

Is there some way to make it work the way you want it to be by eliminating the top level of nesting, and have `subdir`, `subdir2` etc listed in `conf.py` as separate galleries?

**Comment by drammock** [comment]
for example, on this page https://mne.tools/dev/auto_tutorials/index.html if you click the chevron next to "tutorials" in the left sidebar, to collapse the TOC entries, you'll see TOC entries for 2 gallery pages ("tutorials" and "examples").  `subdir` and `subdir2` and all the other subdirs can end up there...  every single tutorial will still be written to that sidebar TOC, but all but the active one will start out in collapsed state.  Now that I've talked through it, I'm not sure that is close enough to what you're after?

**Comment by tacaswell** [comment]
I want a third level as on Matplotlib we have a example / tutorial split and then within each of those have further (domain) categories.

**Comment by drammock** [comment]
OK, so I think I'm sold.  Just to make sure we're on the same page, I'll summarize what I think the proposal is, indicating things that I'm assuming / filling in with *italics*. Starting from:

```
.
├── examples
│   ├── decoding
│   │   ├── decoding_A.py
│   │   ├── decoding_B.py
│   │   ├── decoding_C.py
│   │   └── README.txt
│   └── forward
│       ├── forward_A.py
│       ├── forward_B.py
│       └── README.txt
└── tutorials
    ├── clinical
    │   ├── clinical_A.py
    │   ├── clinical_B.py
    │   └── README.txt
    └── time-freq
        ├── README.txt
        ├── time_freq_A.py
        └── time_freq_B.py
```

Then the goal is that the left sidebar if we were in the "examples" gallery would show
```
├── examples
│   ├── section title from examples/decoding/README.txt  (expandable by clicking the little chevron)
│   └── section title from examples/forward/README.txt  (expandable)
└── tutorials (expandable, collapsed by default)
    ├── section title from tutorials/clinical/README.txt  (expandable once "tutorials" was expanded)
    └── section title from tutorials/time-freq/README.txt  (expandable once "tutorials" was expanded)
```
*and the right sidebar (the "on this page" list) would show each of the individual example or tutorial titles, like this:*
```
ON THIS PAGE (examples)
├── page title of decoding_A.py
├── page title of decoding_B.py
├── page title of decoding_C.py
├── page title of forward_A.py
└── page title of forward_B.py

ON THIS PAGE (tutorials)
├── page title of clinical_A.py
├── page title of clinical_B.py
├── page title of time_freq_A.py
└── page title of time_freq_B.py
```

*(otherwise if left in its current state, it would be redundant with what is now shown in the left sidebar's TOCtree). So if you've configured the theme to show "on this page" in the right sidebar (which is the theme default I think) then you'd still end up with the massive list of all files in the top-level galleries, but that massive list will now be in the **right sidebar** (so that it's not shown at all on narrow displays, and on wide displays it is at least logically after the main content window, so it should be nicer for screen readers too).*

Additionally, new `index.rst` files will get written for each sub-gallery (`auto_examples/decoding/index.rst`, etc). Those will be "gallery pages" too (showing tiles and titles for each example/tutorial within that folder).  Those sub-gallery pages will be accessible from the left bar TOCtree on their parent gallery page, and would automatically fall in a logical place in the linear sequence of pages (because of how they're added to the TOCtree). Their left-sidebar TOCtree would show something like this:

```
├── examples
│   ├── section title from decoding/README.txt (auto-expanded because we're on that page)
│   │   ├── page title of decoding_A.py
│   │   ├── page title of decoding_B.py
│   │   └── page title of decoding_C.py
│   └── section title from forward/README.txt (expandable)
└── tutorials (expandable)
```

and *their right-sidebar "on this page" list will show the page titles from each example/tutorial in them*.
