### ISSUE TITLE
Is the version of the docs on pythonhosted.org maintained?

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#86]
The is a version of the docs on:
http://pythonhosted.org/sphinx-gallery/

I have the feeling that it is not maintained. If this is the case, we should take it down.

**Comment by lesteve** [comment]
Same feeling here, if you look at the top left corner you'll see:

Sphinx-Gallery 0.0.4-git documentation

It doesn't look like there is a completely trivial way of taking it down. Googgling around I found this [link](https://mail.python.org/pipermail/python-dev/2014-March/132883.html) that list this [SO answer](http://stackoverflow.com/a/6531582) as a work-around.

**Comment by amueller** [comment]
yeah it was confusing to me. it mentions ``sphinxgallery`` when the package is now named ``sphinx_gallery``

**Comment by Titan-C** [comment]
I'll try to get the refresh to read the docs website over the weekend or next week

**Comment by Titan-C** [comment]
http://pythonhosted.org/sphinx-gallery/
Is now updated to redirect to Read The docs within 2 seconds.
