### ISSUE TITLE
How to avoid capture of tqdm progress bars

### ISSUE THREAD

**Issue by nss350** [sphinx-gallery/sphinx-gallery#867]
Hi, I'm trying to make a gallery where some processes use tqdm progress bars. These get captured in the output. Is there anyway to avoid capturing this output?

I was looking at the configuration option: ignore_repr_types
But I can't seem to get the right value here to ignore them.  
Does anyone have experience of this?
Thanks

**Comment by lucyleeow** [comment]
I suspect the progress bars may be standard output, which is always captured, see:

https://github.com/sphinx-gallery/sphinx-gallery/blob/2d19681068b4c7bd95791413aee20c1422838b01/sphinx_gallery/gen_rst.py#L635

We could allow you to optionally not capture the standard out for a code block, but I am guessing what you want is to capture the standard output but exclude the progress bar. I am not sure how easy that would be and how much demand there would be for this...

**Comment by nss350** [comment]
I was checking on the tqdm github earlier today and turns out silencing the progress bar is quite a requested feature. See:
https://github.com/tqdm/tqdm/pull/950
https://github.com/tqdm/tqdm/pull/1061

It seems that they are making some progress on this so I'm tempted to see what comes of that.
