### ISSUE TITLE
`0.10.0` breaks `sphinx_gallery.load_style`

### ISSUE THREAD

**Issue by pmeier** [sphinx-gallery/sphinx-gallery#878]
I'm using an exotic setup where the gallery built requires GPUs and thus cannot be run by RTD or the like (see #704) for details. I have a built server set up that builds the galleries and packages them, whereas the normal CI falls back to downloading these pre-built galleries. For that to work, the built server runs with `sphinx_gallery.gen_gallery` whereas the normal CI runs with [`sphinx_gallery.load_style`](https://sphinx-gallery.github.io/stable/advanced.html#using-only-sphinx-gallery-styles).

This worked fine until `0.9.0`. With `0.10.0` images scraped with the default `matplotlib` scraper now use the `.. image-sg::` introduced in #808. Unfortunately, this directive is not loaded when using `sphinx_gallery.load_style`. You end up with warnings like these:

```
.. image-sg:: /galleries/examples/beginner/images/sphx_glr_example_nst_without_pystiche_003.png
   :alt: Input image
   :srcset: /galleries/examples/beginner/images/sphx_glr_example_nst_without_pystiche_003.png
   :class: sphx-glr-single-img
/home/philip/git/pystiche/pystiche/docs/source/galleries/examples/beginner/example_nst_without_pystiche.rst:1305: WARNING: Unknown directive type "image-sg".
```

The build goes through, but the images are not shown in the HTML version.

**Comment by pmeier** [comment]
Here are two RTD builds, that for the purpose of this issue only differ in the `sphinx-gallery` version:

- `0.9.0`: [docs](https://docs.pystiche.org/en/latest/galleries/examples/beginner/example_nst_with_pystiche.html), [log](https://readthedocs.org/projects/pystiche/builds/15205614/)
- `0.10.0`: [docs](https://docs.pystiche.org/en/sphinx-gallery-878/galleries/examples/beginner/example_nst_with_pystiche.html), [log](https://readthedocs.org/projects/pystiche/builds/15201411/)

**Comment by larsoner** [comment]
@pmeier I think we need to add the directive when doing `load-style`. Could you make a PR to fix it?
