### ISSUE TITLE
embed_code_links throwing <exception: list indices must be integers or slices, not str>

### ISSUE THREAD

**Issue by wsavran** [sphinx-gallery/sphinx-gallery#879]
after sphinx upgraded to 4.3.0 earlier today my build broke when trying to embed documentation hyperlinks. here's an output from the GitHub actions build: 

```
Extension error (sphinx_gallery.docs_resolv):
Handler <function embed_code_links at 0x7f17c813c9e0> for event 'build-finished' threw an exception (exception: list indices must be integers or slices, not str)
```

this issue was able to be fixed by pinning the sphinx version to 4.2.0. i couldn't track down what caused this issue in the new sphinx release, but their [changelog](https://github.com/sphinx-doc/sphinx/blob/4.x/CHANGES) might be a clue for someone that's more familiar with sphinx.

**Comment by larsoner** [comment]
Can you see if it's fixed on latest `master`? This might have been fixed by https://github.com/sphinx-gallery/sphinx-gallery/pull/865

**Comment by wsavran** [comment]
it's working on master with sphinx 4.3.0. thanks! i'll close the issue.

**Comment by QuLogic** [comment]
It'd be nice to get a release out with that fix, maybe a bugfix if a feature release is too much. We will pin sphinx for now to avoid this.

**Comment by larsoner** [comment]
@lucyleeow are you up for making a release?

**Comment by lucyleeow** [comment]
FYI New patch release out which has the fix for this.

**Comment by QuLogic** [comment]
Thanks!
