### ISSUE TITLE
Build gallery from .ipynb files only

### ISSUE THREAD

**Issue by mgiammar** [sphinx-gallery/sphinx-gallery#882]
I am a developer working on a library which uses sphinx-gallery to build example pages in our documentation. Right now our library has an examples_source folder which holds `.py` files which build both the `.ipynb` and `.rst` files for each example. We found [jupyter-book](https://jupyterbook.org/intro.html) and like its ability to open an example notebook in Colab or execute with Thebe over launching notebooks in Binder. 

I've got the configuration files working in some testing documentation where each example page is build from an `.ipynb` file. However, the example pages in the library are `.rst` files and the new functionality is not showing up.

Is there a way to build the galleries with notebooks only and have the example pages themselves be notebooks? If this is completely absurd, I apologize since I'm new to building large documentation pages.

**Comment by lucyleeow** [comment]
> I've got the configuration files working in some testing documentation where each example page is build from an .ipynb file.

I don't follow, what did you use to build from .ipynb files? 

> Is there a way to build the galleries with notebooks only and have the example pages themselves be notebooks?

I'm afraid Sphinx-Gallery is designed to work for .py files and I think it would require a bit of work for it to work for .ipynb files as well.

**Comment by lucyleeow** [comment]
I think I'll close this because I think there may exist better utilities that will convert a notebook to executed notebook...please let me know if it should be re-opened though!
