### ISSUE TITLE
Thumbnail for non plot examples

### ISSUE THREAD

**Issue by TimotheeMathieu** [sphinx-gallery/sphinx-gallery#887]
I am wondering how I can have a thumbail for examples that don't have a name that begins with "plot" (i.e. examples that are not compiled). 

My problem is that I have some examples that take a long time to compile and if I do compile them, readthedocs would time out. Hence I don't compile them for the doc but if I don't compile, it seems that [providing an image for the thumbnail](https://sphinx-gallery.github.io/stable/auto_examples/plot_4b_provide_thumbnail.html) do not work. Is there another way to specify a thumbnail or is it something that is not implemented in sphinx-gallery ?

**Comment by lucyleeow** [comment]
I just checked and it should work for examples not included in `filename_pattern` and not included in `ignore_pattern` see: https://sphinx-gallery.github.io/stable/configuration.html#build-pattern

Maybe double check the path? It should be relative to the `conf.py` file.

**Comment by TimotheeMathieu** [comment]
Ok, I solved the problem by deleting `auto_examples` folder and reconstructing the whole docs. I guess my problem was some incremental update problem.
Thanks.
