### ISSUE TITLE
Documentation "Add mini-galleries for API documentation"

### ISSUE THREAD

**Issue by StefRe** [sphinx-gallery/sphinx-gallery#897]
If I understand the code https://github.com/sphinx-gallery/sphinx-gallery/blob/fabc70a4afc0aa72db5d06ea5fd665e1cdcf17a6/sphinx_gallery/backreferences.py#L188-L194

correctly then  `:meth:`, `:attr:`, and `:obj:` should be included in item 2 

> Refer to that function/class using sphinx markup `:func:`/`:class:` in a documentation block.

under https://sphinx-gallery.github.io/stable/configuration.html#add-mini-galleries-for-api-documentation too, shouldn't they?

**Comment by larsoner** [comment]
@StefRe yes, could you make a PR to update our docs? A comment in `backreferences.py` stating that we need to update some RST file whenever this `_regex` changes would nice, too, to prevent similar inconsistencies in the future
