### ISSUE TITLE
Limit adding mini-galleries for API docs to explicitly referred to items only

### ISSUE THREAD

**Issue by StefRe** [sphinx-gallery/sphinx-gallery#898]
When creating backreferences for mini-galleries for instance for matplotlib galleries, practically every example will include a call to `plt.plot` or `plt.subplots` or the like, leading to a huge amount of spurious references from API to gallery examples, see https://github.com/matplotlib/matplotlib/issues/22036 for details.  

Do you think it would be a good idea to have a config option to limit reference collection to explicitly mentioned examples only, e.g. an option `auto-doc` (by default `True`), so that
https://github.com/sphinx-gallery/sphinx-gallery/blob/fabc70a4afc0aa72db5d06ea5fd665e1cdcf17a6/sphinx_gallery/backreferences.py#L203-L206
could be put into an `if` block like
```
if auto_doc:
   finder = NameFinder(global_variables) 
   if node is not None: 
       finder.visit(node) 
   names = list(finder.get_mapping())
else:
   names = []
``` 
This gives the possibility to only include functions you really want to illustrate by the given example and the default behavior would be unchanged.

**Comment by larsoner** [comment]
In NumpyDoc we have a [nice (I think) syntax](https://numpydoc.readthedocs.io/en/latest/validation.html#docstring-validation-during-sphinx-build) for style checks where the default is `'all'`, but you can do `{'all', 'GL01'}` which means "check all but GL01". It would be nice to have this sort of thing I think, where you can have 


1. implicit_backreferences = 'all'` by default (acting as it does now) but then
2. you can pass fully-qualified names like `implicit_backreferences = {'all', 'matplotlib.pyplot.subplots'}` for example to exclude subplots, or
3. `implicit_backreferences = {'matplotlib.pyplot.subplots'}` to *only* get implicit ones for subplots (which you clearly don't want as it does something like the opposite of what you want, but hopefully you get the idea).

@StefRe want to give this a shot? Given you've already looked at the code, hopefully it wouldn't be too much work to implement!

**Comment by StefRe** [comment]
Hm, that's much more than we'd need in the given case: here we only would need a general possibility to *ex*clude implicit back references as  *in*clusion would be by explicitly listing the desired functions in the admonition footer. In that sense, an option like the complementing `numpydoc_validation_exclude` option would be even more appropriate here: for instance `implicit_backref_exclude` (default would be empty, i.e. exclude nothing = current behavior). I guess the easiest way is to do it [like in numpy doc](https://github.com/numpy/numpydoc/blob/4ae1e00e72e522c126403c1814f0b99dc5978622/numpydoc/numpydoc.py#L184-L186): first get everything and then remove the unwanted items from `names`.

**Comment by larsoner** [comment]
Sounds like a reasonable plan @StefRe , feel free to give it a shot!
