### ISSUE TITLE
Add dash to the name of the package on PyPI?

### ISSUE THREAD

**Issue by lesteve** [sphinx-gallery/sphinx-gallery#9]
Just wondering whether it should be called sphinx-gallery (with a dash in the middle) rather than sphinxgallery on PyPI. This would be consistent with the github name.

**Comment by agramfort** [comment]
+1

**Comment by Titan-C** [comment]
actually is the other way around. Originally all had the dash, but it turns out to be a bit problematic to have python modules with dashes or underscores. That's why I changed it for PyPI.
I could remove the dash in Github?

**Comment by lesteve** [comment]
Sorry I shouldn't have used package which is misleading. You can have the project named sphinx-gallery on PyPI so that to install it you have to do `pip install sphinx-gallery` and your package named sphinxgallery or sphinx_gallery or whatever you want so that to import it you do `import sphinxgallery`.

Kind of similar to scikit-learn where you do `pip install scikit-learn` to install it and `import sklearn` to import it.

**Comment by Titan-C** [comment]
There is the new version in PyPI and docs are updated accordingly.

**Comment by lesteve** [comment]
Cool, do you plan to remove the old (sphinxgallery without dash) naming from PyPI at one point?
