### ISSUE TITLE
DOC: Example "Identifying function names in a script"

### ISSUE THREAD

**Issue by StefRe** [sphinx-gallery/sphinx-gallery#900]
While looking into #898 I came across the example  [Identifying function names in a script](https://sphinx-gallery.github.io/stable/auto_examples/plot_6_function_identifier.html). What is the point of retrieving the names of the `os` module here? Should the example not rather use the example file [plot_6_function_identifier.py](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/examples/plot_6_function_identifier.py) itself to demonstrate this feature, or am I missing something here?

**Comment by larsoner** [comment]
I can't remember the point actually... it doesn't seem like we actually want people using these functions. +1 on removing the example entirely

**Comment by StefRe** [comment]
Oh, I like this example - it helps a lot understanding how `sphinx-gallery` works, besides it's needed for the [configuration docs](https://sphinx-gallery.github.io/stable/configuration.html#auto-documenting-your-api-with-links-to-examples) to explain backreferences. So I'll make a PR to just tidy it up a bit.
