### ISSUE TITLE
mini-gallery not shown in grid

### ISSUE THREAD

**Issue by rflamary** [sphinx-gallery/sphinx-gallery#911]
Hello and thank you very much for this awesome code!

I noticed in the last compilation of the (dev) doc of POT : 
https://pythonot.github.io/master/quickstart.html#examples-of-use-for-ot-emd

that the mini-galleries do not show proper grids see screenshot below:
![image](https://user-images.githubusercontent.com/1386873/152330221-73582e39-ddba-4d55-8a54-0260aa742994.png)
which takes tons of space.

Here is the code in the rst file for the gallery above:
```
.. minigallery:: ot.emd2
    :add-heading: Examples of use for :any:`ot.emd2`
    :heading-level: "
```

This is a bit sad because I really like the new css grids that can handle long titles with no problems ;).

I'm pinging @alexisthual who probably knows what to do about this.

**Comment by larsoner** [comment]
I didn't look at the effect the changes had on the minigallery inclusion, sorry about that!

Indeed @alexisthual if you have some ideas, I'm happy to hear them.

**Comment by alexisthual** [comment]
I just opened a PR which I think fixes this.

I tried to check whether other parts of the library could be affected by this (I simply searched for the word "clear"), and it seems that mini galleries are the only candidate :smile:

**Comment by rflamary** [comment]
Thank you so much! This was very efficient.
