### ISSUE TITLE
`html-noplot` does not work with strict build options

### ISSUE THREAD

**Issue by pmeier** [sphinx-gallery/sphinx-gallery#913]
The [official instructions](https://sphinx-gallery.github.io/stable/configuration.html#building-without-executing-examples) for building `html-noplot` include setting `-D plot_gallery=0 -b html $(ALLSPHINXOPTS)`. This will emit the following warning:

```
The config value `plot_gallery' has type `str', defaults to `bool'.
```

This effectively prevents us from having `-W` in `ALLSPHINXOPTS`, i.e. running in strict mode that turns warnings into errors. Given that you cannot set anything besides strings from the CLI, this is pretty limiting.

**Comment by larsoner** [comment]
If you put `plot_gallery = 'True'` in your `conf.py` instead of `plot_gallery = True` in your `conf.py` it should work, as Sphinx will see it as a str var, then in SG we try to be smart about converting string values to booleans. Can you try it, and if it works, open a PR to improve the docs here?

**Comment by pmeier** [comment]
That indeed works, thanks. Still, this feels kinda awkward since we didn't have `plot_gallery` config option before. I'm guessing it just assumes `plot_gallery=True` if nothing is set and then complains because the CLI option is a string. Maybe we should fix this behavior rather than documenting the workaround?

**Comment by larsoner** [comment]
> Maybe we should fix this behavior rather than documenting the workaround?

That would be nice. It might just require making the default configuration `'plot_gallery': 'true'` or something. Want to take a look?
