### ISSUE TITLE
make html-noplot runs the examples

### ISSUE THREAD

**Issue by lesteve** [sphinx-gallery/sphinx-gallery#92]
`make html-noplot` does not seem to do what is says on the tin.

Here is part of the output I get:

```
plotting code blocks in ../examples/plot_strings.py
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output
This is a long test Output

 - time elapsed : 0.00034 sec
plotting code blocks in ../examples/plot_strings.py
one line out
 - time elapsed : 8.9e-05 sec
plotting code blocks in ../tutorials/plot_parse.py
 - time elapsed : 5.7e-05 sec
```

**Comment by lesteve** [comment]
It'd be nice to be able to test this actually. Not sure how at the moment.

**Comment by Titan-C** [comment]
Yes, It caught also my attention from https://github.com/scikit-learn/scikit-learn/pull/4658

I know this was well implemented in https://github.com/sphinx-gallery/sphinx-gallery/commit/6e26ea8815e9c9434748db8f54b60681a79b2ffc. I have not found when it stop working.

**Comment by Titan-C** [comment]
It was deleted here https://github.com/sphinx-gallery/sphinx-gallery/commit/526d2acd467595c86baf645af60589f861a2098b

**Comment by lesteve** [comment]
Well spotted. Looks like I missed that during the review, sorry for that!

Still it'd be good to figure out a way to test this. Maybe we could do something similar to what @jasmainak did with his "test_pattern_matching" test function.

**Comment by Titan-C** [comment]
So, I'll reopen this. Travis just failed as the test_pattern_matching takes a full configuration dictionary to launch the test.
Certainly we need to improve the testing for this option and a better way to setup the test. Some time ago I was reading about sphinx, it test itself launching shorter versions of the build process. It even provided a test agent for that, though is was more complicated to implement.

**Comment by lesteve** [comment]
Just for the record, this feature is used by nilearn and scikit-learn folks from time to time so we will probably need another release before inclusion in nilearn and scikit-learn.

**Comment by jasmainak** [comment]
Sorry about introducing the bug :\ I think a test would really be nice for sure.

**Comment by lesteve** [comment]
> Sorry about introducing the bug :\

No big deal, happens to the best of us :-) and that's what the review is here for ...

**Comment by GaelVaroquaux** [comment]
Should this issue be closed?

**Comment by jasmainak** [comment]
I was looking at this with @jaeilepp and I think it is not working yet. Something is broken with the last two commits in master. The `filename_pattern` does not appear to have an effect.

**Comment by GaelVaroquaux** [comment]
> I was looking at this with @jaeilepp and I think it is not working yet.
> Something is broken with the last two commits in master. The filename_pattern
> does not appear to have an effect.

OK. That's pretty bad, as most projects rely on this behavior. We cannot
merge the new sphinx-gallery in nilearn or scikit-learn.

**Comment by Titan-C** [comment]
>I was looking at this with @jaeilepp and I think it is not working yet. Something is broken with the last two commits in master. The filename_pattern does not appear to have an effect.

Can you be more specific in you use case. For to me it does look good. If you use `filename_pattern` only matching examples get executed to generate output. But if you build with html-noplot nothing gets build `filename_pattern`  becomes irrelevant. Examples are just parsed from python scripts to rst files and downloadable notebooks.

**Comment by jasmainak** [comment]
okay, I think I figured out what the problem was. Basically, the configuration dict has been renamed in the latest version of sphinx. So, basically this won't work: https://github.com/mne-tools/mne-python/blob/master/doc/conf.py#L275. We have to rename it to `sphinx_gallery_conf` or do some version checking there. Not sure what's the right solution

**Comment by lesteve** [comment]
> okay, I think I figured out what the problem was. Basically, the configuration dict has been renamed in the latest version of sphinx

@Titan-C this should probably be mentioned in the changelog along with the sphinxgallery -> sphinx_gallery renaming.

> We have to rename it to sphinx_gallery_conf or do some version checking there. Not sure what's the right solution

What's the problem with renaming sphinxgallery_conf -> sphinx_gallery_conf in mne-python conf.py? Do you really need a conf.py that works with multiple versions of sphinx-gallery?

**Comment by Titan-C** [comment]
>@Titan-C this should probably be mentioned in the changelog along with the sphinxgallery -> sphinx_gallery renaming.

Done

**Comment by GaelVaroquaux** [comment]
In the PRs updating sphinx-gallery in nilearn (ie
https://github.com/nilearn/nilearn/pull/973
and
https://github.com/nilearn/nilearn/pull/961
)

I still seem to have a "make html-noplot" that doesn't work as expected,
ie it runs all the examples.

**Comment by Titan-C** [comment]
> In the PRs updating sphinx-gallery in nilearn (ie nilearn/nilearn#973 and nilearn/nilearn#961 )

Yes the bug fix is only in master not in the old released version v0.1.0 in those PR. I can do a new bug fix release(v0.1.1) now to include this change and also the CSS for the thumbnails and rebase https://github.com/nilearn/nilearn/pull/961. Or do we want to add something more before that release?

**Comment by lesteve** [comment]
> Or do we want to add something more before that release?

Nothing else pops to mind.

**Comment by jasmainak** [comment]
> What's the problem with renaming sphinxgallery_conf -> sphinx_gallery_conf in mne-python conf.py? Do you really need a conf.py that works with multiple versions of sphinx-gallery?

I guess we should do it. I'll fix it to use only one version.

**Comment by Titan-C** [comment]
I'll close this for release v0.1.1 as the bug is fixed. I'll open a new issue to remember to set up test for build options.
