### ISSUE TITLE
Broken plot links if sphinx uses `htmldir`

### ISSUE THREAD

**Issue by ExtremOPS** [sphinx-gallery/sphinx-gallery#921]
If I build our documentation with the sphinx builder option `htmldir` the links to the in-site plots are broken. The thumbnails are working.

I already discussed this issue on [read the docs](https://github.com/readthedocs/readthedocs.org/issues/8982) because I thought the problems is there. But they figured out that this might be a flaw with sphinx-gallery.

**Comment by larsoner** [comment]
Indeed I don't think anyone has considered the `dirhtml` build option. Can we just say it's unsupported? If not, I suspect it might be a bit of work to get it functional (but maybe doable!)

**Comment by ExtremOPS** [comment]
Maybe just state it somewhere on the docu that it only works with `html`.
