### ISSUE TITLE
Add option to generate interactive gallery with replite

### ISSUE THREAD

**Issue by ianhi** [sphinx-gallery/sphinx-gallery#927]
## Proposal
Add an option to use `jupyterlite` to have make a gallery of interactive examples.

## How
Using jupyterlite it's now possible to have interactive python repl on a webpage without a backing from binder. https://jupyterlite-sphinx.readthedocs.io/en/latest/directives/replite.html provides a `:replite:` sphinx directive that enables this. Naively I'd expect that replacing the `..code-block::` with `:replite` might just give automatic interactivity. 

There be some work to get examples with multiple code blocks to share the same kernel between them, but even if this was just enabld for examples wiht single code blocks that would be amazing!

cc @jtpio @martinRenou

**Comment by amueller** [comment]
Is the idea that you can configure whether to add a "run in jupyterlite" to the bottom next to the download buttons? Or potentially replace the default example rendering with an interactive one?

**Comment by ianhi** [comment]
updated the link.

>  "run in jupyterlite" to the bottom next to the download buttons? Or potentially replace the default example rendering with an interactive one?

 I think having an option for both would be good!

**Comment by amueller** [comment]
The `:replite:` seems to provide more of a repl-like experience (as might be gathered from the name), so you can't edit the example and run again.

**Comment by ianhi** [comment]
True, I think a better thing would be to use retrolite: https://jupyterlite-sphinx.readthedocs.io/en/latest/directives/retrolite.html which embeds a mini retrolab (now notebook classic i think?)

**Comment by amueller** [comment]
Yes, but then I don't think they would share state across multiple cells. I'm thinking we might be able to get a separate page to have a full jupyterlab that can then share the jupyterlite instance for all examples which you can browse.
Right now it looks like this but maybe I can make it open in another window instead of an iframe:
![image](https://user-images.githubusercontent.com/449558/179371392-d0a49357-5352-4adf-ab4f-b135740fc65e.png)

**Comment by jtpio** [comment]
> maybe I can make it open in another window instead of an iframe

Yes, for example `ipycanvas` does this by providing a badge on the docs landing page: https://ipycanvas.readthedocs.io/en/latest/?badge=latest

**Comment by Borda** [comment]
Just thinking, what about some form of ipywidgets with precomputed steps?
