### ISSUE TITLE
Sphinx-gallery generating huge rst files

### ISSUE THREAD

**Issue by shivshankardayal** [sphinx-gallery/sphinx-gallery#929]
I am working on https://github.com/deepchecks/deepchecks for sphins gallery implementation. The `implement_sphinx_gallery` is the brnach. Specifically, the folder in concern is `docs/gallery` Sphinx gallery is generating huge rst files and sphinx is OOMing after consuming 17G of RAM on my laptop. The largest file which I have is 543 MB of rst and 23 million LOC.

Can someone help me reduce the size of these rst files?

**Comment by larsoner** [comment]
You'll need to look at your generated RST file to see what is actually being generated. My guess is that it's some `_repr_html_` that is being rendered.

**Comment by shivshankardayal** [comment]
It will take a while to carefully examine these files. I will update the ticket after examination.
