### ISSUE TITLE
Problem in section and example title level in subgalleries

### ISSUE THREAD

**Issue by rflamary** [sphinx-gallery/sphinx-gallery#935]
Hello,

Since I'm using the master branch of sphinx-gallery in POT I get to test all your new features ;).

I have a problem because the examples in the subgalleries that where defined as subsubsection in the original doc:
https://pythonot.github.io/auto_examples/index.html
![image](https://user-images.githubusercontent.com/1386873/160867522-6ec1c107-4150-46d7-893a-8d29dd631f90.png)
are now repeated moved at the end of the list with the wrong level
https://pythonot.github.io/master/auto_examples/index.html
![image](https://user-images.githubusercontent.com/1386873/160866932-278a6c29-f3b4-4b80-90ee-1b7330055ba4.png)

There was no change in the subgalleries files. I'm OK with changing stuff to move back to the original behavior but I can't find the information in the doc.

I also noted that you have the same problem in the dev version of your doc:
https://sphinx-gallery.github.io/dev/auto_examples/index.html#no-image-output-examples
![image](https://user-images.githubusercontent.com/1386873/160868826-2cbe53c7-8392-4836-bbe7-17eb68972b50.png)
so I think it might be a bug.

**Comment by alexisthual** [comment]
Yes it's very likely!
It's still unclear to me where it comes from but I have several ideas. In particular, for `sphinx-gallery`'s documentation, the current implementation appends 2 toctrees to the main rst file (one for examples which do not belong to any sub-category, the other for the sub-category entitled "No image output examples"), and I think it messes up the overall organisation.

I'll look into this when I can. In the meantime, I guess an easy fix for that is to ensure that all examples belong to a sub-category (ie a subfolder).

**Comment by rflamary** [comment]
Thank you @alexisthual good to know,

I will not change the examples tree because it would break links  in the readme file. I can wait for your fix ;)

**Comment by alexisthual** [comment]
> I will not change the examples tree because it would break links in the readme file

Humm good point, I should find a fix then!
