### ISSUE TITLE
Subfolder Examples appearing in main TOC

### ISSUE THREAD

**Issue by ExtremOPS** [sphinx-gallery/sphinx-gallery#939]
We are using `sphinx-gallery` and want to use now subfolders for the examples. Our structure in the `examples` directory is the following:

```shell
examples
├── README.rst
├── from_publications
│   ├── README.rst
│   └── plot_yosioka_fig_2.py
└── own_examples
    ├── README.rst
    ├── plot_ARF_PS_in_water.py
    ├── plot_air_bubble_in_water.py
    ├── plot_cu_in_oil.py
    └── plot_hfe_in_water.py
```

The building and displaying works alright and fine. However, now the subfolders appear in the main Contents Table on the left. [Link to our documentation](https://osaft.readthedocs.io/en/patch-recreating-solutions/). I would expect it to be a subheading of `Examples` itself.

We are using the [furo](https://furo.readthedocs.io/en/latest/index.html) sphinx theme.

Do you happen to know a solution to this? Do you happen to know, if that can be fixed with `sphinx-gallery`? Or do you think, it has to do with `furo`?

**Comment by lucyleeow** [comment]
I think this may be the same problem as this: https://github.com/sphinx-gallery/sphinx-gallery/issues/935
Sorry, I think a fix is coming.

**Comment by ExtremOPS** [comment]
Thank you for the answer. I am looking forward to it. If there is anything I can do just let me know.

**Comment by alexisthual** [comment]
Hi @ExtremOPS,
Sorry for taking so much time to get back to you, I was very busy these past few weeks.
The current `master` branch should do what you expect (include your subfolders as subheadings of Examples).
Can you please tell me if you still have this problem? If yes, can you please show me a screenshot and let me know what you put in these `README.rst` files? Thanks!

**Comment by ExtremOPS** [comment]
Hi @alexisthual,
no worries! The current master really solves my problem. Thank you. I will close the issue now.
