### ISSUE TITLE
"Broken" image appear within an example html

### ISSUE THREAD

**Issue by lesteve** [sphinx-gallery/sphinx-gallery#94]
Weird thing that happens when we tried to release nilearn.

One of the example failed and somehow the "Broken" image founds its way into the example html ...

![sphinx-gallery](https://cloud.githubusercontent.com/assets/1680079/12848546/efd8e20e-cc1a-11e5-98cc-96632f989129.png)

As you can notice the cell it does happen has no error. This is the next one which has an error.

It would be worth trying to reproduce this on a simpler example.

**Comment by Titan-C** [comment]
This is the default behavior. Once the example fails the first images gets overwritten into the broken stamp. Because it is the first image that gets re-scaled into the thumbnail. But once the example fails we don't really care if the images continue to be on the right place, do we?

**Comment by lesteve** [comment]
> Once the example fails the first images gets overwritten into the broken stamp

Ah because the _001 image is the one being showed on the gallery, right? This is slightly surprising, but I agree this is not very high priority.
