### ISSUE TITLE
disable download buttons

### ISSUE THREAD

**Issue by photoniker** [sphinx-gallery/sphinx-gallery#949]
Is it possible to config sphinx-gallery that the download button for jupyter or both are removed from the examples pages?

**Comment by larsoner** [comment]
Have you tried using CSS with `visibility: hidden`? Something like this might work (I know it hides something but I can't remember what):

https://github.com/mne-tools/mne-python/blob/fd0212e5167683a4aca4cd98321af5809a06581f/doc/_static/style.css#L47-L48

**Comment by photoniker** [comment]
ah I have found one possible way. I manipulate the CODE_DOWNLOAD member of sphinx_gallery.downloads. 
Maybe not the best way, but it works. 

`from sphinx_gallery import downloads

downloads.CODE_DOWNLOAD = """
.. _sphx_glr_download_{3}:

\n.. only :: html

 .. container:: sphx-glr-footer
    :class: sphx-glr-footer-example

{2}
\n  .. container:: sphx-glr-download sphx-glr-download-python

     :download:`Download Python source code: {0} <{0}>`\n"""`

**Comment by GaelVaroquaux** [comment]
> ah I have found one possible way. I manipulate the CODE_DOWNLOAD member of sphinx_gallery.downloads.

You should really be using CSS for this. That's what it is made for.

**Comment by photoniker** [comment]
Hi, yes thanks it works mit CSS. 

My last problem is that I build docu for html and Qt. In the Qt help the text of the download buttons are added: 
![image](https://user-images.githubusercontent.com/17592823/164480386-aa627248-ea22-4c42-ad1e-ef86b10189aa.png)

Although I set the buttons in the CSS visibility `visibility: hidden`.

**Comment by photoniker** [comment]
OK yes thanks, now it work
