### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by ExtremOPS** [sphinx-gallery/sphinx-gallery#965]
Dear maintainer,

I wanted to ask for when the next release is scheduled? I am asking because I need the fix of #950 in order to publish our code to pypi. I do not want to rush you, just a rough estimate would be really appreciated! 

Best,
Christoph

**Comment by larsoner** [comment]
A release would be good @lucyleeow would you be up for making one?

**Comment by lucyleeow** [comment]
I'm wondering if we should try to fix https://github.com/sphinx-gallery/sphinx-gallery/issues/935 / #939 first?

**Comment by larsoner** [comment]
@alexisthual can you look into #935 / #939?

**Comment by ExtremOPS** [comment]
@alexisthual, is there anything I can help you do in order to finish/close #935 and #939? I looked at them and it is not straightforward for me to help. However, if you can give me tasks I might be able to help.

**Comment by alexisthual** [comment]
Sorry for being silent for so long, I was busy with other things! I'll try to have all this fixed in the coming days.
It's clear to me what I need to do in #935, but I don't know if the problem still persists in #939 so I would need an update on this!

**Comment by ExtremOPS** [comment]
Hi,
I just closed #939. The problem I was describing there was fixed.

**Comment by ExtremOPS** [comment]
@lucyleeow @larsoner I think @alexisthual closed all merge requests (#939 and #935). I think that means it is ready to be released, right?

**Comment by larsoner** [comment]
Yes I think so. @lucyleeow feel free to cut a release if you have time, otherwise I'll try to do it next week
