### ISSUE TITLE
reference_url failure in sphinx version > 5

### ISSUE THREAD

**Issue by hndgzkn** [sphinx-gallery/sphinx-gallery#967]
After sphinx released version 5, `reference_url` in `sphinx_gallery_conf` section  gives the following error upon doc build:

```
Extension error (sphinx_gallery.docs_resolv):
Handler <function embed_code_links at 0x7fe9e0a40820> for event 'build-finished' threw an exception (exception: Expecting property name enclosed in double quotes: line 1 column 2 (char 1))
```

As far as I could address, for `reference_url` `http://example.com/stable/"`in  `conf.py`, `/"`at the end is treated as escape and removed. If the url is specified as `http://example.com`, then the following error occurs:

```
embedding documentation hyperlinks...
WARNING: The following HTTPError has occurred fetching http://example.com/stable_static/documentation_options.js: 404 (Not Found)
```

The second case can be avoided in https://github.com/sphinx-gallery/sphinx-gallery/blob/e7d7439f6b85c603801945dd9ab510217cd9a269/sphinx_gallery/docs_resolv.py#L153 .

**Comment by larsoner** [comment]
Indeed I think the last one not having a leading `/` is an error, can you make a PR to fix it?

**Comment by ntessore** [comment]
This also breaks when entries in `reference_url` are set to `None`, as shown in the docs

```py
    'reference_url': {
         # The module you locally document uses None
        'sphinx_gallery': None,
    }
```

**Comment by larsoner** [comment]
I implemented the fix in https://github.com/sphinx-gallery/sphinx-gallery/pull/980, will merge and cut a release. Hopefully it fixes the problem, but even if it doesn't, it seems to clearly move in the right direction!

**Comment by LilianBoulard** [comment]
Hi, I see this topic is very recent, so allow me to comment here !
We are having the error reported above [in our CI](https://app.circleci.com/pipelines/github/dirty-cat/dirty_cat/630/workflows/e3ae9561-192a-42e8-bd6e-bceceada87a5/jobs/1634) even though sphinx-gallery 0.11.0 is installed.
I'll try downgrading to 0.10.1, see if it fixes the error.

**Comment by ntessore** [comment]
Just checking in to report that v0.11.0 still has problems with `None` entries in `reference_url`.

**Comment by bouthilx** [comment]
I am having the same issue with `'reference_url': {'sphinx_gallery': None}`. Downgrading sphinx to v4.5.0 solves the issue for `sphinx-gallery<=0.11.0`.
