### ISSUE TITLE
nbsphinx regression since Sphinx Gallery 0.11

### ISSUE THREAD

**Issue by mgeier** [sphinx-gallery/sphinx-gallery#984]
Hi, I'm the maintainer of `nbsphinx`, which recommends using the `sphinx_gallery.load_style` extension (see https://nbsphinx.readthedocs.io/en/0.8.9/subdir/gallery.html).

Apparently, in SG v0.11, the CSS structure has changed, most likely in #905.

This has been reported here:

* https://github.com/spatialaudio/nbsphinx/issues/655
* https://github.com/PlasmaPy/PlasmaPy/pull/1654

I still have to look into that and try to find a solution to make `nbsphinx` work with old and new versions of Sphinx Gallery.
But maybe it's also possible to solve this on the Sphinx Gallery side?
Would it be possible to add some CSS for backwards compatibility with the old structure?

**Comment by larsoner** [comment]
It should be easy enough to keep the old stuff around. @mgeier do you want to try restoring the missing CSS and putting it at the bottom with a comment like "for backward compatibility with the style extension we retain otherwise-unused CSS" or so?

**Comment by mgeier** [comment]
I had a look at the changes from #906, and I don't think it's possible to restore compatibility.

The problem is that the CSS class `sphx-glr-thumbcontainer` has been changed heavily (as opposed to be replaced by a different class with a new name): among many other things, `float: left` has been removed and `width: 100%` has been added.

If I'm missing something, and if anybody knows a way to keep compatibility, please let me know!

But if not, I think I will just give up on the old way and unconditionally implement the new HTML structure in `nbsphinx`.

**Comment by larsoner** [comment]
> If I'm missing something, and if anybody knows a way to keep compatibility, please let me know!

Could you instead override the CSS changes in a `.css` file that `nbsphinx` ships?

**Comment by mgeier** [comment]
> Could you instead override the CSS changes in a `.css` file that `nbsphinx` ships?

I sure could, but my whole idea was for `nbsphinx` to *not* provide any CSS for galleries and instead fully rely on external CSS (or user-provided CSS).

**Comment by larsoner** [comment]
Another idea is to decide how to structure your HTML elements (or whatever else you need to update for latest SG) based on the SG version. Then after a year or however long you want to support the previous release you can remove it

**Comment by mgeier** [comment]
Yeah, I could try to provide different versions of the HTML output, but as long as SG doesn't, I won't either. I assume that the new way is strictly better than the old way.

I've just created a PR for supporting the new way: https://github.com/spatialaudio/nbsphinx/pull/666

**Comment by natestemen** [comment]
@mgeier now that https://github.com/spatialaudio/nbsphinx/pull/706 has been merged, will this issue be fixed in the next release?

**Comment by natestemen** [comment]
@mgeier now that https://github.com/spatialaudio/nbsphinx/pull/706 has been merged, will this issue be fixed in the next release?

**Comment by mgeier** [comment]
Yes, the next release of `nbsphinx` will have its own HTML/CSS and will not depend on Sphinx Gallery anymore.

**Comment by larsoner** [comment]
I think now taht `nbsphinx` doesn't use our "stuff" we can close this... but feel free to reopen if I'm missing something
