### ISSUE TITLE
Uneven height in gallery thumbnails

### ISSUE THREAD

**Issue by timhoffm** [sphinx-gallery/sphinx-gallery#988]
The height of the gallery thumbnails now adapts to the size of the title (likely due to #905). This can make a quite uneven layout if you have some short and long titles.

![grafik](https://user-images.githubusercontent.com/2836374/184554546-59bef461-c843-446f-acdf-99805cd21aed.png)

Is it possible to set a minimum height, so that the thumbnails never get shorter than two or three lines of text?

**Comment by larsoner** [comment]
> This can make a quite uneven layout if you have some short and long titles.

Personally I saw this as a feature more than a bug (better use of space / less wasted space), but I could see how others might disagree.

I would first look into if some CSS could be used to force all the elements to have the same (maximal) height. Alternatively, you could probably use CSS to just set a min height in pixels for that element type

**Comment by timhoffm** [comment]
Thanks, I'll check what CSS can do.

**Comment by alexisthual** [comment]
I agree with @larsoner that this is a feature: it helps minimizing overall space on small devices.
However, I guess you can easily set a `min-height` in your custom CSS :slightly_smiling_face:

**Comment by timhoffm** [comment]
Customizing with `min-height` should be good enough.
