### ISSUE TITLE
Release 0.11 shrinks gallery thumbnails

### ISSUE THREAD

**Issue by mthrok** [sphinx-gallery/sphinx-gallery#990]
Hi

Since the release of 0.11, the thumbnails are rendered differently. It seems to be a regression.
Do you have a suggestion for workaround?

### With 0.10

<img width="731" alt="Screen Shot 2022-08-17 at 10 01 44 PM" src="https://user-images.githubusercontent.com/855818/185140848-d0d519c8-d6e2-4494-94b7-74faede7c60f.png">

Source: https://pytorch.org/audio/0.12.0/io.html#torchaudio.io.StreamReader

### With 0.11

<img width="734" alt="Screen Shot 2022-08-17 at 10 02 23 PM" src="https://user-images.githubusercontent.com/855818/185140952-28f2d98a-b586-424c-a003-b69089f48eb9.png">

Source: https://pytorch.org/audio/stable/io.html#torchaudio.io.StreamReader

**Comment by larsoner** [comment]
In your CSS `article.pytorch-article .sphx-glr-thumbcontainer` CSS has a `width: 30%`, and then later `width: 45%`. If I uncomment these, I get something a little better:

<img width="554" alt="Screen Shot 2022-08-17 at 9 30 51 AM" src="https://user-images.githubusercontent.com/2365790/185146744-0766d8d8-5b03-4c06-bdf6-642f8be2f5e7.png">

<img width="601" alt="Screen Shot 2022-08-17 at 9 30 44 AM" src="https://user-images.githubusercontent.com/2365790/185146759-92f5cb9c-1a41-47d3-9a83-90a2730d8161.png">

Now it's just in a single column, but this is at least progress I think. Can you see if you can fix this your CSS?

**Comment by mthrok** [comment]
@larsoner Thanks for the suggestion. I have successfully override the CSS and built the doc with a similar result. Indeed the column is single. 

<img width="1440" alt="Screen Shot 2022-08-18 at 9 12 14 AM" src="https://user-images.githubusercontent.com/855818/185265477-ba531425-2eca-4af4-bda5-457808f82c81.png">

Do you think we should keep going with the overriding approach or just pin the sphinx-gallery to 0.10?

**Comment by larsoner** [comment]
I would change the CSS, ideally by just removing some overrides.

I'll close this in favor of #992 where we can figure out the one-column issue
